
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.menu.stage-1.2.7.zip"

    [package.publish]
        kitVersion = "107.0.3+107_abi1.171913.67e3d383.gl"
        date = 1744190176
        buildNumber = "107.0.0+master.963.7c28144a.gl"
        repoName = "kit-scene"
        signed = 1
