from __future__ import annotations
import pxr.UsdShade._usdShade
import typing
import Boost.Python
import pxr.Usd
import pxr.UsdShade

__all__ = [
    "AttributeType",
    "ConnectableAPI",
    "ConnectionModification",
    "ConnectionSourceInfo",
    "CoordSysAPI",
    "Input",
    "Material",
    "MaterialBindingAPI",
    "NodeDefAPI",
    "NodeGraph",
    "Output",
    "Shader",
    "ShaderDefParserPlugin",
    "ShaderDefUtils",
    "Tokens",
    "UdimUtils",
    "Utils"
]


class AttributeType(Boost.Python.enum, int):
    Input = pxr.UsdShade.AttributeType.Input
    Invalid = pxr.UsdShade.AttributeType.Invalid
    Output = pxr.UsdShade.AttributeType.Output
    __slots__ = ()
    names = {'Invalid': pxr.UsdShade.AttributeType.Invalid, 'Input': pxr.UsdShade.AttributeType.Input, 'Output': pxr.UsdShade.AttributeType.Output}
    values = {0: pxr.UsdShade.AttributeType.Invalid, 1: pxr.UsdShade.AttributeType.Input, 2: pxr.UsdShade.AttributeType.Output}
    pass
class ConnectableAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CanConnect(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectToSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def DisconnectSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRawConnectedSourcePaths(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasConnectedSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsContainer(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsSourceConnectionFromBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def RequiresEncapsulation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetConnectedSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class ConnectionModification(Boost.Python.enum, int):
    Append = pxr.UsdShade.ConnectionModification.Append
    Prepend = pxr.UsdShade.ConnectionModification.Prepend
    Replace = pxr.UsdShade.ConnectionModification.Replace
    __slots__ = ()
    names = {'Replace': pxr.UsdShade.ConnectionModification.Replace, 'Prepend': pxr.UsdShade.ConnectionModification.Prepend, 'Append': pxr.UsdShade.ConnectionModification.Append}
    values = {0: pxr.UsdShade.ConnectionModification.Replace, 1: pxr.UsdShade.ConnectionModification.Prepend, 2: pxr.UsdShade.ConnectionModification.Append}
    pass
class ConnectionSourceInfo(Boost.Python.instance):
    @staticmethod
    def IsValid(*args, **kwargs) -> typing.Any: ...
    @property
    def source(self) -> None:
        """
        :type: None
        """
    @property
    def sourceName(self) -> None:
        """
        :type: None
        """
    @property
    def sourceType(self) -> None:
        """
        :type: None
        """
    @property
    def typeName(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 80
    pass
class CoordSysAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ApplyAndBind(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Bind(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def BlockBinding(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanContainPropertyName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearBinding(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateBindingRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindBindingWithInheritance(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindBindingsWithInheritance(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindBindingsWithInheritanceForPrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAll(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBindingRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCoordSysRelationshipName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLocalBinding(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLocalBindings(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLocalBindingsForPrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasLocalBindings(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasLocalBindingsForPrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsCoordSysAPIPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Input(Boost.Python.instance):
    @staticmethod
    def CanConnect(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearConnectability(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectToSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def DisconnectSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectability(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplayGroup(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDocumentation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFullName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRawConnectedSourcePaths(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRenderType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetValueProducingAttribute(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetValueProducingAttributes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasConnectedSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasRenderType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsInterfaceInputName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsSourceConnectionFromBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Set(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetConnectability(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetConnectedSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetDisplayGroup(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetDocumentation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetRenderType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Material(NodeGraph, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ClearBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeDisplacementSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeSurfaceSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeVolumeSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDisplacementAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDisplacementOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateMasterMaterialVariant(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSurfaceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSurfaceOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVolumeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVolumeOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseMaterialPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplacementAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplacementOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplacementOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEditContextForVariant(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMaterialVariant(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSurfaceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSurfaceOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSurfaceOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVolumeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVolumeOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVolumeOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetBaseMaterialPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class MaterialBindingAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    class CollectionBinding(Boost.Python.instance):
        @staticmethod
        def GetBindingRel(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetCollection(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetCollectionPath(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetMaterial(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetMaterialPath(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def IsCollectionBindingRel(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def IsValid(*args, **kwargs) -> typing.Any: ...
        __instance_size__ = 72
        pass
    class DirectBinding(Boost.Python.instance):
        @staticmethod
        def GetBindingRel(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetMaterial(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetMaterialPath(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetMaterialPurpose(*args, **kwargs) -> typing.Any: ...
        __instance_size__ = 80
        pass
    @staticmethod
    def AddPrimToBindingCollection(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Bind(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanContainPropertyName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeBoundMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeBoundMaterials(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateMaterialBindSubset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCollectionBindingRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCollectionBindingRels(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCollectionBindings(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDirectBinding(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDirectBindingRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMaterialBindSubsets(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMaterialBindSubsetsFamilyType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMaterialBindingStrength(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMaterialPurposes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetResolvedTargetPathFromBindingRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def RemovePrimFromBindingCollection(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetMaterialBindSubsetsFamilyType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetMaterialBindingStrength(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def UnbindAllBindings(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def UnbindCollectionBinding(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def UnbindDirectBinding(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class NodeDefAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateImplementationSourceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetImplementationSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetImplementationSourceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderNodeForSourceType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceAsset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceAssetSubIdentifier(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceCode(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceTypes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetShaderId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSourceAsset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSourceAssetSubIdentifier(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSourceCode(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class NodeGraph(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeInterfaceInputConsumersMap(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeOutputSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInterfaceInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Output(Boost.Python.instance):
    @staticmethod
    def CanConnect(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectToSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def DisconnectSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFullName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRawConnectedSourcePaths(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRenderType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetValueProducingAttributes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasConnectedSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasRenderType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsSourceConnectionFromBaseMaterial(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Set(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetConnectedSources(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetRenderType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Shader(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ClearSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateImplementationSourceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetImplementationSource(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetImplementationSourceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderNodeForSourceType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceAsset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceAssetSubIdentifier(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceCode(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceTypes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSdrMetadata(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSdrMetadataByKey(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetShaderId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSourceAsset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSourceAssetSubIdentifier(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetSourceCode(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class ShaderDefParserPlugin(Boost.Python.instance):
    @staticmethod
    def GetDiscoveryTypes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSourceType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Parse(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 40
    pass
class ShaderDefUtils(Boost.Python.instance):
    @staticmethod
    def GetNodeDiscoveryResults(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrimvarNamesMetadataString(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderProperties(*args, **kwargs) -> typing.Any: ...
    pass
class Tokens(Boost.Python.instance):
    ConnectableAPI = 'ConnectableAPI'
    CoordSysAPI = 'CoordSysAPI'
    Material = 'Material'
    MaterialBindingAPI = 'MaterialBindingAPI'
    NodeDefAPI = 'NodeDefAPI'
    NodeGraph = 'NodeGraph'
    Shader = 'Shader'
    allPurpose = ''
    bindMaterialAs = 'bindMaterialAs'
    coordSys = 'coordSys'
    coordSys_MultipleApplyTemplate_Binding = 'coordSys:__INSTANCE_NAME__:binding'
    displacement = 'displacement'
    fallbackStrength = 'fallbackStrength'
    full = 'full'
    id = 'id'
    infoId = 'info:id'
    infoImplementationSource = 'info:implementationSource'
    inputs = 'inputs:'
    interfaceOnly = 'interfaceOnly'
    materialBind = 'materialBind'
    materialBinding = 'material:binding'
    materialBindingCollection = 'material:binding:collection'
    materialVariant = 'materialVariant'
    outputs = 'outputs:'
    outputsDisplacement = 'outputs:displacement'
    outputsSurface = 'outputs:surface'
    outputsVolume = 'outputs:volume'
    preview = 'preview'
    sdrMetadata = 'sdrMetadata'
    sourceAsset = 'sourceAsset'
    sourceCode = 'sourceCode'
    strongerThanDescendants = 'strongerThanDescendants'
    subIdentifier = 'subIdentifier'
    surface = 'surface'
    universalRenderContext = ''
    universalSourceType = ''
    volume = 'volume'
    weakerThanDescendants = 'weakerThanDescendants'
    pass
class UdimUtils(Boost.Python.instance):
    @staticmethod
    def IsUdimIdentifier(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ReplaceUdimPattern(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ResolveUdimPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ResolveUdimTilePaths(*args, **kwargs) -> typing.Any: ...
    pass
class Utils(Boost.Python.instance):
    @staticmethod
    def GetBaseNameAndType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectedSourcePath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFullName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrefixForAttributeType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetValueProducingAttributes(*args, **kwargs) -> typing.Any: ...
    pass
class _CanApplyResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
__MFB_FULL_PACKAGE_NAME = 'usdShade'
