from __future__ import annotations
import usdrt.UsdRender._UsdRender
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd

__all__ = [
    "DenoisePass",
    "Pass",
    "Product",
    "Settings",
    "SettingsBase",
    "Tokens",
    "Var"
]


class DenoisePass(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> DenoisePass: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Pass(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateCommandAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDenoiseEnableAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDenoisePassRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateFileNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateInputPassesRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreatePassTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRenderSourceRel(self) -> usdrt.Usd._Usd.Relationship: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Pass: ...
    def GetCommandAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDenoiseEnableAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDenoisePassRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetFileNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetInputPassesRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetPassTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRenderSourceRel(self) -> usdrt.Usd._Usd.Relationship: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Product(SettingsBase, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateOrderedVarsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateProductNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateProductTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Product: ...
    def GetOrderedVarsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetProductNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetProductTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Settings(SettingsBase, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateIncludedPurposesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateMaterialBindingPurposesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateProductsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateRenderingColorSpaceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Settings: ...
    def GetIncludedPurposesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetMaterialBindingPurposesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetProductsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetRenderingColorSpaceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class SettingsBase(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAspectRatioConformPolicyAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateCameraRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateDataWindowNDCAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDisableMotionBlurAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateInstantaneousShutterAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePixelAspectRatioAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateResolutionAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetAspectRatioConformPolicyAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCameraRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetDataWindowNDCAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisableMotionBlurAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetInstantaneousShutterAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPixelAspectRatioAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetResolutionAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    adjustApertureHeight = 'adjustApertureHeight'
    adjustApertureWidth = 'adjustApertureWidth'
    adjustPixelAspectRatio = 'adjustPixelAspectRatio'
    aspectRatioConformPolicy = 'aspectRatioConformPolicy'
    camera = 'camera'
    color3f = 'color3f'
    command = 'command'
    cropAperture = 'cropAperture'
    dataType = 'dataType'
    dataWindowNDC = 'dataWindowNDC'
    denoiseEnable = 'denoise:enable'
    denoisePass = 'denoise:pass'
    disableMotionBlur = 'disableMotionBlur'
    expandAperture = 'expandAperture'
    fileName = 'fileName'
    full = 'full'
    includedPurposes = 'includedPurposes'
    inputPasses = 'inputPasses'
    instantaneousShutter = 'instantaneousShutter'
    intrinsic = 'intrinsic'
    lpe = 'lpe'
    materialBindingPurposes = 'materialBindingPurposes'
    orderedVars = 'orderedVars'
    passType = 'passType'
    pixelAspectRatio = 'pixelAspectRatio'
    preview = 'preview'
    primvar = 'primvar'
    productName = 'productName'
    productType = 'productType'
    products = 'products'
    raster = 'raster'
    raw = 'raw'
    renderSettingsPrimPath = 'renderSettingsPrimPath'
    renderSource = 'renderSource'
    renderingColorSpace = 'renderingColorSpace'
    resolution = 'resolution'
    sourceName = 'sourceName'
    sourceType = 'sourceType'
    pass
class Var(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSourceNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSourceTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Var: ...
    def GetDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetSourceNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetSourceTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
