from __future__ import annotations
import usdrt.UsdShade._UsdShade
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd

__all__ = [
    "AttributeType",
    "ConnectableAPI",
    "ConnectionModification",
    "ConnectionSourceInfo",
    "CoordSysAPI",
    "Input",
    "Material",
    "MaterialBindingAPI",
    "NodeDefAPI",
    "NodeGraph",
    "Output",
    "Shader",
    "Tokens",
    "Utils"
]


class AttributeType():
    """
    Members:

      Invalid

      Input

      Output
    """
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str:
        """
        :type: str
        """
    @property
    def value(self) -> int:
        """
        :type: int
        """
    Input: usdrt.UsdShade._UsdShade.AttributeType # value = <AttributeType.Input: 1>
    Invalid: usdrt.UsdShade._UsdShade.AttributeType # value = <AttributeType.Invalid: 0>
    Output: usdrt.UsdShade._UsdShade.AttributeType # value = <AttributeType.Output: 2>
    __members__: dict # value = {'Invalid': <AttributeType.Invalid: 0>, 'Input': <AttributeType.Input: 1>, 'Output': <AttributeType.Output: 2>}
    pass
class ConnectableAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    @typing.overload
    def ConnectToSource(shadingAttr: usdrt.Usd._Usd.Attribute, source: ConnectionSourceInfo, mod: ConnectionModification = ConnectionModification.Replace) -> bool: ...
    @staticmethod
    @typing.overload
    def ConnectToSource(input: Input, source: ConnectionSourceInfo, mod: ConnectionModification = ConnectionModification.Replace) -> bool: ...
    @staticmethod
    @typing.overload
    def ConnectToSource(output: Output, source: ConnectionSourceInfo, mod: ConnectionModification = ConnectionModification.Replace) -> bool: ...
    def CreateInput(self, name: TfToken, type: usdrt.Sdf._Sdf.ValueTypeName) -> Input: ...
    def CreateOutput(self, name: TfToken, typeName: usdrt.Sdf._Sdf.ValueTypeName) -> Output: ...
    def GetInput(self, name: TfToken) -> Input: ...
    def GetInputs(self, onlyAuthored: bool = True) -> typing.List[Input]: ...
    def GetOutput(self, name: TfToken) -> Output: ...
    def GetOutputs(self, onlyAuthored: bool = True) -> typing.List[Output]: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class ConnectionModification():
    """
    Members:

      Replace

      Prepend

      Append
    """
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str:
        """
        :type: str
        """
    @property
    def value(self) -> int:
        """
        :type: int
        """
    Append: usdrt.UsdShade._UsdShade.ConnectionModification # value = <ConnectionModification.Append: 2>
    Prepend: usdrt.UsdShade._UsdShade.ConnectionModification # value = <ConnectionModification.Prepend: 1>
    Replace: usdrt.UsdShade._UsdShade.ConnectionModification # value = <ConnectionModification.Replace: 0>
    __members__: dict # value = {'Replace': <ConnectionModification.Replace: 0>, 'Prepend': <ConnectionModification.Prepend: 1>, 'Append': <ConnectionModification.Append: 2>}
    pass
class ConnectionSourceInfo():
    def IsValid(self) -> bool: ...
    def __bool__(self) -> bool: ...
    def __eq__(self, arg0: ConnectionSourceInfo) -> bool: ...
    @typing.overload
    def __init__(self) -> None: ...
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> typing.Any: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Stage, arg1: usdrt.Sdf._Sdf.Path) -> None: ...
    def __ne__(self, arg0: ConnectionSourceInfo) -> bool: ...
    def __repr__(self) -> str: ...
    @property
    def source(self) -> typing.Any:
        """
        :type: typing.Any
        """
    @source.setter
    def source(*args, **kwargs) -> None:
        pass
    @property
    def sourceName(self) -> str:
        """
        :type: str
        """
    @sourceName.setter
    def sourceName(self, arg1: str) -> None:
        pass
    @property
    def sourceType(self) -> typing.Any:
        """
        :type: typing.Any
        """
    @sourceType.setter
    def sourceType(*args, **kwargs) -> None:
        pass
    @property
    def typeName(self) -> usdrt.Sdf._Sdf.ValueTypeName:
        """
        :type: usdrt.Sdf._Sdf.ValueTypeName
        """
    @typeName.setter
    def typeName(self, arg0: usdrt.Sdf._Sdf.ValueTypeName) -> None:
        pass
    __hash__ = None
    pass
class CoordSysAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Input():
    @typing.overload
    def ConnectToSource(self, sourceInput: Input) -> bool: ...
    @staticmethod
    @typing.overload
    def ConnectToSource(*args, **kwargs) -> typing.Any: ...
    def Get(self, time: usdrt.Usd._Usd.TimeCode = Usd.TimeCode.Default()) -> object: ...
    def GetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetBaseName(self) -> TfToken: ...
    def GetFullName(self) -> TfToken: ...
    def GetPrim(self) -> usdrt.Usd._Usd.Prim: ...
    def GetTypeName(self) -> usdrt.Sdf._Sdf.ValueTypeName: ...
    def IsDefined(self) -> bool: ...
    @staticmethod
    def IsInput(attr: usdrt.Usd._Usd.Attribute) -> bool: ...
    def Set(self, value: object, time: usdrt.Usd._Usd.TimeCode = Usd.TimeCode.Default()) -> bool: ...
    def __bool__(self) -> bool: ...
    def __init__(self) -> None: ...
    pass
class Material(NodeGraph, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateDisplacementAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDisplacementOutput(self, renderContext: TfToken = '') -> Output: ...
    def CreateSurfaceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSurfaceOutput(self, renderContext: TfToken = '') -> Output: ...
    def CreateVolumeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVolumeOutput(self, renderContext: TfToken = '') -> Output: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Material: ...
    def GetDisplacementAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisplacementOutput(self, renderContext: TfToken = '') -> Output: ...
    def GetDisplacementOutputs(self) -> typing.List[Output]: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetSurfaceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetSurfaceOutput(self, renderContext: TfToken = '') -> Output: ...
    def GetSurfaceOutputs(self) -> typing.List[Output]: ...
    def GetVolumeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVolumeOutput(self, renderContext: TfToken = '') -> Output: ...
    def GetVolumeOutputs(self) -> typing.List[Output]: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class MaterialBindingAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> MaterialBindingAPI: ...
    def Bind(self, material: Material, bindingStrength: TfToken = 'fallbackStrength', materialPurpose: TfToken = '') -> bool: ...
    def ComputeBoundMaterial(self, materialPurpose: TfToken = '') -> tuple: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def UnbindAllBindings(self) -> bool: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class NodeDefAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> NodeDefAPI: ...
    def CreateIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateImplementationSourceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetImplementationSource(self) -> TfToken: ...
    def GetImplementationSourceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShaderId(self) -> object: ...
    def GetSourceAsset(self, sourceType: TfToken = '') -> object: ...
    def GetSourceAssetSubIdentifier(self, sourceType: TfToken = '') -> object: ...
    def GetSourceCode(self, sourceType: TfToken = '') -> object: ...
    def SetShaderId(self, arg0: TfToken) -> bool: ...
    def SetSourceAsset(self, sourceAsset: usdrt.Sdf._Sdf.AssetPath, sourceType: TfToken = '') -> bool: ...
    def SetSourceAssetSubIdentifier(self, subIdentifier: TfToken, sourceType: TfToken = '') -> bool: ...
    def SetSourceCode(self, sourceCode: str, sourceType: TfToken = '') -> bool: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class NodeGraph(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def ComputeOutputSource(self, outputName: TfToken) -> tuple: ...
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    def CreateInput(self, name: TfToken, type: usdrt.Sdf._Sdf.ValueTypeName) -> Input: ...
    def CreateOutput(self, name: TfToken, typeName: usdrt.Sdf._Sdf.ValueTypeName) -> Output: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> NodeGraph: ...
    def GetInput(self, name: TfToken) -> Input: ...
    def GetInputs(self, onlyAuthored: bool = True) -> typing.List[Input]: ...
    def GetOutput(self, name: TfToken) -> Output: ...
    def GetOutputs(self, onlyAuthored: bool = True) -> typing.List[Output]: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> typing.Any: ...
    def __repr__(self) -> str: ...
    pass
class Output():
    @typing.overload
    def ConnectToSource(self, sourceInput: Input) -> bool: ...
    @typing.overload
    def ConnectToSource(self, sourceOutput: Output) -> bool: ...
    def GetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetBaseName(self) -> TfToken: ...
    def GetFullName(self) -> TfToken: ...
    def GetPrim(self) -> usdrt.Usd._Usd.Prim: ...
    def GetTypeName(self) -> usdrt.Sdf._Sdf.ValueTypeName: ...
    def IsDefined(self) -> bool: ...
    @staticmethod
    def IsOutput(attr: usdrt.Usd._Usd.Attribute) -> bool: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Attribute) -> None: ...
    pass
class Shader(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    def CreateIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateImplementationSourceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateInput(self, name: TfToken, type: usdrt.Sdf._Sdf.ValueTypeName) -> Input: ...
    def CreateOutput(self, name: TfToken, type: usdrt.Sdf._Sdf.ValueTypeName) -> Output: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Shader: ...
    def GetIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetImplementationSource(self) -> TfToken: ...
    def GetImplementationSourceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetInput(self, name: TfToken) -> Input: ...
    def GetInputs(self, onlyAuthored: bool = True) -> typing.List[Input]: ...
    def GetOutput(self, name: TfToken) -> Output: ...
    def GetOutputs(self, onlyAuthored: bool = True) -> typing.List[Output]: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShaderId(self) -> object: ...
    def GetSourceAsset(self, sourceType: TfToken = '') -> object: ...
    def GetSourceAssetSubIdentifier(self, sourceType: TfToken = '') -> object: ...
    def GetSourceCode(self, sourceType: TfToken = '') -> object: ...
    def SetShaderId(self, arg0: TfToken) -> bool: ...
    def SetSourceAsset(self, sourceAsset: usdrt.Sdf._Sdf.AssetPath, sourceType: TfToken = '') -> bool: ...
    def SetSourceAssetSubIdentifier(self, subIdentifier: TfToken, sourceType: TfToken = '') -> bool: ...
    def SetSourceCode(self, sourceCode: str, sourceType: TfToken = '') -> bool: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    @staticmethod
    @typing.overload
    def __init__(*args, **kwargs) -> typing.Any: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    allPurpose = ''
    bindMaterialAs = 'bindMaterialAs'
    coordSys = 'coordSys:'
    displacement = 'displacement'
    fallbackStrength = 'fallbackStrength'
    full = 'full'
    id = 'id'
    infoId = 'info:id'
    infoImplementationSource = 'info:implementationSource'
    inputs = 'inputs:'
    interfaceOnly = 'interfaceOnly'
    materialBind = 'materialBind'
    materialBinding = 'material:binding'
    materialBindingCollection = 'material:binding:collection'
    materialVariant = 'materialVariant'
    outputs = 'outputs:'
    outputsDisplacement = 'outputs:displacement'
    outputsSurface = 'outputs:surface'
    outputsVolume = 'outputs:volume'
    preview = 'preview'
    sdrMetadata = 'sdrMetadata'
    sourceAsset = 'sourceAsset'
    sourceCode = 'sourceCode'
    strongerThanDescendants = 'strongerThanDescendants'
    subIdentifier = 'subIdentifier'
    surface = 'surface'
    universalRenderContext = ''
    universalSourceType = ''
    volume = 'volume'
    weakerThanDescendants = 'weakerThanDescendants'
    pass
class Utils():
    @staticmethod
    def GetBaseNameAndType(fullName: TfToken) -> tuple: ...
    @staticmethod
    def GetPrefixForAttributeType(sourceType: AttributeType) -> str: ...
    pass
