
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.test_suite.helpers-c7bb18f8a1b53dee.zip"

    [package.publish]
        kitVersion = "107.3.2+production.219701.4663cf0b.gl"
        date = 1757755121
        buildNumber = "107.3.2+1073.219701.4663cf0b.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
