[package]
title = "Activity UsdResolver plugin"
category = "Telemetry"
version = "1.0.4"
description = "Listen to USD resolve/read/write events in order to generate corresponding activities"
authors = ["NVIDIA"]
keywords = ["activity"]
changelog = "docs/CHANGELOG.md"
support_level = "Sample"

[[python.module]]
name = "omni.activity.usd_resolver"

[[native.plugin]]
path = "bin/*.plugin"

[dependencies]
"omni.activity.core" = {}
"omni.usd" = {}

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
]

stdoutFailPatterns.exclude = [
    "*failed to load native plugin*",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]