
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.usd.schema.omnigraph-d63845fac45bce1e.zip"

    [package.publish]
        kitVersion = "107.3.0+feature.195367.2c7fcd57.gl"
        date = 1757755259
        buildNumber = "107.3.0+1073.195367.2c7fcd57.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
