
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.converter.hoops-509.1.0%2B107.3.1.u353.zip"

    [package.target]

        [package.target.usd]
            0 = "u353f+stock+24.05+cxx11"

        [package.target.kit]
            0 = "107.3.1"

    [package.publish]
        kitVersion = "107.3.1+production.206344.d26c4465.gl"
        date = 1755752896
        buildNumber = "203.0.0+main.3718.1495c948.gl"
        repoName = "cad-converter"
        signed = 1
