r"""Imports for support code that will used internally by OmniGraph but should not be used elsewhere.
These are all subject to change without supported deprecation paths.

Internally they can be imported as follows::

    import omni.graph.tools._internal as _ogti

  _____       _                        _   _    _             ____        _
 |_   _|     | |                      | | | |  | |           / __ \      | |
   | |  _ __ | |_ ___ _ __ _ __   __ _| | | |  | |___  ___  | |  | |_ __ | |_   _
   | | | '_ \| __/ _ \ '__| '_ \ / _` | | | |  | / __|/ _ \ | |  | | '_ \| | | | |
  _| |_| | | | ||  __/ |  | | | | (_| | | | |__| \__ \  __/ | |__| | | | | | |_| |
 |_____|_| |_|\__\___|_|  |_| |_|\__,_|_|  \____/|___/\___|  \____/|_| |_|_|\__, |
                                                                             __/ |
                                                                            |___/
"""

__all__ = [
    "autonode_developer_mode",
    "AUTONODE_DEVELOPER_MODE_SETTING",
    "cache_location",
    "Compatibility",
    "extension_contents_factory",
    "ExtensionContentsBase",
    "ExtensionContentsStandalone",
    "ExtensionContentsV118",
    "ExtensionContentsV119",
    "ExtensionVersion_t",
    "FileType",
    "find_ogn_build_directory",
    "full_cache_path",
    "GENERATED_FILE_CONFIG_NAMES",
    "GenerationVersions",
    "get_generator_extension_version",
    "get_module_path",
    "get_ogn_file_name",
    "get_ogn_type_and_node",
    "get_target_extension_version",
    "import_tests_in_directory",
    "load_module_from_file",
    "LOG",
    "NodeTypeDefinition",
    "OGN_AUTOGENERATED_SUBFOLDER_NAME",
    "OmniGraphExtensionError",
    "python_name_to_ui_name",
    "set_registration_logging",
    "Settings",
    "TemporaryCacheLocation",
    "TemporaryLogLocation",
    "VersionProperties",
    "walk_with_excludes",
]

from ._impl.autonode_generator.utils import (
    AUTONODE_DEVELOPER_MODE_SETTING,
    OGN_AUTOGENERATED_SUBFOLDER_NAME,
    autonode_developer_mode,
    python_name_to_ui_name,
)
from ._impl.internal.cache_utils import TemporaryCacheLocation, cache_location, full_cache_path
from ._impl.internal.extension_contents_1_18 import ExtensionContentsV118
from ._impl.internal.extension_contents_1_19 import ExtensionContentsV119
from ._impl.internal.extension_contents_base import ExtensionContentsBase
from ._impl.internal.extension_contents_factory import extension_contents_factory
from ._impl.internal.extension_contents_standalone import ExtensionContentsStandalone
from ._impl.internal.file_utils import (
    GENERATED_FILE_CONFIG_NAMES,
    FileType,
    find_ogn_build_directory,
    get_module_path,
    get_ogn_file_name,
    get_ogn_type_and_node,
    load_module_from_file,
    walk_with_excludes,
)
from ._impl.internal.logging_utils import LOG, OmniGraphExtensionError, TemporaryLogLocation, set_registration_logging
from ._impl.internal.node_type_definition import NodeTypeDefinition
from ._impl.internal.versions import (
    Compatibility,
    ExtensionVersion_t,
    GenerationVersions,
    VersionProperties,
    get_generator_extension_version,
    get_target_extension_version,
)
from ._impl.node_generator.generate_test_imports import import_tests_in_directory
from ._impl.node_generator.utils import Settings
