
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.scene.optimizer.core-107.3.12%2B107.3.0.lx64.r.cp311.u353.zip"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.usd]
            0 = "u353f+stock+24.05+cxx11"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kit]
            0 = "107.3.0"

    [package.publish]
        kitVersion = "107.3.0+feature.190955.64501597.gl"
        date = 1758848958
        buildNumber = "107.3.12+107-3-12.9955.c90a0690.gl"
        repoName = "scene-optimizer"
        signed = 1
