import carb
from dataclasses import dataclass, field


@dataclass
class IncidentData:
    """
    Data class to be generated by each incident event and passed through carb events.
    It holds basic incident event data.
    """

    event_name: str = ""
    event_type: str = ""
    event_position: carb.Float3 = field(default_factory=lambda: carb.Float3(0, 0, 0))


class IncidentCarbEventHelper:
    """
    Helper class to translate incident event name to carb event name.
    """

    EVENT_PREFIX = "isaacsim.replicator.incident/events/"

    @classmethod
    def carb_event_name(cls, incident_name: str):
        return f"{cls.EVENT_PREFIX}/{incident_name}"
