[package]
authors = ["NVIDIA"]
category = "Services"
changelog = "docs/CHANGELOG.md"
description = "Automated Ov authentication from Starfleet"
icon = "data/icon.png"
keywords = ["kit", "nucleus", "asset"]
readme = "docs/README.md"
repository = ""
title = "Automated Ov authentication from Starfleet"
preview_image = "data/preview.png"
version = "0.1.5"

[dependencies]
"omni.services.core" = {}
"omni.services.pip_archive" = {}
"omni.services.client" = {}
"omni.services.transport.client.http_async" = {}
"omni.client" = {}

[[python.module]]
name = "omni.services.starfleet.auth"

[[python.module]]
name = "omniverse_auth"

[[python.module]]
name = "idl"

[settings]
exts."omni.services.starfleet_auth".launcher_url = "http://localhost:33480"

[[test]]
args = [
    "--no-window"
]
