[package]
title = "Hoops Converter Core"
version = "509.1.0"
description = "Hoops Converter Extension using Hoops Exchange SDK."
category = "Converter"
repository = ""

changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"

preview_image = "data/preview.png"
icon = "data/icon.png"

authors = ["NVIDIA"]

writeTarget.kit = true
writeTarget.usd = true

# Keywords for the extension
keywords = [
    'CAD Converter',
    'cad',
    'CATIA',
    'IFC',
    'NX',
    'Parasolid',
    'Solidworks',
    'Autodesk Inventor',
    'CATIA',
    'AutoCAD 3d',
    'Creo',
    'Revit',
    'Solid Edge',
    'STEP'
]

[dependencies]
"omni.kit.converter.common" = { version = "~507.1"}
"omni.services.convert.cad" = { version = "~507.0", optional = true }

[[python.module]]
name = "omni.kit.converter.hoops_core"

[[python.module]]
name = "omni.converter.hoops"

[[python.module]]
name = "omni.converter.hoops.tokens"

[[native.library]]
"filter:platform"."windows-x86_64"."path" = "bin/${lib_prefix}A3DLIBS${lib_ext}"

[[native.library]]
path = "bin/${lib_prefix}omni_converter_hoops${lib_ext}"

# Extension test settings
[[test]]

args = [
    "--/app/file/ignoreUnsavedOnExit=true",
    "--no-window",
    "--/app/fastShutdown=true",
]
dependencies = ["omni.kit.test_suite.helpers", "omni.services.convert.cad"]
stdoutFailPatterns.include = []

 # Ignore errors purposely triggered in test.
stdoutFailPatterns.exclude = [
    "*A3D_LOAD_CANNOT_ACCESS_CADFILE*",
    "*All of the following settings must be specified*",
]

pyCoverageFilter = ["omni.kit.converter.hoops_core"]
pyCoverageOmit = ["*/tests/*"]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
    "docs/Third_Party_Notices.md",
    "docs/Known_Issues.md",
]
