
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.services.core-1.9.0.zip"

    [package.publish]
        kitVersion = "105.1+release.131334.d5a0f2e2.tc"
        date = 1706382206
        buildNumber = "105.1.0+master.2559.64bc6938.gl"
        repoName = "kit-services"
        signed = 1
