[package]
authors = ["NVIDIA"]
category = "services"
changelog = "docs/CHANGELOG.md"
description = "Core of Kit micro services framework."
icon = "data/icon.png"
keywords = ["kit", "service", "core"]
preview_image = "data/preview.png"
readme = "docs/README.md"
repository = ""
slackids = ["@U010NFP76BU"]
title = "Kit Services Core"
version = "1.9.0"

[dependencies]
"omni.kit.async_engine" = { order = -1000 }
"omni.kit.pipapi" = {}
"omni.kit.pip_archive" = {}
"omni.kit.loop" = {}
"omni.services.facilities.base" = {}

[[python.module]]
name = "omni.services.core"

# Main python module this extension provides
[[python.module]]
name = "omni.services.core.main"

# # If support for `asgi_correlation_id` is enabled:
# [[python.module]]
# name = "asgi_correlation_id"

[settings]
# The applications URL root (ie: /api/v0) in case a service is fronted by a Proxy (https://fastapi.tiangolo.com/advanced/behind-a-proxy/)
exts."omni.services.core".root_path = ""
exts."omni.services.core".show_status_endpoint = true

# Configuration options for generating Correlation IDs to requests issues against the Services framework:
[settings.exts."omni.services.core".correlation_id]
# Flag indicating whether to use the default Correlation ID middleware provided by the Services framework:
use_default_middleware = true
# Name of the HTTP Header to read correlation IDs from. `X-Request-ID` and `X-Correlation-ID` are common choices:
header_name = "X-Correlation-ID"
# Flag indicating whether to update the incoming request's header value with the generated correlation ID. This is to
# support use cases where it's relied on the presence of the request header (like various tracing middlewares):
update_request_header = true

[test]
args = [
    "--allow-root",
]
