
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.window.extensions-22939c2c2a248b52.zip"

    [package.publish]
        kitVersion = "107.3.2+production.211116.ba01cfea.gl"
        date = 1757755127
        buildNumber = "107.3.2+1073.211116.ba01cfea.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
