# Copyright (c) 2022-2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
__all__ = ["VisualizationModel"]

from omni.ui import scene as sc
import omni.usd
import numpy as np


class VisualizationModel(sc.AbstractManipulatorModel):
    """
    The model tracks the lines generated by the OgnDrawLines.
    """

    class Line:
        """
        Line class used to hold data for the manipulator to draw lines
        """

        def __init__(self, start, end, color, thickness):
            self.start = np.copy(start)
            self.end = np.copy(end)
            self.color = np.copy(color)
            self.thickness = thickness

        def __eq__(self, other):
            return (
                    np.array_equal(self.start, other.start) and
                    np.array_equal(self.end, other.end) and
                    np.array_equal(self.color, other.color) and
                    self.thickness == other.thickness
            )

    class Label:
        """
        Label class used to hold data for the manipulator to draw text labels
        """

        def __init__(self, text, color, size, transform):
            self.text = str(text)
            self.color = np.copy(color)
            self.size = size
            self.transform = np.copy(transform)

        def __eq__(self, other):
            return (
                    self.text == other.text and
                    np.array_equal(self.color, other.color) and
                    self.size == other.size and
                    np.array_equal(self.transform, other.transform)
            )

    class PositionItem(sc.AbstractManipulatorItem):
        # This is not used except to pass to self._item_changed()
        def __init__(self):
            super().__init__()
            self.value = [0, 0, 0]

    def __new__(cls):
        """Use a class singleton to hold all drawing data from all OgnDrawLine and OgnDrawLabel nodes"""
        if not hasattr(cls, 'instance'):
            cls.instance = super(VisualizationModel, cls).__new__(cls)
            cls.instance.lines = {}
            cls.instance.labels = {}
            cls.instance.position = VisualizationModel.PositionItem()
        return cls.instance

    def __init__(self):
        super().__init__()
        # Save the UsdContext name (we currently only work with a single Context)
        if not hasattr(self, '_events'):
            usd_context = omni.usd.get_context()

            # Track stage events for renaming, deleting, etc
            self._events = usd_context.get_stage_event_stream()
            self._stage_event_sub = self._events.create_subscription_to_pop(
                self._on_stage_event, name="Visualization Update"
            )

    def add_line(self, path, start, end, color, thickness):
        line = VisualizationModel.Line(start, end, color, thickness)
        item = self.lines.get(path)
        if item is None or line != item:
            self.lines[path] = line
            self._item_changed(self.position)

    def add_label(self, path, text, color, size, transform):
        label = VisualizationModel.Label(text, color, size, transform)
        item = self.labels.get(path)
        if item is None or label != item:
            self.labels[path] = label
            self._item_changed(self.position)

    def _on_stage_event(self, event):
        """Called by stage_event_stream.  We only care about selection changes."""
        # If something changed, rename, reparent, open, close, etc, then clear the lines dictionary.
        self.lines.clear()
        self.labels.clear()
        self._item_changed(self.position)

    def __del__(self):
        self.destroy()

    def destroy(self):
        self._stage_event_sub.unsubscribe()
        self._stage_event_sub = None
