[package]
# Semantic Versioning is used: https://semver.org/
version = "107.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "Variant Presenter"

description="A menu to view and manage variants and variant groups"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# Location of change log file in target (final) folder of extension, relative to the root. Can also be just a content
# of it instead of file path. More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Utility"

# Keywords for the extension
keywords = ["variant", "kit", "usd"]

# Icon to show in the extension manager
icon = "data/icon.svg"

# Preview to show in the extension manager
preview_image = "data/preview.png"

# Use omni.ui to build simple UI
[dependencies]
"omni.ui" = {}
"omni.kit.uiapp" = {}
"omni.kit.widget.searchfield" = {}
"omni.kit.core.collection" = {}
"omni.kit.usd.layers" = {}
"omni.kit.widget.zoombar" = {}
"omni.kit.variant.editor" = {optional=true}
"omni.kit.widget.settings" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.content_browser" = {}
"omni.kit.property.usd" = {}
"omni.kit.property.variants" = {optional=true}

# Main python module this extension provides, it will be publicly available as "import omni.kit.variant_presenter".
[[python.module]]
name = "omni.kit.variant.presenter"

[settings.exts."omni.kit.variant.presenter"]
showStartup = false

[[test]]
# Extra dependencies only to be used during test run
dependencies = [
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers",
    "omni.ui",
    "omni.kit.window.content_browser",
    "omni.kit.variant.editor"
]

stdoutFailPatterns.exclude = [
    "*carb::memory::PooledAllocator*",
]

args = [
    "--/exts/omni.kit.variant.presenter/showStartup=true",
    "--no-window"
]