from __future__ import annotations
import pxr.UsdGeom._usdGeom
import typing
import Boost.Python
import pxr.Usd
import pxr.UsdGeom

__all__ = [
    "BBoxCache",
    "BasisCurves",
    "Boundable",
    "Camera",
    "Capsule",
    "Capsule_1",
    "Cone",
    "ConstraintTarget",
    "Cube",
    "Curves",
    "Cylinder",
    "Cylinder_1",
    "GetFallbackUpAxis",
    "GetStageMetersPerUnit",
    "GetStageUpAxis",
    "Gprim",
    "HermiteCurves",
    "Imageable",
    "LinearUnits",
    "LinearUnitsAre",
    "Mesh",
    "ModelAPI",
    "MotionAPI",
    "NurbsCurves",
    "NurbsPatch",
    "Plane",
    "PointBased",
    "PointInstancer",
    "Points",
    "Primvar",
    "PrimvarsAPI",
    "Scope",
    "SetStageMetersPerUnit",
    "SetStageUpAxis",
    "Sphere",
    "StageHasAuthoredMetersPerUnit",
    "Subset",
    "TetMesh",
    "Tokens",
    "VisibilityAPI",
    "Xform",
    "XformCache",
    "XformCommonAPI",
    "XformOp",
    "XformOpTypes",
    "Xformable"
]


class BBoxCache(Boost.Python.instance):
    @staticmethod
    def Clear(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearBaseTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeLocalBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceLocalBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceLocalBounds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceRelativeBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceRelativeBounds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceUntransformedBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceUntransformedBounds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceWorldBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointInstanceWorldBounds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeRelativeBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeUntransformedBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeWorldBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeWorldBoundWithOverrides(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIncludedPurposes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUseExtentsHint(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasBaseTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetBaseTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetIncludedPurposes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetTime(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 504
    pass
class BasisCurves(Curves, PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeInterpolationForSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeUniformDataSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeVaryingDataSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeVertexDataSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateBasisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateWrapAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBasisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWrapAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Boundable(Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeExtent(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeExtentFromPlugins(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Camera(Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateClippingPlanesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateClippingRangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFStopAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFocalLengthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFocusDistanceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHorizontalApertureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHorizontalApertureOffsetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateProjectionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShutterCloseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShutterOpenAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateStereoRoleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVerticalApertureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVerticalApertureOffsetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCamera(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetClippingPlanesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetClippingRangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFStopAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFocalLengthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFocusDistanceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHorizontalApertureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHorizontalApertureOffsetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetProjectionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShutterCloseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShutterOpenAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetStereoRoleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVerticalApertureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVerticalApertureOffsetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetFromCamera(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Capsule(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Capsule_1(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusBottomAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusTopAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusBottomAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusTopAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Cone(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class ConstraintTarget(Boost.Python.instance):
    @staticmethod
    def ComputeInWorldSpace(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConstraintAttrName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIdentifier(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsDefined(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsValid(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Set(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetIdentifier(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Cube(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class NurbsCurves(Curves, PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePointWeightsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRangesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPointWeightsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRangesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Curves(PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeExtent(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCurveVertexCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateWidthsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCurveCount(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCurveVertexCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthsInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetWidthsInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Cylinder(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Cylinder_1(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusBottomAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusTopAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusBottomAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusTopAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class HermiteCurves(Curves, PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    class PointAndTangentArrays(Boost.Python.instance):
        @staticmethod
        def GetPoints(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def GetTangents(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def Interleave(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def IsEmpty(*args, **kwargs) -> typing.Any: ...
        @staticmethod
        def Separate(*args, **kwargs) -> typing.Any: ...
        __instance_size__ = 104
        pass
    @staticmethod
    def CreateTangentsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTangentsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Mesh(PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateCornerIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCornerSharpnessesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCreaseIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCreaseLengthsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCreaseSharpnessesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFaceVaryingLinearInterpolationAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFaceVertexCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFaceVertexIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHoleIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInterpolateBoundaryAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSubdivisionSchemeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTriangleSubdivisionRuleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCornerIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCornerSharpnessesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCreaseIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCreaseLengthsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCreaseSharpnessesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFaceCount(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFaceVaryingLinearInterpolationAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFaceVertexCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFaceVertexIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHoleIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInterpolateBoundaryAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSubdivisionSchemeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTriangleSubdivisionRuleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ValidateTopology(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    SHARPNESS_INFINITE = 10.0
    __instance_size__ = 48
    pass
class NurbsPatch(PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreatePointWeightsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTrimCurveCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTrimCurveKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTrimCurveOrdersAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTrimCurvePointsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTrimCurveRangesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTrimCurveVertexCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUFormAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateURangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUVertexCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVFormAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVRangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVVertexCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPointWeightsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTrimCurveCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTrimCurveKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTrimCurveOrdersAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTrimCurvePointsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTrimCurveRangesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTrimCurveVertexCountsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUFormAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetURangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUVertexCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVFormAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVKnotsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVRangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVVertexCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Plane(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDoubleSidedAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLengthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateWidthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDoubleSidedAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLengthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Points(PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeExtent(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIdsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateWidthsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIdsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPointCount(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthsInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetWidthsInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class PointBased(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeExtent(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointsAtTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePointsAtTimes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateAccelerationsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNormalsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePointsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVelocitiesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAccelerationsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNormalsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNormalsInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPointsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVelocitiesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetNormalsInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Gprim(Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateDisplayColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDisplayColorPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDisplayOpacityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDisplayOpacityPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDoubleSidedAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOrientationAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplayColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplayColorPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplayOpacityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDisplayOpacityPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDoubleSidedAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOrientationAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Scope(Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Sphere(Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Imageable(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    class PurposeInfo(Boost.Python.instance):
        @staticmethod
        def GetInheritablePurpose(*args, **kwargs) -> typing.Any: ...
        @property
        def isInheritable(self) -> None:
            """
            :type: None
            """
        @property
        def purpose(self) -> None:
            """
            :type: None
            """
        __instance_size__ = 40
        pass
    @staticmethod
    def ComputeEffectiveVisibility(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeLocalBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeLocalToWorldTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeParentToWorldTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeProxyPrim(*args, **kwargs) -> typing.Any: 
        """
        Returns None if neither this prim nor any of its ancestors has a valid renderProxy prim.  Otherwise, returns a tuple of (proxyPrim, renderPrimWithAuthoredProxyPrimRel)
        """
    @staticmethod
    def ComputePurpose(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputePurposeInfo(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeUntransformedBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeVisibility(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeWorldBound(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateProxyPrimRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePurposeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOrderedPurposeTokens(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetProxyPrimRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPurposeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPurposeVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def MakeInvisible(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def MakeVisible(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetProxyPrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class LinearUnits(Boost.Python.instance):
    centimeters = 0.01
    feet = 0.3048
    inches = 0.0254
    kilometers = 1000.0
    lightYears = 9460730472580800.0
    meters = 1.0
    micrometers = 1e-06
    miles = 1609.344
    millimeters = 0.001
    nanometers = 1e-09
    yards = 0.9144
    pass
class ModelAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeExtentsHint(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeModelDrawMode(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConstraintTarget(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelApplyDrawModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardGeometryAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardTextureXNegAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardTextureXPosAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardTextureYNegAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardTextureYPosAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardTextureZNegAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelCardTextureZPosAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelDrawModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateModelDrawModeColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConstraintTarget(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConstraintTargets(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentsHint(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExtentsHintAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelApplyDrawModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardGeometryAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardTextureXNegAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardTextureXPosAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardTextureYNegAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardTextureYPosAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardTextureZNegAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelCardTextureZPosAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelDrawModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetModelDrawModeColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetExtentsHint(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class MotionAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeMotionBlurScale(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeNonlinearSampleCount(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeVelocityScale(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateMotionBlurScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNonlinearSampleCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVelocityScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMotionBlurScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNonlinearSampleCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVelocityScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class PointInstancer(Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    class MaskApplication(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'PointInstancer'
        allValues: tuple # value = (UsdGeom.PointInstancer.ApplyMask, UsdGeom.PointInstancer.IgnoreMask)
        pass
    class ProtoXformInclusion(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'PointInstancer'
        allValues: tuple # value = (UsdGeom.PointInstancer.IncludeProtoXform, UsdGeom.PointInstancer.ExcludeProtoXform)
        pass
    @staticmethod
    def ActivateAllIds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ActivateId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ActivateIds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeExtentAtTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeExtentAtTimes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeInstanceTransformsAtTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeInstanceTransformsAtTimes(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeMaskAtTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateAccelerationsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateAngularVelocitiesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIdsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInvisibleIdsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOrientationsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOrientationsfAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePositionsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateProtoIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePrototypesRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateScalesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateVelocitiesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def DeactivateId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def DeactivateIds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAccelerationsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAngularVelocitiesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIdsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInstanceCount(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInvisibleIdsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOrientationsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOrientationsfAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPositionsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetProtoIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrototypesRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetScalesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetVelocitiesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def InvisId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def InvisIds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def VisAllIds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def VisId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def VisIds(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    ApplyMask: pxr.UsdGeom.MaskApplication # value = UsdGeom.PointInstancer.ApplyMask
    ExcludeProtoXform: pxr.UsdGeom.ProtoXformInclusion # value = UsdGeom.PointInstancer.ExcludeProtoXform
    IgnoreMask: pxr.UsdGeom.MaskApplication # value = UsdGeom.PointInstancer.IgnoreMask
    IncludeProtoXform: pxr.UsdGeom.ProtoXformInclusion # value = UsdGeom.PointInstancer.IncludeProtoXform
    __instance_size__ = 48
    pass
class Primvar(Boost.Python.instance):
    @staticmethod
    def BlockIndices(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeFlattened(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDeclarationInfo(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetElementSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIndices(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNamespace(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrimvarName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeSamples(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeSamplesInInterval(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUnauthoredValuesIndex(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasAuthoredElementSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasAuthoredInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasAuthoredValue(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasValue(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsDefined(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsIdTarget(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsIndexed(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsValidInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsValidPrimvarName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def NameContainsNamespaces(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Set(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetElementSize(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetIdTarget(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetIndices(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetInterpolation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetUnauthoredValuesIndex(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SplitName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def StripPrimvarsName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ValueMightBeTimeVarying(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 72
    pass
class PrimvarsAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def BlockPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanContainPropertyName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIndexedPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNonIndexedPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindIncrementallyInheritablePrimvars(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindInheritablePrimvars(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindPrimvarWithInheritance(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindPrimvarsWithInheritance(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAuthoredPrimvars(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrimvars(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrimvarsWithAuthoredValues(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrimvarsWithValues(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasPossiblyInheritedPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def HasPrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def RemovePrimvar(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Subset(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateElementTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFamilyNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateGeomSubset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUniqueGeomSubset(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAllGeomSubsetFamilyNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAllGeomSubsets(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetElementTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFamilyNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFamilyType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetGeomSubsets(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUnassignedIndices(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetFamilyType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ValidateFamily(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ValidateSubsets(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class TetMesh(PointBased, Gprim, Boundable, Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ComputeSurfaceFaces(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSurfaceFaceVertexIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTetVertexIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def FindInvertedElements(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSurfaceFaceVertexIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTetVertexIndicesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Tokens(Boost.Python.instance):
    BasisCurves = 'BasisCurves'
    Boundable = 'Boundable'
    Camera = 'Camera'
    Capsule = 'Capsule'
    Capsule_1 = 'Capsule_1'
    Cone = 'Cone'
    Cube = 'Cube'
    Curves = 'Curves'
    Cylinder = 'Cylinder'
    Cylinder_1 = 'Cylinder_1'
    GeomModelAPI = 'GeomModelAPI'
    GeomSubset = 'GeomSubset'
    Gprim = 'Gprim'
    HermiteCurves = 'HermiteCurves'
    Imageable = 'Imageable'
    Mesh = 'Mesh'
    MotionAPI = 'MotionAPI'
    NurbsCurves = 'NurbsCurves'
    NurbsPatch = 'NurbsPatch'
    Plane = 'Plane'
    PointBased = 'PointBased'
    PointInstancer = 'PointInstancer'
    Points = 'Points'
    PrimvarsAPI = 'PrimvarsAPI'
    Scope = 'Scope'
    Sphere = 'Sphere'
    TetMesh = 'TetMesh'
    VisibilityAPI = 'VisibilityAPI'
    Xform = 'Xform'
    XformCommonAPI = 'XformCommonAPI'
    Xformable = 'Xformable'
    accelerations = 'accelerations'
    all = 'all'
    angularVelocities = 'angularVelocities'
    axis = 'axis'
    basis = 'basis'
    bezier = 'bezier'
    bilinear = 'bilinear'
    boundaries = 'boundaries'
    bounds = 'bounds'
    box = 'box'
    bspline = 'bspline'
    cards = 'cards'
    catmullClark = 'catmullClark'
    catmullRom = 'catmullRom'
    clippingPlanes = 'clippingPlanes'
    clippingRange = 'clippingRange'
    closed = 'closed'
    constant = 'constant'
    cornerIndices = 'cornerIndices'
    cornerSharpnesses = 'cornerSharpnesses'
    cornersOnly = 'cornersOnly'
    cornersPlus1 = 'cornersPlus1'
    cornersPlus2 = 'cornersPlus2'
    creaseIndices = 'creaseIndices'
    creaseLengths = 'creaseLengths'
    creaseSharpnesses = 'creaseSharpnesses'
    cross = 'cross'
    cubic = 'cubic'
    curveVertexCounts = 'curveVertexCounts'
    default_ = 'default'
    doubleSided = 'doubleSided'
    edge = 'edge'
    edgeAndCorner = 'edgeAndCorner'
    edgeOnly = 'edgeOnly'
    elementSize = 'elementSize'
    elementType = 'elementType'
    exposure = 'exposure'
    extent = 'extent'
    extentsHint = 'extentsHint'
    fStop = 'fStop'
    face = 'face'
    faceVarying = 'faceVarying'
    faceVaryingLinearInterpolation = 'faceVaryingLinearInterpolation'
    faceVertexCounts = 'faceVertexCounts'
    faceVertexIndices = 'faceVertexIndices'
    familyName = 'familyName'
    focalLength = 'focalLength'
    focusDistance = 'focusDistance'
    fromTexture = 'fromTexture'
    guide = 'guide'
    guideVisibility = 'guideVisibility'
    height = 'height'
    hermite = 'hermite'
    holeIndices = 'holeIndices'
    horizontalAperture = 'horizontalAperture'
    horizontalApertureOffset = 'horizontalApertureOffset'
    ids = 'ids'
    inactiveIds = 'inactiveIds'
    indices = 'indices'
    inherited = 'inherited'
    interpolateBoundary = 'interpolateBoundary'
    interpolation = 'interpolation'
    invisible = 'invisible'
    invisibleIds = 'invisibleIds'
    knots = 'knots'
    left = 'left'
    leftHanded = 'leftHanded'
    length = 'length'
    linear = 'linear'
    loop = 'loop'
    metersPerUnit = 'metersPerUnit'
    modelApplyDrawMode = 'model:applyDrawMode'
    modelCardGeometry = 'model:cardGeometry'
    modelCardTextureXNeg = 'model:cardTextureXNeg'
    modelCardTextureXPos = 'model:cardTextureXPos'
    modelCardTextureYNeg = 'model:cardTextureYNeg'
    modelCardTextureYPos = 'model:cardTextureYPos'
    modelCardTextureZNeg = 'model:cardTextureZNeg'
    modelCardTextureZPos = 'model:cardTextureZPos'
    modelDrawMode = 'model:drawMode'
    modelDrawModeColor = 'model:drawModeColor'
    mono = 'mono'
    motionBlurScale = 'motion:blurScale'
    motionNonlinearSampleCount = 'motion:nonlinearSampleCount'
    motionVelocityScale = 'motion:velocityScale'
    nonOverlapping = 'nonOverlapping'
    none = 'none'
    nonperiodic = 'nonperiodic'
    normals = 'normals'
    open = 'open'
    order = 'order'
    orientation = 'orientation'
    orientations = 'orientations'
    orientationsf = 'orientationsf'
    origin = 'origin'
    orthographic = 'orthographic'
    partition = 'partition'
    periodic = 'periodic'
    perspective = 'perspective'
    pinned = 'pinned'
    pivot = 'pivot'
    point = 'point'
    pointWeights = 'pointWeights'
    points = 'points'
    positions = 'positions'
    power = 'power'
    primvarsDisplayColor = 'primvars:displayColor'
    primvarsDisplayOpacity = 'primvars:displayOpacity'
    projection = 'projection'
    protoIndices = 'protoIndices'
    prototypes = 'prototypes'
    proxy = 'proxy'
    proxyPrim = 'proxyPrim'
    proxyVisibility = 'proxyVisibility'
    purpose = 'purpose'
    radius = 'radius'
    radiusBottom = 'radiusBottom'
    radiusTop = 'radiusTop'
    ranges = 'ranges'
    render = 'render'
    renderVisibility = 'renderVisibility'
    right = 'right'
    rightHanded = 'rightHanded'
    scales = 'scales'
    shutterClose = 'shutter:close'
    shutterOpen = 'shutter:open'
    size = 'size'
    smooth = 'smooth'
    stereoRole = 'stereoRole'
    subdivisionScheme = 'subdivisionScheme'
    surfaceFaceVertexIndices = 'surfaceFaceVertexIndices'
    tangents = 'tangents'
    tetVertexIndices = 'tetVertexIndices'
    tetrahedron = 'tetrahedron'
    triangleSubdivisionRule = 'triangleSubdivisionRule'
    trimCurveCounts = 'trimCurve:counts'
    trimCurveKnots = 'trimCurve:knots'
    trimCurveOrders = 'trimCurve:orders'
    trimCurvePoints = 'trimCurve:points'
    trimCurveRanges = 'trimCurve:ranges'
    trimCurveVertexCounts = 'trimCurve:vertexCounts'
    type = 'type'
    uForm = 'uForm'
    uKnots = 'uKnots'
    uOrder = 'uOrder'
    uRange = 'uRange'
    uVertexCount = 'uVertexCount'
    unauthoredValuesIndex = 'unauthoredValuesIndex'
    uniform = 'uniform'
    unrestricted = 'unrestricted'
    upAxis = 'upAxis'
    vForm = 'vForm'
    vKnots = 'vKnots'
    vOrder = 'vOrder'
    vRange = 'vRange'
    vVertexCount = 'vVertexCount'
    varying = 'varying'
    velocities = 'velocities'
    vertex = 'vertex'
    verticalAperture = 'verticalAperture'
    verticalApertureOffset = 'verticalApertureOffset'
    visibility = 'visibility'
    visible = 'visible'
    width = 'width'
    widths = 'widths'
    wrap = 'wrap'
    x = 'X'
    xformOpOrder = 'xformOpOrder'
    y = 'Y'
    z = 'Z'
    pass
class VisibilityAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateGuideVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateProxyVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRenderVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetGuideVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetProxyVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPurposeVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRenderVisibilityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Xform(Xformable, Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class XformCache(Boost.Python.instance):
    @staticmethod
    def Clear(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeRelativeTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLocalToWorldTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLocalTransformation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetParentToWorldTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetTime(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Swap(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 72
    pass
class XformCommonAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    class OpFlags(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'XformCommonAPI'
        allValues: tuple # value = (UsdGeom.XformCommonAPI.OpTranslate, UsdGeom.XformCommonAPI.OpRotate, UsdGeom.XformCommonAPI.OpScale, UsdGeom.XformCommonAPI.OpPivot)
        pass
    class RotationOrder(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'XformCommonAPI'
        allValues: tuple # value = (UsdGeom.XformCommonAPI.RotationOrderXYZ, UsdGeom.XformCommonAPI.RotationOrderXZY, UsdGeom.XformCommonAPI.RotationOrderYXZ, UsdGeom.XformCommonAPI.RotationOrderYZX, UsdGeom.XformCommonAPI.RotationOrderZXY, UsdGeom.XformCommonAPI.RotationOrderZYX)
        pass
    @staticmethod
    def CanConvertOpTypeToRotationOrder(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConvertOpTypeToRotationOrder(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConvertRotationOrderToOpType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateXformOps(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetResetXformStack(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotationTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetXformVectors(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetXformVectorsByAccumulation(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetPivot(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetResetXformStack(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetRotate(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetScale(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetTranslate(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetXformVectors(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    OpPivot: pxr.UsdGeom.OpFlags # value = UsdGeom.XformCommonAPI.OpPivot
    OpRotate: pxr.UsdGeom.OpFlags # value = UsdGeom.XformCommonAPI.OpRotate
    OpScale: pxr.UsdGeom.OpFlags # value = UsdGeom.XformCommonAPI.OpScale
    OpTranslate: pxr.UsdGeom.OpFlags # value = UsdGeom.XformCommonAPI.OpTranslate
    RotationOrderXYZ: pxr.UsdGeom.RotationOrder # value = UsdGeom.XformCommonAPI.RotationOrderXYZ
    RotationOrderXZY: pxr.UsdGeom.RotationOrder # value = UsdGeom.XformCommonAPI.RotationOrderXZY
    RotationOrderYXZ: pxr.UsdGeom.RotationOrder # value = UsdGeom.XformCommonAPI.RotationOrderYXZ
    RotationOrderYZX: pxr.UsdGeom.RotationOrder # value = UsdGeom.XformCommonAPI.RotationOrderYZX
    RotationOrderZXY: pxr.UsdGeom.RotationOrder # value = UsdGeom.XformCommonAPI.RotationOrderZXY
    RotationOrderZYX: pxr.UsdGeom.RotationOrder # value = UsdGeom.XformCommonAPI.RotationOrderZYX
    __instance_size__ = 56
    pass
class XformOp(Boost.Python.instance):
    class Precision(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'XformOp'
        allValues: tuple # value = (UsdGeom.XformOp.PrecisionDouble, UsdGeom.XformOp.PrecisionFloat, UsdGeom.XformOp.PrecisionHalf)
        pass
    class Type(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'XformOp'
        allValues: tuple # value = (UsdGeom.XformOp.TypeInvalid, UsdGeom.XformOp.TypeTranslate, UsdGeom.XformOp.TypeScale, UsdGeom.XformOp.TypeRotateX, UsdGeom.XformOp.TypeRotateY, UsdGeom.XformOp.TypeRotateZ, UsdGeom.XformOp.TypeRotateXYZ, UsdGeom.XformOp.TypeRotateXZY, UsdGeom.XformOp.TypeRotateYXZ, UsdGeom.XformOp.TypeRotateYZX, UsdGeom.XformOp.TypeRotateZXY, UsdGeom.XformOp.TypeRotateZYX, UsdGeom.XformOp.TypeOrient, UsdGeom.XformOp.TypeTransform)
        pass
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetBaseName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNamespace(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNumTimeSamples(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOpName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOpTransform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOpType(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOpTypeEnum(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOpTypeToken(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPrecision(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeSamples(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeSamplesInInterval(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeName(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsDefined(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsInverseOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def MightBeTimeVarying(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Set(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SplitName(*args, **kwargs) -> typing.Any: ...
    PrecisionDouble: pxr.UsdGeom.Precision # value = UsdGeom.XformOp.PrecisionDouble
    PrecisionFloat: pxr.UsdGeom.Precision # value = UsdGeom.XformOp.PrecisionFloat
    PrecisionHalf: pxr.UsdGeom.Precision # value = UsdGeom.XformOp.PrecisionHalf
    TypeInvalid: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeInvalid
    TypeOrient: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeOrient
    TypeRotateX: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateX
    TypeRotateXYZ: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateXYZ
    TypeRotateXZY: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateXZY
    TypeRotateY: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateY
    TypeRotateYXZ: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateYXZ
    TypeRotateYZX: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateYZX
    TypeRotateZ: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateZ
    TypeRotateZXY: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateZXY
    TypeRotateZYX: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeRotateZYX
    TypeScale: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeScale
    TypeTransform: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeTransform
    TypeTranslate: pxr.UsdGeom.Type # value = UsdGeom.XformOp.TypeTranslate
    __instance_size__ = 160
    pass
class XformOpTypes(Boost.Python.instance):
    orient = 'orient'
    resetXformStack = '!resetXformStack!'
    rotateX = 'rotateX'
    rotateXYZ = 'rotateXYZ'
    rotateXZY = 'rotateXZY'
    rotateY = 'rotateY'
    rotateYXZ = 'rotateYXZ'
    rotateYZX = 'rotateYZX'
    rotateZ = 'rotateZ'
    rotateZXY = 'rotateZXY'
    rotateZYX = 'rotateZYX'
    scale = 'scale'
    transform = 'transform'
    translate = 'translate'
    pass
class Xformable(Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def AddOrientOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateXOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateXYZOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateXZYOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateYOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateYXZOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateYZXOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateZOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateZXYOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddRotateZYXOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddScaleOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddTransformOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddTranslateOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def AddXformOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ClearXformOpOrder(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateXformOpOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLocalTransformation(*args, **kwargs) -> typing.Any: 
        """
        Compute the fully-combined, local-to-parent transformation for this prim.
        If a client does not need to manipulate the individual ops themselves, and requires only the combined transform on this prim, this method will take care of all the data marshalling and linear algebra needed to combine the ops into a 4x4 affine transformation matrix, in double-precision, regardless of the precision of the op inputs.
        The python version of this function only returns the computed  local-to-parent transformation. Clients must independently call  GetResetXformStack() to be able to construct the local-to-world transformation.

        Compute the fully-combined, local-to-parent transformation for this prim as efficiently as possible, using pre-fetched list of ordered xform ops supplied by the client.
        The python version of this function only returns the computed  local-to-parent transformation. Clients must independently call  GetResetXformStack() to be able to construct the local-to-world transformation.
        """
    @staticmethod
    def GetOrderedXformOps(*args, **kwargs) -> typing.Any: 
        """
        Return the ordered list of transform operations to be applied to this prim, in least-to-most-local order.  This is determined by the intersection of authored op-attributes and the explicit ordering of those attributes encoded in the "xformOpOrder" attribute on this prim.

        Any entries in "xformOpOrder" that do not correspond to valid attributes on the xformable prim are skipped and a warning is issued.

        A UsdGeomTransformable that has not had any ops added via AddXformOp() will return an empty vector.



        The python version of this function only returns the ordered list of xformOps. Clients must independently call GetResetXformStack() if they need the info.
        """
    @staticmethod
    def GetOrientOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetResetXformStack(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateXOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateXYZOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateXZYOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateYOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateYXZOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateYZXOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateZOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateZXYOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRotateZYXOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetScaleOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeSamples(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeSamplesInInterval(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTransformOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTranslateOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetXformOp(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetXformOpOrderAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsTransformationAffectedByAttrNamed(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def MakeMatrixXform(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetResetXformStack(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def SetXformOpOrder(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def TransformMightBeTimeVarying(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class _CanApplyResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
def GetFallbackUpAxis(*args, **kwargs) -> typing.Any:
    pass
def GetStageMetersPerUnit(*args, **kwargs) -> typing.Any:
    pass
def GetStageUpAxis(*args, **kwargs) -> typing.Any:
    pass
def LinearUnitsAre(*args, **kwargs) -> typing.Any:
    pass
def SetStageMetersPerUnit(*args, **kwargs) -> typing.Any:
    pass
def SetStageUpAxis(*args, **kwargs) -> typing.Any:
    pass
def StageHasAuthoredMetersPerUnit(*args, **kwargs) -> typing.Any:
    pass
__MFB_FULL_PACKAGE_NAME = 'usdGeom'
