[package]
title = "OmniGraph Tools"
# Note that for this extension the semantic versioning is interpreted slightly differently as it has to be concerned
# with the public Python API, the content of the generated code, and the .ogn format. Ordinarily the versioning of the
# generated code would be handled by a dependency on a particular version of omni.graph/omni.graph.core, however as
# this extension cannot see them the dependency has to be managed manually.
#
#    MAJOR VERSION: Changes are made to the generated code, OGN format, or the public API that are not backward compatible.
#                   i.e. the user has to change some of their code to make it work with the new version
#
#    MINOR VERSION: 1. A change is made to the Python API that is backward compatible with no user changes
#                   2. A change is made to the .ogn format that is backward compatible with no user changes
#                   3. A change is made that would require regeneration of the Python node database at runtime in order
#                     to ensure backward compatibility, but with no user changes required to the .ogn or node files.
#                     e.g. extra runtime information is added to the database
#
#    PATCH VERSION: 1. A change is made to the implementation of the Python API that does not change functionality
#                   2. A change is made to the .ogn parsing that does not change the generated code
#
version = "1.79.2"
category = "Graph"
readme = "docs/README.md"
changelog = "docs/CHANGELOG.md"
description = "Contains the implementation of the Omniverse Graph node generator scripts."
repository = ""
support_level = "Core"
keywords = ["kit", "omnigraph", "tools"]
authors = ["NVIDIA"]

# The tools are used for the build and so have no dependencies
[dependencies]
"omni.usd.libs" = {}
# The tests generated by the node parser import omni.kit.test and we import them even when not running tests.
# See OM-109169.
"omni.kit.test" = {}

# Main python module this extension provides, it will be publicly available as "import omni.graph.tools".
[[python.module]]
name = "omni.graph.tools"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
]
terms = [
    "docs/TERMS",
]

[[tests]]
pyCoverageOmit = [
    "omni/graph/tools/_impl/autonode_generator",
    "omni/graph/tools/generate_node.py", # Build script; not used at runtime.
    "omni/graph/tools/make_docs_toc.py", # Build script; not used at runtime.
]
