"""
This file is auto-generated by idl.core.
Do not change it manually.
"""

from typing import Union, List, Optional, Dict
from idl.types import Enum, Record

{% set generation = namespace(last={"type": "struct"}) -%}
{%- for definition in spec -%}
{%- if definition.type == "enum" %}
{%- if generation.last.type not in ["struct", "enum"] or (generation.last.type == "struct" and generation.last.mapping) -%}
{%- raw %}

{% endraw -%}
{%- endif %}
class {{ definition.name }}(metaclass=Enum):
    {%- for member in definition.members %}
    {{ member.name }} = {{ member.value }}
    {%- endfor %}

{% elif definition.type == "const" %}
{{ definition.name }} = {{ definition.value }}
{%- elif definition.type == "alias" %}
{{ definition.name }} = {{ definition.value|py.type_name }}
{%- elif definition.type == "union" %}
{{ definition.name }} = Union[{{ ", ".join(definition['members']|map('py.type_name')) }}]
{%- elif definition.type == "struct" -%}
{%- if generation.last.type not in ["struct", "enum"] or (generation.last.type == "struct" and generation.last.mapping) -%}
{%- raw %}

{% endraw -%}
{%- endif %}
{% if definition.mapping -%}
{{ definition.name }} = Dict[{{ definition.mapping.key|py.type_name }}, {{ definition.mapping.value|py.type }}]

{%- else -%}
class {{ definition.name }}{% if definition.extends %}({{ definition.extends }}){% else %}(Record){% endif %}:
    {%- for field in definition.fields %}
    {{ field.name }}: {{ field|py.type }}
    {%- else %}
    pass
    {%- endfor %}

{% endif -%}
{%- endif -%}
{%- set generation.last = definition -%}
{%- endfor -%}
