
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.window.quicksearch-2.4.4.zip"

    [package.publish]
        kitVersion = "105.2+release.137305.fba2ab7a.tc"
        date = 1709137095
        buildNumber = "1.0.0+main.44.2c407d82.gl"
        repoName = "kit-quicksearch"
        signed = 1
