
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.pip_archive-d38fa9ecd1fb6df4.zip"

    [package.publish]
        kitVersion = "107.3.2+production.214668.960036eb.gl"
        date = 1757755257
        buildNumber = "107.3.2+1073.214668.960036eb.gl"

    [package.target]

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
