
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.window.material_graph-1.9.1.zip"

    [package.publish]
        kitVersion = "108.0.0+feature.217967.1c73315e.gl"
        date = 1756892184
        buildNumber = "108.0.0+main.231.fec8f509.gl"
        repoName = "kit-sample-extensions"
        signed = 1
