"""
Create a table off contents file in index.rst that references all of the OmniGraph node generated
documentation files that live in that directory.

This processing is highly tied to the formatting of the OGN generated documentation files so if they
change this has to as well.

Two tables of contents are produced:
- index.rst, where the nodes are grouped by category
- byExtension.rst, where the nodes are grouped by the extension that owns them

In both cases the number of columns the node names are listed in is configurable, defaulting to 4. Each entry is just
the name of the node type as a link to its full documentation.

In the case of the grouping by category, a node type may appear in multiple places if it has multiple categories.
There is also an added "Uncategorized" grouping to capture those types that do not have a category specified.

Only those node types who have documentation generated by the build are added to this index. Node types created at
runtime must have their documentation accessed in some other way
"""

import argparse
import logging
import os
import sys
from enum import Enum, auto
from pathlib import Path

from .generate_documentation import (
    RE_OGN_BODY_MARKER,
    RE_OGN_CATEGORIES,
    RE_OGN_DESCRIPTION_BEGIN,
    RE_OGN_DESCRIPTION_END,
    RE_OGN_NAME_INFO,
)
from .utils import ReadableDirs, WritableDir, logger, rst_title

# If True then perform more aggressive directory checks, not safe in a multi-threaded environment
SAFE_DIRECTORY_CREATION = False

# Name of the generated files
BY_CATEGORY_FILENAME = "index.rst"
BY_EXTENSION_FILENAME = "byExtension.rst"

# RST labels for each of the generated files
BY_CATEGORY_LABEL = "ogn_index_by_category"
BY_EXTENSION_LABEL = "ogn_index_by_extension"


# ==============================================================================================================
class OgnIndexCreator:
    """Handler to analyze OGN documentation files and generate a Table of Contents for them

    Attributes:
        documentation_files: List of (file, extension) of documentation files found for inclusion
        by_category_file_path: Full path to the generated index file organized by category
        by_extension_file_path: Full path to the generated index file organized by extension
        ogn_directory: Path where the table of contents will be generated
        extension_directories: List of paths where extensions with generated documentation live
        read_parser: Argument for extension directories, saved to allow delayed validation
        warnings_only: Downgrade all errors to warnings (mostly for testing error states)
    """

    def __init__(self):
        self.ogn_directory = None
        self.extension_directories = None
        self.by_category_file_path = None
        self.by_extension_file_path = None
        self.documentation_files = []
        self.read_parser = None
        self.warnings_only = False

    # --------------------------------------------------------------------------------------------------------------
    def _error(self, *args, **kwargs):
        """Log an error message, demoting to a warning if in test mode to avoid failures when testing error states"""
        (logger.warn if self.warnings_only else logger.error)(*args, **kwargs)

    # --------------------------------------------------------------------------------------------------------------
    def construct_parser(self) -> argparse.ArgumentParser:
        """Construct and return the parser for the script arguments"""

        # If no output directory is specified generated files will end up in the current directory
        default_output_dir = Path.cwd()

        # This helps format the usage information in a nicer way
        os.putenv("COLUMNS", "120")

        # Construct the parsing information. Run the script with "--help" to see the usage.
        parser = argparse.ArgumentParser(
            description="Read a directory of OGN documentation files and create an index for them",
            formatter_class=argparse.RawTextHelpFormatter,
        )
        parser.add_argument(
            "-od",
            "--ognDirectory",
            action=WritableDir,
            const=default_output_dir,
            default=default_output_dir,
            type=Path,
            metavar="DIR",
            help="Directory containing the OGN documentation files, where the index will be generated",
        )
        # Remember the extensionRoot argument Action so that the values can be validated by ReadableDirs before use
        # as it's the only way to have a custom action respect the "nargs" value.
        self.read_parser = parser.add_argument(
            "-er",
            "--extensionRoot",
            action=ReadableDirs,
            type=Path,
            nargs="+",
            metavar="DIR",
            help="Root directories where extensions can be found that contain generated documentation files",
        )
        parser.add_argument("-w", "--warningsOnly", action="store_true", help="Downgrade errors to warnings")
        parser.add_argument("-v", "--verbose", action="store_true", help="Output basic debugging information")
        parser.add_argument("-vv", "--veryVerbose", action="store_true", help="Output detailed debugging information")
        return parser

    # --------------------------------------------------------------------------------------------------------------
    def parse(self, args_to_parse: list = None):
        """Parse the arguments to configure the index creator

        Args:
            args_to_parse: List of arguments in the form of sys.argv
        """
        parser = self.construct_parser()
        args = parser.parse_args(args_to_parse)
        self.read_parser.validate()

        # If the script steps are to be echoed enable the logger and dump the script arguments as a first step
        logger.setLevel(logging.DEBUG if args.veryVerbose else logging.INFO if args.verbose else logging.WARN)
        logger.info("ognDirectory = %s", args.ognDirectory)
        logger.info("extensionRoot = %s", args.extensionRoot)

        self.ogn_directory = args.ognDirectory
        self.extension_directories = args.extensionRoot
        self.warnings_only = args.warningsOnly
        self.by_category_file_path = self.ogn_directory / BY_CATEGORY_FILENAME
        self.by_extension_file_path = self.ogn_directory / BY_EXTENSION_FILENAME

    # --------------------------------------------------------------------------------------------------------------
    def _add_all_node_type_definitions(self, root_directory: Path):
        """Scans the root_directory and adds all node type definitions from documentation

        The root directory is assumed to house a list of subdirectories. Each subdirectory is checked for a
        further subdirectory with the path "ogn/docs", where generated node type documentation lives. No other
        directories are scanned when looking for the documentation.

        Args:
            root_directory: Directory to scan for documentation
        """
        logger.info("Looking for node type documentation files in %s", root_directory)

        for extension_directory in root_directory.iterdir():
            ogn_docs_directory = extension_directory / "ogn" / "docs"
            if not ogn_docs_directory.is_dir():
                continue
            docs_found = 0
            for node_type_docs_file in ogn_docs_directory.iterdir():
                if node_type_docs_file.is_file() and node_type_docs_file.suffix == ".rst":
                    logger.debug("   Adding node type %s", node_type_docs_file)
                    self.documentation_files.append((node_type_docs_file, extension_directory.name))
                    docs_found += 1
            logger.info("  Adding extension %s = %d nodes", extension_directory.name, docs_found)

    # --------------------------------------------------------------------------------------------------------------
    def extract_node_type_information(self, ogn_doc_path: str) -> tuple[str, str, str, list[str]]:
        """Read the OGN documentation file and extract the information to use for the index

        Patterns assumed, in order:
            One line matching RE_OGN_BODY_MARKER with the link to the node type documentation
            One line matching RE_OGN_NAME_INFO with the node name
            One line matching RE_OGN_DESCRIPTION_BEGIN followed by one or more lines with the description, terminated
            by one line matching RE_OGN_DESCRIPTION_END, marking the end of the description. Blank lines at the start
            and end of the description are ignored.
            One line matching RE_OGN_CATEGORIES with the list of categories to which the node type belongs
            The rest will be ignored as there is no more relevant information

        Args:
            ogn_doc_path: Path to the node's documentation file

        Returns:
            (Marker, Name, Description, Categories) tuple with the node's information
        """
        logger.debug("Extracting node type information from documentation file %s", ogn_doc_path)
        name = ""
        description = []
        categories = []
        marker = ""

        class ParseState(Enum):
            """The phases of parsing a node type documentation file for specific information"""

            LOOKING_FOR_LABEL = auto()
            """Start of the parse, looking for the label linking to the node type documentation file"""
            LOOKING_FOR_NAME = auto()
            """Found the label, now looking for the node type name"""
            LOOKING_FOR_DESCRIPTION = auto()
            """Found the node type name, now looking for the node type description start tag"""
            READING_DESCRIPTION = auto()
            """Found the node type description start tag, reading description lines until encountering the end tag"""
            LOOKING_FOR_CATEGORIES = auto()
            """Found the node type description end tag, now looking for the category list (may not have any)"""

        try:
            parse_state = ParseState.LOOKING_FOR_LABEL
            with open(ogn_doc_path, "r", encoding="utf-8") as doc_fd:
                for line in doc_fd:
                    match parse_state:
                        case ParseState.LOOKING_FOR_LABEL:
                            body_marker_match = RE_OGN_BODY_MARKER.match(line)
                            if body_marker_match:
                                parse_state = ParseState.LOOKING_FOR_NAME
                                marker = body_marker_match.group(1)
                        case ParseState.LOOKING_FOR_NAME:
                            name_match = RE_OGN_NAME_INFO.match(line)
                            if name_match:
                                parse_state = ParseState.LOOKING_FOR_DESCRIPTION
                                name = name_match.group(1).rstrip()
                        case ParseState.LOOKING_FOR_DESCRIPTION:
                            start_description_match = RE_OGN_DESCRIPTION_BEGIN.match(line)
                            if start_description_match:
                                parse_state = ParseState.READING_DESCRIPTION
                        case ParseState.READING_DESCRIPTION:
                            if RE_OGN_DESCRIPTION_END.match(line):
                                parse_state = ParseState.LOOKING_FOR_CATEGORIES
                            else:
                                description.append(line[:-1])
                        case ParseState.LOOKING_FOR_CATEGORIES:
                            category_match = RE_OGN_CATEGORIES.match(line)
                            if category_match:
                                categories = category_match.group(1).split(",")
                                break

            if not marker:
                self._error("Marker not found in %s", ogn_doc_path)
            if not name:
                self._error("Name not found in %s", ogn_doc_path)
            if not description:
                self._error("Description not found in %s", ogn_doc_path)
            if not categories:
                logger.debug("No categories found in %s", ogn_doc_path)
        except Exception as error:  # pylint: disable=broad-except
            # Report the failure but continue processing other files
            self._error("Error processing %s: %s", ogn_doc_path, error)

        return (marker, name, description, categories)

    # --------------------------------------------------------------------------------------------------------------
    def _construct_category_grouping_index(
        self, node_type_information: dict[Path, tuple[str, str, list[str], list[str], str]], keys: list[Path]
    ):
        """Construct the index file with the node types grouped by category

        Args:
            node_type_information: Dictionary of node type information that was extracted from all of the generation
                              documentation files. The key is the path to the file, the value is a tuple with
                              the RST link label to the file, the node type UI name, the list of strings comprising the
                              node type description, the list of strings comprising the node type's categories, and
                              a string that is the node type's extension
            keys: A list of keys to node_type_information, sorted in order by node type UI name
        """
        logger.info("Constructing the index grouped by category for %d node types", len(keys))
        uncategorized = "__UNCATEGORIZED__"

        # Construct the list with a union of all categories found for all node types
        all_categories = set()
        node_types_in_category = {uncategorized: []}
        for node_docs_path, (_, _, _, node_type_categories, _) in node_type_information.items():
            all_categories.update(set(node_type_categories))
            for category in node_type_categories or [uncategorized]:
                node_types_in_category[category] = node_types_in_category.get(category, []) + [node_docs_path]
        logger.info("Categories: %s", all_categories)

        # Standardize the formatting of category names for making titles
        category_titles = {uncategorized: "No Category"}
        for raw_category_name in all_categories:
            category_name = raw_category_name.lower()
            category_name = category_name.replace(":", "-")
            category_name = category_name.replace(".", "-")
            category_name = category_name.replace("_", "-")
            category_name = category_name.replace(" ", "-")
            category_titles[raw_category_name] = " ".join(category_name.split("-")).title()

        # Gather the new contents of the file in a list first so that it can be compared against current contents
        # and not written if nothing has changed.
        new_contents = []
        new_contents.append(":orphan:\n")
        new_contents.append("\n")
        new_contents.append(".. _omnigraph_nodes_by_category:\n\n")
        new_contents.append(rst_title("OmniGraph Nodes By Category", 0))
        new_contents.append("\n")
        new_contents.append("See also the list :ref:`grouped by extension<omnigraph_nodes_by_extension>`\n\n")

        for category_name in sorted(category_titles.keys()):
            category_node_types = node_types_in_category[category_name]
            if not category_node_types:
                continue
            category_title = category_titles[category_name]
            new_contents.append(rst_title(category_title, 1))
            new_contents.append("\n")
            for node_docs_path in keys:
                if node_docs_path not in category_node_types:
                    continue
                label, name, _, _, _ = node_type_information[node_docs_path]
                new_contents.append(f"- :ref:`{name} <{label}>`\n")
            new_contents.append("\n")

        # If the old contents did not exist or were different from the new contents then write out the file
        try:
            with open(self.by_category_file_path, "r", newline="\n", encoding="utf-8") as index_file:
                current_contents = "".join(index_file.readlines())
            contents_have_changed = current_contents != "".join(new_contents)
        except IOError:
            contents_have_changed = True

        if contents_have_changed:
            logger.info("Category index file has changed. Writing the new contents.")
            # Using the explicit newline so that the file reflects the Python strings on all platforms
            with open(self.by_category_file_path, "w", newline="\n", encoding="utf-8") as index_file:
                for line in new_contents:
                    index_file.write(line)

    # --------------------------------------------------------------------------------------------------------------
    def _construct_extension_grouping_index(
        self, node_type_information: dict[Path, tuple[str, str, list[str], list[str]]], keys: list[Path]
    ):
        """Construct the index file with the node types grouped by extension

        Args:
            node_type_information: Dictionary of node type information that was extracted from all of the generation
                              documentation files. The key is the path to the file, the value is a tuple with
                              the RST link label to the file, the node type UI name, the list of strings comprising the
                              node type description, the list of strings comprising the node type's categories, and
                              a string that is the node type's extension
            keys: A list of keys to node_type_information, sorted in order by node type UI name
        """
        logger.info("Constructing the index grouped by extension for %d node types", len(keys))

        # Construct the list with a union of all categories found for all node types
        all_extensions = set()
        node_types_in_extension = {}
        for node_docs_path, (_, _, _, _, extension) in node_type_information.items():
            all_extensions.add(extension)
            node_types_in_extension[extension] = node_types_in_extension.get(extension, []) + [node_docs_path]
        logger.info("Extensions: %s", all_extensions)

        # Gather the new contents of the file in a list first so that it can be compared against current contents
        # and not written if nothing has changed.
        new_contents = []
        new_contents.append(":orphan:\n")
        new_contents.append("\n")
        new_contents.append(".. _omnigraph_nodes_by_extension:\n\n")
        new_contents.append(rst_title("OmniGraph Nodes By Extension", 0))
        new_contents.append("\n")
        new_contents.append("See also the list :ref:`grouped by category<omnigraph_nodes_by_category>`\n\n")

        for extension_name in sorted(all_extensions):
            new_contents.append(rst_title(extension_name, 1))
            new_contents.append("\n")
            extension_node_types = node_types_in_extension[extension_name]
            for node_docs_path in keys:
                if node_docs_path not in extension_node_types:  # pragma: no cover
                    continue
                label, name, _, _, _ = node_type_information[node_docs_path]
                new_contents.append(f"- :ref:`{name} <{label}>`\n")
            new_contents.append("\n")

        # If the old contents did not exist or were different from the new contents then write out the file
        try:
            with open(self.by_extension_file_path, "r", newline="\n", encoding="utf-8") as index_file:
                current_contents = "".join(index_file.readlines())
            contents_have_changed = current_contents != "".join(new_contents)
        except IOError:
            contents_have_changed = True

        if contents_have_changed:
            logger.info("Index file grouped by extension has changed. Writing the new contents.")
            # Using the explicit newline so that the file reflects the Python strings on all platforms
            with open(self.by_extension_file_path, "w", newline="\n", encoding="utf-8") as index_file:
                for line in new_contents:
                    index_file.write(line)

    # --------------------------------------------------------------------------------------------------------------
    def construct_index(self):
        """Construct the table of contents in an index file"""
        # Find all of the generated node type documentation files in the requested directories
        for directory in self.extension_directories:
            self._add_all_node_type_definitions(directory)

        # No out-of-date check is performed here as in order to determine if everything is correct all of the
        # generated documentation files have to be checked to find their link and timestamps to compare against
        # the contents of the index files. The process of generation is quick enough that this shouldn't be a
        # problem but if it is one possible mitigation would be to include metadata in the generated documentation
        # file that contains information like relative to paths to all documentation files so that a much faster
        # comparison can be made.

        # Dictionary containing the information needed to generate the index file
        # Key = Node File, Value = [Marker, Name, Version, Description, Categories]
        node_type_information = {}
        for ogn_doc_file, extension in self.documentation_files:
            logger.debug("Processing %s", ogn_doc_file)
            node_type_information[ogn_doc_file] = self.extract_node_type_information(ogn_doc_file) + (extension,)

        # Get a list of the node information keys sorted by the name of the node, which will be used as the
        # secondary sort for all grouping types.
        sorted_keys = sorted(node_type_information.keys(), key=lambda key: node_type_information[key][1].lower())

        self._construct_category_grouping_index(node_type_information, sorted_keys)
        self._construct_extension_grouping_index(node_type_information, sorted_keys)


# ==============================================================================================================
def main_docs(args_to_parse: list = None):
    """Parse the contents of sys.args and perform the requested function."""

    # Save and restore the log level since it is a shared logger
    old_log_level = logger.level
    index_handler = OgnIndexCreator()
    index_handler.parse(args_to_parse)
    index_handler.construct_index()
    logger.setLevel(old_log_level)


# ==============================================================================================================
if __name__ == "__main__":  # pragma: no cover
    main_docs(sys.argv)
