"""
This file is auto-generated by idl.core.
Do not change it manually.
"""

from typing import Union, List, Optional, Dict
from idl.types import Enum, Record


Capabilities = Dict[str, int]
CustomSchemaType = "custom"


Meta = Dict[str, str]
TypeName = str
UnionSchemaType = "union"
AliasSchemaType = "alias"
EnumValue = Union[str, int]


class EnumMemberSchema(Record):
    name: str
    value: EnumValue
    meta: Meta
    comment: str


EnumSchemaType = "enum"
ConstValue = Union[str, int, bool, dict]
ConstSchemaType = "const"


class StructMappingSchemaValue(Record):
    type: str
    is_array: bool


class StructMappingSchema(Record):
    index: str
    key: str
    value: StructMappingSchemaValue


class PropertySchema(Record):
    name: str
    type: TypeName
    is_array: bool
    is_const: bool
    optional: bool
    meta: Meta
    comment: str


StructSchemaType = "struct"


class MethodReturnSchema(Record):
    meta: Meta
    type: TypeName
    is_many: bool


class MethodSchema(Record):
    name: str
    returns: MethodReturnSchema
    params: List[PropertySchema]
    version: Optional[int]
    deprecation: Optional[str]
    meta: Meta
    comment: str


InterfaceSchemaType = "interface"


class CustomSchema(Record):
    name: Optional[str]
    type: CustomSchemaType
    schema: str


class ConstSchema(Record):
    name: str
    type: ConstSchemaType
    value: ConstValue
    value_type: TypeName
    meta: Meta
    comment: str


class UnionSchema(Record):
    name: str
    type: UnionSchemaType
    members: List[TypeName]
    meta: Meta
    comment: str


class AliasSchema(Record):
    name: str
    type: AliasSchemaType
    value: str
    meta: Meta
    comment: str
    is_array: bool
    is_const: bool


class EnumSchema(Record):
    name: str
    type: EnumSchemaType
    members: List[EnumMemberSchema]
    meta: Meta
    comment: str


class StructSchema(Record):
    name: str
    type: StructSchemaType
    extends: TypeName
    fields: List[PropertySchema]
    mapping: Optional[StructMappingSchema]
    meta: Meta
    comment: str


class InterfaceSchema(Record):
    name: str
    type: InterfaceSchemaType
    fields: List[PropertySchema]
    functions: List[MethodSchema]
    meta: Meta
    comment: str


Definition = Union[InterfaceSchema, StructSchema, EnumSchema, AliasSchema, UnionSchema, ConstSchema, CustomSchema]


class TranspilerResult(Record):
    origin: str
    types: List[Definition]


class BuiltinType(metaclass=Enum):
    boolean = "boolean"
    float = "float"
    double = "double"
    int8 = "int8"
    uint8 = "uint8"
    int16 = "int16"
    uint16 = "uint16"
    int32 = "int32"
    number = "number"
    uint32 = "uint32"
    int64 = "int64"
    uint64 = "uint64"
    string = "string"
    bytes = "bytes"
    blob = "Blob"
    object = "object"

