[core]
reloadable = false
# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
order = -100

[package]
version = "107.3.3"
category = "Animation"
title = "USD Animation Graph schema (BETA)"
description="USD Animation Graph schema"
authors = ["NVIDIA"]
keywords = ["animation", "animgraph", "anim", "graph", "skeleton", "skeletal", "usd", "schema"]

[dependencies]
"omni.usd.libs" = {}

[[python.module]]
name = "pxr"

[[python.module]]
name = "AnimGraphSchema"

[[python.module]]
name = "omni.anim.graph.schema"

[[native.library]]
"filter:platform"."linux-x86_64"."path" = "lib/${lib_prefix}animGraphSchema${lib_ext}"
"filter:platform"."linux-aarch64"."path" = "lib/${lib_prefix}animGraphSchema${lib_ext}"
"filter:platform"."windows-x86_64"."path" = "bin/${lib_prefix}animGraphSchema${lib_ext}"

[package.writeTarget]
kit = true
usd = true

[[test]]
waiver = "USD Schema, tested externally"
