[package]
title = "Lidar Sensor Simulation"
description = "Nvidia Lidar Sensor Simulation including Point Cloud Converter, Profile Reader and utilities nodes."
version = "3.0.0"
authors = ["NVIDIA"]
changelog="docs/CHANGELOG.md"
readme="docs/README.md"
preview_image="package/preview.png"
icon="package/icon.png"
keywords=["sensors","lidar"]
repository = ""
category="Omniverse Simulation"
support_level = "Core"

[[native.library]]
"filter:os".linux.path = "${kit}/dev/libs/sensors/generic_model_output/bin/libgeneric_mo_io.so"
"filter:platform"."windows-x86_64".path = "${kit}/dev/libs/sensors/generic_model_output/bin/generic_mo_io.dll"

# Main module for the Python interface
[[python.module]]
name = "omni.sensors.nv.lidar"


# Other extensions that need to load before this one
[dependencies]
"omni.graph.core" = {}
"omni.sensors.nv.common" = {}
"omni.sensors.nv.materials" = {}
"omni.sensors.net" = {}


[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[documentation]
pages = [
    "docs/lidar_extension.rst",
    "docs/CHANGELOG.md",
]