[package]
# Semantic Versionning is used: https://semver.org/
version = "507.0.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "CAD Converter Service"
description = "The CAD Converter Service is a service for batch conversion of CAD files to USD."

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/Overview.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "services"

# Locks extension to the Kit SDK version being used or higher
writeTarget.kit = true

# Locks to USD with ABI 1
writeTarget.usd = true

# Keywords for the extension
keywords = [
    'CAD Converter',
    'cad',
    'kit',
    'services'
]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

[dependencies]
"omni.services.core" = {}
"omni.services.facilities.monitoring.progress" = {}
"omni.kit.async_engine" = {}
"omni.kit.converter.common" = { version = "~507.1"}
"omni.services.transport.client.base" = {}
"omni.services.transport.client.http_async" = {}
"omni.services.transport.server.http" = {}

# Main python module this extension provides, it will be publicly available as
[[python.module]]
name = "omni.services.convert.cad"

[settings]
exts."omni.services.convert.cad" = {}

[[test]]
timeout = 2000
# Ignore errors purposely triggered in test.
stdoutFailPatterns.exclude = [
    "*No compatible converter found*",
    "*Provided output_path isn't supported*"
]

[documentation]
pages = ["docs/Overview.md", "docs/CHANGELOG.md", "docs/Usage.md"]
