
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.services.convert.cad-507.0.2%2B107.3.1.u353.zip"

    [package.target]

        [package.target.usd]
            0 = "u353f+stock+24.05+cxx11"

        [package.target.kit]
            0 = "107.3.1"

    [package.publish]
        kitVersion = "107.3.1+production.206344.d26c4465.gl"
        date = 1754094739
        buildNumber = "203.0.0+main.3662.f11ab5b1.gl"
        repoName = "cad-converter"
        signed = 1
