[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.2"

category = "Internal"
feature = false

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "USD Property Adapter"
description="Allows Property Widget to read and write attributes to USD"

# URL of the extension source repository.
repository = ""

# Preview image. Folder named "data" automatically goes in git lfs (see .gitattributes file).
preview_image = "data/preview.png"

# Keywords for the extension
keywords = ["kit", "usd", "property"]
support_level = "Core"

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

[dependencies]
"omni.usd" = {}
"omni.kit.property.adapter.core" = {}
"usdrt.scenegraph" = {}

[[python.module]]
name = "omni.kit.property.adapter.usd"

[settings]
exts."omni.kit.property.adapter.usd".priority_read = 200
exts."omni.kit.property.adapter.usd".priority_write = 100

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
]

dependencies = [
    "omni.kit.renderer.capture",
    "omni.kit.mainwindow",
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers"
]

stdoutFailPatterns.exclude = [
    "*Failed to acquire interface [omni::kit::renderer::IGpuFoundation v0.2]*", # Leak
]
