[package]
title = "JT Converter"
version = "508.1.0"
description = "JT Converter."
category = "Converter"
repository = ""

changelog = "docs/CHANGELOG.md"
readme = "docs/Overview.md"

preview_image = "data/preview.png"
icon = "data/icon.png"

authors = ["NVIDIA"]

writeTarget.kit = true
writeTarget.usd = true

[dependencies]
"omni.client" = {}
"omni.kit.tool.asset_importer" = {}
"omni.kit.converter.jt_core" = { version = "~508.1"}
"omni.kit.converter.common" = { version = "~507.1"}

[[python.module]]
name = "omni.kit.converter.jt"

# Extension test settings
[[test]]
args = [
    "--/app/file/ignoreUnsavedOnExit=true",
    "--no-window",
    "--/app/fastShutdown=true",
]
dependencies = []
stdoutFailPatterns.include = []
stdoutFailPatterns.exclude = [
    "*is not writeable*",
    "*`startup()` must succeed prior calling*",
    "*All of the following settings must be specified*",
]

pyCoverageThreshold = 80
pyCoverageFilter = ["omni.kit.converter.jt"]
pyCoverageOmit = [
    "*/tests/*"
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
    "docs/Usage.md",
    "docs/Third_Party_Notices.md"
]
