[package]
# Semantic Versioning is used: https://semver.org/
version = "1.3.1"

# Which category this extension belongs to
category="Animation"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "Animation Curve Runtime"
description = "An Animation Curve Data runtime to parse and process the authored animation curve data schema"

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ["animation", "curve", "key", "runtime", "authoring"]

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
icon = "data/icon.svg"
preview_image = "data/preview.png"

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"
readme = "docs/README.md"
support_level = "core"

[[python.module]]
name = "omni.anim.curve.core"


# Other extensions that must be loaded before this one
[dependencies]
"omni.usd" = {}
"omni.graph" = {}
"omni.timeline" = {}
"omni.kit.commands" = {}
"omni.kit.usd_undo" = {}
"omni.kit.notification_manager" = {}
"omni.usd.schema.anim" = {}

[[native.plugin]]
path = "bin/*.plugin"
recursive = false

[[native.library]]
"filter:platform"."windows-x86_64"."path" = "bin/AnimX.dll"

[[test]]
dependencies = [
    # "omni.kit.window.viewport",
    "omni.kit.viewport.window",  # to only test against the new viewport
    "omni.kit.window.property",
    "omni.kit.property.usd",
    "omni.kit.property.transform",
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers",
    "omni.kit.window.content_browser",
    "omni.kit.property.geometry",  # for context menu unit tests
]
args = [
    "--/app/asyncRendering=false",
    "--/app/hydraEngine/waitIdle=true",
    "--/app/renderer/waitIdle=true",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/renderer/multiGpu/autoEnable=false",
    "--/rtx/materialDb/syncLoads=true",
    "--/omni.kit.plugin/syncUsdLoads=true",
    "--/rtx/hydra/materialSyncLoads=true",
    "--/exts/omni.usd/updatePriority=1",
    # Copy/paste code in context menu test (test_anim_curve_property_remove_animation) needs a window to be available, or it crashes.
    "--no-window",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/exts/omni.kit.viewport.window/startup/windowName=Viewport",  # to only test against the new viewport
]
timeout = 600

stdoutFailPatterns.exclude = [
    "*Failed to acquire interface [omni::kit::renderer::IGpuFoundation v0.2]*", # Leak
    "*the paths input must be a type of python list*", # Add/RemoveAnimCurves: test_anim_curve_add_remove_invalid
    "*one of the path*is*not a string type*",
    # CommandBase
    "*AnimCurveCommandBase: `name` TypeError: Expected str, got <class 'float'>.*",
    "*AnimCurveCommandBaseTest*",
    # TODO: better to use more precise filters
    "*TypeError: Expected*",  # Add/RemoveAnimCurves: `paths` TypeError: Expected None or list, got <class 'int'>.'
    "*PasteAnimCurveKeys: mixture of prim paths*",
    "*Failed to execute a command:*",
    "*PyperclipException:*",  # Value copy/paste uses system's clipboard. it will fail on Linux TC clients,
    "*TypeError: __init__(self, ...) called with invalid `self` argument*",
    "*SetAnimCurveKeys: key and value count must match.*",
    "*SetAnimCurveKeys: tangentBreakDown must be a bool value or None.*",
    "*SetAnimCurveKeys: inTangentType must be None, 'auto', 'smooth', 'flat', 'linear', 'step', or 'fixed'.*",
    "*SetAnimCurveKeys: outTangentType must be None, 'auto', 'smooth', 'flat', 'linear', 'step', or 'fixed'.*",
    "*SetAnimKeyCommand: Invalid param. * is a prim path, but value is not None!*",
    "*SetAnimCurveKeys: `time` and `value` must be None or of length 1, if preserveCurveShape=True!*",
    "*SetAnimKeyCommand: Invalid prim*",
    "*SetAnimKeyCommand: Specifies a vector component index out of range*",
    "*SetAnimKeyCommand: path * value is a vector of *, but the value *",
    "*SetAnimKeyCommand: path * is a vector component path, but the value * is a vector.*",
    "*ArgumentError: Python argument types in*",
]


[package]
writeTarget.usd = true
writeTarget.kit = true
