from .test_ext_inst import *
from .test_hotkeys import *
from .test_list_window import *
from .test_model import *
from .test_playlist_card import *
from .test_settings import *
from .test_viewport_waypoint import *
from .test_widget import *
from .test_window_settings import *
