[core]
reloadable = false
# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
order = -150

[package]
title = "USD Schema For Metrics Assembler"
description="USD Schema For Metrics Assembler"
toggleable = false
version = "107.3.1"
authors = ["NVIDIA"]
category = "Example"
repository = ""
preview_image = "data/preview.png"
icon = "data/icon.png"
readme  = "docs/README.md"
changelog = "docs/CHANGELOG.md"
keywords = ["usd"]
support_level = "Core"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.usd.libs" = {}

[[python.module]]
name = "omni.MetricsAssembler"

[[python.module]]
name = "usd.schema.metricsassembler"

[[native.library]]
path = "bin/${lib_prefix}metricsAssembler${lib_ext}"