[package]
version = "107.3.3"
title = "Navigation Bundle (BETA)"
authors = ["NVIDIA"]
keywords = ["animation", "navigation"]
readme = "docs/README.md"
changelog = "docs/CHANGELOG.md"
description = "Bundle for navigation extensions"
category = "Animation"
preview_image = "data/preview.png"
icon = "data/icon.png"

[[python.module]]
name = "omni.anim.navigation.bundle"

[dependencies]
"omni.anim.navigation.schema" = { version="~107.3" }
"omni.anim.navigation.core" = { version="~107.3" }
"omni.anim.navigation.ui" = { version="~107.3" }

[package.writeTarget]
kit = true

[[test]]
waiver = "Bundle extension"
