
[package]
    archivePath = "./archives/isaacsim.replicator.incident/isaacsim.replicator.incident-0.1.28+107.3.3.lx64.zip"

    [package.target]

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kit]
            0 = "107.3.3"

    [package.publish]
        kitVersion = "107.3.3+production.229672.69cbf6ad.gl"
        date = 1759788738
        buildNumber = "0.1.3+510.13041.c3d4c0fe.gl"
        repoName = "isaacsim.action_and_event_data_generation"
