[package]
# Semantic Versionning is used: https://semver.org/
version = "1.5.13"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
description = "Extension that provides snap functionality to transform manipulator as well as a registry for external snap tools"
title = "Manipulator Snap Tool"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Scene"
support_level = "Core"

# Keywords for the extension
keywords = ["kit", "manipulator", "tool", "snap"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

[dependencies]
"omni.kit.actions.core" = {}
"omni.kit.context_menu" = {}
"omni.kit.manipulator.transform" = {}
"omni.kit.raycast.query" = {}
"omni.kit.viewport.utility" = {}
"omni.kit.widget.toolbar" = {}
"omni.kit.widget.options_menu" = {}
"omni.ui.scene" = {}
"omni.usd" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "omni.kit.manipulator.tool.snap"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
    "docs/USAGE_PYTHON.md",
    "docs/SETTINGS.md"
]

[[test]]
dependencies = [
  "omni.kit.viewport.window",
  "omni.hydra.rtx",
  "omni.kit.viewport.legacy_gizmos", # to test snap to grid
  # FIXME: Test already takes too long due to RTX dependency it shouldn't have
  # Adding a second exclusive test-section to also load RTX is avoided.
  "usdrt.scenegraph",
]

args = [
  "--/app/window/width=512",
  "--/app/window/height=512",
  "--/app/renderer/resolution/width=512",
  "--/app/renderer/resolution/height=512",
  "--/app/window/dpiScaleOverride=1.0",
  "--/app/window/scaleToMonitor=false",
  "--/app/window/hideUi=true",
  "--/app/asyncRendering=false",
  "--/app/docks/disabled=True",
  "--/app/viewport/forceHideFps=True",
  "--/app/viewport/grid/enabled=True",
]

[settings]
exts."omni.kit.manipulator.tool.snap".providerNames = {}
persistent.exts."omni.kit.manipulator.tool.snap".conformToTarget = false
persistent.exts."omni.kit.manipulator.tool.snap".conformUpAxis = "Stage"           # ["X", "Y", "Z", "Stage"]
persistent.exts."omni.kit.manipulator.tool.snap".explicitTransform.rotate = 1.0
persistent.exts."omni.kit.manipulator.tool.snap".explicitTransform.scale = 1.0
persistent.exts."omni.kit.manipulator.tool.snap".explicitTransform.translate = 1.0
persistent.exts."omni.kit.manipulator.tool.snap".keepSpacing = true
