// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * A polymorphic owner of buffers
 * @note expected to dispose/free/release it's underlying implementation
 * when destroyed. Best passed around as a @ref IBufferCapsulePtr
 */
template <>
class omni::core::Generated<omni::sensors::net::IBufferCapsule_abi> : public omni::sensors::net::IBufferCapsule_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IBufferCapsule")

    /**
     * Get a mutable view of the underlying buffer
     * @return a pointer to the underlying buffer
     */
    void* data() noexcept;

    /**
     * Get the size of the actual data, regardless of the implementation
     * @return size of data in bytes
     */
    size_t size() noexcept;

    /**
     * Set the size of the actual data, regardless of the implementation
     * @param size size of the actual data in bytes
     */
    void setSize(size_t size) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline void* omni::core::Generated<omni::sensors::net::IBufferCapsule_abi>::data() noexcept
{
    return data_abi();
}

inline size_t omni::core::Generated<omni::sensors::net::IBufferCapsule_abi>::size() noexcept
{
    return size_abi();
}

inline void omni::core::Generated<omni::sensors::net::IBufferCapsule_abi>::setSize(size_t size) noexcept
{
    setSize_abi(size);
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
