// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<omni::sensors::net::IReceptionConsumer_abi> : public omni::sensors::net::IReceptionConsumer_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IReceptionConsumer")


    void onReceive(omni::core::ObjectParam<omni::sensors::net::IBufferCapsule> bufferCapsule,
                   const omni::sensors::net::Endpoint* endPoint) noexcept;
};

/**
 * Channel interface for sending/receiving data over different kinds of networks
 *
 * @note Create a channel according to a description using the network factory. See @ref INetworkFactory
 */
template <>
class omni::core::Generated<omni::sensors::net::IChannel_abi> : public omni::sensors::net::IChannel_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IChannel")

    /**
     * Check if the channel is connected/ready for sending and receiving
     * @return true if the channel is connected/ready
     * @note call this before sending or to check if a connection is dead to release the channel
     */
    bool isConnected() noexcept;

    /**
     * Send the inBuffer on the channel according to the channel implementation
     * @param inBuffer the buffer capsule that has the buffer to be sent
     * @param endpoint the sender address/id or (default) eNone if the destination is configured
     * @return true if the operation is successful, false otherwise
     */
    bool send(omni::core::ObjectParam<omni::sensors::net::IBufferCapsule> inBuffer,
              const omni::sensors::net::Endpoint* destination) noexcept;

    /**
     * Register a consumer that will be called when data is received on the channel
     * @param consumer The consumer class to be used when making a callback. See @ref IChannel::IReceptionConsumer
     */
    void addReceptionConsumer(omni::core::ObjectParam<omni::sensors::net::IReceptionConsumer> consumer) noexcept;

    /**
     * Unregister a previously registered consumer
     * @param consumer The previously registered consumer on this channel
     */
    void removeReceptionConsumer(omni::core::ObjectParam<omni::sensors::net::IReceptionConsumer> consumer) noexcept;

    /**
     * Register a consumer that will be called when data is received on the channel
     * @param consumer The consumer class to be used when making a callback. See @ref IChannel::IReceptionConsumer
     */
    omni::core::ObjectPtr<omni::sensors::net::IReceptionConsumer> addReceptionConsumer(
        std::function<void(omni::sensors::net::IBufferCapsule* bufferCapsule,
                           const omni::sensors::net::Endpoint* endPoint)> fun) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline void omni::core::Generated<omni::sensors::net::IReceptionConsumer_abi>::onReceive(
    omni::core::ObjectParam<omni::sensors::net::IBufferCapsule> bufferCapsule,
    const omni::sensors::net::Endpoint* endPoint) noexcept
{
    onReceive_abi(bufferCapsule.get(), endPoint);
}

inline bool omni::core::Generated<omni::sensors::net::IChannel_abi>::isConnected() noexcept
{
    return isConnected_abi();
}

inline bool omni::core::Generated<omni::sensors::net::IChannel_abi>::send(
    omni::core::ObjectParam<omni::sensors::net::IBufferCapsule> inBuffer,
    const omni::sensors::net::Endpoint* destination) noexcept
{
    return send_abi(inBuffer.get(), destination);
}

inline void omni::core::Generated<omni::sensors::net::IChannel_abi>::addReceptionConsumer(
    omni::core::ObjectParam<omni::sensors::net::IReceptionConsumer> consumer) noexcept
{
    addReceptionConsumer_abi(consumer.get());
}

inline void omni::core::Generated<omni::sensors::net::IChannel_abi>::removeReceptionConsumer(
    omni::core::ObjectParam<omni::sensors::net::IReceptionConsumer> consumer) noexcept
{
    removeReceptionConsumer_abi(consumer.get());
}

inline omni::core::ObjectPtr<omni::sensors::net::IReceptionConsumer> omni::core::Generated<omni::sensors::net::IChannel_abi>::
    addReceptionConsumer(std::function<void(omni::sensors::net::IBufferCapsule* bufferCapsule,
                                            const omni::sensors::net::Endpoint* endPoint)> fun) noexcept
{

    class Consumer : public omni::core::Implements<omni::sensors::net::IReceptionConsumer>
    {
    public:
        virtual void onReceive_abi(omni::sensors::net::IBufferCapsule* bufferCapsule,
                                   const omni::sensors::net::Endpoint* endPoint) noexcept override
        {
            m_function(bufferCapsule, endPoint);
        }

        Consumer(std::function<void(omni::sensors::net::IBufferCapsule* bufferCapsule,
                                    const omni::sensors::net::Endpoint* endPoint)> cb)
            : m_function(std::move(cb))
        {
        }

    private:
        std::function<void(omni::sensors::net::IBufferCapsule* bufferCapsule, const omni::sensors::net::Endpoint* endPoint)>
            m_function;
    };

    auto consumer{ omni::core::steal(new Consumer{ std::move(fun) }) };
    addReceptionConsumer_abi(consumer.get());
    return consumer;
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
static_assert(std::is_standard_layout<omni::sensors::net::IP4Endpoint>::value,
              "omni::sensors::net::IP4Endpoint must be standard layout to be used in ONI ABI");
static_assert(std::is_standard_layout<omni::sensors::net::RealmEndpoint>::value,
              "omni::sensors::net::RealmEndpoint must be standard layout to be used in ONI ABI");
static_assert(std::is_standard_layout<omni::sensors::net::Endpoint>::value,
              "omni::sensors::net::Endpoint must be standard layout to be used in ONI ABI");
