// SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * An interface to a format serializer that serializes sensor network messages.
 */
template <>
class omni::core::Generated<omni::sensors::net::IFormatSerializer_abi> : public omni::sensors::net::IFormatSerializer_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IFormatSerializer")

    /**
     * Serialize network message.
     * @param capsule buffer containing network message payload.
     * @param endpoint network message endpoint information.
     */
    void serialize(omni::core::ObjectParam<omni::sensors::net::IBufferCapsule> capsule,
                   const omni::sensors::net::Endpoint* endpoint) noexcept;
};

/**
 * An interface to a format serializer factory.
 */
template <>
class omni::core::Generated<omni::sensors::net::IFormatSerializerFactory_abi>
    : public omni::sensors::net::IFormatSerializerFactory_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IFormatSerializerFactory")

    /**
     * Create a format serializer according to description
     * @param channelDescription network channel description as defined in INetworkFactory.
     * @param outputPath A file or directory path (depending on implementation) in which to write the serialized data.
     * Parent dirs can be assumed to exist by the implementation.
     * @return a serializer object, if successful, nullptr otherwise.
     */
    omni::core::ObjectPtr<omni::sensors::net::IFormatSerializer> makeSerializer(
        const carb::dictionary::Item* channelDescription, const char* outputPath) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline void omni::core::Generated<omni::sensors::net::IFormatSerializer_abi>::serialize(
    omni::core::ObjectParam<omni::sensors::net::IBufferCapsule> capsule,
    const omni::sensors::net::Endpoint* endpoint) noexcept
{
    serialize_abi(capsule.get(), endpoint);
}

inline omni::core::ObjectPtr<omni::sensors::net::IFormatSerializer> omni::core::Generated<
    omni::sensors::net::IFormatSerializerFactory_abi>::makeSerializer(const carb::dictionary::Item* channelDescription,
                                                                      const char* outputPath) noexcept
{
    return omni::core::steal(makeSerializer_abi(channelDescription, outputPath));
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
