// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<omni::sensors::net::INetworkFactory_abi> : public omni::sensors::net::INetworkFactory_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::INetworkFactory")

    /**
     * Create a buffer capsule for use with net::IChannel
     * @param size capsule length in bytes
     * @return a buffer capsule that is (at least) the requested bytes
     *
     * @note the caller owns the server
     */
    omni::core::ObjectPtr<omni::sensors::net::IBufferCapsule> makeCapsule(size_t size) noexcept;

    /**
     * Create a networking channel using the backend selected in the description
     * @param description a dictionary that has a "backend" param naming the backend that will
     * create and service the channel along with a list of backend-specific parameters
     * @return a channel object pointer if successful, empty/nullptr otherwise
     *
     * @note the caller owns the channel
     */
    omni::core::ObjectPtr<omni::sensors::net::IChannel> makeChannel(const carb::dictionary::Item* description) noexcept;

    /**
     * Create a networking server using the backend selected in the description
     * @param description a dictionary that has a "backend" param naming the backend that will
     * create and service the server along with a list of backend-specific parameters
     * @return a server object pointer if successful, empty/nullptr otherwise
     *
     * @note the caller owns the server
     */
    omni::core::ObjectPtr<omni::sensors::net::IServer> makeServer(const carb::dictionary::Item* description) noexcept;

    /**
     * Get the backend associated with the @ref description
     * @param description A description of the backend to get.
     * @returns The backend, if it exists, nullptr otherwise.
     *
     * @note This function is useful when needed to access the backend directly, for example it may expose additional
     * interfaces.
     */
    omni::core::ObjectPtr<omni::sensors::net::INetworkBackend> getBackend(const carb::dictionary::Item* description) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::core::ObjectPtr<omni::sensors::net::IBufferCapsule> omni::core::Generated<
    omni::sensors::net::INetworkFactory_abi>::makeCapsule(size_t size) noexcept
{
    return omni::core::steal(makeCapsule_abi(size));
}

inline omni::core::ObjectPtr<omni::sensors::net::IChannel> omni::core::Generated<
    omni::sensors::net::INetworkFactory_abi>::makeChannel(const carb::dictionary::Item* description) noexcept
{
    return omni::core::steal(makeChannel_abi(description));
}

inline omni::core::ObjectPtr<omni::sensors::net::IServer> omni::core::Generated<
    omni::sensors::net::INetworkFactory_abi>::makeServer(const carb::dictionary::Item* description) noexcept
{
    return omni::core::steal(makeServer_abi(description));
}

inline omni::core::ObjectPtr<omni::sensors::net::INetworkBackend> omni::core::Generated<
    omni::sensors::net::INetworkFactory_abi>::getBackend(const carb::dictionary::Item* description) noexcept
{
    return omni::core::steal(getBackend_abi(description));
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
