// SPDX-FileCopyrightText: Copyright (c) 2022-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * An interface to a network channel and server decorator factory.
 */
template <>
class omni::core::Generated<omni::sensors::net::INetworkDecorator_abi> : public omni::sensors::net::INetworkDecorator_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::INetworkDecorator")

    /**
     * Create a network channel decorator
     *
     * @note If a decorator is created, it will manage the channel.
     *
     * @param channelDesc network channel description as defined in INetworkFactory.
     * @param channel the network channel to be decorated.
     * @return a decorated channel if successful, the original channel otherwise.
     */
    omni::core::ObjectPtr<omni::sensors::net::IChannel> decorateChannel(
        const carb::dictionary::Item* channelDesc, omni::core::ObjectParam<omni::sensors::net::IChannel> channel) noexcept;

    /**
     * Create a network server decorator
     *
     * @note If a decorator is created, it will manage the server.
     *
     * @param serverDesc network server description as defined in INetworkFactory.
     * @param server the network server to be decorated.
     * @return a decorated server if successful, the original server otherwise.
     */
    omni::core::ObjectPtr<omni::sensors::net::IServer> decorateServer(
        const carb::dictionary::Item* serverDesc, omni::core::ObjectParam<omni::sensors::net::IServer> server) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::core::ObjectPtr<omni::sensors::net::IChannel> omni::core::Generated<omni::sensors::net::INetworkDecorator_abi>::decorateChannel(
    const carb::dictionary::Item* channelDesc, omni::core::ObjectParam<omni::sensors::net::IChannel> channel) noexcept
{
    return omni::core::steal(decorateChannel_abi(channelDesc, channel.get()));
}

inline omni::core::ObjectPtr<omni::sensors::net::IServer> omni::core::Generated<omni::sensors::net::INetworkDecorator_abi>::decorateServer(
    const carb::dictionary::Item* serverDesc, omni::core::ObjectParam<omni::sensors::net::IServer> server) noexcept
{
    return omni::core::steal(decorateServer_abi(serverDesc, server.get()));
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
