// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * An interface to a network backend that provides channel-based networking
 *
 * @note used by the INetworkFactory to create channels supported by that backend
 */
template <>
class omni::core::Generated<omni::sensors::net::INetworkBackend_abi> : public omni::sensors::net::INetworkBackend_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::INetworkBackend")

    /**
     * Get the name of the backend (to be matched to the description)
     * @return backend name
     */
    const char* getName() noexcept;

    /**
     * Create a networking channel according to the description
     * @param description the backend-specific parameters for creating a specific channel
     * @return a channel object pointer if successful, empty/nullptr otherwise
     *
     * @note the caller owns the channel
     */
    omni::core::ObjectPtr<omni::sensors::net::IChannel> makeChannel(const carb::dictionary::Item* description) noexcept;

    /**
     * Create a networking server according to the description
     * @param description the backend-specific parameters for creating a specific server
     * @return a server object pointer if successful, empty/nullptr otherwise
     *
     * @note the caller owns the server
     */
    omni::core::ObjectPtr<omni::sensors::net::IServer> makeServer(const carb::dictionary::Item* description) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline const char* omni::core::Generated<omni::sensors::net::INetworkBackend_abi>::getName() noexcept
{
    return getName_abi();
}

inline omni::core::ObjectPtr<omni::sensors::net::IChannel> omni::core::Generated<
    omni::sensors::net::INetworkBackend_abi>::makeChannel(const carb::dictionary::Item* description) noexcept
{
    return omni::core::steal(makeChannel_abi(description));
}

inline omni::core::ObjectPtr<omni::sensors::net::IServer> omni::core::Generated<
    omni::sensors::net::INetworkBackend_abi>::makeServer(const carb::dictionary::Item* description) noexcept
{
    return omni::core::steal(makeServer_abi(description));
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
