// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


/**
 * REALM backend interface, allowing for the creation of buffer capsules managed by REALM.
 */
template <>
class omni::core::Generated<omni::sensors::net::IRealmBackend_abi> : public omni::sensors::net::IRealmBackend_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IRealmBackend")

    /**
     * Create a Host buffer capsule for use with net::RealmChannel
     * @param size capsule length in bytes
     * @return a buffer capsule that is (at least) the requested bytes
     *
     */
    omni::core::ObjectPtr<omni::sensors::net::IBufferCapsule> makeHostCapsule(size_t size) noexcept;

    /**
     * Create a CUDA buffer capsule for use with net::RealmChannel
     * @param size capsule length in bytes
     * @return a buffer capsule that is (at least) the requested bytes
     *
     */
    omni::core::ObjectPtr<omni::sensors::net::IBufferCapsule> makeCUDACapsule(size_t size,
                                                                              uint32_t cudaDeviceIdx) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline omni::core::ObjectPtr<omni::sensors::net::IBufferCapsule> omni::core::Generated<
    omni::sensors::net::IRealmBackend_abi>::makeHostCapsule(size_t size) noexcept
{
    return omni::core::steal(makeHostCapsule_abi(size));
}

inline omni::core::ObjectPtr<omni::sensors::net::IBufferCapsule> omni::core::Generated<
    omni::sensors::net::IRealmBackend_abi>::makeCUDACapsule(size_t size, uint32_t cudaDeviceIdx) noexcept
{
    return omni::core::steal(makeCUDACapsule_abi(size, cudaDeviceIdx));
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
