// SPDX-FileCopyrightText: Copyright (c) 2024-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: LicenseRef-NvidiaProprietary
//
// NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
// property and proprietary rights in and to this material, related
// documentation and any modifications thereto. Any use, reproduction,
// disclosure or distribution of this material and related documentation
// without an express license agreement from NVIDIA CORPORATION or
// its affiliates is strictly prohibited.

// --------- Warning: This is a build system generated file. ----------
//

//! @file
//!
//! @brief This file was generated by <i>omni.bind</i>.

#include <omni/core/Interface.h>
#include <omni/core/OmniAttr.h>
#include <omni/core/ResultError.h>

#include <functional>
#include <type_traits>
#include <utility>

#ifndef OMNI_BIND_INCLUDE_INTERFACE_IMPL


template <>
class omni::core::Generated<omni::sensors::net::IConnectionConsumer_abi>
    : public omni::sensors::net::IConnectionConsumer_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IConnectionConsumer")


    void onConnect(omni::core::ObjectParam<omni::sensors::net::IChannel> channel,
                   const omni::sensors::net::Endpoint* endPoint) noexcept;
};

/**
 * Server interface for connection-based channels (eg. TCP and WebSocket servers)
 *
 * @note Create a server according to a description using the network factory. See @ref INetworkFactory
 */
template <>
class omni::core::Generated<omni::sensors::net::IServer_abi> : public omni::sensors::net::IServer_abi
{
public:
    OMNI_PLUGIN_INTERFACE("omni::sensors::net::IServer")

    /**
     * Register a consumer that will be called when a new client connects to the server
     * @param consumer The consumer class to be used when making a callback. See @ref IChannel::IReceptionConsumer
     */
    void addConnectionConsumer(omni::core::ObjectParam<omni::sensors::net::IConnectionConsumer> consumer) noexcept;

    /**
     * Unregisters a previously registered handler
     * @param id handler id of a handler previously registered on this server
     */
    void removeConnectionConsumer(omni::core::ObjectParam<omni::sensors::net::IConnectionConsumer> consumer) noexcept;

    /**
     * Register a consumer that will be called when a new client connects to the server
     * @param consumer The consumer class to be used when making a callback. See @ref IChannel::IReceptionConsumer
     */
    omni::core::ObjectPtr<omni::sensors::net::IConnectionConsumer> addConnectionConsumer(
        std::function<void(omni::sensors::net::IChannel* channel, const omni::sensors::net::Endpoint* endPoint)> fun) noexcept;
};

#endif

#ifndef OMNI_BIND_INCLUDE_INTERFACE_DECL

inline void omni::core::Generated<omni::sensors::net::IConnectionConsumer_abi>::onConnect(
    omni::core::ObjectParam<omni::sensors::net::IChannel> channel, const omni::sensors::net::Endpoint* endPoint) noexcept
{
    onConnect_abi(channel.get(), endPoint);
}

inline void omni::core::Generated<omni::sensors::net::IServer_abi>::addConnectionConsumer(
    omni::core::ObjectParam<omni::sensors::net::IConnectionConsumer> consumer) noexcept
{
    addConnectionConsumer_abi(consumer.get());
}

inline void omni::core::Generated<omni::sensors::net::IServer_abi>::removeConnectionConsumer(
    omni::core::ObjectParam<omni::sensors::net::IConnectionConsumer> consumer) noexcept
{
    removeConnectionConsumer_abi(consumer.get());
}

inline omni::core::ObjectPtr<omni::sensors::net::IConnectionConsumer> omni::core::
    Generated<omni::sensors::net::IServer_abi>::addConnectionConsumer(
        std::function<void(omni::sensors::net::IChannel* channel, const omni::sensors::net::Endpoint* endPoint)> fun) noexcept
{

    class Consumer : public omni::core::Implements<omni::sensors::net::IConnectionConsumer>
    {
    public:
        virtual void onConnect_abi(omni::sensors::net::IChannel* channel,
                                   const omni::sensors::net::Endpoint* endPoint) noexcept override
        {
            m_function(channel, endPoint);
        }

        Consumer(std::function<void(omni::sensors::net::IChannel* channel, const omni::sensors::net::Endpoint* endPoint)> cb)
            : m_function(std::move(cb))
        {
        }

    private:
        std::function<void(omni::sensors::net::IChannel* channel, const omni::sensors::net::Endpoint* endPoint)> m_function;
    };

    auto consumer{ omni::core::steal(new Consumer{ std::move(fun) }) };
    addConnectionConsumer_abi(consumer.get());
    return consumer;
}

#endif

#undef OMNI_BIND_INCLUDE_INTERFACE_DECL
#undef OMNI_BIND_INCLUDE_INTERFACE_IMPL
