from __future__ import annotations
import usdrt.Usd._Usd
import typing
import usdrt.Gf._Gf
import usdrt.Sdf._Sdf
import usdrt.helpers._helpers

__all__ = [
    "APISchemaBase",
    "Access",
    "AttrSpec",
    "Attribute",
    "ClipsAPI",
    "CollectionAPI",
    "ListPosition",
    "ModelAPI",
    "Overwrite",
    "Prim",
    "PrimRange",
    "Read",
    "ReadWrite",
    "Relationship",
    "SchemaBase",
    "SchemaRegistry",
    "Stage",
    "TimeCode",
    "Tokens",
    "Typed",
    "UsdCollectionMembershipQuery"
]


class APISchemaBase(SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    pass
class Access():
    """
    Members:

      Read

      ReadWrite

      Overwrite
    """
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str:
        """
        :type: str
        """
    @property
    def value(self) -> int:
        """
        :type: int
        """
    Overwrite: usdrt.Usd._Usd.Access # value = <Access.Overwrite: 3>
    Read: usdrt.Usd._Usd.Access # value = <Access.Read: 1>
    ReadWrite: usdrt.Usd._Usd.Access # value = <Access.ReadWrite: 2>
    __members__: dict # value = {'Read': <Access.Read: 1>, 'ReadWrite': <Access.ReadWrite: 2>, 'Overwrite': <Access.Overwrite: 3>}
    pass
class AttrSpec():
    def __init__(self, arg0: typing.Tuple[usdrt.Sdf._Sdf.ValueTypeName, TfToken, Access]) -> None: ...
    pass
class Attribute():
    def AddConnection(self, source: usdrt.Sdf._Sdf.Path, position: ListPosition = ListPosition.ListPositionBackOfPrependList) -> bool: ...
    def ClearConnections(self) -> bool: ...
    def Get(self, time: TimeCode = Usd.TimeCode.Default()) -> object: ...
    def GetBaseName(self) -> TfToken: ...
    def GetConnections(self) -> typing.List[usdrt.Sdf._Sdf.Path]: ...
    def GetName(self) -> TfToken: ...
    def GetNamespace(self) -> TfToken: ...
    def GetPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetPrim(self) -> Prim: ...
    def GetPrimPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetStage(self) -> Stage: ...
    def GetTypeName(self) -> usdrt.Sdf._Sdf.ValueTypeName: ...
    def HasAuthoredConnections(self) -> bool: ...
    def HasAuthoredValue(self) -> bool: ...
    def HasValue(self) -> bool: ...
    def InvalidateCpuData(self) -> bool: 
        """
        Invalidate CPU data (for debugging)
        """
    def InvalidateGpuData(self) -> bool: 
        """
        Invalidate GPU data (for debugging)
        """
    def IsCpuDataValid(self) -> bool: 
        """
        Check if Fabric CPU data is currently valid
        """
    def IsGpuDataValid(self) -> bool: 
        """
        Check if Fabric GPU data is currently valid
        """
    def IsValid(self) -> bool: ...
    def RemoveConnection(self, source: usdrt.Sdf._Sdf.Path) -> bool: ...
    def Set(self, value: object, time: TimeCode = Usd.TimeCode.Default()) -> bool: ...
    def SetConnections(self, sources: typing.List[usdrt.Sdf._Sdf.Path]) -> bool: ...
    def SplitName(self) -> typing.List[str]: ...
    def SyncDataToCpu(self) -> bool: 
        """
        Force a sync to CPU memory from GPU memory (for debugging)
        """
    def SyncDataToGpu(self) -> bool: 
        """
        Force a sync to GPU memory from CPU memory (for debugging)
        """
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    pass
class ClipsAPI(APISchemaBase, SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class CollectionAPI(APISchemaBase, SchemaBase):
    @staticmethod
    def Apply(prim: Prim, name: TfToken) -> CollectionAPI: ...
    @staticmethod
    def ComputeIncludedPaths(query: UsdCollectionMembershipQuery, stageId: usdrt.helpers._helpers.StageReaderWriterId) -> typing.Set[usdrt.Sdf._Sdf.Path]: ...
    @typing.overload
    def ComputeMembershipQuery(self) -> UsdCollectionMembershipQuery: ...
    @typing.overload
    def ComputeMembershipQuery(self, arg0: UsdCollectionMembershipQuery) -> None: ...
    def CreateExcludesRel(self) -> Relationship: ...
    def CreateExpansionRuleAttr(self) -> Attribute: ...
    def CreateIncludeRootAttr(self) -> Attribute: ...
    def CreateIncludesRel(self) -> Relationship: ...
    def ExcludePath(self, pathToExclude: usdrt.Sdf._Sdf.Path) -> bool: ...
    def GetCollectionPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetExcludesRel(self) -> Relationship: ...
    def GetExpansionRuleAttr(self) -> Attribute: ...
    def GetIncludeRootAttr(self) -> Attribute: ...
    def GetIncludesRel(self) -> Relationship: ...
    def GetName(self) -> TfToken: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def IncludePath(self, pathToInclude: usdrt.Sdf._Sdf.Path) -> bool: ...
    @staticmethod
    def IsCollectionAPIPath(path: usdrt.Sdf._Sdf.Path, name: TfToken) -> bool: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: Prim, arg1: TfToken) -> None: ...
    @typing.overload
    def __init__(self, arg0: SchemaBase, arg1: TfToken) -> None: ...
    def __repr__(self) -> str: ...
    @staticmethod
    @typing.overload
    def sComputeMembershipQuery(stageId: usdrt.helpers._helpers.StageReaderWriterId, collectionPath: usdrt.Sdf._Sdf.Path) -> UsdCollectionMembershipQuery: ...
    @staticmethod
    @typing.overload
    def sComputeMembershipQuery(stageId: usdrt.helpers._helpers.StageReaderWriterId, collectionPath: usdrt.Sdf._Sdf.Path, query: UsdCollectionMembershipQuery) -> None: ...
    pass
class ListPosition():
    """
    Members:

      ListPositionFrontOfPrependList

      ListPositionBackOfPrependList

      ListPositionFrontOfAppendList

      ListPositionBackOfAppendList
    """
    def __eq__(self, other: object) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    @property
    def name(self) -> str:
        """
        :type: str
        """
    @property
    def value(self) -> int:
        """
        :type: int
        """
    ListPositionBackOfAppendList: usdrt.Usd._Usd.ListPosition # value = <ListPosition.ListPositionBackOfAppendList: 3>
    ListPositionBackOfPrependList: usdrt.Usd._Usd.ListPosition # value = <ListPosition.ListPositionBackOfPrependList: 1>
    ListPositionFrontOfAppendList: usdrt.Usd._Usd.ListPosition # value = <ListPosition.ListPositionFrontOfAppendList: 2>
    ListPositionFrontOfPrependList: usdrt.Usd._Usd.ListPosition # value = <ListPosition.ListPositionFrontOfPrependList: 0>
    __members__: dict # value = {'ListPositionFrontOfPrependList': <ListPosition.ListPositionFrontOfPrependList: 0>, 'ListPositionBackOfPrependList': <ListPosition.ListPositionBackOfPrependList: 1>, 'ListPositionFrontOfAppendList': <ListPosition.ListPositionFrontOfAppendList: 2>, 'ListPositionBackOfAppendList': <ListPosition.ListPositionBackOfAppendList: 3>}
    pass
class ModelAPI(APISchemaBase, SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Prim():
    def AddAppliedSchema(self, appliedSchemaName: TfToken) -> bool: ...
    def ApplyAPI(self, schemaIdentifier: TfToken, instanceName: TfToken = '') -> bool: ...
    def ClearTypeName(self) -> bool: ...
    @staticmethod
    def CreateAttribute(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRelationship(*args, **kwargs) -> typing.Any: ...
    def GetAllChildren(self, prefetchFromUsd: bool = True) -> typing.List[Prim]: ...
    def GetAllChildrenNames(self, prefetchFromUsd: bool = True) -> typing.List[TfToken]: ...
    def GetAppliedSchemas(self) -> typing.List[TfToken]: ...
    @staticmethod
    def GetAttribute(*args, **kwargs) -> typing.Any: ...
    def GetAttributes(self) -> typing.List[usdrt::UsdAttribute]: ...
    def GetAuthoredAttributes(self) -> typing.List[usdrt::UsdAttribute]: ...
    def GetAuthoredPropertyNames(self) -> typing.List[TfToken]: ...
    def GetAuthoredRelationships(self) -> typing.List[usdrt::UsdRelationship]: ...
    def GetChild(self, name: TfToken, prefetchFromUsd: bool = True) -> Prim: ...
    def GetChildren(self, prefetchFromUsd: bool = True) -> typing.List[Prim]: ...
    def GetChildrenNames(self, prefetchFromUsd: bool = True) -> typing.List[TfToken]: ...
    def GetName(self) -> TfToken: ...
    def GetNextSibling(self, prefetchFromUsd: bool = True) -> Prim: ...
    def GetParent(self, prefetchFromUsd: bool = True) -> Prim: ...
    def GetPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetPrim(self) -> Prim: ...
    def GetPrimPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetPropertyNames(self) -> typing.List[TfToken]: ...
    @staticmethod
    def GetRelationship(*args, **kwargs) -> typing.Any: ...
    def GetRelationships(self) -> typing.List[usdrt::UsdRelationship]: ...
    def GetStage(self) -> Stage: ...
    def GetTypeName(self) -> TfToken: ...
    def HasAPI(self, schemaIdentifier: TfToken, instanceName: TfToken = '') -> bool: ...
    def HasAttribute(self, name: TfToken) -> bool: ...
    def HasAuthoredTypeName(self) -> bool: ...
    def HasProperty(self, propName: TfToken) -> bool: ...
    def HasRelationship(self, relName: TfToken) -> bool: ...
    @typing.overload
    def IsA(self, schemaType: object) -> bool: ...
    @typing.overload
    def IsA(self, schemaTypeName: TfToken) -> bool: ...
    def IsValid(self) -> bool: ...
    def RemoveAPI(self, schemaIdentifier: TfToken, instanceName: TfToken = '') -> bool: ...
    def RemoveAppliedSchema(self, appliedSchemaName: TfToken) -> bool: ...
    def RemoveProperty(self, propName: TfToken) -> bool: ...
    def SetTypeName(self, typeName: TfToken) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    pass
class PrimRange():
    def IsValid(self) -> bool: 
        """
        true if the iterator is not yet exhausted
        """
    def __bool__(self) -> bool: ...
    def __eq__(self, arg0: PrimRange) -> bool: ...
    @typing.overload
    def __init__(self, arg0: Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: UsdPrimRange) -> None: ...
    @staticmethod
    def __iter__(*args, **kwargs) -> typing.Any: ...
    def __ne__(self, arg0: PrimRange) -> bool: ...
    def __repr__(self) -> str: ...
    __hash__ = None
    pass
class Relationship():
    def AddTarget(self, target: usdrt.Sdf._Sdf.Path, position: ListPosition = ListPosition.ListPositionBackOfPrependList) -> bool: ...
    def ClearTargets(self, removeSpec: bool) -> bool: ...
    def GetBaseName(self) -> TfToken: ...
    def GetForwardedTargets(self) -> typing.List[usdrt.Sdf._Sdf.Path]: ...
    def GetName(self) -> TfToken: ...
    def GetNamespace(self) -> TfToken: ...
    def GetPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetPrim(self) -> Prim: ...
    def GetPrimPath(self) -> usdrt.Sdf._Sdf.Path: ...
    def GetStage(self) -> Stage: ...
    def GetTargets(self) -> typing.List[usdrt.Sdf._Sdf.Path]: ...
    def HasAuthoredTargets(self) -> bool: ...
    def IsValid(self) -> bool: ...
    def RemoveTarget(self, target: usdrt.Sdf._Sdf.Path) -> bool: ...
    def SetTargets(self, targets: typing.List[usdrt.Sdf._Sdf.Path]) -> bool: ...
    def SplitName(self) -> typing.List[str]: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    pass
class SchemaBase():
    def GetPrim(self) -> Prim: ...
    def GetPrimPath(self) -> usdrt.Sdf._Sdf.Path: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class SchemaRegistry():
    def GetAliasFromName(self, name: TfToken) -> TfToken: ...
    @staticmethod
    def GetInstance() -> SchemaRegistry: ...
    def GetSchemaTypeName(self, schemaType: object) -> TfToken: ...
    @typing.overload
    def IsA(self, sourceType: object, queryType: object) -> bool: ...
    @typing.overload
    def IsA(self, sourceTypeName: TfToken, queryType: object) -> bool: ...
    @typing.overload
    def IsA(self, sourceType: object, queryTypeName: TfToken) -> bool: ...
    @typing.overload
    def IsA(self, sourceTypeName: TfToken, queryTypeName: TfToken) -> bool: ...
    def IsAppliedAPISchema(self, apiSchemaType: TfToken) -> bool: ...
    def IsConcrete(self, primType: TfToken) -> bool: ...
    def IsMultipleApplyAPISchema(self, apiSchemaType: TfToken) -> bool: ...
    def IsTyped(self, primType: TfToken) -> bool: ...
    def IsUnknown(self, apiSchemaType: TfToken) -> bool: ...
    def __bool__(self) -> bool: ...
    def __repr__(self) -> str: ...
    pass
class Stage():
    class InitialLoadSet():
        """
        Members:

          LoadAll

          LoadNone
        """
        def __eq__(self, other: object) -> bool: ...
        def __getstate__(self) -> int: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __init__(self, value: int) -> None: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        def __repr__(self) -> str: ...
        def __setstate__(self, state: int) -> None: ...
        @property
        def name(self) -> str:
            """
            :type: str
            """
        @property
        def value(self) -> int:
            """
            :type: int
            """
        LoadAll: usdrt.Usd._Usd.Stage.InitialLoadSet # value = <InitialLoadSet.LoadAll: 0>
        LoadNone: usdrt.Usd._Usd.Stage.InitialLoadSet # value = <InitialLoadSet.LoadNone: 1>
        __members__: dict # value = {'LoadAll': <InitialLoadSet.LoadAll: 0>, 'LoadNone': <InitialLoadSet.LoadNone: 1>}
        pass
    class TimeChange():
        """
        Members:

          LazyUpdate

          ForceUpdate

          NoUpdate
        """
        def __eq__(self, other: object) -> bool: ...
        def __getstate__(self) -> int: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __init__(self, value: int) -> None: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        def __repr__(self) -> str: ...
        def __setstate__(self, state: int) -> None: ...
        @property
        def name(self) -> str:
            """
            :type: str
            """
        @property
        def value(self) -> int:
            """
            :type: int
            """
        ForceUpdate: usdrt.Usd._Usd.Stage.TimeChange # value = <TimeChange.ForceUpdate: 1>
        LazyUpdate: usdrt.Usd._Usd.Stage.TimeChange # value = <TimeChange.LazyUpdate: 0>
        NoUpdate: usdrt.Usd._Usd.Stage.TimeChange # value = <TimeChange.NoUpdate: 2>
        __members__: dict # value = {'LazyUpdate': <TimeChange.LazyUpdate: 0>, 'ForceUpdate': <TimeChange.ForceUpdate: 1>, 'NoUpdate': <TimeChange.NoUpdate: 2>}
        pass
    @staticmethod
    @typing.overload
    def Attach(stageId: int) -> Stage: ...
    @staticmethod
    @typing.overload
    def Attach(fabricId: usdrt.helpers._helpers.FabricId) -> Stage: ...
    @staticmethod
    def CreateInMemory(identifier: str, load: Stage.InitialLoadSet = InitialLoadSet.LoadAll) -> Stage: ...
    @staticmethod
    def CreateNew(identifier: str, load: Stage.InitialLoadSet = InitialLoadSet.LoadAll) -> Stage: ...
    @staticmethod
    def CreateOnlyInFabric() -> Stage: ...
    @staticmethod
    def DefinePrim(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttributeAtPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDefaultPrim(*args, **kwargs) -> typing.Any: ...
    def GetFabricId(self) -> usdrt.helpers._helpers.FabricId: ...
    @staticmethod
    def GetPrimAtPath(*args, **kwargs) -> typing.Any: ...
    def GetPrimsWithAppliedAPIName(self, apiName: TfToken) -> typing.List[usdrt.Sdf._Sdf.Path]: ...
    def GetPrimsWithTypeAndAppliedAPIName(self, typeName: TfToken, apiNames: typing.List[TfToken]) -> typing.List[usdrt.Sdf._Sdf.Path]: ...
    def GetPrimsWithTypeName(self, typeName: TfToken) -> typing.List[usdrt.Sdf._Sdf.Path]: ...
    @staticmethod
    def GetPseudoRoot(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRelationshipAtPath(*args, **kwargs) -> typing.Any: ...
    def GetStageExtent(self) -> usdrt.Gf._Gf.Range3d: ...
    def GetStageId(self) -> int: ...
    def GetStageIdAsStageId(self) -> usdrt.helpers._helpers.UsdStageId: ...
    def GetStageIdAsUInt(self) -> int: ...
    def GetStageInProgressId(self) -> usdrt.helpers._helpers.StageReaderWriterId: 
        """
        Deprecated: Use GetStageReaderWriterId instead
        """
    def GetStageReaderWriterId(self) -> usdrt.helpers._helpers.StageReaderWriterId: ...
    def HasPrimAtPath(self, path: usdrt.Sdf._Sdf.Path, excludeTags: bool = True) -> bool: ...
    def IsFabricOnlyStage(self) -> bool: ...
    @staticmethod
    def Open(filePath: str, load: Stage.InitialLoadSet = InitialLoadSet.LoadAll) -> Stage: ...
    def RemovePrim(self, path: usdrt.Sdf._Sdf.Path) -> bool: ...
    @staticmethod
    def SelectPrims(*args, **kwargs) -> typing.Any: ...
    def SetAttributeValue(self, path: usdrt.Sdf._Sdf.Path, value: object, time: TimeCode = Usd.TimeCode.Default()) -> bool: ...
    @staticmethod
    def SimStageWithHistoryExists(stageId: int) -> bool: ...
    @staticmethod
    def StageWithHistoryExists(stageId: int) -> bool: 
        """
        Deprecated: Use SimStageWithHistoryExists instead
        """
    def SynchronizeToFabric(self, time_change: Stage.TimeChange = TimeChange.NoUpdate, time: TimeCode = Usd.TimeCode.Default()) -> None: ...
    def Traverse(self) -> UsdPrimRange: ...
    def WriteToLayer(self, filePath: str, includePrivateFabricProperties: bool = True, convertFabricXforms: bool = False) -> None: ...
    def WriteToStage(self, includePrivateFabricProperties: bool = True, convertFabricXforms: bool = False) -> None: ...
    def __repr__(self) -> str: ...
    pass
class TimeCode():
    @staticmethod
    def Default() -> TimeCode: ...
    @staticmethod
    def EarliestTime() -> TimeCode: ...
    def GetValue(self) -> float: ...
    def IsDefault(self) -> bool: ...
    def IsEarliestTime(self) -> bool: ...
    def IsNumeric(self) -> bool: ...
    def __eq__(self, arg0: TimeCode) -> bool: ...
    def __ge__(self, arg0: TimeCode) -> bool: ...
    def __gt__(self, arg0: TimeCode) -> bool: ...
    def __init__(self, t: float = 0.0) -> None: ...
    def __le__(self, arg0: TimeCode) -> bool: ...
    def __lt__(self, arg0: TimeCode) -> bool: ...
    def __ne__(self, arg0: TimeCode) -> bool: ...
    def __repr__(self) -> str: ...
    __hash__ = None
    pass
class Tokens():
    apiSchemas = 'apiSchemas'
    clipSets = 'clipSets'
    clips = 'clips'
    collection = 'collection'
    exclude = 'exclude'
    excludes = 'excludes'
    expandPrims = 'expandPrims'
    expandPrimsAndProperties = 'expandPrimsAndProperties'
    expansionRule = 'expansionRule'
    explicitOnly = 'explicitOnly'
    fallbackPrimTypes = 'fallbackPrimTypes'
    includeRoot = 'includeRoot'
    includes = 'includes'
    pass
class Typed(SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class UsdCollectionMembershipQuery():
    def IsPathIncluded(self, path: usdrt.Sdf._Sdf.Path, expansionRule: TfToken = None) -> bool: ...
    pass
class _PrimRangeIterator():
    def GetCurrentPrim(self) -> Prim: 
        """
        Since an iterator cannot be dereferenced in python, GetCurrentPrim()
         performs the same function: yielding the currently visited prim.
        """
    def IsValid(self) -> bool: 
        """
        true if the iterator is not yet exhausted
        """
    def PruneChildren(self) -> None: ...
    def __iter__(self) -> _PrimRangeIterator: ...
    def __next__(self) -> Prim: ...
    pass
Overwrite: usdrt.Usd._Usd.Access # value = <Access.Overwrite: 3>
Read: usdrt.Usd._Usd.Access # value = <Access.Read: 1>
ReadWrite: usdrt.Usd._Usd.Access # value = <Access.ReadWrite: 2>
