# Copyright (c) 2018-2024, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.
#
__all__ = [
    "CollectorStatus",
    "CollectorFailureOptions",
    "CollectorTaskType",
    "CollectorException",
    "Collector",
    "DefaultPrimOnlyOptions",
    "FlatCollectionTextureOptions",
    "COLLECT_MAPPING_FILE_NAME",
]

import asyncio
import hashlib
import json
import os
import sys
import time
import traceback
from enum import Enum, IntFlag
from typing import Callable, Dict, Tuple, Union
from urllib.parse import unquote

import carb
import omni
import omni.client
import omni.usd
from pxr import Sdf, Tf, Usd, UsdLux, UsdShade, UsdUtils

from .async_utils import aio_open_layer, aio_re_sub_all, aio_replace_all
from .mdl_parser import MDLParser
from .omni_client_wrapper import OmniClientWrapper
from .utils import Utils

"""Mapping file records the source info of the collected stage, which can be used to avoid re-collecting files that are not modified."""
COLLECT_MAPPING_FILE_NAME = ".collect.mapping.json"

COLLECT_MAPPING_FILE_VERSION_KEY = "version"
COLLECT_MAPPING_FILE_VERSION = "1.0"
COLLECT_MAPPING_FILE_RECORDS_KEY = "file_records"


class CollectorStatus(Enum):
    """Collector status."""

    NOT_STARTED = 0
    "Collection is not started yet."

    IN_PROGRESS = 1
    "Collection is in progress."

    FINISHED = 2
    "Collection is sucessfully done."

    CANCELLED = 3
    "Collection is cancelled."


class CollectorFailureOptions(IntFlag):
    """Options to customize failure options for collector."""

    SILENT = 0
    "Silent for all failures except root USD."

    EXTERNAL_USD_REFERENCES = 1
    "Throws exception if any external USD file is not found."

    OTHER_EXTERNAL_REFERENCES = 4
    "Throws exception if external references other than all above are missing."


class CollectorItem:
    """
    CollectorItem represents an item that's collected from the source. For each file collected from
    the source url, it has one corresponding record. This info can be used to check if it needs to
    re-collect the file or not.
    """

    def __init__(self):
        self.source_url = None  # Source url that the asset is from.
        self.source_hash = None  # Source hash from server or None if source location doesn't support hash.
        self.target_url = None  # Target url as relative path to the root of the collect folder.
        self.target_hash = None  # SHA1 hash generated by collector to check if target content has been modified.
        self.copy_skipped = False  # Checkes if copy is skipped during collection.

    @staticmethod
    def _from_dict(json_dict: dict):
        item = CollectorItem()
        item.source_url = json_dict.get("source_url", None)
        item.source_hash = json_dict.get("source_hash", None)
        item.target_url = json_dict.get("target_url", None)
        item.target_hash = json_dict.get("target_hash", None)

        # Invalid record
        if not item.source_url or not item.target_url or not item.source_hash or not item.target_hash:
            return None

        return item

    def _to_dict(self, collection_dir):
        return {
            "source_url": self.source_url,
            "source_hash": self.source_hash,
            "target_url": unquote(omni.client.make_relative_url_if_possible(collection_dir, self.target_url)),
            "target_hash": self.target_hash,
        }

    def __str__(self) -> str:
        return (
            f"<source_url = {self.source_url}, source_hash = {self.source_hash}, "
            f"target_url = {self.target_url}, target_hash = {self.target_hash}, copy_skipped = {self.copy_skipped}>"
        )


class CollectorException(Exception):
    """General collector excpetion. See :class:`.CollectorFailureOptions` for options to customize exception behaviors."""

    def __init__(self, error: str):
        self._error = error

    def __str__(self):
        return self._error


class CollectorTaskType(Enum):
    """Internal. Task type of collector."""

    READ_TASK = 0
    """Read task that reads content of a file."""

    WRITE_TASK = 1
    """Write task that writes content to a target file."""

    COPY_TASK = 2
    """Copy task that copies a file to a target location."""

    RESOLVE_TASK = 3
    """Resolve task that re-maps external references in a USD layer to new locations."""


class FlatCollectionTextureOptions(Enum):
    """Collection options for textures under 'Flat Collection' mode."""

    BY_MDL = 0
    "Groups textures by MDL."

    BY_USD = 1
    "Groups textures by USD."

    FLAT = 2
    "All textures will be under the same hierarchy, flat."


class DefaultPrimOnlyOptions(Enum):
    """Options for collecting USD with 'default prim only' mode."""

    ROOT_LAYER_ONLY = 0
    "Collects default prim only for root layer."

    ALL_LAYERS = 1
    "Collects default prim only for all layers."


class Collector:
    """Collector provides API to collect USD file with its dependencies that are scattered around different places."""

    def __init__(
        self,
        usd_path: str,
        collect_dir: str,
        usd_only: bool = False,
        flat_collection: bool = False,
        material_only: bool = False,
        failure_options=CollectorFailureOptions.SILENT,
        skip_existing: bool = False,
        max_concurrent_tasks=32,
        texture_option=FlatCollectionTextureOptions.BY_MDL,
        force_non_read_only=True,
        exclusion_rules={},
        default_prim_only=False,
        **kwargs,
    ):
        """Constructor.

        Args:
            usd_path (str): The usd stage to be collected.

            collect_dir (str): The target folder to collect the usd stage to.

            usd_only (bool, Optional): Collects usd files only or not. If it's True, it will ignore all asset types except USD files. Default is False.

            flat_collection (bool, Optional): Collects stage without keeping the original dir structure. Default is False.

            material_only (bool, Optional): Collects material and textures only or not. If it's True, it will ignore all other asset types. Default is False.
                If both `usd_only` and `material_only` are true, it will collect all asset types.

            skip_existing (bool, Optional): If files already exist in the target location, don't copy them again. Default is False.

            max_concurrent_tasks (int, Optional): The maximum concurrent tasks to run at the same time. Default is 32.

            texture_option (FlatCollectionTextureOptions, Optional): Specifies how textures are grouped in flat collection mode.
                This is to avoid name collision which results in textures overwriting each other in the cases where textures
                for different assets are not uniquely named.

            force_non_read_only (bool, Optional): If it's true and source file copied is read-only, it will set the target file writable.
                By default, it's true, which means to make all copied files writable. For USD and MDL files, they will
                always be writable after copy as it needs to be modified during collecting.

            exclusion_rules (Dict[str, str], Optional): Collector will collect and re-map all dependencies if no exclusion rules are given.
                It allows you to specify the rules to exclude specified URLs so they won't be collected, and provide
                options to map them to new locations. Here is an example.

                .. code-block:: python

                    {
                        "s3://test-path/": "/mount/test-path/",
                        "s3://another-path/": None
                    }

                Here, it defines two rules to exclude the urls prefixed by the key.
                The first rule will map those URLs prefixed with "s3://test-path/" into location "/mount/test-path/",
                and the second one will keep those URLs untouched in the collected file.

            default_prim_only (bool, Optional): If it's True, it will only collect the assets under the default prim, and only save default prim
                in the main usd file. By default, it's false, which means to collect all the assets. See :class:`DefaultPrimOnlyOptions`
                for more customizations.

        Keyword Args:
            default_prim_option (DefaultPrimOnlyOptions, Optional): Specifies how to collect default prims when default_prim_only is True.
                This option can be used to skip collecting assets that are not used in the stage composition.
                By default, it only collects default prim for root layer. REMINDER: When the option is to collect default prim
                only for all layers, it's likely that non-default prims in a layer are referenced in any layers and they are
                removed which causes invalid references.

            convert_usda_to_usdc (bool, Optional): If it's True, it will convert ascii USD files (.usda) to binary format (.usdc).
                By default, it is False and keeps the original format for all USD files.
        """
        self._usd_path = Utils.normalize_path(usd_path)

        # Collect assets that are before timestamp.
        # If asset doesn't have version that is before timestamp. It will fetch the latest one.
        self._timestamp_before = None

        self._collect_dir = Utils.normalize_path(collect_dir)
        if not self._collect_dir.endswith("/"):
            self._collect_dir += "/"
        self._collect_mapping_file = omni.client.make_absolute_url_if_possible(
            self._collect_dir, COLLECT_MAPPING_FILE_NAME
        )
        self._usd_only = usd_only and not material_only
        self._material_only = material_only and not usd_only
        self._flat_collection = flat_collection
        self._texture_option = texture_option
        self._force_non_read_only = force_non_read_only
        self._default_prim_only = default_prim_only

        self._default_prim_option = kwargs.get("default_prim_option", DefaultPrimOnlyOptions.ROOT_LAYER_ONLY)
        self._convert_usda_to_usdc = kwargs.get("convert_usda_to_usdc", False)

        # Normalize all the urls
        self._exclusion_rules = {}
        for key, value in exclusion_rules.items():
            if not key:
                continue

            key = omni.client.make_file_url_if_possible(key)
            if value:
                value = omni.client.make_file_url_if_possible(value)

            self._exclusion_rules[key] = value

        self._status = CollectorStatus.NOT_STARTED
        self._finished_callback = None
        self._progress_callback = None

        # The maximum coroutines to run in parallel.
        self.MAX_CONCURRENT_TASKS = max_concurrent_tasks

        # Current coroutines created.
        self._current_tasks = set([])

        # Records the count key that appears in the collected paths to generate unique name.
        self._unique_path_name = {}

        # It records source to target url mapping. DEPRECATED.
        self._source_target_path_mapping = {}

        # It records more detailed information from source to target mapping than _source_target_path_mapping.
        self._source_target_items = {}

        self._failure_options = failure_options
        self._skip_existing = skip_existing

        # Cached layer handle of target USD files.
        self._layer_store = {}

        # MDL parsers that record all dependencies to a MDL file.
        self._mdl_parsers = {}
        self._sublayer_offsets = {}
        self._other_asset_paths = set({})
        self._current_progress = 0
        self._total_steps = 0

        # Auxiliary structure to avoid duplicate query with omni.client.stat to speed up path existence check.
        self._path_cache = {}

        # A path will be firstly moved into self._pending_read_paths
        # once it's found, and wait for task scheduler to create tasks
        # for them. Once those tasks are created, they will be moved into
        # self._pending_processing_paths to mark that they are created, but not
        # started yet. After they are started, they will be moved into
        # self._all_read_paths.
        self._pending_read_paths = set({})
        self._pending_processing_paths = set({})
        self._all_read_paths = set({})

    def __reset(self):
        self._layer_store = {}
        self._pending_read_paths = set()
        self._pending_processing_paths = set()
        self._mdl_parsers = {}
        self._sublayer_offsets = {}
        self._other_asset_paths = set()
        self._unique_path_name.clear()
        self._source_target_path_mapping = {}
        self._current_progress = 0
        self._total_steps = 0
        self._all_read_paths.clear()
        self._path_cache = {}
        self._source_target_items = {}

    def destroy(self):
        """Destructor to release all resources."""

        self.__reset()
        self._finished_callback = None
        self._progress_callback = None
        self._status = CollectorStatus.NOT_STARTED

    @property
    def target_folder(self) -> str:
        """The target folder to collect assets into."""

        return self._collect_dir

    @property
    def source_stage_url(self) -> str:
        """The source url to be collected."""

        return self._usd_path

    @property
    def collect_mapping_file_url(self):
        """
        The mapping file path. Mapping file records the collection history of this collector.
        It can help avoiding duplication in collection if the target file exists and is not changed.
        """

        return self._collect_mapping_file

    @carb.profiler.profile
    def _caculate_flat_target_path(self, path, parent_asset=None):
        path = Utils.normalize_path(path)
        target_url = omni.client.break_url(self._collect_dir)
        is_root_usd = path == self._usd_path

        is_anon_layer = Sdf.Layer.IsAnonymousLayerIdentifier(path)
        if not is_anon_layer:
            file_url = omni.client.break_url(path)
            file_name = os.path.basename(file_url.path)
        else:
            # For anonymous layer, it will generate a name if necessary.
            file_name = Sdf.Layer.GetDisplayNameFromIdentifier(path)
            if not file_name:
                valid_name = omni.usd.make_valid_identifier(path)
                valid_name = valid_name.strip("_")
                file_name = f"{valid_name}_layer.usd"
            file_url = None

        master_usd = path == self._usd_path
        material_only = self._material_only
        if Utils.is_usd_writable_filetype(path) and master_usd:
            int_dir = ""
        else:
            if not material_only:
                int_dir = "SubUSDs/"
            else:
                int_dir = ""

            if Utils.is_material(file_name):
                int_dir = f"{int_dir}materials/"
            elif not Utils.is_usd_writable_filetype(file_name):
                int_dir = f"{int_dir}textures/"
                # OM-52799 add options to group textures by MDL / USD assets to avoid name collision causing overwrites
                if parent_asset:
                    parent_name, _ = os.path.splitext(os.path.basename(parent_asset))
                    # currently not including the file extension in parent folder names, but could add it  in if it is
                    #  more clear to show the ext as a suffix to the folder name
                    int_dir += f"{parent_name}/"

        target_path = target_url.path + int_dir + file_name
        if file_url and file_url.query and not is_root_usd:
            branch_checkpoint = omni.client.get_branch_and_checkpoint_from_query(file_url.query)
            if branch_checkpoint:
                branch, checkpoint = branch_checkpoint
                file_path, ext = os.path.splitext(target_path)
                if not branch:
                    branch = "default"
                target_path = f"{file_path}__{branch}__v{checkpoint}{ext}"

        target_path = omni.client.make_url(
            scheme=target_url.scheme,
            user=target_url.user,
            host=target_url.host,
            port=target_url.port,
            path=target_path,
            query=None,
            fragment=None,
        )
        return Utils.normalize_path(target_path)

    # All paths must be absolute path
    @carb.profiler.profile
    def _calculate_target_path(self, file_path, parent_asset=None):
        file_path = Utils.normalize_path(file_path)
        is_root_usd = file_path == self._usd_path

        # If it's to collect stage with anonymous root layer, it always uses
        # flat collection since relative paths cannot be computed.
        is_anon_root = Sdf.Layer.IsAnonymousLayerIdentifier(self._usd_path)
        if is_anon_root or self._flat_collection:
            return self._caculate_flat_target_path(file_path, parent_asset=parent_asset)

        target_url = omni.client.break_url(self._collect_dir)
        stage_url = omni.client.break_url(self._usd_path)
        file_url = omni.client.break_url(file_path)

        # OMPRW-393: Handling references from different local drive.
        if sys.platform == "win32":
            stage_drive = self._usd_path[0] if len(self._usd_path) > 1 and self._usd_path[1] == ":" else None
            file_drive = file_path[0] if len(file_path) > 1 and file_path[1] == ":" else None
        else:
            stage_drive = None
            file_drive = None

        if stage_url.scheme != file_url.scheme or stage_drive != file_drive or stage_url.host != file_url.host:
            file_path = file_url.path.lstrip("/")

            # Strip off ":"
            if file_drive and stage_drive != file_drive:
                file_path = file_drive + file_path[2:]

            if file_url.host:
                target_path = target_url.path + file_url.host + "/" + file_path
            else:
                target_path = target_url.path + file_path
        else:
            relative_url = omni.client.make_relative_url_if_possible(self._usd_path, file_path)
            relative_url = relative_url.lstrip("./")
            relative_url = relative_url.lstrip("../")
            target_path = target_url.path + relative_url

        if file_url.query:
            branch_checkpoint = omni.client.get_branch_and_checkpoint_from_query(file_url.query)
            file_name, _ = os.path.splitext(target_path)
            # Gets ext from file_url.path as it does not include query string.
            _, ext = os.path.splitext(file_url.path)
            if branch_checkpoint:
                if is_root_usd:
                    target_path = f"{file_name}{ext}"
                else:
                    branch, checkpoint = branch_checkpoint
                    if not branch:
                        branch = "default"
                    target_path = f"{file_name}__{branch}__v{checkpoint}{ext}"

        target_path = omni.client.make_url(
            scheme=target_url.scheme,
            user=target_url.user,
            host=target_url.host,
            port=target_url.port,
            path=target_path,
            query=None,
            fragment=None,
        )

        return Utils.normalize_path(target_path)

    async def _load_mapping_file(self):
        if not await OmniClientWrapper.exists(self._collect_mapping_file):
            carb.log_info(f"Skip loading mapping file {self._collect_mapping_file} as it doesn't exist.")
            return

        carb.log_info(f"Loading collector mapping file {self._collect_mapping_file}...")
        content = await OmniClientWrapper.read(self._collect_mapping_file)
        if not content:
            return

        """
        Mapping file is in format of the following:

        {
            "version": "1.0",
            "file_records" : [
                {
                    "source_url": "omniverse://test-server/test/a.usd",
                    "target_url": "./test/a.usd",
                    "target_hash": "1234",
                    "source_hash": "5678",
                },
                ...
            ]
        }

        """
        try:
            json_values = json.loads(content)
        except json.JSONDecodeError as e:
            carb.log_warn(f"Failed to load {self._collect_mapping_file} as it's broken.")
            return

        # It must be a list of file records.
        if json_values and isinstance(json_values, dict):
            version = json_values.get(COLLECT_MAPPING_FILE_VERSION_KEY, None)
            if version != COLLECT_MAPPING_FILE_VERSION:
                carb.log_warn(f"Invalid version of mapping file found.")
                return

            file_records = json_values.get(COLLECT_MAPPING_FILE_RECORDS_KEY, [])
            for value in file_records:
                if not isinstance(value, dict):
                    continue

                collect_item = CollectorItem._from_dict(value)
                if not collect_item:
                    carb.log_warn(f"Invalid record found in mapping file: {value}")
                    continue

                self._source_target_items[collect_item.source_url] = collect_item

        carb.log_info(f"Loading collector mapping file done, {len(self._source_target_items)} records found.")

    async def _save_mapping_file(self):
        carb.log_info(f"Dumping collector mapping file {self._collect_mapping_file}...")

        # Generating hash for those files that have not done yet.
        json_items = []
        for _, item in self._source_target_items.items():
            result, target_stat = await omni.client.stat_async(item.target_url)
            if result == omni.client.Result.OK:
                item.target_hash = await self.__generate_hash(target_stat)

            if not item.source_hash or not item.target_hash:
                continue

            # It dumps relative path only so that the collected folder is moveable.
            json_items.append(item._to_dict(self._collect_dir))

        # Save it to file.
        json_dict = {
            COLLECT_MAPPING_FILE_VERSION_KEY: COLLECT_MAPPING_FILE_VERSION,
            COLLECT_MAPPING_FILE_RECORDS_KEY: json_items,
        }

        try:
            json_data = json.dumps(json_dict, indent=4)
            await OmniClientWrapper.write(self._collect_mapping_file, json_data)
        except Exception:
            carb.log_warn(f"Failed to dump file records into mapping file {self._collect_mapping_file}.")

    @carb.profiler.profile
    async def _get_total_steps(self):
        stage_path = self._usd_path
        collect_usd_only = self._usd_only

        carb.log_info(f"Downloading and collecting dependencies: {stage_path}...")

        # Pre-warming to download all USDs and MDLs in parallel.
        target_path = await self.__mapping_source_path(stage_path)

        if target_path and target_path == stage_path:
            self._raise_or_log(
                stage_path, f"Failed to collect layer {stage_path} as it tries to overwrite itself.", True
            )

        self.__add_pending_read_paths(stage_path)
        await self.__add_read_task(stage_path)

        # Cancelled
        if not await self.wait_all_unfinished_tasks(True):
            return None

        if collect_usd_only:
            total = len(self._layer_store)
        else:
            total_textures = 0
            for parser in self._mdl_parsers.values():
                raw_to_absolute_texture_paths, _ = await parser.parse()
                self.__report_one_total_step(len(raw_to_absolute_texture_paths))
                total_textures += len(raw_to_absolute_texture_paths)

            total_material_assets = len(self._mdl_parsers) + total_textures

            if self._material_only:
                total = len(self._other_asset_paths) + total_material_assets
            else:
                total = len(self._layer_store) + len(self._other_asset_paths) + total_material_assets

        return total

    def _remove_prim_spec(self, layer: Sdf.Layer, prim_spec):
        if prim_spec.nameParent:
            name_parent = prim_spec.nameParent
        else:
            name_parent = layer.pseudoRoot

        if not name_parent:
            return False

        name = prim_spec.name
        if name in name_parent.nameChildren:
            del name_parent.nameChildren[name]

    def _remove_all_prims_except_default(self, target_layer):
        default_prim_name = target_layer.defaultPrim
        # Report warning if default prim is not present in this layer.
        # And we don't take any actions here, otherwise, the layer will be cleared.
        if not default_prim_name:
            carb.log_warn(
                f"Skip removing non-default prims for layer {target_layer.identifier} as it has no default prim set."
            )
            return

        to_be_removed = []
        with Sdf.ChangeBlock():
            for name, prim_spec in target_layer.rootPrims.items():
                if name == default_prim_name:
                    continue

                to_be_removed.append(prim_spec)

            for prim_spec in to_be_removed:
                self._remove_prim_spec(target_layer, prim_spec)

        target_layer.Save()

    def _remove_all_materials_and_bindings(self, stage_path):
        stage = Usd.Stage.Open(stage_path)
        if not stage:
            return

        to_be_removed = []
        for prim in stage.Traverse():
            # OMPE-15324: If the prim is coming from a reference or payload, don't touch the prim otherwise we would modify the
            # original asset.
            ancestor_paths = prim.GetPath().GetAncestorsRange()
            should_avoid = False
            for ancestor_path in ancestor_paths:
                ancestor_prim = stage.GetPrimAtPath(ancestor_path)
                if ancestor_prim.HasAuthoredReferences() or ancestor_prim.HasAuthoredPayloads():
                    should_avoid = True
                    break
            if should_avoid:
                continue

            if prim.IsA(UsdShade.Material):
                to_be_removed.append(prim)

            binding_api = UsdShade.MaterialBindingAPI(prim)
            if binding_api:
                binding_api.UnbindAllBindings()

            if prim.IsA(UsdLux.DomeLight):
                dome_light = UsdLux.DomeLight(prim)
                dome_light.GetTextureFileAttr().Set("")

        for prim in to_be_removed:
            to_remove_paths = []
            if prim:
                for prim_spec in prim.GetPrimStack():
                    layer = prim_spec.layer
                    to_remove_paths.append((layer, prim_spec))

            for item in to_remove_paths:
                self._remove_prim_spec(item[0], item[1])

        stage.Save()

    def __filter_url_with_exclusion_rules(self, url):
        normalized_url = omni.client.make_file_url_if_possible(url)
        for key, value in self._exclusion_rules.items():
            if normalized_url.startswith(key):
                if value:
                    normalized_url = value + normalized_url[len(key) :]
                else:
                    normalized_url = url
                return True, normalized_url

        # Keep it untouched if it's not excluded.
        return False, url

    @carb.profiler.profile
    def __modify_external_references(self, original_layer_identifier, target_layer):
        def modifiy_paths_cb(path):
            absolute_path = Utils.compute_absolute_path(original_layer_identifier, path)

            # OM-80511: Excluded URL patterns.
            excluded, mapped_url = self.__filter_url_with_exclusion_rules(absolute_path)
            if excluded:
                return mapped_url

            target_path = self.__get_target_url(absolute_path)
            if not target_path:
                normalized_path = Utils.normalize_path(path)
                url = omni.client.break_url(normalized_path)
                if url.scheme or os.path.isabs(normalized_path):
                    # Absolute paths that are removed from arc compositions
                    # and cannot be found by UsdUtils.ExtractExternalReferences
                    # should be converted to be relative to the parent layer to avoid exposing internal paths.
                    target_path = self._calculate_target_path(absolute_path)

                if not target_path:
                    return path

            return Utils.make_relative_path(target_layer.identifier, target_path)

        try:
            UsdUtils.ModifyAssetPaths(target_layer, modifiy_paths_cb)
        except Exception as e:
            carb.log_error(f"Failed to modify asset paths {target_layer.identifier}:" + str(e))

        LAYER_OMNI_CUSTOM_KEY = "omni_layer"
        LAYER_MUTENESS_CUSTOM_KEY = "muteness"
        LAYER_LOCK_CUSTOM_KEY = "locked"
        custom_data = target_layer.customLayerData
        if LAYER_OMNI_CUSTOM_KEY in custom_data:
            omni_data = custom_data[LAYER_OMNI_CUSTOM_KEY]
            if not omni_data:
                return

            changed = False
            for custom_key in [LAYER_MUTENESS_CUSTOM_KEY, LAYER_LOCK_CUSTOM_KEY]:
                if custom_key in omni_data:
                    new_data = {}
                    custom_key_data = omni_data[custom_key]
                    if not custom_key_data:
                        continue

                    changed = True
                    for path, value in custom_key_data.items():
                        absolute_path = Utils.compute_absolute_path(original_layer_identifier, path)
                        target_path = self.__get_target_url(absolute_path)
                        if target_path:
                            target_path = Utils.make_relative_path(target_layer.identifier, target_path)
                            new_data[target_path] = value

                    omni_data[custom_key] = new_data
                    custom_data[LAYER_OMNI_CUSTOM_KEY] = omni_data

            if changed:
                target_layer.customLayerData = custom_data

    async def __mapping_source_path(self, source_path, parent_asset=None):
        if self.__is_source_path_mapped(source_path):
            return None

        # OM-52799 add options to group textures by MDL / USD assets to avoid name collision causing overwrites
        target_path = self._calculate_target_path(source_path, parent_asset=parent_asset)
        target_path = self._make_sure_unique_path(target_path)
        await self.__add_source_target_mapping(source_path, target_path)

        return target_path

    async def __add_source_target_mapping(self, source_path, target_path, overwrite_if_exists=False):
        if not overwrite_if_exists and self.__is_source_path_mapped(source_path):
            return False

        self._source_target_path_mapping[source_path] = target_path
        self._source_target_items.setdefault(source_path, CollectorItem())
        item = self._source_target_items[source_path]
        item.source_url = source_path
        if not item.source_hash:
            result, stat = await omni.client.stat_async(source_path)
            if result == omni.client.Result.OK:
                item.source_hash = await self.__generate_hash(stat)

        item.target_url = target_path

        return True

    def get_target_url(self, source_url: str) -> str:
        """
        Gets the target url that the source url is collected to. It returns valid
        value when collect task is done. See :func:`get_status` to query
        collector status.

        Args:
            source_url (str): The source url to query.

        Returns:
            str: The corresponding target url that the source url has been collected to.
        """

        source_url = omni.client.normalize_url(source_url)

        return self.__get_target_url(source_url)

    def get_source_target_url_mapping(self) -> Dict[str, str]:
        """
        Gets the mapping of all source files to target files. It returns valid
        value when collect task is done. See :func:`.get_status` to query
        collector status.

        Returns:
            Dict[str, str]: A dict that key is the source url of files, and value is the target url of files.
        """

        return self._source_target_path_mapping

    def is_copy_skipped(self, source_url) -> bool:
        """
        Checkes if it skips copying source_url during collection.
        It returns valid value when collect task is done. See :func:`.get_status` to query
        collector status.

        Returns:
            bool: Successful or not.
        """

        item = self._source_target_items.get(source_url, None)
        return item is not None and item.copy_skipped

    def __get_target_url(self, source_url):
        return self._source_target_path_mapping.get(source_url, None)

    def __is_source_path_mapped(self, source_path):
        return source_path in self._source_target_path_mapping

    async def __generate_hash(self, stat):
        # Checking target file to see if it's not modified also
        if stat.hash:
            file_hash = stat.hash
        else:
            # Otherwise, hash = sha1(version + modified time + file size)
            # If version doesnot exist (local files, mounted files), it uses modified time + file size.
            # FIXME: Is modified time reliable for hash?
            sha1 = hashlib.sha1()

            # We must have valid modified time instead of default timestamp started from 1970/1/1.
            if stat.modified_time.timestamp() != 0:
                if stat.version:
                    sha1.update(str.encode(str(stat.version)))

                sha1.update(str.encode(str(stat.size)))
                sha1.update(str.encode(str(stat.modified_time.timestamp())))
                file_hash = sha1.hexdigest()
            else:
                file_hash = None

        return file_hash

    async def __copy_asset(self, source_url, target_url, set_target_writable_if_read_only=False, collect_item_key=None, raise_error=False):
        result, target_stat = await omni.client.stat_async(target_url)
        if collect_item_key is None:
            collect_item_key = source_url
        collect_item = self._source_target_items.get(collect_item_key, None)

        # Check target file to see if it should be copied.
        if collect_item and result == omni.client.Result.OK and collect_item.target_hash:
            result, source_stat = await omni.client.stat_async(source_url)
            if result == omni.client.Result.OK:
                # Source file was not modified.
                source_hash = await self.__generate_hash(source_stat)
                if source_hash == collect_item.source_hash:
                    # Checking target file to see if it's not modified also
                    target_hash = await self.__generate_hash(target_stat)
                    if target_hash == collect_item.target_hash:
                        collect_item.copy_skipped = True

                        carb.log_info(f"Skip copy to {source_url} as target exists arleady and was not modified.")
                        return True
                else:
                    collect_item.source_hash = source_hash

                # Target hash should be invalid too since it needs to do copy that will change target file.
                collect_item.target_hash = None

        return await OmniClientWrapper.copy(source_url, target_url, set_target_writable_if_read_only, raise_error=raise_error)

    # Gets external references.
    @carb.profiler.profile
    async def __get_external_references(self, original_layer_identifier, target_layer):
        try:
            sublayer_paths, reference_paths, payload_paths = UsdUtils.ExtractExternalReferences(target_layer.identifier)
        except Exception as e:
            carb.log_error(f"Failed to collect {target_layer.identifier}: " + str(e))
            sublayer_paths = []
            reference_paths = []
            payload_paths = []

        all_usd_paths = set()
        all_mdl_paths = set()
        other_asset_paths = set()

        async def track_path(path):
            absolute_path = Utils.compute_absolute_path(original_layer_identifier, path)

            # OM-80511: Excluded URL patterns.
            excluded, _ = self.__filter_url_with_exclusion_rules(absolute_path)
            if excluded:
                return

            if self.__is_source_path_mapped(absolute_path):
                return

            if Utils.is_material(path):
                existed = await OmniClientWrapper.exists(absolute_path)
                # OM-44975: If it does not exist locally and it cannot be resolved with search paths,
                # just leave the path as it is.
                if not existed:
                    absolute_path = Utils.compute_absolute_path(self._usd_path, path)
                    # OM-43965: resolve agaist stage path.
                    existed = await OmniClientWrapper.exists(absolute_path)
                    if not existed:
                        return

            mapping_kwargs = {}
            if Utils.is_udim_texture(absolute_path):
                all_asset_paths = await self.__populate_udim_textures(absolute_path)
                for path in all_asset_paths:
                    await self.__mapping_source_path(path, **mapping_kwargs)
            else:
                all_asset_paths = [absolute_path]

            if Utils.is_usd_writable_filetype(absolute_path):
                all_usd_paths.add(absolute_path)
            elif Utils.is_material(absolute_path):
                all_mdl_paths.add(absolute_path)
            else:
                # should only add parent asset option in mapping if the current path is not USD or MDL
                if self._flat_collection and self._texture_option is FlatCollectionTextureOptions.BY_USD:
                    # do not add the root stage itself as a parent
                    if original_layer_identifier != self._usd_path:
                        mapping_kwargs["parent_asset"] = original_layer_identifier

                # Adds udim mapping but not into copy list.
                if Utils.is_udim_texture(absolute_path):
                    all_asset_paths = await self.__populate_udim_textures(absolute_path)
                    for path in all_asset_paths:
                        await self.__mapping_source_path(path, **mapping_kwargs)
                else:
                    all_asset_paths = [absolute_path]
                other_asset_paths.update(all_asset_paths)

            await self.__mapping_source_path(absolute_path, **mapping_kwargs)

        async def check_paths(paths):
            tasks = []
            for path in paths:
                future = asyncio.ensure_future(track_path(path))
                tasks.append(future)

            if tasks:
                await asyncio.wait(tasks, return_when=asyncio.ALL_COMPLETED)

        await check_paths(sublayer_paths)
        await check_paths(reference_paths)
        await check_paths(payload_paths)

        return all_usd_paths, all_mdl_paths, other_asset_paths

    async def open_or_create_layer(self, layer_path, clear=True):
        """Deprecated."""

        # WA to fix OM-33212
        await omni.client.create_folder_async(os.path.dirname(layer_path))
        layer = await aio_open_layer(layer_path)
        if not layer:
            layer = Sdf.Layer.CreateNew(layer_path)
        elif clear:
            layer.Clear()

        return layer

    async def add_copy_task(self, source: str, target: str, skip_if_existed=False):
        """
        Internal. Adds a copy task that copies file from source to target.

        Args:
            source (str): The source url to copy.
            target (str): The target url to copy source url into.
            skip_if_existed (bool, Optional): If it should skip copy when the target file exists already.
        """

        return self.__add_copy_task(source, target, skip_if_existed)

    async def __add_copy_task(self, source, target, skip_if_existed=False, collect_item_key=None):
        if skip_if_existed and await OmniClientWrapper.exists(target):
            carb.log_info(f"Asset file {target} already exists, skipping copy")
        else:
            carb.log_info(f"Adding copy task from {source} to {target}")
            task = asyncio.ensure_future(self.__copy_asset(source, target, self._force_non_read_only, collect_item_key))
            task.source = source
            task.start_time = time.monotonic()
            task.target = target
            task.task_type = CollectorTaskType.COPY_TASK
            self._current_tasks.add(task)

        if len(self._current_tasks) >= self.MAX_CONCURRENT_TASKS:
            await self.wait_all_unfinished_tasks()

    async def add_write_task(self, target: str, content: Union[str, bytes]):
        """
        Internal. Adds a write task that writes target file.

        Args:
            target (str): The target url to write.
            content: (Union[str, bytes]): The content to write. It could be str, or bytes.
        """

        carb.log_info(f"Adding write task to {target}")
        task = asyncio.ensure_future(OmniClientWrapper.write(target, content))
        task.task_type = CollectorTaskType.WRITE_TASK
        task.source = None
        task.start_time = time.monotonic()
        task.target = target
        self._current_tasks.add(task)
        if len(self._current_tasks) >= self.MAX_CONCURRENT_TASKS:
            await self.wait_all_unfinished_tasks()

    async def __add_layer_resolve_task(self, source_layer_path, target_layer):
        carb.log_info(f"Adding layer resolve task for {target_layer.identifier}")
        task = asyncio.ensure_future(self.__resolve_layer(source_layer_path, target_layer))
        task.task_type = CollectorTaskType.RESOLVE_TASK
        task.source = target_layer.identifier
        task.start_time = time.monotonic()
        task.target = None
        self._current_tasks.add(task)
        if len(self._current_tasks) >= self.MAX_CONCURRENT_TASKS:
            await self.wait_all_unfinished_tasks()

    @carb.profiler.profile
    async def __resolve_layer(self, source_layer_path, target_layer):
        # Resolve all external assets
        # OM-87405: DON'T CALL THIS FROM ANOTHER THREAD AS MIX PYBIND11 AND
        # PY.BOOST MAY CAUSE HANG DUE TO GIL ISSUE.
        self.__modify_external_references(source_layer_path, target_layer)

        # OM-40291: Copy sublayer offsets.
        sublayer_offsets = self._sublayer_offsets.get(source_layer_path, None)
        if sublayer_offsets:
            for i in range(len(sublayer_offsets)):
                target_layer.subLayerOffsets[i] = sublayer_offsets[i]

        # return await aio_save_layer(target_layer)
        # Don't use async save as it will cause hang when hang detector is enabled.
        return target_layer.Save()

    async def __append_checkpoint_to_url_if_possible(self, source_path):
        if not self._timestamp_before or source_path == self._usd_path:
            return source_path

        result, server_info = await omni.client.get_server_info_async(source_path)
        if result == omni.client.Result.OK:
            support_checkpoint = server_info and server_info.checkpoints_enabled
        else:
            support_checkpoint = False

        # OMPRW-665: We should inject checkpoint into the query string if main stage USD specifies that so we only
        # collect asset version that is equal or before the expected version.
        # The following checks are to skip those URLs except root USD file that have explicit version specified.
        # FIXME: Besides checkpoints params, it also includes to query version with timestamp which is not supported
        # currently, for example, omniverse://test-server/url?timesample=170xxxxxx.
        if support_checkpoint:
            source_url = omni.client.break_url(source_path)
            if not source_url.query or not omni.client.get_branch_and_checkpoint_from_query(source_url.query):
                result, entries = await omni.client.list_checkpoints_async(source_path)
                if result == omni.client.Result.OK and entries:
                    # Find checkpoint that's equal or older than the expected timestamp.
                    for entry in entries:
                        if entry.modified_time.timestamp() > self._timestamp_before:
                            continue

                        query_string = source_url.query
                        if not query_string:
                            query_string = ""

                        # relative_path includes the checkpoint query string.
                        query_string += entry.relative_path
                        url_with_checkpoint = omni.client.make_url(
                            scheme=source_url.scheme,
                            user=source_url.user,
                            host=source_url.host,
                            port=source_url.port,
                            path=source_url.path,
                            query=query_string,
                            fragment=source_url.fragment,
                        )

                        source_path = url_with_checkpoint

        return Utils.normalize_path(source_path)

    @carb.profiler.profile
    async def __open_and_analyze_layer(self, source_path, target_path):
        is_main_usd = source_path == self._usd_path
        source_path_with_checkpoint = await self.__append_checkpoint_to_url_if_possible(source_path)
        if self._material_only:
            target_layer = await aio_open_layer(source_path_with_checkpoint)
        else:
            layer = Sdf.Find(source_path_with_checkpoint)
            if layer:
                # OM-104209: Layer is opened already. Export it to the target location to adopt latest changes.
                try:
                    success = layer.Export(target_path)
                # OMPE-15096: We could encounter target path cannot be opened for write issue, in this case fallback to
                # copying the layer instead of erroring.
                except Tf.ErrorException as e:
                    carb.log_warn(
                        f"Failed to export layer directly {source_path_with_checkpoint} to {target_path}, "
                        "copying layer instead: {str(e)}"
                    )
                    success = await self.__copy_asset(source_path_with_checkpoint, target_path, True, source_path, raise_error=True)
                else:
                    if success is False:
                        success = await self.__copy_asset(source_path_with_checkpoint, target_path, True, source_path, raise_error=True)
                    collect_item = self._source_target_items.get(source_path, None)
                    if collect_item:
                        # Clears source hash as layer opened in the memory may be modified already.
                        collect_item.source_hash = None
            else:
                # OM-52207: copy it firstly to keep tags for omniverse path.
                success = await self.__copy_asset(source_path_with_checkpoint, target_path, True, source_path, raise_error=True)
            if not success:
                return False

            try:
                target_layer = await aio_open_layer(target_path)

                # OMPRW-387: Ensure any ascii USD gets converted to binary form
                if self._convert_usda_to_usdc:
                    is_usda = target_layer.GetFileFormat() == Sdf.FileFormat.FindByExtension(".usda")
                    underlying_file_format = Usd.UsdFileFormat.GetUnderlyingFormatForLayer(target_layer)
                    if is_usda or underlying_file_format == "usda":
                        file_path, ext = os.path.splitext(target_path)
                        path_changed = ext != ".usd"

                        if path_changed:
                            # Rename the target path
                            file_path += ".usd"
                            new_target_path = self._make_sure_unique_path(file_path)
                            await self.__add_source_target_mapping(source_path, new_target_path, True)
                            usdc_layer = Sdf.Layer.New(Sdf.FileFormat.FindByExtension(".usdc"), new_target_path)
                        else:
                            usdc_layer = Sdf.Layer.CreateAnonymous(
                                "temp", format=Sdf.FileFormat.FindByExtension(".usdc")
                            )
                        usdc_layer.TransferContent(target_layer)

                        # Release opened layer to write new content
                        old_target_path = target_layer.identifier
                        target_layer = None

                        if path_changed:
                            # Remove old file
                            await OmniClientWrapper.delete(old_target_path)
                            target_layer = usdc_layer
                            target_layer.Save()
                            usdc_layer = None
                        else:
                            # Overwrite original layer.
                            usdc_layer.Export(target_path)
                            usdc_layer = None

                            # Re-open layer after format change.
                            target_layer = await aio_open_layer(target_path)
            except Tf.ErrorException:
                # WA for OM-52094: usda in server may be saved as usdc format,
                # which cannot be opened with USD library locally.
                # The solution here is to rename it as .usd.
                target_layer = None
                root, _ = os.path.splitext(target_path)
                renamed_usd = root + ".usd"
                renamed_usd = self._make_sure_unique_path(renamed_usd)
                success = await self.__copy_asset(target_path, renamed_usd)
                if success:
                    await OmniClientWrapper.delete(target_path)
                    target_layer = await aio_open_layer(renamed_usd)
                    await self.__add_source_target_mapping(source_path, renamed_usd, True)

        if not target_layer:
            return False

        self._layer_store[source_path] = target_layer
        if not self._material_only:
            self.__report_one_total_step()

        if target_layer.subLayerOffsets:
            self._sublayer_offsets[source_path] = target_layer.subLayerOffsets.copy()

        if not self._material_only and self._default_prim_only:
            if is_main_usd or self._default_prim_option == DefaultPrimOnlyOptions.ALL_LAYERS:
                self._remove_all_prims_except_default(target_layer)

        carb.log_info(f"Collecting dependencies for usd {source_path}...")
        all_usd_paths, all_mdl_paths, all_other_paths = await self.__get_external_references(source_path, target_layer)

        self.__add_pending_read_paths(all_usd_paths)
        if self._usd_only:
            self._remove_all_materials_and_bindings(target_layer.identifier)
        else:
            self.__add_pending_read_paths(all_mdl_paths)
            self._other_asset_paths.update(all_other_paths)
            self.__report_one_total_step(len(all_other_paths))

        return True

    async def __populate_udim_textures(self, udim_texture_path):
        src_dir = os.path.dirname(udim_texture_path)
        if not src_dir.endswith("/"):
            src_dir = src_dir + "/"

        result, entries = await omni.client.list_async(src_dir)
        if result != omni.client.Result.OK:
            self._raise_or_log(
                udim_texture_path, f"Failed to list UDIM textures {udim_texture_path}, error code: {result}"
            )

        texture_paths = []
        for entry in entries:
            texture_path = Utils.compute_absolute_path(src_dir, entry.relative_path)
            if Utils.is_udim_wildcard_texture(texture_path, udim_texture_path):
                texture_paths.append(texture_path)

        return texture_paths

    @carb.profiler.profile
    async def __open_and_analyze_mdl(self, path, target_path):
        path_with_checkpoint = await self.__append_checkpoint_to_url_if_possible(path)

        # OM-52207: copy it firstly to keep tags for omniverse path.
        success = await self.__copy_asset(path_with_checkpoint, target_path, True, path)
        if not success:
            return False

        content = await OmniClientWrapper.read(target_path)
        if not content:
            return False

        mdl_parser = MDLParser(path, content, self._path_cache)
        self._mdl_parsers[path] = mdl_parser
        self.__report_one_total_step()

        carb.log_info(f"Collecting dependencies for mdl {path}...")
        raw_to_absolute_texture_paths, imports = await mdl_parser.parse()
        mapping_kwargs = {}
        if self._flat_collection and self._texture_option is FlatCollectionTextureOptions.BY_MDL:
            mapping_kwargs["parent_asset"] = path
        for absolute_texture_path in raw_to_absolute_texture_paths.values():
            # OM-80511: Excluded URL patterns.
            excluded, _ = self.__filter_url_with_exclusion_rules(absolute_texture_path)
            if excluded:
                continue

            if not await self.__mapping_source_path(absolute_texture_path, **mapping_kwargs):
                continue

            if Utils.is_udim_texture(absolute_texture_path):
                all_asset_paths = await self.__populate_udim_textures(absolute_texture_path)
                for path in all_asset_paths:
                    # Put them into other paths without copying from mdl parser.
                    self._other_asset_paths.add(path)
                    await self.__mapping_source_path(path, **mapping_kwargs)

        for mdl_import in imports:
            if self.__is_cancelled():
                break

            absolute_import_path = mdl_import.package_path
            # OM-80511: Excluded URL patterns.
            excluded, _ = self.__filter_url_with_exclusion_rules(absolute_import_path)
            if excluded:
                continue

            await self.__mapping_source_path(absolute_import_path)
            self.__add_pending_read_paths(absolute_import_path)

        return True

    def __add_pending_read_paths(self, paths):
        if isinstance(paths, str):
            paths = [paths]

        for path in paths:
            if path not in self._all_read_paths:
                self._pending_read_paths.add(path)

    async def __add_read_task(self, path):
        self._pending_read_paths.discard(path)
        self._pending_processing_paths.discard(path)
        if path in self._all_read_paths:
            return

        self._all_read_paths.add(path)

        if path in self._layer_store or path in self._mdl_parsers:
            return

        carb.log_info(f"Adding read task to {path}")
        is_usd_type = Utils.is_usd_writable_filetype(path)
        is_mdl_path = Utils.is_material(path)
        target_path = self.__get_target_url(path)
        if not target_path:
            carb.log_warn(f"Unexpected error: target path {target_path} is not mapped.")
            return

        if is_usd_type:
            task = asyncio.ensure_future(self.__open_and_analyze_layer(path, target_path))
        elif is_mdl_path and not self._usd_only:
            task = asyncio.ensure_future(self.__open_and_analyze_mdl(path, target_path))
        else:
            task = None

        if task:
            self.__report_one_total_step()
            task.task_type = CollectorTaskType.READ_TASK
            task.source = path
            task.target = None
            task.start_time = time.monotonic()
            self._current_tasks.add(task)
        if len(self._current_tasks) >= self.MAX_CONCURRENT_TASKS:
            await self.wait_all_unfinished_tasks()

    def __cancel_all_tasks(self):
        try:
            self._progress_callback = None
            for task in self._current_tasks:
                task.cancel()
        except Exception:
            pass
        finally:
            self._current_tasks.clear()

    async def wait_all_unfinished_tasks(self, all_completed=False):
        """Internal."""

        if len(self._current_tasks) == 0:
            return True

        if self.__is_cancelled():
            self.__cancel_all_tasks()
            return False

        carb.log_info(f"Waiting for {len(self._current_tasks)} tasks...")

        while len(self._current_tasks) > 0 or len(self._pending_read_paths) > 0:
            if self.__is_cancelled():
                self.__cancel_all_tasks()
                return False

            if self._current_tasks:
                try:
                    done, _ = await asyncio.wait(self._current_tasks, return_when=asyncio.FIRST_COMPLETED)
                    failed_tasks = set()
                    for task in done:
                        if task not in self._current_tasks:
                            continue

                        self.__report_one_progress()

                        result = task.result()
                        if not result:
                            failed_tasks.add(task)
                            if task.task_type == CollectorTaskType.COPY_TASK:
                                self._raise_or_log(task.source, f"Failed to move from {task.source} to {task.target}.")
                            elif task.task_type == CollectorTaskType.WRITE_TASK:
                                self._raise_or_log(task.target, f"Failed to write {task.target}.")
                            elif task.task_type == CollectorTaskType.READ_TASK:
                                self._raise_or_log(task.source, f"Failed to read {task.source} as it does not exist.")
                            elif task.task_type == CollectorTaskType.RESOLVE_TASK:
                                self._raise_or_log(task.source, f"Failed to resolve layer {task.source}.")
                        else:
                            carb.log_info(
                                f"Task done, source: {task.source}, time cost: {time.monotonic() - task.start_time}s"
                            )

                        self._current_tasks.discard(task)

                    if done:
                        # Waits one frame for progress callback, like updating UI, etc.
                        await omni.kit.app.get_app().next_update_async()
                except CollectorException as e:
                    raise e
                except Exception:
                    traceback.print_exc()

            # Fill new tasks if it's not over the maximum.
            if len(self._current_tasks) < self.MAX_CONCURRENT_TASKS:
                to_discard_paths = []
                to_read_paths = []

                # Capacity to create tasks
                left = self.MAX_CONCURRENT_TASKS - len(self._current_tasks)
                left -= len(self._pending_processing_paths)

                count = 0
                for path in self._pending_read_paths:
                    # It's handled already.
                    if path in self._all_read_paths:
                        to_discard_paths.append(path)
                        continue

                    # It's in progress of processing.
                    if path in self._pending_processing_paths:
                        continue

                    if count >= left:
                        break

                    count += 1
                    to_read_paths.append(path)

                for path in to_discard_paths:
                    self._pending_read_paths.discard(path)

                for path in to_read_paths:
                    self._pending_processing_paths.add(path)
                    asyncio.ensure_future(self.__add_read_task(path))

            if not all_completed:
                break

            await asyncio.sleep(0.1)

        carb.log_info(f"Waiting for unfinished done, left {len(self._current_tasks)} tasks...")

        return True

    def get_status(self) -> CollectorStatus:
        """
        Gets the collector status. See :class:`.CollectorStatus` for more details.

        Returns:
            CollectorStatus: The current status of the collector.
        """

        return self._status

    def is_finished(self):
        """
        Collect is done or not. It returns True no matter it's cancelled or successfully done.
        REMINDER: This function is DEPRECATED. See :func:`.get_status` for more accurate status.

        Returns:
            bool: Collection is finished or not.
        """

        status = self.get_status()
        return status == CollectorStatus.CANCELLED or status == CollectorStatus.FINISHED

    def is_cancelled(self):
        """
        Collector is cancelled or not. REMINDER: This function is DEPRECATED. See :func:`.get_status` for more accurate status.

        Returns:
            bool: Collection is cancelled or not.
        """

        return self.__is_cancelled()

    def __is_cancelled(self):
        status = self.get_status()
        return status == CollectorStatus.CANCELLED

    def cancel(self):
        """Cancel the collector if it's in progress."""

        status = self.get_status()
        if status == CollectorStatus.IN_PROGRESS:
            self._status = CollectorStatus.CANCELLED
            self.__cancel_all_tasks()

    def _make_sure_unique_path(self, path):
        # Generates unique path name
        if Utils.is_udim_texture(path):
            return path

        path = Utils.normalize_path(path)
        while True:
            index = self._unique_path_name.get(path, -1)
            if index == -1:
                self._unique_path_name[path] = 0
                break
            else:
                index += 1
                self._unique_path_name[path] = index
                file_path, ext = os.path.splitext(path)
                path = file_path + "_" + str(index) + ext
        self._unique_path_name[path] = 0

        return path

    def _raise_or_log(self, path, error, force_raise=False):
        is_usd_type = Utils.is_usd_writable_filetype(path)
        has_usd_failure_option = self._failure_options & CollectorFailureOptions.EXTERNAL_USD_REFERENCES
        has_other_failure_option = self._failure_options & CollectorFailureOptions.OTHER_EXTERNAL_REFERENCES
        if force_raise or (is_usd_type and has_usd_failure_option) or (not is_usd_type and has_other_failure_option):
            raise CollectorException(error)
        else:
            carb.log_warn(error)

    @carb.profiler.profile
    async def collect(
        self, progress_callback: Callable[[int, int], None] = None, finish_callback: Callable[[], None] = None
    ) -> Tuple[bool, str]:
        """Collects stage in an asynchronous way.

        Args:
            progress_callback (Callable[[int, int], None]): The progress callback that notifies the current progress in
                (current_step, total_steps) style.
            finish_callback (Callable[[], None]): Finish callback when task is done or cancelled.

        Returns:
            Tuple[bool, str]: The success status and the path of the collected stage root if it exists.
        """

        try:
            self.__reset()
            self._status = CollectorStatus.IN_PROGRESS
            self._finished_callback = finish_callback
            self._progress_callback = progress_callback
            return await self._collect_internal()
        except Exception as e:
            self._status = CollectorStatus.CANCELLED
            raise e
        finally:
            if finish_callback:
                finish_callback()

            self._finished_callback = None
            self._progress_callback = None
            self._layer_store = {}

    def __report_one_total_step(self, step=1):
        self._total_steps += step
        if self._progress_callback:
            self._progress_callback(self._current_progress, self._total_steps)

    def __report_one_progress(self):
        self._current_progress += 1
        if self._current_progress >= self._total_steps:
            self._current_progress = self._total_steps

        if self._progress_callback:
            self._progress_callback(self._current_progress, self._total_steps)

    @carb.profiler.profile
    async def _collect_internal(self):
        # Loading mapping file, the content of which can be used to speed up collect by comparing
        # the content hash recorded in the file.
        await self._load_mapping_file()

        file_url = omni.client.break_url(self._usd_path)
        if file_url.query:
            branch_checkpoint = omni.client.get_branch_and_checkpoint_from_query(file_url.query)
            if branch_checkpoint:
                result, stat = await omni.client.stat_async(self._usd_path)
                if result == omni.client.Result.OK:
                    self._timestamp_before = stat.modified_time.timestamp()

        carb.log_info(f"Collecting stage {self._usd_path} to {self._collect_dir}...")
        total = await self._get_total_steps()
        if total == 0:
            raise CollectorException(f"Failed to collect {self._usd_path} as it cannot be opened.")
        elif total is None:
            carb.log_info(f"Collecting stage {self._usd_path} to {self._collect_dir} is cancelled.")
            return False, None

        # Add one more step to wait for tasks to be done.
        self.__report_one_total_step()

        carb.log_info(f"Starting to collect: total steps {self._total_steps} found...")

        if not self._material_only:
            for source_layer_path, target_layer in self._layer_store.items():
                carb.log_info(f"Modifying external references for {target_layer.identifier}...")
                if self.__is_cancelled():
                    break

                await self.__add_layer_resolve_task(source_layer_path, target_layer)

        if not self._usd_only:
            for mdl_absolute_path, mdl_parser in self._mdl_parsers.items():
                if self.__is_cancelled():
                    break

                carb.log_info(f"Collecting mdl {mdl_absolute_path}...")
                # Per MDL.
                processed_texture_path = set([])
                mdl_target_path = self.__get_target_url(mdl_absolute_path)
                mdl_content = mdl_parser.content
                raw_to_absolute_texture_paths, mdl_imports = await mdl_parser.parse()
                for raw_texture_path, absolute_texture_path in raw_to_absolute_texture_paths.items():
                    if self.__is_cancelled():
                        break

                    if absolute_texture_path in processed_texture_path:
                        continue

                    processed_texture_path.add(absolute_texture_path)

                    # OM-80511: Excluded URL patterns.
                    excluded, texture_target_path = self.__filter_url_with_exclusion_rules(absolute_texture_path)
                    if excluded:
                        relative_path = texture_target_path
                    else:
                        texture_target_path = self.__get_target_url(absolute_texture_path)
                        relative_path = Utils.make_relative_path(mdl_target_path, texture_target_path)

                    mdl_content = await aio_re_sub_all(
                        mdl_content,
                        rf'(\btexture_(?:2d|3d|cube|ptex)\("){raw_texture_path}(")',
                        rf'\1{relative_path}\2'
                    )

                    mdl_content = await aio_replace_all(
                        mdl_content,
                        f'<input name="file" type="filename" value="{raw_texture_path}',
                        f'<input name="file" type="filename" value="{relative_path}',
                    )
                    # OMPE-41571: also need replace texture path inbsdf_measurement
                    mdl_content = await aio_re_sub_all(
                        mdl_content, rf'(.*bsdf_measurement\("){raw_texture_path}(.*)', rf"\1{relative_path}\2"
                    )

                    if not excluded and not Utils.is_udim_texture(absolute_texture_path):
                        path_with_checkpoint = await self.__append_checkpoint_to_url_if_possible(absolute_texture_path)
                        carb.log_info(f"Moving texture file {path_with_checkpoint} to {texture_target_path}")
                        await self.__add_copy_task(
                            path_with_checkpoint, texture_target_path, self._skip_existing, absolute_texture_path
                        )

                # Handling mdls that's imported
                for mdl_import in mdl_imports:
                    if self.__is_cancelled():
                        break

                    # OM-80511: Excluded URL patterns.
                    excluded, import_target_path = self.__filter_url_with_exclusion_rules(mdl_import.package_path)
                    if excluded:
                        relative_path = import_target_path
                    else:
                        import_target_path = self.__get_target_url(mdl_import.package_path)
                        # It's not mapped so it does not exist.
                        if not import_target_path:
                            continue

                        relative_path = Utils.make_relative_path(mdl_target_path, import_target_path)

                    import_clause = mdl_import.import_clause
                    if relative_path.endswith(".mdl"):
                        relative_path = relative_path[:-4]
                    while relative_path.startswith("./"):
                        relative_path = relative_path[2:]
                    relative_path = relative_path.replace("/", "::")
                    if mdl_import.module_preset:
                        # OM-7604
                        has_prefix = False
                        while relative_path.startswith("..::"):
                            has_prefix = True
                            relative_path = relative_path[4:]
                        if has_prefix and relative_path:
                            relative_path = f"::{relative_path}"

                    import_clause = import_clause.replace(mdl_import.import_package, relative_path)
                    mdl_content = await aio_replace_all(mdl_content, mdl_import.import_clause, import_clause)

                    import_package = mdl_import.import_package
                    while import_package.startswith(".::") or import_package.startswith("..::"):
                        if import_package.startswith(".::"):
                            import_package = import_package[3:]
                        else:
                            import_package = import_package[4:]

                    # OM-37410: It's possible that function is referenced with full module path.
                    # OMPE-41571: this not only occurs in flat collection
                    if import_package:
                        mdl_content = await aio_replace_all(
                            mdl_content, import_package, relative_path, exact_match=True
                        )

                await self.add_write_task(mdl_target_path, mdl_content)

        # Copy all external assets except USD and MDLs to target path
        for absolute_asset_path in self._other_asset_paths:
            if self.__is_cancelled():
                break

            # Skip udim path as it's expanded already.
            if Utils.is_udim_texture(absolute_asset_path):
                continue

            asset_target_path = self.__get_target_url(absolute_asset_path)
            path_with_checkpoint = await self.__append_checkpoint_to_url_if_possible(absolute_asset_path)
            carb.log_info(f"Moving asset file from {path_with_checkpoint} to {asset_target_path}")
            await self.__add_copy_task(
                path_with_checkpoint, asset_target_path, self._skip_existing, absolute_asset_path
            )

        if not await self.wait_all_unfinished_tasks(True):
            carb.log_info("Collecting is cancelled.")
            success = False
            root_usd_url = None
        else:
            self._status = CollectorStatus.FINISHED
            carb.log_info("Collecting is finished.")

            success = True
            if self._material_only:
                root_usd_url = None
            else:
                root_usd_url = self.__get_target_url(self._usd_path)

            await self._save_mapping_file()

        return success, root_usd_url
