
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.materialx.libs-6c547c3dd5ef2807.zip"

    [package.publish]
        kitVersion = "107.3.2+production.212355.196c58f4.gl"
        date = 1757755258
        buildNumber = "107.3.2+1073.212355.196c58f4.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
