from __future__ import annotations
import usdrt.UsdGeom._UsdGeom
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd

__all__ = [
    "BasisCurves",
    "Boundable",
    "Camera",
    "Capsule",
    "Cone",
    "Cube",
    "Curves",
    "Cylinder",
    "Gprim",
    "HermiteCurves",
    "Imageable",
    "Mesh",
    "ModelAPI",
    "MotionAPI",
    "NurbsCurves",
    "NurbsPatch",
    "Plane",
    "PointBased",
    "PointInstancer",
    "Points",
    "Primvar",
    "PrimvarsAPI",
    "Scope",
    "Sphere",
    "Subset",
    "Tokens",
    "VisibilityAPI",
    "Xform",
    "XformCommonAPI",
    "Xformable"
]


class BasisCurves(Curves, PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateBasisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateWrapAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> BasisCurves: ...
    def GetBasisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetWrapAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Boundable(Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Camera(Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateClippingPlanesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateClippingRangeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExposureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFStopAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFocalLengthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFocusDistanceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateHorizontalApertureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateHorizontalApertureOffsetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateProjectionAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShutterCloseAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShutterOpenAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateStereoRoleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVerticalApertureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVerticalApertureOffsetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Camera: ...
    def GetClippingPlanesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetClippingRangeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExposureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFStopAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFocalLengthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFocusDistanceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetHorizontalApertureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetHorizontalApertureOffsetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetProjectionAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShutterCloseAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShutterOpenAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetStereoRoleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVerticalApertureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVerticalApertureOffsetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Capsule(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Capsule: ...
    def GetAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Cone(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Cone: ...
    def GetAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Cube(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Cube: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetSizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Curves(PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateCurveVertexCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateWidthsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCurveVertexCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetWidthsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Cylinder(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Cylinder: ...
    def GetAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class HermiteCurves(Curves, PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateTangentsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> HermiteCurves: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTangentsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Mesh(PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateCornerIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateCornerSharpnessesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateCreaseIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateCreaseLengthsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateCreaseSharpnessesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFaceVaryingLinearInterpolationAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFaceVertexCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFaceVertexIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateHoleIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateInterpolateBoundaryAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSubdivisionSchemeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTriangleSubdivisionRuleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Mesh: ...
    def GetCornerIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCornerSharpnessesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCreaseIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCreaseLengthsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCreaseSharpnessesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFaceVaryingLinearInterpolationAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFaceVertexCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFaceVertexIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetHoleIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetInterpolateBoundaryAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetSubdivisionSchemeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTriangleSubdivisionRuleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class NurbsCurves(Curves, PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateFormAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePointWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRangesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> NurbsCurves: ...
    def GetFormAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPointWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRangesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class NurbsPatch(PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreatePointWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTrimCurveCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTrimCurveKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTrimCurveOrdersAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTrimCurvePointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTrimCurveRangesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTrimCurveVertexCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateUFormAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateUKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateUOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateURangeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateUVertexCountAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVFormAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVRangeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVVertexCountAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> NurbsPatch: ...
    def GetPointWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTrimCurveCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTrimCurveKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTrimCurveOrdersAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTrimCurvePointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTrimCurveRangesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTrimCurveVertexCountsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetUFormAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetUKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetUOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetURangeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetUVertexCountAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVFormAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVKnotsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVRangeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetVVertexCountAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Plane(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDoubleSidedAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLengthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateWidthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Plane: ...
    def GetAxisAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDoubleSidedAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLengthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetWidthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Points(PointBased, Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateIdsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateWidthsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Points: ...
    def GetIdsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetWidthsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class PointBased(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAccelerationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateNormalsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVelocitiesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetAccelerationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetNormalsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetVelocitiesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Gprim(Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateDisplayColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDisplayOpacityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDoubleSidedAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateOrientationAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisplayColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisplayOpacityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDoubleSidedAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetOrientationAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Imageable(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateProxyPrimRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreatePurposeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetProxyPrimRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetPurposeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class ModelAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> ModelAPI: ...
    def CreateModelApplyDrawModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardGeometryAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardTextureXNegAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardTextureXPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardTextureYNegAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardTextureYPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardTextureZNegAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelCardTextureZPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelDrawModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateModelDrawModeColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelApplyDrawModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardGeometryAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardTextureXNegAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardTextureXPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardTextureYNegAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardTextureYPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardTextureZNegAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelCardTextureZPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelDrawModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetModelDrawModeColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class MotionAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> MotionAPI: ...
    def CreateMotionBlurScaleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateNonlinearSampleCountAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVelocityScaleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetMotionBlurScaleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetNonlinearSampleCountAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetVelocityScaleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class PointInstancer(Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAccelerationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateAngularVelocitiesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateIdsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateInvisibleIdsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateOrientationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePositionsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateProtoIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePrototypesRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateScalesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVelocitiesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> PointInstancer: ...
    def GetAccelerationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetAngularVelocitiesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetIdsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetInvisibleIdsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetOrientationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPositionsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetProtoIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPrototypesRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetScalesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetVelocitiesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Primvar():
    def Get(self, time: usdrt.Usd._Usd.TimeCode = Usd.TimeCode.Default()) -> object: ...
    def GetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetInterpolation(self) -> TfToken: ...
    def GetName(self) -> TfToken: ...
    def HasAuthoredInterpolation(self) -> bool: ...
    def HasAuthoredValue(self) -> bool: ...
    def HasValue(self) -> bool: ...
    def IsDefined(self) -> bool: ...
    @staticmethod
    def IsPrimvar(attr: usdrt.Usd._Usd.Attribute) -> bool: ...
    @staticmethod
    def IsValidInterpolation(interpolation: TfToken) -> bool: ...
    @staticmethod
    def IsValidInterpolationName(name: TfToken) -> bool: ...
    @staticmethod
    def IsValidPrimvarName(name: TfToken) -> bool: ...
    def Set(self, value: object, time: usdrt.Usd._Usd.TimeCode = Usd.TimeCode.Default()) -> bool: ...
    def SetInterpolation(self, interpolation: TfToken) -> bool: ...
    @staticmethod
    def StripInterpolationName(name: TfToken) -> TfToken: ...
    @staticmethod
    def StripPrimvarsName(name: TfToken) -> TfToken: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Attribute) -> None: ...
    pass
class PrimvarsAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def CanContainPropertyName(name: TfToken) -> bool: ...
    def CreatePrimvar(self, name: TfToken, typeName: usdrt.Sdf._Sdf.ValueTypeName, interpolation: TfToken = '') -> Primvar: ...
    def FindIncrementallyInheritablePrimvars(self, inheritedFromAncestors: typing.List[Primvar]) -> typing.List[Primvar]: ...
    def FindInheritablePrimvars(self) -> typing.List[Primvar]: ...
    def FindInheritedPrimvar(self, arg0: TfToken) -> Primvar: ...
    def FindInheritedPrimvars(self) -> typing.List[Primvar]: ...
    @typing.overload
    def FindPrimvarWithInheritance(self, arg0: TfToken) -> Primvar: ...
    @typing.overload
    def FindPrimvarWithInheritance(self, arg0: TfToken, arg1: typing.List[Primvar]) -> Primvar: ...
    @typing.overload
    def FindPrimvarsWithInheritance(self) -> typing.List[Primvar]: ...
    @typing.overload
    def FindPrimvarsWithInheritance(self, arg0: typing.List[Primvar]) -> typing.List[Primvar]: ...
    def GetAuthoredPrimvars(self) -> typing.List[Primvar]: ...
    def GetPrimvar(self, arg0: TfToken) -> Primvar: ...
    def GetPrimvars(self) -> typing.List[Primvar]: ...
    def GetPrimvarsWithAuthoredValues(self) -> typing.List[Primvar]: ...
    def GetPrimvarsWithValues(self) -> typing.List[Primvar]: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def HasPossiblyInheritedPrimvar(self, name: TfToken) -> bool: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Scope(Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Scope: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Sphere(Gprim, Boundable, Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Sphere: ...
    def GetExtentAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Subset(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateElementTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFamilyNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Subset: ...
    def GetElementTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFamilyNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    accelerations = 'accelerations'
    all = 'all'
    angularVelocities = 'angularVelocities'
    axis = 'axis'
    basis = 'basis'
    bezier = 'bezier'
    bilinear = 'bilinear'
    boundaries = 'boundaries'
    bounds = 'bounds'
    box = 'box'
    bspline = 'bspline'
    cards = 'cards'
    catmullClark = 'catmullClark'
    catmullRom = 'catmullRom'
    clippingPlanes = 'clippingPlanes'
    clippingRange = 'clippingRange'
    closed = 'closed'
    constant = 'constant'
    cornerIndices = 'cornerIndices'
    cornerSharpnesses = 'cornerSharpnesses'
    cornersOnly = 'cornersOnly'
    cornersPlus1 = 'cornersPlus1'
    cornersPlus2 = 'cornersPlus2'
    creaseIndices = 'creaseIndices'
    creaseLengths = 'creaseLengths'
    creaseSharpnesses = 'creaseSharpnesses'
    cross = 'cross'
    cubic = 'cubic'
    curveVertexCounts = 'curveVertexCounts'
    default_ = 'default'
    doubleSided = 'doubleSided'
    edgeAndCorner = 'edgeAndCorner'
    edgeOnly = 'edgeOnly'
    elementSize = 'elementSize'
    elementType = 'elementType'
    exposure = 'exposure'
    extent = 'extent'
    extentsHint = 'extentsHint'
    fStop = 'fStop'
    face = 'face'
    faceVarying = 'faceVarying'
    faceVaryingLinearInterpolation = 'faceVaryingLinearInterpolation'
    faceVertexCounts = 'faceVertexCounts'
    faceVertexIndices = 'faceVertexIndices'
    familyName = 'familyName'
    focalLength = 'focalLength'
    focusDistance = 'focusDistance'
    form = 'form'
    fromTexture = 'fromTexture'
    guide = 'guide'
    guideVisibility = 'guideVisibility'
    height = 'height'
    hermite = 'hermite'
    holeIndices = 'holeIndices'
    horizontalAperture = 'horizontalAperture'
    horizontalApertureOffset = 'horizontalApertureOffset'
    ids = 'ids'
    inactiveIds = 'inactiveIds'
    indices = 'indices'
    inherited = 'inherited'
    interpolateBoundary = 'interpolateBoundary'
    interpolation = 'interpolation'
    invisible = 'invisible'
    invisibleIds = 'invisibleIds'
    knots = 'knots'
    left = 'left'
    leftHanded = 'leftHanded'
    length = 'length'
    linear = 'linear'
    loop = 'loop'
    metersPerUnit = 'metersPerUnit'
    modelApplyDrawMode = 'model:applyDrawMode'
    modelCardGeometry = 'model:cardGeometry'
    modelCardTextureXNeg = 'model:cardTextureXNeg'
    modelCardTextureXPos = 'model:cardTextureXPos'
    modelCardTextureYNeg = 'model:cardTextureYNeg'
    modelCardTextureYPos = 'model:cardTextureYPos'
    modelCardTextureZNeg = 'model:cardTextureZNeg'
    modelCardTextureZPos = 'model:cardTextureZPos'
    modelDrawMode = 'model:drawMode'
    modelDrawModeColor = 'model:drawModeColor'
    mono = 'mono'
    motionBlurScale = 'motion:blurScale'
    motionNonlinearSampleCount = 'motion:nonlinearSampleCount'
    motionVelocityScale = 'motion:velocityScale'
    nonOverlapping = 'nonOverlapping'
    none = 'none'
    nonperiodic = 'nonperiodic'
    normals = 'normals'
    open = 'open'
    order = 'order'
    orientation = 'orientation'
    orientations = 'orientations'
    origin = 'origin'
    orthographic = 'orthographic'
    partition = 'partition'
    periodic = 'periodic'
    perspective = 'perspective'
    pinned = 'pinned'
    pivot = 'pivot'
    pointWeights = 'pointWeights'
    points = 'points'
    positions = 'positions'
    power = 'power'
    primvarsDisplayColor = 'primvars:displayColor'
    primvarsDisplayOpacity = 'primvars:displayOpacity'
    projection = 'projection'
    protoIndices = 'protoIndices'
    prototypes = 'prototypes'
    proxy = 'proxy'
    proxyPrim = 'proxyPrim'
    proxyVisibility = 'proxyVisibility'
    purpose = 'purpose'
    radius = 'radius'
    ranges = 'ranges'
    render = 'render'
    renderVisibility = 'renderVisibility'
    right = 'right'
    rightHanded = 'rightHanded'
    scales = 'scales'
    shutterClose = 'shutter:close'
    shutterOpen = 'shutter:open'
    size = 'size'
    smooth = 'smooth'
    stereoRole = 'stereoRole'
    subdivisionScheme = 'subdivisionScheme'
    tangents = 'tangents'
    triangleSubdivisionRule = 'triangleSubdivisionRule'
    trimCurveCounts = 'trimCurve:counts'
    trimCurveKnots = 'trimCurve:knots'
    trimCurveOrders = 'trimCurve:orders'
    trimCurvePoints = 'trimCurve:points'
    trimCurveRanges = 'trimCurve:ranges'
    trimCurveVertexCounts = 'trimCurve:vertexCounts'
    type = 'type'
    uForm = 'uForm'
    uKnots = 'uKnots'
    uOrder = 'uOrder'
    uRange = 'uRange'
    uVertexCount = 'uVertexCount'
    unauthoredValuesIndex = 'unauthoredValuesIndex'
    uniform = 'uniform'
    unrestricted = 'unrestricted'
    upAxis = 'upAxis'
    vForm = 'vForm'
    vKnots = 'vKnots'
    vOrder = 'vOrder'
    vRange = 'vRange'
    vVertexCount = 'vVertexCount'
    varying = 'varying'
    velocities = 'velocities'
    vertex = 'vertex'
    verticalAperture = 'verticalAperture'
    verticalApertureOffset = 'verticalApertureOffset'
    visibility = 'visibility'
    visible = 'visible'
    width = 'width'
    widths = 'widths'
    wrap = 'wrap'
    x = 'X'
    xformOpOrder = 'xformOpOrder'
    y = 'Y'
    z = 'Z'
    pass
class VisibilityAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> VisibilityAPI: ...
    def CreateGuideVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateProxyVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRenderVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetGuideVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetProxyVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRenderVisibilityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Xform(Xformable, Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Xform: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class XformCommonAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Xformable(Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateXformOpOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetXformOpOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
