
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.viewport.scene_camera_model-eee83dbce5099538.zip"

    [package.publish]
        kitVersion = "107.3.2+production.208540.31331489.gl"
        date = 1757755258
        buildNumber = "107.3.2+1073.208540.31331489.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
