[package]
# Semantic Versioning is used: https://semver.org/
version = "1.3.12"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Asset Browser"
description="A browser to imports Assets"

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ['browser', 'asset']

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.rst"

category = "Rendering"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.svg"
feature = true

[dependencies]
"omni.kit.browser.folder.core" = {}
"omni.kit.commands" = {}
"omni.kit.menu.utils" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = { }
"omni.kit.tool.collect" = { optional=true }
"omni.kit.menu.stage" = { optional=true }
"omni.kit.clipboard" = { optional=true }

# Main python module this extension provides, it will be publicly available as "import omni.kit.browser.asset".
[[python.module]]
name = "omni.kit.browser.asset"

[settings]
exts."omni.kit.browser.asset".folders = [
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Vegetation",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/ArchVis/Commercial",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/ArchVis/Industrial",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/ArchVis/Residential",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/DigitalTwin/Assets/Warehouse/Equipment",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/DigitalTwin/Assets/Warehouse/Safety",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/DigitalTwin/Assets/Warehouse/Shipping",
    "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/DigitalTwin/Assets/Warehouse/Storage",
]
exts."omni.kit.browser.asset".instanceable = []
exts."omni.kit.browser.asset".data.timeout = 5
exts."omni.kit.browser.asset".visible_after_startup = false

[[trigger]]
menu.name = "Window/Browsers/Assets"
menu.window = "NVIDIA Assets"

[[test]]
dependencies = [
    "omni.kit.tool.collect",
    "omni.kit.menu.stage",
    "omni.kit.ui_test",
    "omni.kit.context_menu",
]

args = [
    "--no-window",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/menu/legacy_mode=false",
    "--/exts/omni.kit.browser.asset/folders/0='http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Vegetation'",
    "--/exts/omni.kit.browser.asset/folders/1=''",
    "--/exts/omni.kit.browser.asset/folders/2=''",
    "--/exts/omni.kit.browser.asset/visible_after_startup=true",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.rst",
]
