import carb
import carb.events
import omni.usd
import omni.timeline
from pxr import Sdf, Usd, UsdUtils


class MonoBScript:
    """
    MonoBScript is inspired by the MonoBehavior script from Unity and
    obviously the BehaviorScript from Isaac Sim. This is a workaround due
    to the security warnings generated by BehaviorScripts
    """

    def __init__(self, prim_path: Sdf.Path):
        """Initializes a BehaviorScript for the prim_path( Sdf.Path) this script was assigned to."""
        self._has_on_update_error = False
        self._prim_path = prim_path
        self._settings = carb.settings.get_settings()
        self._usd_context = omni.usd.get_context()
        self._selection = self._usd_context.get_selection()
        self._stage = UsdUtils.StageCache.Get().Find(Usd.StageCache.Id.FromLongInt(self._usd_context.get_stage_id()))
        self._prim = self._stage.GetPrimAtPath(self._prim_path)
        self._timeline_playing = False
        self._timeline = omni.timeline.get_timeline_interface()
        self._timeline_event_sub = self._timeline.get_timeline_event_stream().create_subscription_to_pop(
            lambda event: self._on_timeline_event(event), name="MonoBScript::TimelineEvent"
        )
        self.on_init()

    @property
    def prim_path(self) -> Sdf.Path:
        """Returns the prim path that this script is assigned to."""
        return self._prim_path

    @property
    def prim(self) -> Usd.Prim:
        """Returns the prim that this script is assigned to."""
        return self._prim

    @property
    def stage(self) -> Usd.Stage:
        """Returns the current USD stage that is opened/loaded."""
        return self._stage

    @property
    def settings(self) -> carb.settings.ISettings:
        """Returns the current settings."""
        return self._settings

    def _on_timeline_event(self, e: carb.events.IEvent):
        """
        Handles the timeline event.
        """
        if e.type == int(omni.timeline.TimelineEventType.PLAY):
            self._timeline_playing = True
            self.on_play()
        elif e.type == int(omni.timeline.TimelineEventType.PAUSE):
            self.on_pause()
            self._timeline_playing = False
        elif e.type == int(omni.timeline.TimelineEventType.STOP):
            self.on_stop()
            self._timeline_playing = False
            self._current_time = 0.0
        elif e.type == int(omni.timeline.TimelineEventType.CURRENT_TIME_TICKED):
            self.on_update()

    def on_init(self):
        """Override this method to handle when the BehaviorScript is initialize from being assigned to a USD prim."""
        pass

    def destroy(self):
        """Destroys the BehaviorScript."""
        if self._timeline_event_sub:
            self._timeline_event_sub.unsubscribe()
            self._timeline_event_sub = None
        self.on_destroy()

    def on_destroy(self):
        """Override this method to handle when the BehaviorScript is destroyed from being unassigned from a USD prim."""
        pass

    def on_play(self):
        """Override this method to handle when `play` is pressed."""
        pass

    def on_pause(self):
        """Override this method to handle when `pause` is pressed."""
        pass

    def on_stop(self):
        """Override this method to handle when the `stop` is pressed."""
        pass

    def on_update(self):
        """Override this method to handle per frame update events that occur when `playing`.
        Args:
            current_time: The current time. (in seconds).
            delta_time: The delta time (in seconds).
        """
        pass
