from __future__ import annotations

import sys
from importlib import import_module
from pathlib import Path

import carb

from ..autonode_generator.utils import (
    AUTONODE_DEVELOPER_MODE_SETTING,
    OGN_AUTOGENERATED_SUBFOLDER_NAME,
    autonode_developer_mode,
)
from .extension_contents_1_18 import ExtensionContentsV118

# TODO: from .extension_contents_1_19 import ExtensionContentsV119
from .extension_contents_base import ExtensionContentsBase
from .extension_contents_standalone import ExtensionContentsStandalone
from .file_utils import walk_with_excludes
from .logging_utils import LOG

__all__ = [
    "extension_contents_factory",
]


# ==============================================================================================================
def extension_contents_factory(ext_id: str, module_name: str, ext_path: str | Path) -> ExtensionContentsBase | None:
    """Figures out what kind of OmniGraph content is in the named extension module
    Args:
        ext_id: ID of the extension for which this factory is constructing a manager ("NAME-VERSION")
        module_name: Python module within the extension being handled
        ext_path: Root directory of the extension
    Returns:
        Constructed manager for OmniGraph contents in the given extension, or None if there is no OmniGraph content
        in the Python module.
    """
    _ = LOG.disabled or LOG.info(
        "Finding OmniGraph extension content manager for %s in module %s at %s", ext_id, module_name, ext_path
    )
    try:
        main_module = sys.modules[module_name]
        _ = LOG.disabled or LOG.info("Found main module %s in %s", module_name, main_module.__path__)
    except KeyError:
        try:
            main_module = import_module(module_name)
            _ = LOG.disabled or LOG.info("Imported main module %s as %s", module_name, main_module.__path__)
        except ModuleNotFoundError:
            _ = LOG.disabled or LOG.info("-> No Python module %s in extension %s", module_name, ext_id)
            return None

    # TODO: Check for a new-style extension with generated code in the top level ogn/ subdirectory.
    # e.g. exts/omni.my.extension/ogn/omni.my.extension/
    # generated_folder = ext_path / "ogn" / module_name
    # if generated_folder.is_dir():
    #     return ExtensionContentsV119(ext_id, main_module, ext_path)

    # Check for a V1.18 extension with generated code in the module's ogn/ subdirectory.
    # e.g. exts/omni.my.extension/omni/my/extension/ogn/
    module_path = ext_path / module_name.replace(".", "/")
    ogn_folder = module_path / "ogn"
    if ogn_folder.is_dir():
        return ExtensionContentsV118(ext_id, main_module, ext_path)
    _ = LOG.disabled or LOG.info("...ogn/ directory did not exist - %s", ogn_folder)

    # Check for standalone nodes in the extension by walking the module's directory tree.
    # os.walk is used instead of Path.rglob because in tests it was found to be 50% faster.
    # Remember the contents of the tree to avoid walking it again in the scan phase.
    python_files = []
    ogn_files = []
    for root, _, files in walk_with_excludes(module_path, ["__pycache__"]):
        if not autonode_developer_mode() and OGN_AUTOGENERATED_SUBFOLDER_NAME in Path(root).parts:
            carb.log_warn(
                f"Found AutoNode definitions in {root} but the setting '{AUTONODE_DEVELOPER_MODE_SETTING}'"
                f" has not been enabled. Skipping registration of node types in that directory."
            )
            continue
        for file in files:
            if file.endswith(".ogn"):
                ogn_files.append(Path(root) / file)
            elif file.endswith(".py") or file.endswith(".pyc") or file.endswith(".pyo"):
                python_files.append(Path(root) / file)

    if ogn_files:
        standalone_manager = ExtensionContentsStandalone(ext_id, main_module, ext_path)
        standalone_manager.set_scanned_files(python_files, ogn_files)
        return standalone_manager

    _ = LOG.disabled or LOG.info("-> Extension contents were not recognized as containing OmniGraph Python information")
    return None
