from __future__ import annotations

import sys
import traceback
from collections import defaultdict
from concurrent.futures import ALL_COMPLETED, ThreadPoolExecutor, wait
from contextlib import suppress
from importlib import import_module
from pathlib import Path
from types import ModuleType

import carb
import carb.profiler

from ..autonode_generator.utils import (
    AUTONODE_DEVELOPER_MODE_SETTING,
    OGN_AUTOGENERATED_SUBFOLDER_NAME,
    autonode_developer_mode,
)
from ..node_generator.utils import UNWRITABLE_TAG_FILE
from .extension_contents_base import ExtensionContentsBase
from .file_utils import FileType, get_module_path, get_ogn_type_and_node, load_module_from_file, walk_with_excludes
from .logging_utils import LOG, OmniGraphExtensionError
from .node_type_definition import NodeTypeDefinition


class OgnScanner:
    """Scan the ogn folders for nodes and tests"""

    def __init__(self, extension: ExtensionContentsV118, ogn_directory):
        self.ogn_directory = ogn_directory
        self.extension = extension
        self.other_files_found = defaultdict(list)  # Dictionary of ClassName: list of (file path, file type) to process
        self.has_tests = False

    @carb.profiler.profile
    def process_directory(self, entry: tuple):
        """Collect the file names with the associated class names and file types from the given root path."""
        root, dirs, file_names = entry
        root_path = Path(root)
        if root != self.ogn_directory:
            for ogn_subdir in dirs:
                if ogn_subdir != "tests":
                    _ = LOG.disabled or LOG.info("....Adding scanned directory %s/%s", root, ogn_subdir)
                    self.extension.ogn_subdirectories.append(root_path / ogn_subdir)

        result = []
        for file_name in file_names:
            file_path = root_path / file_name
            (class_name, file_type) = get_ogn_type_and_node(file_path.name)

            if file_type is None:
                continue

            # self.other_files_found[class_name].append((file_path, file_type))
            result.append((class_name, file_path, file_type))
        return result

    @carb.profiler.profile
    def add_files(self, entries, start, end):
        """Add the files that are discovered to each node definition."""
        for i in range(start, end):
            class_name, definition = entries[i]
            definition.add_files(
                self.other_files_found[class_name], self.extension._built_versions  # noqa: protected-access
            )

    @carb.profiler.profile
    def add_file_types(self, entries: list, start, end):
        """Create the NodeTypeDefinitions for each discovered node class."""
        file_type = FileType.OGN
        for i in range(start, end):
            class_name, file_path = entries[i]
            # Register this file name in the first pass to establish file names that represent node types
            if class_name in self.extension.node_type_definitions:
                # This can happen in old builds where the build has created both nodes/ and a linked ogn/nodes/
                # directory. They are identical so they can be ignored. An identical size is a good enough
                # confirmation that this is the case.
                file_size = file_path.stat().st_size
                try:
                    old_size = self.extension.node_type_definitions[class_name].file_path(file_type).stat().st_size
                except TypeError:
                    old_size = 0
                if old_size != file_size:
                    carb.log_warn(
                        f"Multiple .ogn files found for class '{class_name}'\n"
                        f"  Using {self.extension.node_type_definitions[class_name]}, ignoring {file_path}@{file_size}"
                    )
                continue
            _ = LOG.disabled or LOG.info("...constructing node type definition for %s at %s", class_name, file_path)
            self.extension.node_type_definitions[class_name] = NodeTypeDefinition(class_name, file_path)

    def run_processing(self):
        """Walk the extension paths to discover the nodes and tests."""
        file_types = []
        with ThreadPoolExecutor() as executor:
            for results in executor.map(
                self.process_directory, walk_with_excludes(self.ogn_directory, ["__pycache__"])
            ):
                for class_name, file_path, file_type in results:
                    # This information is needed at import time. Track it now to avoid a traversal to find it later.
                    if file_type == FileType.TEST:
                        self.has_tests = True

                    if file_type == FileType.OGN:
                        file_types.append((class_name, file_path))
                        continue

                    if (
                        file_type in (FileType.PYTHON_DB, FileType.CPP_DB)
                        and not self.extension._built_versions.has_version()  # noqa: protected-access
                    ):
                        # All database files should give the same version information since this is part of a build tree
                        # so choosing the first one to be representative is good enough. If that's not true then the fault
                        # is with the build and should not be corrected here.
                        self.extension._built_versions.set_versions_from_database(file_path)  # noqa: protected-access
                        _ = LOG.disabled or LOG.info(
                            "...extracted db versions %s from %s (%s)",
                            self.extension._built_versions,  # noqa: protected-access
                            file_path,
                            self.extension._built_versions.has_version(),  # noqa: protected-access
                        )

                    _ = LOG.disabled or LOG.info("...found file of type %s - %s", file_type, file_path)
                    self.other_files_found[class_name].append((file_path, file_type))

        # Try to add all of the build-related files to the node type definition
        futures = []
        thread_count = 32

        with ThreadPoolExecutor(thread_count) as executor:
            file_type_count = len(file_types)
            for start in range(0, file_type_count, thread_count):
                futures.append(
                    executor.submit(self.add_file_types, file_types, start, min(file_type_count, start + thread_count))
                )
        wait(futures, timeout=None, return_when=ALL_COMPLETED)

        with ThreadPoolExecutor(thread_count) as executor:
            defs = list(self.extension.node_type_definitions.items())
            def_count = len(defs)
            for start in range(0, def_count, thread_count):
                futures.append(executor.submit(self.add_files, defs, start, min(def_count, start + thread_count)))
        wait(futures, timeout=None, return_when=ALL_COMPLETED)


# ==============================================================================================================
class ExtensionContentsV118(ExtensionContentsBase):
    """Variation of the ExtensionContents class that handles the case of node types that were generated in version
    1.18 of omni.graph.tools or earlier, where the module path contains the generated ogn/ directory and has all of
    the nodes defined in its subdirectories.
    Attributes:
        ogn_subdirectories (list[Path]): List of non-generated subdirectories in the generated ogn/ directory
    """

    def __init__(self, ext_id: str, module: ModuleType, ext_path: str | Path):
        super().__init__(ext_id, module, ext_path)
        self.ogn_subdirectories: list[Path] = []
        _ = LOG.disabled or LOG.info("Creating 1.18 extension manager for %s in %s at %s", ext_id, module, ext_path)

    # --------------------------------------------------------------------------------------------------------------
    def __str__(self) -> str:
        return f"V1.18 {super().__str__()}"

    # --------------------------------------------------------------------------------------------------------------
    @carb.profiler.profile
    def __scan_module_directory(self):
        """Scan the high level module directory to find any node type definitions at that level, not including ogn/"""
        _ = LOG.disabled or LOG.info("Scanning root %s for nodes", self.module_directory)
        for root, dirs, _file_names in walk_with_excludes(self.module_directory, ["__pycache__", "ogn"]):
            for subdir in dirs:
                self.__scan_ogn_directory(Path(root) / subdir)

    # --------------------------------------------------------------------------------------------------------------
    @carb.profiler.profile(add_args=True)
    def __scan_ogn_directory(self, ogn_directory: Path):
        """Looks in the ogn/ subdirectory of the module to find all of the .ogn and .py implementation files."""
        _ = LOG.disabled or LOG.info("Scanning %s for nodes in OGN path %s", self._ext_id, ogn_directory)
        if not autonode_developer_mode() and OGN_AUTOGENERATED_SUBFOLDER_NAME in ogn_directory.parts:
            carb.log_warn(
                f"Found AutoNode definitions in {ogn_directory} but the setting '{AUTONODE_DEVELOPER_MODE_SETTING}'"
                f" has not been enabled. Skipping registration of node types in that directory."
            )
            return

        scanner = OgnScanner(self, ogn_directory)
        scanner.run_processing()
        self._has_tests = self._has_tests or scanner.has_tests

    # --------------------------------------------------------------------------------------------------------------
    @carb.profiler.profile
    def scan_for_nodes(self):
        """Looks in the ogn/ subdirectory of the module to find all of the .ogn and .py implementation files."""
        ogn_directory = self.module_directory / "ogn"
        _ = LOG.disabled or LOG.info("Scanning for V1.18 node in %s", ogn_directory)
        if ogn_directory.is_dir():
            # If the marker file indicating that the ogn/ directory came from a build isn't present then it might
            # also not contain the nodes/ subdirectories that the build creates so scan the main directory first.
            prebuilt_marker = ogn_directory / UNWRITABLE_TAG_FILE
            if not prebuilt_marker.is_file():
                self.__scan_module_directory()
            self.__scan_ogn_directory(ogn_directory)
        else:
            _ = LOG.disabled or LOG.info(
                "Could not scan %s for nodes, %s is not a directory", self._ext_id, ogn_directory
            )

        # There may be nodes in the cache already so check there too
        self.scan_cache()

    # --------------------------------------------------------------------------------------------------------------
    # TODO: The description is customized for V1.18 setups, the code is not
    def ensure_required_modules_exist(self) -> tuple[ModuleType | None, ModuleType | None]:
        """Make sure the required OGN modules exist (i.e. the .ogn and .ogn.tests submodules of the extension module).
        For V1.18 extensions the modules will be checked in this order:
            1. If the user added a [[python.modules]] entry for either one they will already be in the module list
            2. Otherwise the 'ogn' module member will have to be created as it is only a directory with no __init__.py
            3. Failing that it will fall back to the cache and use the common method for defining the modules

        Returns:
            A tuple with the populated .ogn and .ogn.tests modules. If nothing was needed in the modules (e.g. no
            node definitions or no tests) then the module will be None. As a side effect the tuples are stored on
            this object for future use.

        Raises:
            OmniGraphExtensionError if anything that prevents proper registration happens
        """
        (ogn_module_name, ogn_test_module_name) = self.ogn_module_names()
        _ = LOG.disabled or LOG.info(
            "Importing %s and %s with%s tests", ogn_module_name, ogn_test_module_name, "" if self._has_tests else "out"
        )

        def __find_module(module_name: str, parent_module: ModuleType, submodule_name: str) -> ModuleType | None:
            """Find a module in this extension's space, or import it from the cache"""
            _ = LOG.disabled or LOG.info(
                "--- Finding module %s in %s with submodule name %s", module_name, parent_module, submodule_name
            )
            module = None

            # Check 1 - has the module already been imported on its own?
            with suppress(KeyError):
                module = sys.modules[module_name]
                _ = LOG.disabled or LOG.info("...module %s was already in the Python namespace", module_name)
                return module

            _ = LOG.disabled or LOG.info("--X module was not already imported")

            # Check 2 - has the module been imported as a member of the main module?
            # submodule_name might be ogn.tests but the parent module is ogn so only the "tests" part is needed here
            last_element = ".".join(submodule_name.split(".")[:-1])
            if hasattr(parent_module, last_element):
                submodule = getattr(parent_module, last_element)
                _ = LOG.disabled or LOG.info("...ogn found as an object in %s (%s)", parent_module, submodule)
                if isinstance(submodule, ModuleType):
                    return submodule
                raise OmniGraphExtensionError(f"ogn object {submodule} should have been a module itself")

            # Check 3 - can the module be imported from a directory in the build tree?
            _ = LOG.disabled or LOG.info("... Trying to import %s directly", module_name)
            with suppress(ModuleNotFoundError):
                module = import_module(module_name)
                _ = LOG.disabled or LOG.info("--> Found the module at %s", module)
                return module

            _ = LOG.disabled or LOG.info("--X Module %s could not be imported, trying the subdirectory", module_name)

            # Check 4 - does the ogn/ directory exist in the main module for importing?
            ogn_directory = self.module_directory
            if ogn_directory.is_dir():
                with suppress(ModuleNotFoundError):
                    module = load_module_from_file(module_name, ogn_directory)
                    return module

            _ = LOG.disabled or LOG.info(
                "--X Subdirectory %s could not be imported, trying cache %s", ogn_directory, self.cache_path
            )

            # If all else fails import the module from the cache tree, which must exist if everything is consistent
            if self.cache_path is None or not self.cache_path.is_dir():
                raise OmniGraphExtensionError(f"Cache path required for import is not a directory - {self.cache_path}")
            # The cache path already includes the ogn/ subdirectory so bump it up one level
            cache_submodule_path = "/".join(submodule_name.split(".")[1:])
            submodule_cache_path = self.cache_path / cache_submodule_path / "__init__.py"
            if not submodule_cache_path.is_file():
                raise OmniGraphExtensionError(
                    f"Submodule cache path required for import is not a file - {submodule_cache_path}"
                )

            try:
                module = load_module_from_file(module_name, submodule_cache_path)
            except ModuleNotFoundError as error:
                raise OmniGraphExtensionError(
                    f"Submodule cache path {submodule_cache_path} could not be imported"
                ) from error

            return module

        # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        # Construct the EXTENSION.ogn import space, either from the build if available, or the cache if not
        if self.ogn_module is None:
            try:
                self.ogn_module = __find_module(ogn_module_name, self._module, "ogn")
            except KeyError as error:
                raise OmniGraphExtensionError(f"Main module {self.module_name} could not be found") from error
        if self.ogn_test_module is None and self._has_tests and self.ogn_module is not None:
            _ = LOG.disabled or LOG.info("-> Found .ogn module, looking for ogn.tests too")
            self.ogn_test_module = __find_module(ogn_test_module_name, self.ogn_module, "ogn.tests")
        return (self.ogn_module, self.ogn_test_module)

    # --------------------------------------------------------------------------------------------------------------
    # TODO: The description is customized for V1.18 setups, the code is not
    def do_python_imports(self):
        """Find or create the .ogn and .ogn.tests modules in the extension and import the required files into them

        If self.ogn_subdirectories is not empty then all of the directories in it will be imported into the .ogn
        namespace, representing node directories that have been linked in the build.

        After the required modules have been established they will be populated from the existing generated files by
        walking the list of node type definitions and importing the one that is most up to date (generated or cached)

        Returns:
            2-tuple of the main ogn/ module that was imported and the ogn/tests/ module
        """
        _ = LOG.disabled or LOG.info("Attempting OGN 1.18 Python imports for %s", self._ext_id)
        if not self.node_type_definitions:
            _ = LOG.disabled or LOG.info("...no node definitions to import")
            return (None, None)

        (ogn_module, ogn_test_module) = self.ensure_required_modules_exist()
        node_classes = {}

        def do_import_node_definition(
            definition: NodeTypeDefinition,
            ogn_module: ModuleType,
            module_name: str,
            module_directory: Path,
            node_classes: dict,
        ):
            """Import a node definition from the ogn module

            Args:
                definition: The node definition currently imported.
                ogn_module: The module currently imported, which contains the node definition.
                module_name: The module name.
                module_directory: The path to the module.
                node_classes: Output dictionary of file name to the node class, used to register the nodes in the imported module.
            """
            carb.profiler.begin(3, f"do_import_node_definition {ogn_module.__name__} - {definition.name}")
            db_file = definition.database_to_use()
            if db_file is not None:
                db_module_name = f"{ogn_module.__name__}.{db_file.stem}"
                try:
                    db_module = load_module_from_file(db_module_name, db_file)
                    setattr(ogn_module, db_file.stem, db_module)
                    _ = LOG.disabled or LOG.info(
                        "...Import DB %s into %s from %s", db_module_name, dir(db_module), db_file
                    )
                    node_file = definition.file_path(FileType.PYTHON)
                except Exception:  # noqa PLW0703
                    carb.log_warn(f"Exception while importing db file {db_file}: {traceback.format_exc()}")

                if node_file is not None:
                    try:
                        relative_location = ".".join(node_file.relative_to(module_directory).with_suffix("").parts)
                        node_module_name = f"{module_name}.{relative_location}"
                        node_module = load_module_from_file(node_module_name, node_file)
                        _ = LOG.disabled or LOG.info(
                            "...Import Node %s into %s from %s", node_module_name, node_module, node_file
                        )
                        node_class = getattr(node_module, definition.name, None)
                        if node_class is None:
                            carb.log_warn(f"Node definition in {node_file} had no implementation of the node class")
                        else:
                            node_classes[db_file.stem] = node_class
                    except Exception:  # noqa PLW0703
                        carb.log_warn(f"Exception while importing file {node_file}: {traceback.format_exc()}")
            else:
                _ = LOG.disabled or LOG.info("No database file for %s - not trying to import the node", definition.name)
            carb.profiler.end(3)

        def do_import_test_definition(definition: NodeTypeDefinition, ogn_test_module: ModuleType):
            """
            Import the test definitions.

            Args:
                definition: The test definition currently imported.
                ogn_test_module: The test module containing the definition.
            """
            carb.profiler.begin(3, f"do_import_test_definition {ogn_test_module.__name__} - {definition.name}")
            test_file = definition.test_to_use()
            if test_file is not None:
                test_module_name = f"{ogn_test_module.__name__}.{test_file.stem}"
                try:
                    test_module = load_module_from_file(test_module_name, test_file)
                    setattr(ogn_test_module, test_file.stem, test_module.TestOgn)
                    _ = LOG.disabled or LOG.info(
                        "...Imported test %s into %s from %s", test_module_name, test_module, test_file
                    )
                except Exception:  # noqa PLW0703
                    carb.log_error(f"Exception while importing test {test_module_name}: {traceback.format_exc()}")
            carb.profiler.end(3)

        def do_import_extra(ogn_module: ModuleType, module_path: Path, ogn_subdirectories: list[Path]):
            """
            Add any symlinked or copied non-generated files into the module, for backward compatibility.

            Args:
                ogn_module: The module currently imported.
                module_path: The path to the module.
                ogn_subdirectories: List of non-generated subdirectories in the generated ogn/ directory.
            """

            carb.profiler.begin(3, f"do_import_extra {ogn_module.__name__}")
            ogn_module_path = get_module_path(ogn_module)
            if module_path in ogn_module_path.parents:
                for subdirectory in ogn_subdirectories:
                    submodule_name = subdirectory.stem
                    # The generated tests directory, database files, and Python caches can be ignored
                    if submodule_name in ["tests", "__pycache__"]:
                        continue
                    # if submodule_name.endswith("Database"):
                    #     continue

                    import_module_name = f"{ogn_module.__name__}.{submodule_name}"
                    # top_level_module = load_module_from_file(import_module_name, potential_import)
                    # if top_level_module is not None:
                    #     setattr(ogn_module, submodule_name, top_level_module)
                    try:
                        _ = LOG.disabled or LOG.info(
                            "...Importing extra subdirectory of ogn/ as %s", import_module_name
                        )
                        submodule = import_module(submodule_name, ogn_module.__name__)
                        _ = LOG.disabled or LOG.info("...Imported as %s containing %s", submodule, dir(submodule))
                    except Exception:  # noqa PLW0703
                        carb.log_error(
                            f"Exception while importing module {import_module_name}: {traceback.format_exc()}"
                        )
            carb.profiler.end(3)

        def do_import_node_definitions_serial(
            node_type_definitions: dict[str, NodeTypeDefinition],
            ogn_module: ModuleType,
            module_name: str,
            module_directory: Path,
            node_classes: dict,
        ):
            """
            Import the node defnitions by iterating over them one after another.
            This function is executed on a separate thread.

            Args:
                node_type_definitions: the node definitions to import
                ogn_module: the module containing the imported definitions
                module_name: the name of the module
                module_directory: the path to the module
                node_classes: Output parameter, contains the list of node classes that are imported.
            """
            carb.profiler.begin(3, f"do_import_node_definitions_serial {ogn_module.__name__}")
            for definition in node_type_definitions.values():
                if ogn_module is not None:
                    do_import_node_definition(definition, ogn_module, module_name, module_directory, node_classes)
            carb.profiler.end(3)

        match self.import_mode:
            case self.ImportThreadingType.SingleThreaded:
                # Import the nodes and the tests modules on the main thread.
                # This is the most conservative option.
                carb.profiler.begin(2, f"do_python_imports submit tasks {self.module_name}")
                # Walk all of the known node types and insert their XDatabase.py and TestX.py files into the module,
                # if they exist. (Either may be legally excluded from generation.)
                for definition in self.node_type_definitions.values():
                    if ogn_module is not None:
                        do_import_node_definition(
                            definition, ogn_module, self.module_name, self.module_directory, node_classes
                        )

                    if ogn_test_module is not None:
                        do_import_test_definition(definition, ogn_test_module)

                # The special node implementation
                if ogn_module is not None:
                    setattr(ogn_module, self.NODE_STORAGE_OBJECT, node_classes)

                    do_import_extra(ogn_module, self.module_path, self.ogn_subdirectories)

                carb.profiler.end(2)

            case self.ImportThreadingType.ParallelThread:
                # Walk all of the known node types and insert their XDatabase.py and TestX.py files into the module,
                # if they exist. (Either may be legally excluded from generation.)
                carb.profiler.begin(2, f"do_python_imports submit tasks {self.module_name}")
                futures: list = []
                with ThreadPoolExecutor() as executor:
                    for definition in self.node_type_definitions.values():
                        if ogn_module is not None:
                            future = executor.submit(
                                do_import_node_definition,
                                definition,
                                ogn_module,
                                self.module_name,
                                self.module_directory,
                                node_classes,
                            )
                            futures.append(future)

                        if ogn_test_module is not None:
                            future = executor.submit(do_import_test_definition, definition, ogn_test_module)
                            futures.append(future)

                    # The special node implementation
                    if ogn_module is not None:
                        # Add any symlinked or copied non-generated files into the module, for backward compatibility.
                        future = executor.submit(do_import_extra, ogn_module, self.module_path, self.ogn_subdirectories)
                        futures.append(future)

                wait(futures, timeout=None, return_when=ALL_COMPLETED)

                if ogn_module is not None:
                    setattr(ogn_module, self.NODE_STORAGE_OBJECT, node_classes)

                carb.profiler.end(2)

            case self.ImportThreadingType.SerialThread:
                carb.profiler.begin(2, f"do_import_node_definitions_serial submit tasks {self.module_name}")
                futures: list = []
                with ThreadPoolExecutor() as executor:
                    # Submit a single task for importing the nodes.
                    # This avoids potential data dependency problems where one node imports another node with a relative path.
                    future = executor.submit(
                        do_import_node_definitions_serial,
                        self.node_type_definitions,
                        ogn_module,
                        self.module_name,
                        self.module_directory,
                        node_classes,
                    )
                    futures.append(future)

                    # Walk all of the known node types and insert their XDatabase.py and TestX.py files into the module,
                    # if they exist. (Either may be legally excluded from generation.)
                    for definition in self.node_type_definitions.values():
                        if ogn_test_module is not None:
                            future = executor.submit(do_import_test_definition, definition, ogn_test_module)
                            futures.append(future)

                    # The special node implementation
                    if ogn_module is not None:
                        # Add any symlinked or copied non-generated files into the module, for backward compatibility.
                        future = executor.submit(do_import_extra, ogn_module, self.module_path, self.ogn_subdirectories)
                        futures.append(future)

                wait(futures, timeout=None, return_when=ALL_COMPLETED)

                if ogn_module is not None:
                    setattr(ogn_module, self.NODE_STORAGE_OBJECT, node_classes)

                carb.profiler.end(2)

        return (ogn_module, ogn_test_module)
