"""General utilities for internal file generation support.

This is part of the _internal module. Objects with a leading underscore are not intended to be used outside
of this module. All others may only be used for internal OmniGraph purposes.
"""

from __future__ import annotations

import os
import sys
from collections import defaultdict
from enum import Enum, auto
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from types import ModuleType

from ..node_generator.generate_cpp import generate_cpp
from ..node_generator.generate_documentation import generate_documentation
from ..node_generator.generate_icon import generate_icon
from ..node_generator.generate_python import generate_python
from ..node_generator.generate_tests import generate_tests
from ..node_generator.generate_usd import generate_usd
from .logging_utils import LOG


# ==============================================================================================================
class FileType(Enum):
    """Enum enumerating the different files accessed by the node generator.
    User Files:
    - CPP -> C++ file, OgnMyNode.cpp, lives in same directory as the .ogn file
    - CU -> Cuda file, OgnMyNode.cu, lives in same directory as the .ogn file
    - OGN -> .ogn node definition file, usually in the source tree and symlinked to in the build tree
    - PYTHON -> python file, OgnMyNode.py, lives in same directory as the .ogn file

    Generated Files:
    - CPP_DB -> cpp header database, OgnMyNodeDatabase.h, lives in the include/ subdir of the ogn generated files dir
    - DOCS -> documentation, lives in docs/ subdir of the ogn generated files dir
    - PYTHON_DB -> python database, OgnMyNodeDatabase.py, lives in the ogn generated files dir
    - TEST -> test script, TestOgnMyNode.py, lives in the tests/ subdir of the ogn generated files dir
    - USD -> USD template, OgnMyNodeTemplate.usda, lives in the tests/usd/ subdir of the ogn generated files dir
    """

    CPP = auto()
    CPP_DB = auto()
    CU = auto()
    DOCS = auto()
    ICON = auto()
    OGN = auto()
    PYTHON = auto()
    PYTHON_DB = auto()
    TEST = auto()
    USD = auto()

    @classmethod
    def all_in_pattern_order(cls) -> list[FileType]:
        """Returns the list of file type enums in order of how their file name patterns should be matched.
        The ordering is important because some patterns match more than one prefix/suffix combination so the
        most restrictive need to go first."""
        return [cls.TEST, cls.USD, cls.OGN, cls.DOCS, cls.CU, cls.CPP_DB, cls.CPP, cls.ICON, cls.PYTHON_DB, cls.PYTHON]


# ==============================================================================================================
def is_user_file_type(file_type: FileType) -> bool:
    """Return True iff the given file type is to a file written by the user, not generated"""
    return file_type in [FileType.OGN, FileType.CPP, FileType.CU, FileType.PYTHON]


# ==============================================================================================================
def is_generated_file_type(file_type: FileType) -> bool:
    """Return True iff the given file type is to a file generated by the code"""
    return file_type in [FileType.DOCS, FileType.ICON, FileType.USD, FileType.TEST, FileType.CPP_DB, FileType.PYTHON_DB]


# ==============================================================================================================
# strings used by the node generator to specify a file type (ie. those in FileType) to generate
GENERATED_FILE_CONFIG_NAMES = {
    FileType.CPP_DB: "c++",
    FileType.DOCS: "docs",
    FileType.ICON: "icon",
    FileType.PYTHON_DB: "python",
    FileType.TEST: "tests",
    FileType.USD: "usd",
}


# ==============================================================================================================
# relative subdirectory paths inside the ogn generated files dir to locate/generate generated files into/from
GENERATED_FILE_LOCATIONS = {
    FileType.CPP_DB: "include",
    FileType.DOCS: "docs",
    FileType.ICON: "icons",
    FileType.PYTHON_DB: ".",
    FileType.TEST: "tests",
    FileType.USD: "tests/usd",
}


# ==============================================================================================================
# Functions that are used to generate the various types of files
GENERATORS = {
    FileType.CPP_DB: generate_cpp,
    FileType.DOCS: generate_documentation,
    FileType.ICON: generate_icon,
    FileType.PYTHON_DB: generate_python,
    FileType.TEST: generate_tests,
    FileType.USD: generate_usd,
}


# ==============================================================================================================
# File suffixes for the various types of generated files
_FILE_SUFFIXES = defaultdict(
    lambda: "",
    {
        FileType.CPP_DB: "Database.h",
        FileType.CPP: ".cpp",
        FileType.CU: ".cu",
        FileType.DOCS: ".rst",
        FileType.ICON: ".svg",
        FileType.OGN: ".ogn",
        FileType.PYTHON_DB: "Database.py",
        FileType.PYTHON: ".py",
        FileType.TEST: ".py",
        FileType.USD: "Template.usda",
    },
)


# ==============================================================================================================
# File prefixes for the various types of generated files
_FILE_PREFIXES = defaultdict(lambda: "", {FileType.TEST: "Test"})


# ==============================================================================================================
def get_ogn_file_name(node_type_name: str, ogn_file_type: FileType) -> str:
    """Get the full file name expected for the given file type on the given node type
    Args:
        node_type_name: Name of the node for which the filename is to be retrieved
        ogn_file_type: Type of file for which the filename is to be retrieved
    Returns:
        Name of the given file type on the given node type
    """
    return _FILE_PREFIXES[ogn_file_type] + node_type_name + _FILE_SUFFIXES[ogn_file_type]


# ==============================================================================================================
def get_ogn_type_and_node(filename: str) -> tuple(str, FileType):
    """Figure out what type of ogn-related file is passed in and what the name of the source node type is
    Args:
        filename: Name of the file to parse
    Returns:
        (Root node type name of the file, Type of File filename was) - Nones if the pattern was not recognized
    """
    for ogn_file_type in FileType.all_in_pattern_order():
        prefix = _FILE_PREFIXES.get(ogn_file_type, "")
        suffix = _FILE_SUFFIXES.get(ogn_file_type, "")
        if filename.startswith(prefix) and filename.endswith(suffix):
            node_type_name = filename[len(prefix) : (-len(suffix)) if suffix else None]
            return node_type_name, ogn_file_type
    return None, None


# ==============================================================================================================
def walk_with_excludes(start: Path, exclude: set(str)) -> tuple(str, list[str], list[str]):
    """Same usage as os.walk:
    Crawl the directory tree from the start, yields a 3 tuple for itself and each subdirectory,
    except don't follow symlinks to paths already searched, and don't search directories excluded by name

    Args:
        start: Path to some directory to crawl, presumably the extension root.
        exclude: Set of directory names to exclude from the walk

    Returns:
        dirpath, dirnames, filenames
    """
    _ = LOG.disabled or LOG.info("_walk_with_excludes(start=%s, exclude=%s)", start, exclude)

    followed_targets = set()  # to exclude redundant symlinks

    def __dir_is_excluded_or_redundant(start, subdir_name):
        if subdir_name in exclude:
            return True
        subdir_path = Path(start) / subdir_name
        target = str(subdir_path.resolve())
        if target in followed_targets:
            return True
        followed_targets.add(target)
        return False

    for root, subdirs, filenames in os.walk(start, topdown=True, followlinks=True):
        subdirs[:] = [d for d in subdirs if not __dir_is_excluded_or_redundant(root, d)]
        _ = LOG.disabled or LOG.info("   ... walked %s, %s, %s", Path(root).as_posix(), subdirs, filenames)
        yield (Path(root).as_posix(), subdirs, filenames)


# ==============================================================================================================
def find_ogn_build_directory(current_path: Path) -> Path | None:
    """Walk up from the current_path and find the _build/ogn/ directory in the build tree above it.
    Returns None if the directory could not be found
    """
    # _build is the root in a local build, dev is the root in an installed build
    if current_path.name in ["_build", "dev"]:
        test_path = current_path / "ogn"
        if test_path.is_dir():
            return test_path
    parent_path = current_path.parent
    if parent_path != current_path:
        return find_ogn_build_directory(parent_path)
    return None


# ==============================================================================================================
def load_module_from_file(new_module_name: str, python_file_path: Path) -> ModuleType:
    """Loads a Python module directly from a file, installs it into the module space, and returns the new module"""
    _ = LOG.disabled or LOG.info("Importing module %s from %s", new_module_name, python_file_path)
    if python_file_path.is_dir():
        # There's no guarantee the directory is a module or a package in its own right so the safest thing to do
        # is to find some arbitrary file and import it to populate the namespace
        for path_object in python_file_path.rglob("*.py"):
            if path_object.is_file():
                relative_location = ".".join(path_object.relative_to(python_file_path).with_suffix("").parts)
                return load_module_from_file(f"{new_module_name}.{relative_location}", path_object)
        _ = LOG.disabled or LOG.info("--> No Python files in the directory. No module returned.")
        return None

    # Not sure if things like .pyc will work but no reason to outright exclude them
    if not python_file_path.suffix.startswith(".py"):
        _ = LOG.disabled or LOG.info("--> Not a Python file. No module returned.")
        return None

    module = None
    spec = spec_from_file_location(new_module_name, str(python_file_path))
    if spec is None:
        _ = LOG.disabled or LOG.error("--> Could not create spec. Asserting an error.")
        raise ImportError(f"Could not load spec for module '{new_module_name}' at: {python_file_path}")
    module = module_from_spec(spec)
    sys.modules[new_module_name] = module
    try:
        spec.loader.exec_module(module)
    except FileNotFoundError as error:
        raise ImportError(f"{error.strerror}: {python_file_path}") from error
    _ = LOG.disabled or LOG.info("... created the module as %s", module)
    return module


# ==============================================================================================================
def get_module_path(module_to_check: ModuleType) -> Path | None:
    """Returns the path from which the module was generated, either file or directory, None if it could not be found"""
    path_to_module = None
    try:
        file_attribute = module_to_check.__file__
        path_to_module = Path(file_attribute)
    except (AttributeError, TypeError):
        try:
            if isinstance(module_to_check.__path__, list):
                file_attribute = module_to_check.__path__[0]  # pylint: disable=protected-access
            else:
                file_attribute = module_to_check.__path__._path[0]  # pylint: disable=protected-access
            path_to_module = Path(file_attribute)
        except (AttributeError, IndexError, TypeError):
            return None
    return path_to_module
