[package]
title = "Scene Visualization System"
category = "Rendering"
version = "105.1.0"

icon = "data/icon.png"
preview_image = "data/icon.png"
changelog = "docs/CHANGELOG.md"
readme = "docs/index.rst"
description="Debug line/point/etc drawing interface."
authors = ["NVIDIA"]

repository = ""

keywords = ["debugdraw"]

[dependencies]
"omni.scene.visualization.core" = {}
"omni.scene.visualization.ui" = {}

[[test]]
waiver = "Bundle extension without any code"

[package.writeTarget]
kit = true
