[package]
title = "Physics PhysX Backend"
description="Physics PhysX Backend."
repository = ""
keywords = ["physics", "physx"]
category = "physics"

version = "107.3.26"
authors = ["NVIDIA"]

icon = "data/icon.png"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/README.md"
support_level = "Core"

[package.writeTarget]
kit = true
python = true
usd = true

[dependencies]
"omni.physics" = { version = "107.3.26", exact = true }
"omni.physx" = { version = "107.3.26", exact = true }

[[native.plugin]]
path = "bin/*.plugin"

[[python.module]]
name = "omni.physics.physx"


[[test]]
stdoutFailPatterns.exclude = [
    "*Failed to create Cuda Context Manager*",
    "*nable to create PxCudaContextManager*",
]

