[package]
title = "Search Delegate Widget"
version = "1.0.7"
category = "Internal"
description = "Base module that provides a search widget for searching the file system"
authors = ["NVIDIA"]
slackids = ["UQY4RMR3N"]
repository = ""
keywords = ["kit", "ui"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
support_level = "Sample"

[dependencies]
"omni.ui" = {}
"omni.client" = {}
"omni.kit.widget.filebrowser" = {}
"omni.kit.search_core" = {}

[[python.module]]
name = "omni.kit.widget.search_delegate"

[[test]]
dependencies = [
    "omni.kit.ui_test",
]

args = [
   "--/app/window/dpiScaleOverride=1.0",
   "--/app/window/scaleToMonitor=false",
]

[documentation]
pages = ["docs/Overview.md", "docs/CHANGELOG.md", "docs/SETTINGS.md", "docs/USAGE_PYTHON.md"]
