
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.rtx.settings.core-71dd2bc618e50411.zip"

    [package.publish]
        kitVersion = "107.3.0+feature.196706.da1eb258.gl"
        date = 1757755129
        buildNumber = "107.3.0+1073.196706.da1eb258.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
