[package]
# Semantic Versioning is used: https://semver.org/
version = "2.0.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarily for displaying extension info in UI
title = "Semantics Schema Editor"
description = "A simple UI for adding a semantics schema label to selected objects in the scene."

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ["kit", "semantics", "schema", "editor"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

display_name = "Semantic Schema Editor"

category = "Synthetic Data"

# Location of the license files for this extension
ext_licenses = ["docs/license.txt <NVIDIA>"]

[dependencies]
"omni.usd" = {}
"omni.kit.menu.utils" = {}
"omni.usd.schema.semantics" = {}

# Main python module this extension provides, it will be publicly available as "import omni.semantics.schema.editor".
[[python.module]]
name = "semantics.schema.editor"

[[test]]
timeout = 3600
args = [
    "--no-window",
]
dependencies = [
    "omni.kit.test"
]
stdoutFailPatterns.exclude = [
]
