
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/semantics.schema.editor-2.0.2.zip"

    [package.publish]
        kitVersion = "107.3.0+master.186802.ff68c0b8.gl"
        date = 1755549887
        buildNumber = "2.0.2+master.380.c9950160.gl"
        repoName = "semantics_schema_tools"
        signed = 1
