[package]
title = "Omniverse micro service Consumer"
version = "1.2.4"
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"
icon = "data/icon.png"
preview_image = "data/preview.png"
description = "Base class for Omniverse micro service Consumers"
category = "services"
authors = ["NVIDIA"]
repository = ""
slackids = ["@U010NFP76BU"]
keywords = ["kit", "service", "client", "base"]

# Main python module this extension provides
[[python.module]]
name = "omni.services.transport.client.base"
