
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.capture.viewport-d57af40a6bd66395.zip"

    [package.publish]
        kitVersion = "107.3.2+production.219829.c5b447f3.gl"
        date = 1757755119
        buildNumber = "107.3.2+1073.219829.c5b447f3.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
