[package]
# Semantic Versioning is used: https://semver.org/
version = "1.0.16"

category = "Internal"
support_level = "Core"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Audio Property Widget"
description="View and Edit Audio Property Values"

# URL of the extension source repository.
repository = ""

# Preview image. Folder named "data" automatically goes in git lfs (see .gitattributes file).
preview_image = "data/preview.png"

# Keywords for the extension
keywords = ["kit", "usd", "property", "audio", "sound"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

[dependencies]
"omni.usd" = {}
"omni.ui" = {}
"omni.kit.window.property" = {}
"omni.kit.property.usd" = {}

[[python.module]]
name = "omni.kit.property.audio"

[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/multiGpu/autoEnable=false", # Disable mGPU with PXR due to OM-51026, OM-53611
    "--/renderer/multiGpu/maxGpuCount=1",
    "--/app/asyncRendering=false",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/persistent/app/omniverse/filepicker/options_menu/show_details=false",
]

dependencies = [
    "omni.hydra.pxr",
    "omni.kit.mainwindow",
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers",
    "omni.kit.property.layer"
]

stdoutFailPatterns.exclude = [
    "*carb::memory::PooledAllocator*",
]

pyCoverageFilter = ["omni.kit.property.audio"]  # Restrict coverage to this extension

[documentation]
pages = ["docs/Overview.md", "docs/CHANGELOG.md"]
