"""
This file is automatically generated by idl.py package and should not be edited manually.
"""

from typing import List, Optional, Dict, AsyncIterator
from idl.types import Enum, Record, Literal

{% include "types.pyi" %}

{% for interface in spec.interfaces.values() %}
{%- for function in interface.functions %}
{%- set definition = function|py.request_record(interface) %}
{% include "struct.pyi" %}
{%- endfor %}
{%- endfor %}
