"""
This file is automatically generated by idl.py package and should not be edited manually.
"""

from abc import ABC, abstractmethod
from idl.service import ServiceStub
from .__data__ import *


class I{{ interface.name }}(ServiceStub, ABC):
{%- for function in interface.functions %}
    @abstractmethod
{% include "service_func_def.pyi" %}
        ...
{% endfor %}
    __interface_name__ = "{{ interface.name }}"
    __interface_methods__ = [
        {%- for function in interface.functions %}
        ["{{ function.name }}", {{ function.name|underscore }}, {{ function.name|py.request_record_name(interface.name) }}, {{ function.returns.type|py.type_name }}, {{ function.returns.is_many }}],
        {%- endfor %}
    ]
    __interface_fields__ = [
        {%- for field in interface.fields %}
        ["{{ field.name }}", {{ field.type|py.type_name }}],
        {%- endfor %}
    ]
    __interface_origin__ = "{{ spec.origin }}"
    {%- set capabilities = interface.name|capabilities.find(side="server") -%}
    {% if capabilities %}
    __interface_capabilities__ = {{ capabilities.name }}
    {%- endif %}

