from __future__ import annotations
import usdrt.UsdSkel._UsdSkel
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd
import usdrt.UsdGeom._UsdGeom

__all__ = [
    "Animation",
    "BindingAPI",
    "BlendShape",
    "PackedJointAnimation",
    "Root",
    "Skeleton",
    "Tokens"
]


class Animation(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateBlendShapeWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateBlendShapesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateJointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRotationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateScalesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTranslationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Animation: ...
    def GetBlendShapeWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetBlendShapesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetJointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRotationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetScalesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTranslationsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class BindingAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> BindingAPI: ...
    def CreateAnimationSourceRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateBlendShapeTargetsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateBlendShapesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateGeomBindTransformAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateJointIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateJointWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateJointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSkeletonRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateSkinningBlendWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSkinningMethodAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetAnimationSourceRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetBlendShapeTargetsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetBlendShapesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetGeomBindTransformAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetJointIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetJointWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetJointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetSkeletonRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetSkinningBlendWeightsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetSkinningMethodAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class BlendShape(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateNormalOffsetsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateOffsetsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePointIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> BlendShape: ...
    def GetNormalOffsetsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetOffsetsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPointIndicesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class PackedJointAnimation(Animation, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> PackedJointAnimation: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Root(usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Root: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Skeleton(usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateBindTransformsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateJointNamesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateJointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRestTransformsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Skeleton: ...
    def GetBindTransformsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetJointNamesAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetJointsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRestTransformsAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    bindTransforms = 'bindTransforms'
    blendShapeWeights = 'blendShapeWeights'
    blendShapes = 'blendShapes'
    classicLinear = 'ClassicLinear'
    dualQuaternion = 'DualQuaternion'
    jointNames = 'jointNames'
    joints = 'joints'
    normalOffsets = 'normalOffsets'
    offsets = 'offsets'
    pointIndices = 'pointIndices'
    primvarsSkelGeomBindTransform = 'primvars:skel:geomBindTransform'
    primvarsSkelJointIndices = 'primvars:skel:jointIndices'
    primvarsSkelJointWeights = 'primvars:skel:jointWeights'
    primvarsSkelSkinningBlendWeights = 'primvars:skel:skinningBlendWeights'
    restTransforms = 'restTransforms'
    rotations = 'rotations'
    scales = 'scales'
    skelAnimationSource = 'skel:animationSource'
    skelBlendShapeTargets = 'skel:blendShapeTargets'
    skelBlendShapes = 'skel:blendShapes'
    skelJoints = 'skel:joints'
    skelSkeleton = 'skel:skeleton'
    skelSkinningMethod = 'skel:skinningMethod'
    translations = 'translations'
    weight = 'weight'
    weightedBlend = 'WeightedBlend'
    pass
