
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.scene.visualization.ui-107.0.1%2B107.0.3.zip"

    [package.target]

        [package.target.kit]
            0 = "107.0.3"

    [package.publish]
        kitVersion = "107.0.3+107_abi1.171913.67e3d383.gl"
        date = 1739964968
        buildNumber = "107.0.0+107.6880.f7d0aca0.gl"
        repoName = "particle-system"
        signed = 1
