[package]
title = "Scene Visualization System UI"
category = "Rendering"
version = "107.0.1"

icon = "data/icon.png"
preview_image = "data/icon.png"
changelog = "docs/CHANGELOG.md"
readme = "docs/index.rst"
description="Debug line/point/etc drawing interface."
authors = ["NVIDIA"]

# URL of the extension source repository.
repository = ""

# Main module for the Python interface
[[python.module]]
name = "omni.scene.visualization.ui"

# Keywords for the extension
keywords = ["debugdraw"]

# Extensions required to load before this one
[dependencies]
"omni.kit.actions.core" = {}
"omni.kit.window.preferences" = {}
"omni.scene.visualization.core" = {}
"omni.kit.property.geometry" = {}

# Avoid test failure due to error message in ImageProvider when renderer
# interface cannot be acquired
[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--no-window"
]

dependencies = [
    "omni.hydra.pxr",
    "omni.kit.mainwindow",
    "omni.kit.menu.create",
    "omni.kit.primitive.mesh", # for Create/Mesh/Sphere
    "omni.kit.ui_test",
    "omni.kit.viewport.menubar.core",
    "omni.kit.viewport.menubar.display",
    "omni.kit.viewport.menubar.render",
    "omni.kit.viewport.window",
    "omni.kit.window.stage",
    "omni.kit.viewport.utility",
    "omni.kit.test_helpers_gfx",
]

pyCoverageOmit = ["*/tests/*"]

[package.writeTarget]
kit = true
