[package]
title = "Asset Importer"
description = "Omniverse Asset Importer: It supports FBX, OBJ, GLTF, MD5, BVH and etc."

version = "4.3.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

changelog = "docs/CHANGELOG.md"
readme  = "docs/Overview.md"
category = "Utility"
repository = ""

# Locks extension to the Kit version to make the extension work with that version or higher
writeTarget.kit = true

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

support_level = "Core"

[dependencies]
"omni.usd" = {}
"omni.client" = {}
"omni.ui" = {}
"omni.kit.asset_converter" = {}
"omni.kit.window.content_browser" = {}
"omni.kit.menu.utils" = {}
"omni.kit.notification_manager" = {}
"omni.kit.widget.farm" = {optional=true}
"omni.kit.widget.prompt" = {}
"omni.kit.window.file" = {}
"omni.kit.actions.core" = {}
"omni.kit.usd.layers" = {}
"omni.kit.usdz_export" = {}

[settings]
exts."omni.kit.tool.asset_importer".appSettings = "/persistent/app/asset_importer"

[[python.module]]
name = "omni.kit.tool.asset_importer"

# Extension test settings
[[test]]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/multiGpu/autoEnable=false", # Disable mGPU with PXR due to OM-51026, OM-53611
    "--/renderer/multiGpu/maxGpuCount=1",
    "--/omni.kit.plugin/syncUsdLoads=true",
    "--/app/asyncRendering=false",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/persistent/app/omniverse/filepicker/options_menu/show_details=false",
    "--no-window"
]

dependencies = [
    "omni.kit.mainwindow",
    "omni.kit.ui_test"
]
stdoutFailPatterns.include = []
stdoutFailPatterns.exclude = [
    "*Cannot copy from*"
]

# only perform pyCoverage for asset_importer
pyCoverageFilter = ["omni.kit.tool.asset_importer"]
pyCoverageOmit = ["omni/kit/tool/asset_importer/tests/*"]

[documentation]
pages = [
    "docs/CHANGELOG.md",
    "docs/Overview.md",
    "docs/Usage.md",
]
