[package]
title = "USD Collection Window (Preview)"
description = "USD Collection Window"
version = "0.3.1"
category = "Internal"
authors = ["NVIDIA"]
keywords = ["usd", "collections"]
changelog = "docs/CHANGELOG.md"
repository = ""
preview_image = "data/preview.png"
icon = "data/icon.png"
readme = "docs/README.md"
target.kit = ["106.5.0"]

[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.widget.collection" = {version="~0.3"}
"omni.kit.widget.stage_icons" = {}
"omni.kit.editor" = { optional=true }
"omni.kit.renderer.core" = {}
"usdrt.scenegraph" = {}

[[python.module]]
name = "omni.kit.window.collection"


[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window",
]

dependencies = [
    "omni.kit.mainwindow",
    "omni.kit.ui_test",
    "omni.kit.material.library",
    "omni.kit.window.stage",
    "omni.kit.test_suite.helpers"
]

#TODO: This is being caused by menu creation callbacks being set, don't seem to be
#able to get access to them to unregister before teardown. Investigate
stdoutFailPatterns.exclude = [
    "*extension object is still alive*"
]

pythonTests.unreliable = [
]
