[package]
title = "USD Collection Widget (Preview)"
description = "USD Collection Widget"
version = "0.3.1"
category = "Internal"
authors = ["NVIDIA"]
keywords = ["collection", "outliner", "usd"]
changelog = "docs/CHANGELOG.md"
repository = ""
preview_image = "data/preview.png"
icon = "data/icon.png"
readme = "docs/README.md"
target.kit = ["106.5.0"]

[dependencies]
"omni.kit.context_menu" = {}
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.core.collection" = {}
"omni.kit.widget.stage" = {}
"omni.kit.widget.stage_icons" = {}
"omni.kit.property.usd" = {}  # PrimSelectionPayload only
"omni.kit.async_engine" = {}
"usdrt.scenegraph" = {}

[[python.module]]
name = "omni.kit.widget.collection"

[[test]]
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window",
]

dependencies = [
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers",
    "omni.kit.window.collection",
    "omni.kit.window.stage",
    "omni.kit.mainwindow",
]

[[test]]
name = "usdrt"
args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/useFabricSceneDelegate=1",
    "--no-window",
]

dependencies = [
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers",
    "omni.kit.window.collection",
    "omni.kit.window.stage",
    "omni.kit.mainwindow",
    "omni.hydra.usdrt_delegate",
]
