
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.graph.editor.core-1.5.3.zip"

    [package.publish]
        kitVersion = "106.0+master.140498.2b2de844.tc"
        date = 1711054200
        buildNumber = "106.0+master.2329.bdcd3fd6.tc"
        repoName = "kit-graphs"
        signed = 1
