[core]
reloadable = false
# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
order = -100

[package]
category = "Internal"
title = "USD RTX Lens Distortion Schemas"
description="USD Schemas for RTX lens distortion models"
keywords = ["usd", "schema", "rtx", "sensor"]

[dependencies]
"omni.usd.libs" = {}
# Required for proper startup during test-suite run, so make it optional.
"omni.usd.core" = { optional = true }

[[python.module]]
name = "omni.usd.schema.omni_lens_distortion"

[[test]]
dependencies = [
    "omni.usd",
]