
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.livestream.messaging-1.1.1.zip"

    [package.publish]
        kitVersion = "106.0+release.150156.165c5942.tc"
        date = 1713452723
        buildNumber = "105.2+106.0.698.15c8e9f3.gl"
        repoName = "kit-livestream"
        signed = 1
