import os
import carb
from copy import deepcopy
from openai import OpenAI, APITimeoutError, APIError, APIConnectionError, RateLimitError

if os.getenv("OPENAI_API_KEY") is None:
    os.environ["OPENAI_API_KEY"] = "placeholder"

MODUEL_DIR = os.path.dirname(__file__)
MODEL_NAME = "meta/llama3-8b-instruct"


class GenSceneCap:
    """
    Generates scene caption based on the scene graph. Right now it supports 4 formats of captions:
    - global caption: a general description of the scene
    - brief caption: a shorter version of the global caption
    - question and answer: a set of questions and answers regarding the scene
    - custom caption: caption generated by custom prompts

    attributes:
        scene_graph (dict): A simplified scene graph dictionary converted from the exported scene graph
        client (OpenAI): OpenAI client object

    """

    def __init__(self, scene_graph_dict, url="https://integrate.api.nvidia.com/v1", name=MODEL_NAME, key="placeholder"):
        """
        scene_graph_dict (dict): A scene graph dictionary exported from SceneGraph object
        """
        if not os.getenv("NIM_API_KEY"):
            NIM_API_KEY = "placeholder"
        else:
            NIM_API_KEY = os.getenv("NIM_API_KEY")
            key = NIM_API_KEY

        self.client = None
        self.url = url
        self.name = name
        self.key = key

        if key == "placeholder":
            carb.log_warn("NIM_API_KEY is not set. Scene level caption is not able to be generated.")

        if key != "placeholder":
            self.client = OpenAI(base_url=url, api_key=key, timeout=30.0)  # llama3.1 with 30 second timeout
        else:
            self.client = None

        self.scene_graph = self.__convert_scene_graph(scene_graph_dict)

    async def prompt_global_caption(self):
        """
        Generates a global caption for the scene, based on the scene graph.

        Returns:
            str: The generated caption if successful, None if an error occurs

        Note:
            Errors are logged using carb.log_error but not raised
        """
        if self.client is None:
            raise Exception("NIM_API_KEY is not set")
        system_message = open(f"{MODUEL_DIR}/sft_prompts/system_message_caption.txt", "r").read()

        user_message = str(self.scene_graph)

        try:
            completion = self.client.chat.completions.create(
                model=self.name,  # hard-coded model # TODO: support other models
                messages=[
                    {"role": "system", "content": system_message},
                    {"role": "user", "content": user_message},
                ],
                temperature=0.2,
                top_p=0.7,
                max_tokens=1024,
                stream=False,
                timeout=30.0,  # 30 second timeout for the completion request
            )
            response = completion.choices[0].message.content
            return response
        except APITimeoutError:
            carb.log_error("Request timed out after 30 seconds while generating global caption")
        except APIConnectionError as e:
            carb.log_error(f"Failed to connect to the API: {str(e)}")
        except RateLimitError as e:
            carb.log_error(f"Rate limit exceeded: {str(e)}")
        except APIError as e:
            carb.log_error(f"API error occurred: {str(e)}")
        except Exception as e:
            carb.log_error(f"Unexpected error while generating global caption: {str(e)}")

        return None

    async def prompt_sft_qa(self):
        """
        Generates a set of questions and answers for the scene, based on the scene graph.

        Returns:
            str: The generated Q&A if successful, None if an error occurs

        Note:
            Errors are logged using carb.log_error but not raised
        """
        if self.client is None:
            raise Exception("NIM_API_KEY is not set")
        system_prompt = open(f"{MODUEL_DIR}/sft_prompts/system_message_qa.txt", "r").read()
        user_message = str(self.scene_graph)

        try:
            completion = self.client.chat.completions.create(
                model=self.name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message},
                ],
                temperature=0.2,
                top_p=0.7,
                max_tokens=1024,
                stream=False,
                timeout=30.0,
            )
            response = completion.choices[0].message.content
            return response
        except APITimeoutError:
            carb.log_error("Request timed out after 30 seconds while generating Q&A")
        except APIConnectionError as e:
            carb.log_error(f"Failed to connect to the API: {str(e)}")
        except RateLimitError as e:
            carb.log_error(f"Rate limit exceeded: {str(e)}")
        except APIError as e:
            carb.log_error(f"API error occurred: {str(e)}")
        except Exception as e:
            carb.log_error(f"Unexpected error while generating Q&A: {str(e)}")

        return None

    async def prompt_brief_caption(self):
        """
        Generates a brief caption for the scene, based on the scene graph.

        Returns:
            str: The generated brief caption if successful, None if an error occurs

        Note:
            Errors are logged using carb.log_error but not raised
        """
        if self.client is None:
            raise Exception("NIM_API_KEY is not set")
        system_prompt = open(f"{MODUEL_DIR}/sft_prompts/system_brief_caption.txt", "r").read()
        user_message = str(self.scene_graph)

        try:
            completion = self.client.chat.completions.create(
                model=self.name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message},
                ],
                temperature=0.2,
                top_p=0.7,
                max_tokens=1024,
                stream=False,
                timeout=30.0,
            )
            response = completion.choices[0].message.content
            return response
        except APITimeoutError:
            carb.log_error("Request timed out after 30 seconds while generating brief caption. Please try a different model.")
        except APIConnectionError as e:
            carb.log_error(f"Failed to connect to the API: {str(e)}")
        except RateLimitError as e:
            carb.log_error(f"Rate limit exceeded: {str(e)}")
        except APIError as e:
            carb.log_error(f"API error occurred: {str(e)}")
        except Exception as e:
            carb.log_error(f"Unexpected error while generating brief caption: {str(e)}")

        return None

    async def prompt_custom_caption(self, prompt_txt_path):
        """
        Generates a custom caption for the scene by custom prompts, based on the scene graph.

        Args:
            prompt_txt_path (str): Path to the custom prompt text file

        Returns:
            str: The generated custom caption if successful, None if an error occurs

        Note:
            Errors are logged using carb.log_error but not raised
        """
        if self.client is None:
            raise Exception("NIM_API_KEY is not set")
        system_prompt = open(prompt_txt_path, "r").read()
        user_message = str(self.scene_graph)

        try:
            completion = self.client.chat.completions.create(
                model=self.name,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message},
                ],
                temperature=0.2,
                top_p=0.7,
                max_tokens=1024,
                stream=False,
                timeout=30.0,
            )
            response = completion.choices[0].message.content
            return response
        except APITimeoutError:
            carb.log_error("Request timed out after 30 seconds while generating custom caption")
        except APIConnectionError as e:
            carb.log_error(f"Failed to connect to the API: {str(e)}")
        except RateLimitError as e:
            carb.log_error(f"Rate limit exceeded: {str(e)}")
        except APIError as e:
            carb.log_error(f"API error occurred: {str(e)}")
        except Exception as e:
            carb.log_error(f"Unexpected error while generating custom caption: {str(e)}")

        return None

    def __convert_scene_graph(self, scene_graph_dict):
        scene_graph_dict_copy = deepcopy(scene_graph_dict)
        objects = scene_graph_dict_copy["obj"]
        for obj in objects.values():
            # remove spatial data
            obj.pop("2d_bbox")
            obj.pop("3d_bbox")
            obj.pop("3d_centroid")
            try:
                obj.pop("world_3d_bbox")
            except KeyError:
                # skip if key not exist
                pass
            obj["class"] = obj["class"].replace("_", " ")
            obj_idx = str(obj["id"])
            obj["relations"] = []
        edges = scene_graph_dict_copy["edges"]["obj-obj"]
        for edge in edges:
            target_id = edge["target"]
            source_id = edge["source"]
            target_num_id = str(objects[target_id]["id"])
            target_class = objects[target_id]["class"]
            summarized_relation = edge["relation"]
            if "," in edge["relation"]:
                relations = summarized_relation.split(",")
                if relations[-1] in ["far", "near"]:
                    summarized_relation = f"to the {relations[-1]} {', '.join(relations[:-1])} of"
                else:
                    summarized_relation = f"to the {', '.join(relations)} of"
            objects[source_id]["relations"].append(f"{summarized_relation} {target_num_id}-{target_class}")
        new_scene_graph = {}
        for obj in objects.values():
            obj_idx = str(obj["id"])
            new_scene_graph[f"{obj_idx}-{obj['class']}"] = obj

        return new_scene_graph
