"""
Mini-Compiler for AutoNode files.
Contains functions to handle AST definitions.

Exports:
    AutoNodeGenerator: Class that handles all of the AutoNode generation within a single Python module
"""

import ast
import logging
from contextlib import suppress
from pathlib import Path
from typing import Iterable, TypedDict

from ..node_generator.ThreadsafeOpen import ThreadsafeOpen
from .function import NodeTypeFromFunctionScan
from .utils import (
    AUTONODE_TOKENS_ALL,
    NO_ANNOTATION,
    OGN_AUTOGENERATED_SUBFOLDER_NAME,
    PRIVATE_MEMBER_PREFIX,
    as_class_name,
    python_name_to_ui_name,
)

_logger = logging.getLogger("AutoNode")


# ==============================================================================================================
class _SubscriptDict(TypedDict):
    """Return type when unpacking an ast.Subscript object"""

    value: any
    """Subscripted object name"""
    contents: any
    """Subscript constant or slice values"""


# ==============================================================================================================
class _CallDict(TypedDict):
    """Return type when unpacking an ast.Call object"""

    name: str
    """Name of the function"""
    call_args: list
    """List of unpacked positional arguments"""
    call_kws: dict
    """Dictionary of unpacked keyword arguments"""


# ==============================================================================================================
# Unpackers
def _unpack_type_annotation(
    annotation: ast.Name | ast.Constant | ast.Subscript | ast.Tuple | ast.BinOp | ast.Attribute,
) -> str | dict:  # pragma: no cover    Unsupported code
    """Unpack a type annotation on a value from its AST description

    This is what is returned from the various legal types of annotation:

        ast.Name -> A string representing the annotation type type (e.g. a:str -> "str")
        ast.Constant -> A string with the constant value in it (e.g. a:str -> "4")
        ast.Subscript -> A subscripted element (e.g. a[4] -> {"value": "a", "contents": "4"})
        ast.Tuple -> A dictionary with "value":"tuple" and "content":(the annotated types taken from the tuple elements)
        ast.BinOp -> Must be "|" representing a union of multiple types. Returns a list of each of the annotated types
                     e.g. a:int|str -> ["int", "str"]
        ast.Attribute -> A string representing the composed type (e.g. a: x.y.z -> "x.y.z")

    Args:
        annotation: Annotation from the AST to be unpacked

    Returns:
        str: Name of the annotation if it has one (e.g. f() -> MyClass returns "MyClass")
        dict: Dictionary of the more complex annotation information
    """
    _logger.info("Unpacking type annotation %s", annotation)
    if isinstance(annotation, ast.Name):
        return annotation.id

    if isinstance(annotation, ast.Constant):
        return annotation.value

    if isinstance(annotation, ast.Attribute):
        return _unpack_type_annotation(annotation.value) + f".{annotation.attr}"

    if isinstance(annotation, ast.Subscript):
        return _unpack_subscript_type(annotation)

    if isinstance(annotation, ast.Tuple):
        return tuple(_unpack_type_annotation(element) for element in annotation.elts)

    if isinstance(annotation, ast.BinOp):
        left_op = _unpack_type_annotation(annotation.left)
        left_op = left_op if isinstance(left_op, list) else [left_op]
        right_op = _unpack_type_annotation(annotation.right)
        right_op = right_op if isinstance(right_op, list) else [right_op]
        return left_op + right_op

    return annotation


# --------------------------------------------------------------------------------------------------------------
def _unpack_subscript_type(subscript: ast.Subscript) -> _SubscriptDict:  # pragma: no cover    Unsupported code
    """Unpack a subscripted element from its type description

    Used for unpacking attribute tuple types, such as "float[3]".

    Args:
        subscript: Subscript element from the AST to unpack

    Returns:
        dict: Dictionary with a value in it indicating the item being subscripted (e.g. "float") and an optional
            subscript slice contents, which will always be a constant (e.g. "3")
    """
    _logger.info("Unpacking subscript %s", subscript)
    value = _unpack_type_annotation(subscript.value)
    if subscript.slice:
        slice_obj = _unpack_type_annotation(subscript.slice)
    else:
        slice_obj = None
    return {"value": value, "contents": slice_obj}


# --------------------------------------------------------------------------------------------------------------
def _unpack_args(arglist: ast.arguments) -> dict:  # pragma: no cover    Unsupported code
    """Unpack a list of arguments from the AST into a dictionary of contents

    Args:
        arglist: Argument list from the AST to unpack

    Returns:
        dict: Dictionary whose keys are the argument names and whose values are the unpacked annotations of the
            argument types. e.g. the return from the arg list (a:float, b:str) would be {"a": "float", "b": "str"}
    """
    _logger.info("Unpacking argument list %s", arglist)
    _logger.debug("AST --> %s", ast.dump(arglist, indent=2))
    if arglist.vararg:
        raise ValueError(f"Specifying **args not supported in argument list {arglist.vararg}")
    if arglist.kwarg:
        raise ValueError(f"Specifying **kwargs not supported in argument list {arglist.kwarg}")
    out = {}
    for arg in arglist.posonlyargs + arglist.args + arglist.kwonlyargs:
        annotation = NO_ANNOTATION
        if arg.annotation:
            annotation = _unpack_type_annotation(arg.annotation)
        out[arg.arg] = annotation
    _logger.debug("Unpacked Args --> %s", out)
    return out


# --------------------------------------------------------------------------------------------------------------
def _unpack_expression(arg: ast.Expression):  # pragma: no cover    Unsupported code
    """Unpack a single argument that is an expression (element without an assigment)

    Args:
        arg: Expression from the AST

    Returns:
        any: Constant value of the expression (e.g. "5", "x")

    Raises:
        ValueError: If the expression was not a constant (e.g. "a or b")
    """
    _logger.info("Unpacking expression %s", arg)
    if isinstance(arg, ast.Constant):
        return arg.value

    with suppress(AttributeError):
        if isinstance(arg.body, ast.Constant):
            return arg.body.value

    err = "Only constant values are supported"
    _logger.error(err)
    raise ValueError(err)


# --------------------------------------------------------------------------------------------------------------
def _unpack_call(call: ast.Call) -> _CallDict:  # pragma: no cover    Unsupported code
    """Unpack a function call from the AST

    Args:
        call: Function call from the AST

    Returns:
        dict: Dictionary with a fixed set of keys containing the unpacked function call information. For the
            function call `mean(1, who="grinch")` the dictionary will be populated as follows:
            **name**: *Name of the function* = "mean"
            **call_args**: *List of unpacked positional arguments* = [1]
            **call_kws**: *Dictionary of unpacked keyword arguments* = {"who": "grinch"}
    """
    _logger.info("Unpacking call %s", call)
    _logger.debug("AST --> %s", ast.dump(call, indent=2))
    func = call.func
    if isinstance(func, ast.Attribute):
        name = func.attr
    elif isinstance(func, ast.Name):
        name = func.id
    else:
        raise NotImplementedError(f"Call function {func} must be an ast.Attribute or ast.Name")

    result = {
        "name": name,
        "call_args": [_unpack_type_annotation(arg) for arg in call.args],
        "call_kws": {kw.arg: _unpack_expression(kw.value) for kw in call.keywords},
    }
    _logger.debug("Unpacked Call --> %s", result)
    return result


# --------------------------------------------------------------------------------------------------------------
def _unpack_decorators(decorators: Iterable) -> list[any]:  # pragma: no cover    Unsupported code
    """Unpacks a list of decorators from the AST

    Args:
        decorators: Iterable list of decorators from the AST

    Returns:
        list[any]: List of unpacked elements from the decorators, as dictionaries and restricted to a few types
            Name: A simple named decorator, e.g. "@property"
            Call: A named decorator with arguments, e.g. "@deprecated('Do not use this')"
            Subscript: A named decorator with subscripts, e.g. "@grab_x_y_z[2]"
    """
    _logger.info("Unpacking decorators %s", decorators)
    _logger.debug("AST --> %s", "\n".join([ast.dump(decorator, indent=2) for decorator in decorators]))
    out = []
    for a_decorator in decorators:
        # Simple named decorator
        if isinstance(a_decorator, (ast.Name, ast.Attribute)):
            out.append({"name": _unpack_type_annotation(a_decorator)})

        # This is a decorator that has a function call in it
        elif isinstance(a_decorator, ast.Call):
            call = _unpack_call(a_decorator)
            out.append({"name": call["name"], "arguments": call["call_args"], "keywords": call["call_kws"]})

        # Decorator with subscripts in it
        elif isinstance(a_decorator, ast.Subscript):
            subscript = _unpack_subscript_type(a_decorator)
            out.append(subscript)

    _logger.debug("Unpacked Decorators --> %s", out)
    return out


# --------------------------------------------------------------------------------------------------------------
def _unpack_classdef_functions(class_def: ast.ClassDef) -> Iterable:  # pragma: no cover    Unsupported code
    """Unpack the functions from a class definition from the AST

    Args:
        class_def: Class definition from the AST

    Returns:
        Iterable: A list of dictionaries containing the unpacked definitions for all functions in the class. The
            dictionaries will each contain three elements:
            **name**: *The name of the function*
            **arguments**: *The unpacked list of the arguments to the function (see _unpack_args())*
            **return_annotation**: *The unpacked definition of the return value type (see _unpack_annotation())*
    """
    _logger.info("Unpacking functons from class %s", class_def)
    _logger.debug("AST --> %s", ast.dump(class_def, indent=2))

    functions = (function for function in class_def.body if isinstance(function, ast.FunctionDef))
    ret = []
    for function in functions:
        if function.name.startswith(PRIVATE_MEMBER_PREFIX):
            continue
        arglist = _unpack_args(function.args)
        out_sig = _unpack_type_annotation(function.returns)
        out = {"arguments": arglist, "name": function.name, "return_annotation": out_sig}

        ret.append(out)

    _logger.debug("Unpacked Class Functions --> %s", ret)
    return ret


# --------------------------------------------------------------------------------------------------------------
def _unpack_classdef_members(class_def: ast.ClassDef) -> Iterable:  # pragma: no cover    Unsupported code
    """Unpack the class-level members of a class definition from the AST

    Args:
        class_def: Class definition from the AST

    Returns:
        Iterable: List of dictionaries with the unpacked description of all class member variables that are not
            explicitly marked as internal via the dunder ("__") prefix. The dictionary members will be:
            **name**: *Name of the class variable*
            **annotation**: *Unpacked annotation of that variable (see _unpack_annotation())*
    """
    _logger.info("Unpacking members from class %s", class_def)
    _logger.debug("AST --> %s", ast.dump(class_def, indent=2))

    variables = (variable for variable in class_def.body if isinstance(variable, ast.AnnAssign))
    ret = []
    for variable in variables:
        if not isinstance(variable.target, ast.Name):
            raise NotImplementedError(type(variable.target))
        if variable.target.id.startswith(PRIVATE_MEMBER_PREFIX):
            continue
        annotation = _unpack_type_annotation(variable.annotation)
        value = _unpack_type_annotation(variable.value)
        out = {"name": variable.target.id, "annotation": annotation, "value": value}
        ret.append(out)

    _logger.debug("Unpacked Class Members --> %s", ret)
    return ret


# ==============================================================================================================
def _scan_for_decorated_objects(source: str, file_path: str) -> tuple[Iterable, Iterable]:  # pragma: no cover
    """
    Scans a python file and extracts all objects with decorators.

    Args:
        source: Contents of the file to be scanned
        file_path: Corresponding path to file source (important for AST).

    Returns:
        tuple[Iterable, Iterable]: Tuple consisting of the list of decorated free function descriptors and the list of
            class descriptors. The free function descriptors are fixed key dictionaries consisting of:
                **name**: *The name of the function*
                **decorators**: *The unpacked list of decorators on the function*
                **return_annotation**: *The unpacked return type of the function*
                **parameters**: *The unpacked list of arguments to the function, both positional and keyword*
                **docstring**: *The docstring of the function**
            The class descriptions are also fixed key dictionaries consisting of:
                **name**: *The name of the function*
                **decorators**: *The unpacked list of decorators on the function*
                **functions**: *The unpacked list of functions in the class*
                **members**: *The unpacked list of class variables*
                **docstring**: *The docstring of the class as a whole**
    """
    _logger.info("Scanning for decorated objects %d lines from %s", source.count("\n") + 1, file_path)

    tree = ast.parse(source, filename=file_path)
    functions = (func for func in ast.walk(tree) if isinstance(func, (ast.FunctionDef, ast.AsyncFunctionDef)))
    parsed_funcs = []

    for function in functions:
        if not function.decorator_list:
            continue
        decorators = _unpack_decorators(function.decorator_list)
        arglist = _unpack_args(function.args)
        out_sig = _unpack_type_annotation(function.returns)
        out = {
            "name": function.name,
            "decorators": decorators,
            "return_annotation": out_sig,
            "parameters": arglist,
            "docstring": ast.get_docstring(function),
        }
        parsed_funcs.append(out)

    classes = (class_def for class_def in ast.walk(tree) if isinstance(class_def, ast.ClassDef))
    parsed_classes = []

    for class_def in classes:
        if not class_def.decorator_list:
            continue
        decorators = _unpack_decorators(class_def.decorator_list)
        functions = _unpack_classdef_functions(class_def)
        members = _unpack_classdef_members(class_def)
        out = {
            "name": class_def.name,
            "decorators": decorators,
            "functions": functions,
            "members": members,
            "docstring": ast.get_docstring(class_def),
        }
        parsed_classes.append(out)

    _logger.debug("Scanned functions --> %s", parsed_funcs)
    _logger.debug("Scanned classes --> %s", parsed_classes)
    return parsed_funcs, parsed_classes


# ==============================================================================================================
class _CodeDestination:  # pragma: no cover    Unsupported code
    """Helper class that handles the different paths required for output to file versus output via strings"""

    def __init__(self, _file_path: str | None, _out_folder: str | None):
        """Set up the code path information
        Args:
            _file_path: Location containing the AutoNode definition, or "<string>" if it came directly from a string
            _out_folder: Directory to write the generated code, or None if the code is to be returned as strings
        """
        if _file_path is None:
            # Generating code from a bare string (only for testing)
            self._file_path = "<string>"
            self._out_folder = _out_folder
        else:
            self._file_path = Path(_file_path)
            self._out_folder = self._file_path.parent if _out_folder is None else _out_folder
        if self._out_folder is not None:
            self._out_folder = Path(self._out_folder) / OGN_AUTOGENERATED_SUBFOLDER_NAME
        self._results = []
        _logger.info("Code destination of %s set to %s", self._file_path, self._out_folder)

    @property
    def file_path(self) -> str:
        """Returns:
        The location of the file that contained the AutoNode definition, or "<string>" if it generated from a string
        """
        return self._file_path

    @property
    def results(self) -> Iterable[tuple[str, str, str]]:
        """Get the code generation results
        Returns:
            List of generated code information. The first element of the tuple will always be the name of the class
            implementing the node type. If there was no output folder specified the next two elements will contain
            the generated .ogn and .py code as strings for the node type implementation, otherwise they will contain
            the paths to the .ogn and .py files containing that generated code.
        """
        return self._results

    def _add_code_as_string(self, class_file_name: str, ogn_code: str, python_code: str):
        """Add the generated code to the dictionary of string results"""
        _logger.info("Adding code string definition for %s", class_file_name)
        self._results.append((class_file_name, ogn_code, python_code))

    def _add_code_as_files(self, class_file_name: str, ogn_code: str, python_code: str):
        """Add the generated code to the folders and append the new file names to the results"""
        ogn_filepath = (self._out_folder / class_file_name).with_suffix(".ogn")
        py_filepath = (self._out_folder / class_file_name).with_suffix(".py")
        _logger.info("Adding .ogn/.py as %s", ogn_filepath)

        try:
            # Create the generated ogn folder for all modules in this subfolder
            if not self._out_folder.is_dir():
                self._out_folder.mkdir(mode=777, parents=True, exist_ok=False)
            with ThreadsafeOpen(ogn_filepath, "w") as f:
                f.write(ogn_code)
            _logger.info("Generated ogn: %s", ogn_filepath)
            with ThreadsafeOpen(py_filepath, "w") as f:
                f.write(python_code)
            _logger.info("Generated implementation: %s", py_filepath)

            self._results.append((class_file_name, ogn_filepath, py_filepath))

        except OSError as error:
            _logger.error("Operation failed when trying to write files: %s, %s: %s", ogn_filepath, py_filepath, error)
            raise error

    def add_code(self, class_file_name: str, ogn_code: str, python_code: str):
        """Add the generated code to the results, writing to the folder if provided"""
        if self._out_folder is None:
            self._add_code_as_string(class_file_name, ogn_code, python_code)
        else:
            self._add_code_as_files(class_file_name, ogn_code, python_code)


# ==============================================================================================================
def _generate_autonode_calls(
    source: str, file_path: str | None, module_name: str, module_relative: str, out_folder: str = None
) -> Iterable[tuple[str, str, str]]:  # pragma: no cover    Unsupported code
    """
    Generates .ogn and .py implementation files from a source file.

    Args:
        source: Source code to scan
        file_path: File path corresponding with the location of source. None means it is a plain string.
        module_name: Name of the python module being parsed
        module_relative: Relative path from the python module's root to this file.
        out_folder: Folder to which all .py and .ogn files get written. By default it's a subfolder of the module root.
           None means that the generated code should be returned rather than written out to the folder.

    Returns:
        Iterable[tuple[str, str,str]]: A list of class name,.ogn,.py for each generated node type implementation. If
        the out_folder was None then the .ogn/.py values will be the generated code as strings, otherwise they will be
        the paths to the generated files containing that code.
    """
    _logger.info(
        "Generating AutoNode calls from %d lines, file=%s, module=%s, relative=%s, out=%s",
        source.count("\n") + 1,
        file_path,
        module_name,
        module_relative,
        out_folder,
    )
    destination = _CodeDestination(file_path, out_folder)
    funcs, _ = _scan_for_decorated_objects(source, file_path=destination.file_path)

    for func in funcs:
        # Find the AutoNode decorators
        autonode_decorator = None
        for decorator in func["decorators"]:
            if decorator["name"].split(".")[-1] in AUTONODE_TOKENS_ALL:
                autonode_decorator = decorator
                break

        if not autonode_decorator:
            _logger.info("No AutoNode decorators found on %s, skipping it", func["name"])
            continue

        _logger.info("Found AutoNode annotation %s on %s", autonode_decorator["name"], func["name"])
        _name = func["name"]
        keywords = autonode_decorator.get("keywords", {})
        _add_execution_pins = keywords.get("add_execution_pins", False)

        full_module_name = module_relative if module_relative else module_name
        _unique_name = f"{full_module_name}.{func['name']}"

        _ui_name = keywords.get("ui_name", f"{python_name_to_ui_name(_name)} (AutoNode)") or _unique_name
        # Sanitize
        _file_name = as_class_name(_name)

        _tags = []
        wrapper = NodeTypeFromFunctionScan(
            func_descriptor=None,
            func_name=_name,
            func_signature=func,
            func_docstring=func.get("docstring", ""),
            add_execution_pins=_add_execution_pins,
            ui_name=_ui_name,
            unique_name=_unique_name,
            module_name=full_module_name,
            tags=_tags,
        )

        destination.add_code(_file_name, wrapper.get_ogn(), wrapper.get_node_impl_source())

    return destination.results


# ==============================================================================================================
class AutoNodeGenerator:  # pragma: no cover    Unsupported code
    """
    Entry point to parsing all AutoNode Python files in a single module.

    Parameters:
        module_name: The module name as described in an omniverse `extension.toml` file under `python.module`.
        python_root: The corresponding root folder where the python path begins for the module name
        import_paths: List of paths to the files being imported
        node_folder: The folder where the ogn nodes should be saved to. Defaults to `python_root` if not provided.
    """

    def __init__(self, module_name: str, python_root: str, import_paths: list[Path], node_folder: str | None):
        """Initialize the generator class for AutoNode definitions
        Args:
            module_name: The module name as described in an omniverse `extension.toml` file under `python.module`.
            python_root: The corresponding root folder where the python path begins for the module name
            import_paths: List of paths to the files being imported
            node_folder: The folder where the ogn nodes should be saved to. Defaults to `python_root` if not provided.
        """
        self.module_name = module_name
        self.python_root = Path(python_root)
        self.import_paths = import_paths
        self.node_folder = Path(node_folder or python_root)
        _logger.info(
            "AutoNode generation on module %s from files %s into node folder %s", module_name, import_paths, node_folder
        )

    # --------------------------------------------------------------------------------------------------------------
    def parse_all(self) -> Iterable[tuple[str, str, str]]:
        """Run the parser on every AutoNode definition in this module

        Returns:
            Iterable[tuple[str, str,str]]: A list of class name,.ogn,.py for each generated node type implementation.
            If the out_folder was None then the .ogn/.py values will be the generated code as strings, otherwise they
            will be the paths to the generated files containing that code.
        """
        # Scan once before parsing. This will prevent ambiguity on filesystem changes.
        # os.walk is used instead of Path.iterdir because it is faster.
        files_to_parse = []
        for import_path in self.import_paths:
            relative_import = import_path.relative_to(self.python_root)

            # Don't parse generated files
            if OGN_AUTOGENERATED_SUBFOLDER_NAME in relative_import.parts:
                _logger.debug("Skipping autogenerated subfolder %s", relative_import)
                continue

            if ".." in relative_import.parts:
                _logger.error(
                    "Module path '%s' is not relative to the given Python root directory '%s' - skipping.",
                    import_path,
                    self.python_root,
                )
                continue

            if relative_import.suffix == ".py":
                module_relative = f"{'.'.join(relative_import.parts[:-1])}.{relative_import.stem}"
                _logger.debug("...Adding (%s, %s)", relative_import, module_relative)
                files_to_parse.append((import_path, module_relative))

        # parse files from list
        generated_files = []

        # TODO: Potentially data parallel
        for file_path, module_relative in files_to_parse:
            _logger.info("Generating AutoNode Calls for %s as %s", file_path, module_relative)

            try:
                with ThreadsafeOpen(file_path, "r") as sourcefile:
                    source = sourcefile.read()
            except OSError as error:
                _logger.error("Unable to parse file at %s: %s", file_path, error)
                raise error

            extracted_call_files = _generate_autonode_calls(
                source,
                file_path=file_path,
                module_name=self.module_name,
                module_relative=module_relative,
                out_folder=self.node_folder,
            )
            generated_files += extracted_call_files

        return generated_files
