"""Assorted support utilities for AutoNode"""

from contextlib import contextmanager
from typing import NewType

AUTONODE_DEVELOPER_MODE_SETTING = "/omnigraph/autonode/developer"
"""Setting that enables the AutoNode feature. Remove when the feature is released."""

PRIVATE_MEMBER_PREFIX = "_"
"""Prefix that denotes an object is private"""
NO_ANNOTATION = NewType("NoAnnotation", int)
"""Special type indicating an annotation value is not present"""
SELF_TYPE = NewType("SelfType", int)
"""Special type corresponding to the self value inside a class function"""
OGN_AUTOGENERATED_SUBFOLDER_NAME = "__autonode"
"""Name of the subfolder in which generated .ogn files will be put"""
AUTONODE_TOKEN_FUNC = "node_type"
"""The token for the decorator that marks an AutoNode definition that is a class"""
AUTONODE_TOKENS_ALL = {AUTONODE_TOKEN_FUNC}
"""The list of all legal AutoNode decorator names"""


# ==============================================================================================================
def autonode_developer_mode() -> bool:
    """Returns True if the developer mode of the AutoNode feature has been enabled. This can only be correctly done at
    runtime so protect the import that extracts the setting and default to True at build time. The definitions will
    build but they will not be allowed to register.
    """
    try:
        import carb

        return bool(carb.settings.get_settings().get(AUTONODE_DEVELOPER_MODE_SETTING))
    except ModuleNotFoundError:  # pragma: no cover   Firewall
        return True


# ==============================================================================================================
def as_class_name(object_name: str) -> str:
    """Create a unique and legal class name from an object name

    Args:
        object_name: snake_case or module.namespace name to be converted, e.g. omni.my.module

    Returns:
        str: Class name derived from the module, e.g. OmniMyModule
    """
    strings = object_name.replace(".", "_").split("_")
    return "".join(element.capitalize() if element.islower() else element for element in strings)


# ==============================================================================================================
def python_name_to_ui_name(name: str) -> str:
    """Extract a readable name from a python function name.

    Modifies the "snake_case_name" to "Snake Case Name" with capitalized words and space separators.
    Leaves alone another already capitalized so "big_USD_function" becomes "Big USD Function"

    Args:
        name: Python name to convert

    Returns:
        str: Readable version of name
    """
    strings = name.split("_")
    case_corrected = [s.capitalize() if s.islower() else s for s in strings]
    return " ".join(case_corrected)


# ==============================================================================================================
def is_private(name: str) -> bool:
    """Returns True if a name should be considered private (i.e. starts with an underscore)"""
    return len(name) > 1 and name.startswith("_")


# ==============================================================================================================
def is_class_private(name: str) -> bool:
    """Returns true if a name is a class private member, i.e. starts but does not end with a dunder ("__")
    Used to warn if a name will get mangled.  Based on
    https://github.com/python/cpython/blob/bd46174a5a09a54e5ae1077909f923f56a7cf710/Python/compile.c#L236-L258
    """
    return name.startswith("__") and not name.endswith("__")


# ==============================================================================================================
def is_dunder(name: str) -> bool:
    """Returns True if a name is an internal python name, i.e. starts and ends with a dunder ("__")

    Based on
    https://github.com/python/cpython/blob/148f32913573c29250dfb3f0d079eb8847633621/Objects/typeobject.c#L3299-L3306
    """
    return len(name) > 4 and name.isascii() and name.startswith("__") and name.endswith("__")


# ==============================================================================================================
class GeneratedCode:
    """Tiny code generation utility. Manages progressive indentation levels and code blocks."""

    strbuf = ""
    indent_level = 0

    # --------------------------------------------------------------------------------------------------------------
    def line(self, txt: str):
        self.strbuf += self.indent_level * " " + txt + "\n"

    # --------------------------------------------------------------------------------------------------------------
    def block(self, txt: str):
        lines = txt.split("\n")
        for line in lines:
            self.line(line)

    # --------------------------------------------------------------------------------------------------------------
    @contextmanager
    def indent(self, txt):
        try:
            self.line(txt)
            self.indent_level += 4
            yield None
        finally:
            self.indent_level -= 4

    # --------------------------------------------------------------------------------------------------------------
    def __repr__(self) -> str:
        return self.strbuf
