from __future__ import annotations
import usdrt.UsdUI._UsdUI
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd

__all__ = [
    "Backdrop",
    "NodeGraphNodeAPI",
    "SceneGraphPrimAPI",
    "Tokens"
]


class Backdrop(usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateDescriptionAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Backdrop: ...
    def GetDescriptionAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class NodeGraphNodeAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> NodeGraphNodeAPI: ...
    def CreateDisplayColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExpansionStateAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateIconAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateStackingOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisplayColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExpansionStateAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetIconAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPosAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetSizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetStackingOrderAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class SceneGraphPrimAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> SceneGraphPrimAPI: ...
    def CreateDisplayGroupAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDisplayNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisplayGroupAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDisplayNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    closed = 'closed'
    minimized = 'minimized'
    open = 'open'
    uiDescription = 'ui:description'
    uiDisplayGroup = 'ui:displayGroup'
    uiDisplayName = 'ui:displayName'
    uiNodegraphNodeDisplayColor = 'ui:nodegraph:node:displayColor'
    uiNodegraphNodeExpansionState = 'ui:nodegraph:node:expansionState'
    uiNodegraphNodeIcon = 'ui:nodegraph:node:icon'
    uiNodegraphNodePos = 'ui:nodegraph:node:pos'
    uiNodegraphNodeSize = 'ui:nodegraph:node:size'
    uiNodegraphNodeStackingOrder = 'ui:nodegraph:node:stackingOrder'
    pass
