
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.services.transport.server.base-1.1.1.zip"

    [package.publish]
        buildNumber = "104.0.0+master.2804.f7cf66c4.tc"
        date = 1677628394
        kitVersion = "105.0+master.103480.0029c5ae.tc"
