[core]
reloadable = false
# Load at the start, load all schemas with order -100 (with order -1000 the USD libs are loaded)
order = -100

[package]
version = "107.3.0"
category = "Animation"
title = "USD Character Behavior schema (EXPERIMENTAL)"
description="USD Behavior schema"
authors = ["NVIDIA"]
keywords = ["usd", "schema", "animation", "character", "behavior", "motion", "human", "people"]

[dependencies]
"omni.usd.libs" = {}

[[python.module]]
name = "pxr"

[[python.module]]
name = "BehaviorSchema"

[[python.module]]
name = "omni.anim.behavior.schema"

[[native.library]]
"filter:platform"."linux-x86_64"."path" = "lib/${lib_prefix}behaviorSchema${lib_ext}"
"filter:platform"."linux-aarch64"."path" = "lib/${lib_prefix}behaviorSchema${lib_ext}"
"filter:platform"."windows-x86_64"."path" = "bin/${lib_prefix}behaviorSchema${lib_ext}"

[package.writeTarget]
kit = true
usd = true

[[test]]
waiver = "USD Schema, tested externally"
