from __future__ import annotations
import usdrt.UsdLux._UsdLux
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd
import usdrt.UsdGeom._UsdGeom

__all__ = [
    "BoundableLightBase",
    "CylinderLight",
    "DiskLight",
    "DistantLight",
    "DomeLight",
    "GeometryLight",
    "LightAPI",
    "LightFilter",
    "LightListAPI",
    "ListAPI",
    "MeshLightAPI",
    "NonboundableLightBase",
    "PluginLight",
    "PluginLightFilter",
    "PortalLight",
    "RectLight",
    "ShadowAPI",
    "ShapingAPI",
    "SphereLight",
    "Tokens",
    "VolumeLightAPI"
]


class CylinderLight(BoundableLightBase, usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateLengthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTreatAsLineAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> CylinderLight: ...
    def GetLengthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTreatAsLineAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class DiskLight(BoundableLightBase, usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> DiskLight: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class BoundableLightBase(usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class DistantLight(NonboundableLightBase, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAngleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateIntensityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> DistantLight: ...
    def GetAngleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetIntensityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class DomeLight(NonboundableLightBase, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateGuideRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePortalsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateTextureFileAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTextureFormatAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> DomeLight: ...
    def GetGuideRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPortalsRel(self) -> usdrt.Usd._Usd.Relationship: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTextureFileAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetTextureFormatAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class GeometryLight(NonboundableLightBase, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateGeometryRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> GeometryLight: ...
    def GetGeometryRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class LightAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> LightAPI: ...
    def CreateCollectionLightLinkIncludeRootAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateCollectionShadowLinkIncludeRootAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateColorTemperatureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateDiffuseAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateEnableColorTemperatureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateExposureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFiltersRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def CreateIntensityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateMaterialSyncModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateNormalizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateSpecularAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCollectionLightLinkIncludeRootAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetCollectionShadowLinkIncludeRootAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetColorTemperatureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetDiffuseAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetEnableColorTemperatureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetExposureAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFiltersRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetIntensityAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetMaterialSyncModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetNormalizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetSpecularAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class LightFilter(usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateCollectionFilterLinkIncludeRootAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> LightFilter: ...
    def GetCollectionFilterLinkIncludeRootAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class LightListAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> LightListAPI: ...
    def CreateLightListCacheBehaviorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightListRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetLightListCacheBehaviorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightListRel(self) -> usdrt.Usd._Usd.Relationship: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class ListAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> ListAPI: ...
    def CreateLightListCacheBehaviorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightListRel(self) -> usdrt.Usd._Usd.Relationship: ...
    def GetLightListCacheBehaviorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightListRel(self) -> usdrt.Usd._Usd.Relationship: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class MeshLightAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> MeshLightAPI: ...
    def CreateLightMaterialSyncModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightMaterialSyncModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class NonboundableLightBase(usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class PluginLight(usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> PluginLight: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class PluginLightFilter(LightFilter, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> PluginLightFilter: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class PortalLight(BoundableLightBase, usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> PortalLight: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class RectLight(BoundableLightBase, usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTextureFileAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateWidthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> RectLight: ...
    def GetHeightAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTextureFileAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetWidthAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class ShadowAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> ShadowAPI: ...
    def CreateShadowColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShadowDistanceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShadowEnableAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShadowFalloffAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShadowFalloffGammaAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShadowColorAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShadowDistanceAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShadowEnableAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShadowFalloffAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShadowFalloffGammaAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class ShapingAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> ShapingAPI: ...
    def CreateShapingConeAngleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShapingConeSoftnessAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShapingFocusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShapingFocusTintAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShapingIesAngleScaleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShapingIesFileAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateShapingIesNormalizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetShapingConeAngleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShapingConeSoftnessAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShapingFocusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShapingFocusTintAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShapingIesAngleScaleAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShapingIesFileAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetShapingIesNormalizeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class SphereLight(BoundableLightBase, usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateTreatAsPointAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> SphereLight: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetRadiusAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetTreatAsPointAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    angular = 'angular'
    automatic = 'automatic'
    collectionFilterLinkIncludeRoot = 'collection:filterLink:includeRoot'
    collectionLightLinkIncludeRoot = 'collection:lightLink:includeRoot'
    collectionShadowLinkIncludeRoot = 'collection:shadowLink:includeRoot'
    consumeAndContinue = 'consumeAndContinue'
    consumeAndHalt = 'consumeAndHalt'
    cubeMapVerticalCross = 'cubeMapVerticalCross'
    cylinderLight = 'CylinderLight'
    diskLight = 'DiskLight'
    distantLight = 'DistantLight'
    domeLight = 'DomeLight'
    extent = 'extent'
    filterLink = 'filterLink'
    geometry = 'geometry'
    geometryLight = 'GeometryLight'
    guideRadius = 'guideRadius'
    ignore = 'ignore'
    independent = 'independent'
    inputsAngle = 'inputs:angle'
    inputsColor = 'inputs:color'
    inputsColorTemperature = 'inputs:colorTemperature'
    inputsDiffuse = 'inputs:diffuse'
    inputsEnableColorTemperature = 'inputs:enableColorTemperature'
    inputsExposure = 'inputs:exposure'
    inputsHeight = 'inputs:height'
    inputsIntensity = 'inputs:intensity'
    inputsLength = 'inputs:length'
    inputsNormalize = 'inputs:normalize'
    inputsRadius = 'inputs:radius'
    inputsShadowColor = 'inputs:shadow:color'
    inputsShadowDistance = 'inputs:shadow:distance'
    inputsShadowEnable = 'inputs:shadow:enable'
    inputsShadowFalloff = 'inputs:shadow:falloff'
    inputsShadowFalloffGamma = 'inputs:shadow:falloffGamma'
    inputsShapingConeAngle = 'inputs:shaping:cone:angle'
    inputsShapingConeSoftness = 'inputs:shaping:cone:softness'
    inputsShapingFocus = 'inputs:shaping:focus'
    inputsShapingFocusTint = 'inputs:shaping:focusTint'
    inputsShapingIesAngleScale = 'inputs:shaping:ies:angleScale'
    inputsShapingIesFile = 'inputs:shaping:ies:file'
    inputsShapingIesNormalize = 'inputs:shaping:ies:normalize'
    inputsSpecular = 'inputs:specular'
    inputsTextureFile = 'inputs:texture:file'
    inputsTextureFormat = 'inputs:texture:format'
    inputsWidth = 'inputs:width'
    latlong = 'latlong'
    lightFilterShaderId = 'lightFilter:shaderId'
    lightFilters = 'light:filters'
    lightLink = 'lightLink'
    lightList = 'lightList'
    lightListCacheBehavior = 'lightList:cacheBehavior'
    lightMaterialSyncMode = 'light:materialSyncMode'
    lightShaderId = 'light:shaderId'
    materialGlowTintsLight = 'materialGlowTintsLight'
    meshLight = 'MeshLight'
    mirroredBall = 'mirroredBall'
    noMaterialResponse = 'noMaterialResponse'
    orientToStageUpAxis = 'orientToStageUpAxis'
    portalLight = 'PortalLight'
    portals = 'portals'
    rectLight = 'RectLight'
    shadowLink = 'shadowLink'
    sphereLight = 'SphereLight'
    treatAsLine = 'treatAsLine'
    treatAsPoint = 'treatAsPoint'
    volumeLight = 'VolumeLight'
    pass
class VolumeLightAPI(usdrt.Usd._Usd.APISchemaBase, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Apply(prim: usdrt.Usd._Usd.Prim) -> VolumeLightAPI: ...
    def CreateLightMaterialSyncModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightMaterialSyncModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetLightShaderIdAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
