[package]
# Semantic Versionning is used: https://semver.org/
version = "1.1.6"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Asset Validator (UI)"
description="UIs for Asset Validation to ensure compliance with all Omniverse products."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/extension_readme.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "other"

# Keywords for the extension
keywords = ["asset", "usd", "validator", "checker"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icons/assetValidatorActive.256x256.png"

[dependencies]
"omni.asset_validator.core" = {version="1.1.6", exact=true}
"omni.kit.menu.utils" = {}
"omni.kit.widget.filebrowser" = {}
"omni.kit.widget.filter" = {}
"omni.kit.widget.options_menu" = {}
"omni.kit.widget.searchfield" = {}
"omni.kit.window.file_importer" = {}
"omni.kit.window.file_exporter" = {}
"omni.kit.window.content_browser" = {optional=true}
"omni.kit.window.stage" = {optional=true}
"omni.kit.widget.layers" = {optional=true}
"omni.kit.context_menu" = { optional = true }
"omni.ui" = {}
"omni.usd" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "omni.asset_validator.ui"

# Demonstrate how to add another folder to sys.path. Here we add pip packages installed at build time.
[[python.module]]
path = "pip_prebundle"

[settings]
# note: AtomicAsset is disabled by default in core extension. We want to show it in UI, so we override it here.
exts."omni.asset_validator.core".disabledCategories = [ "Omni:SimReady" ]
exts."omni.asset_validator.ui".hideDisabledCategories = true
exts."omni.asset_validator.ui".hideDisabledRules = true
exts."omni.asset_validator.ui".selectedCategories = ["Usd:Schema"]
exts."omni.asset_validator.ui".capabilities.enabled = false
exts."omni.asset_validator.ui".capabilities.url = "http://omniverse-docs.s3-website-us-east-1.amazonaws.com/content-capabilities/0.2.0"

[[test]]
pyCoverageEnabled = true
pyCoverageIncludeModules = true
pyCoverageIncludeDependencies = false
pyCoverageIncludeTestDependencies = false

args = [
    "--no-window"
]

dependencies = [
    "omni.kit.ui_test",
    "omni.kit.context_menu",
]
