from __future__ import annotations
import pxr.UsdLux._usdLux
import typing
import Boost.Python
import pxr.Usd
import pxr.UsdGeom
import pxr.UsdLux

__all__ = [
    "BlackbodyTemperatureAsRgb",
    "BoundableLightBase",
    "CylinderLight",
    "DiskLight",
    "DistantLight",
    "DomeLight",
    "DomeLight_1",
    "GeometryLight",
    "LightAPI",
    "LightFilter",
    "LightListAPI",
    "ListAPI",
    "MeshLightAPI",
    "NonboundableLightBase",
    "PluginLight",
    "PluginLightFilter",
    "PortalLight",
    "RectLight",
    "ShadowAPI",
    "ShapingAPI",
    "SphereLight",
    "Tokens",
    "VolumeLightAPI"
]


class CylinderLight(BoundableLightBase, pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateLengthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTreatAsLineAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLengthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTreatAsLineAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class DiskLight(BoundableLightBase, pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class BoundableLightBase(pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDiffuseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEnableColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFiltersRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIntensityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSpecularAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDiffuseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEnableColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFiltersRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIntensityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSpecularAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def LightAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class DistantLight(NonboundableLightBase, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAngleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAngleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class DomeLight(NonboundableLightBase, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateGuideRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePortalsRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTextureFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTextureFormatAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetGuideRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPortalsRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTextureFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTextureFormatAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def OrientToStageUpAxis(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class DomeLight_1(NonboundableLightBase, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateGuideRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePoleAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePortalsRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTextureFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTextureFormatAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetGuideRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPoleAxisAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPortalsRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTextureFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTextureFormatAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class GeometryLight(NonboundableLightBase, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateGeometryRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetGeometryRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class LightAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDiffuseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEnableColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFiltersRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIntensityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateMaterialSyncModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShaderIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShaderIdAttrForRenderContext(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSpecularAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDiffuseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEnableColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFiltersRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIntensityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLightLinkCollectionAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMaterialSyncModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderIdAttrForRenderContext(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShadowLinkCollectionAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSpecularAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class LightFilter(pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShaderIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShaderIdAttrForRenderContext(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFilterLinkCollectionAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderId(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderIdAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShaderIdAttrForRenderContext(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class LightListAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    class ComputeMode(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'LightListAPI'
        allValues: tuple # value = (UsdLux.LightListAPI.ComputeModeConsultModelHierarchyCache, UsdLux.LightListAPI.ComputeModeIgnoreCache)
        pass
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeLightList(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLightListCacheBehaviorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLightListRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLightListCacheBehaviorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLightListRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def InvalidateLightList(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def StoreLightList(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    ComputeModeConsultModelHierarchyCache: pxr.UsdLux.ComputeMode # value = UsdLux.LightListAPI.ComputeModeConsultModelHierarchyCache
    ComputeModeIgnoreCache: pxr.UsdLux.ComputeMode # value = UsdLux.LightListAPI.ComputeModeIgnoreCache
    __instance_size__ = 56
    pass
class ListAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    class ComputeMode(pxr.Tf.Tf_PyEnumWrapper, pxr.Tf.Enum, Boost.Python.instance):
        @staticmethod
        def GetValueFromName(*args, **kwargs) -> typing.Any: ...
        _baseName = 'ListAPI'
        allValues: tuple # value = (UsdLux.ListAPI.ComputeModeConsultModelHierarchyCache, UsdLux.ListAPI.ComputeModeIgnoreCache)
        pass
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ComputeLightList(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLightListCacheBehaviorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLightListRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLightListCacheBehaviorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLightListRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def InvalidateLightList(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def StoreLightList(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    ComputeModeConsultModelHierarchyCache: pxr.UsdLux.ComputeMode # value = UsdLux.ListAPI.ComputeModeConsultModelHierarchyCache
    ComputeModeIgnoreCache: pxr.UsdLux.ComputeMode # value = UsdLux.ListAPI.ComputeModeIgnoreCache
    __instance_size__ = 56
    pass
class MeshLightAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class NonboundableLightBase(pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDiffuseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEnableColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFiltersRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateIntensityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateSpecularAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDiffuseAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEnableColorTemperatureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetExposureAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFiltersRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetIntensityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSpecularAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def LightAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class PluginLight(pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNodeDefAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class PluginLightFilter(LightFilter, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNodeDefAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class PortalLight(BoundableLightBase, pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateWidthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class RectLight(BoundableLightBase, pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTextureFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateWidthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHeightAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTextureFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetWidthAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class ShadowAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShadowColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShadowDistanceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShadowEnableAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShadowFalloffAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShadowFalloffGammaAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShadowColorAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShadowDistanceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShadowEnableAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShadowFalloffAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShadowFalloffGammaAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class ShapingAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def ConnectableAPI(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingConeAngleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingConeSoftnessAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingFocusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingFocusTintAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingIesAngleScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingIesFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateShapingIesNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetInputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutput(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOutputs(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingConeAngleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingConeSoftnessAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingFocusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingFocusTintAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingIesAngleScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingIesFileAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetShapingIesNormalizeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class SphereLight(BoundableLightBase, pxr.UsdGeom.Boundable, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTreatAsPointAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetRadiusAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTreatAsPointAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Tokens(Boost.Python.instance):
    BoundableLightBase = 'BoundableLightBase'
    CylinderLight = 'CylinderLight'
    DiskLight = 'DiskLight'
    DistantLight = 'DistantLight'
    DomeLight = 'DomeLight'
    DomeLight_1 = 'DomeLight_1'
    GeometryLight = 'GeometryLight'
    LightAPI = 'LightAPI'
    LightFilter = 'LightFilter'
    LightListAPI = 'LightListAPI'
    ListAPI = 'ListAPI'
    MeshLight = 'MeshLight'
    MeshLightAPI = 'MeshLightAPI'
    NonboundableLightBase = 'NonboundableLightBase'
    PluginLight = 'PluginLight'
    PluginLightFilter = 'PluginLightFilter'
    PortalLight = 'PortalLight'
    RectLight = 'RectLight'
    ShadowAPI = 'ShadowAPI'
    ShapingAPI = 'ShapingAPI'
    SphereLight = 'SphereLight'
    VolumeLight = 'VolumeLight'
    VolumeLightAPI = 'VolumeLightAPI'
    Y = 'Y'
    Z = 'Z'
    angular = 'angular'
    automatic = 'automatic'
    collectionFilterLinkIncludeRoot = 'collection:filterLink:includeRoot'
    collectionLightLinkIncludeRoot = 'collection:lightLink:includeRoot'
    collectionShadowLinkIncludeRoot = 'collection:shadowLink:includeRoot'
    consumeAndContinue = 'consumeAndContinue'
    consumeAndHalt = 'consumeAndHalt'
    cubeMapVerticalCross = 'cubeMapVerticalCross'
    filterLink = 'filterLink'
    geometry = 'geometry'
    guideRadius = 'guideRadius'
    ignore = 'ignore'
    independent = 'independent'
    inputsAngle = 'inputs:angle'
    inputsColor = 'inputs:color'
    inputsColorTemperature = 'inputs:colorTemperature'
    inputsDiffuse = 'inputs:diffuse'
    inputsEnableColorTemperature = 'inputs:enableColorTemperature'
    inputsExposure = 'inputs:exposure'
    inputsHeight = 'inputs:height'
    inputsIntensity = 'inputs:intensity'
    inputsLength = 'inputs:length'
    inputsNormalize = 'inputs:normalize'
    inputsRadius = 'inputs:radius'
    inputsShadowColor = 'inputs:shadow:color'
    inputsShadowDistance = 'inputs:shadow:distance'
    inputsShadowEnable = 'inputs:shadow:enable'
    inputsShadowFalloff = 'inputs:shadow:falloff'
    inputsShadowFalloffGamma = 'inputs:shadow:falloffGamma'
    inputsShapingConeAngle = 'inputs:shaping:cone:angle'
    inputsShapingConeSoftness = 'inputs:shaping:cone:softness'
    inputsShapingFocus = 'inputs:shaping:focus'
    inputsShapingFocusTint = 'inputs:shaping:focusTint'
    inputsShapingIesAngleScale = 'inputs:shaping:ies:angleScale'
    inputsShapingIesFile = 'inputs:shaping:ies:file'
    inputsShapingIesNormalize = 'inputs:shaping:ies:normalize'
    inputsSpecular = 'inputs:specular'
    inputsTextureFile = 'inputs:texture:file'
    inputsTextureFormat = 'inputs:texture:format'
    inputsWidth = 'inputs:width'
    latlong = 'latlong'
    lightFilterShaderId = 'lightFilter:shaderId'
    lightFilters = 'light:filters'
    lightLink = 'lightLink'
    lightList = 'lightList'
    lightListCacheBehavior = 'lightList:cacheBehavior'
    lightMaterialSyncMode = 'light:materialSyncMode'
    lightShaderId = 'light:shaderId'
    materialGlowTintsLight = 'materialGlowTintsLight'
    mirroredBall = 'mirroredBall'
    noMaterialResponse = 'noMaterialResponse'
    orientToStageUpAxis = 'orientToStageUpAxis'
    poleAxis = 'poleAxis'
    portals = 'portals'
    scene = 'scene'
    shadowLink = 'shadowLink'
    treatAsLine = 'treatAsLine'
    treatAsPoint = 'treatAsPoint'
    pass
class VolumeLightAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class _CanApplyResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
def BlackbodyTemperatureAsRgb(*args, **kwargs) -> typing.Any:
    pass
__MFB_FULL_PACKAGE_NAME = 'usdLux'
