[package]
authors = ["NVIDIA"]
category = "Services"
changelog="docs/CHANGELOG.md"
description="The metrics facility allows users to instrument Kit services with metrics and expose them via a /metrics endpoint. \n Metrics are using the Prometheus format."
icon = "data/icon.png"
keywords = ["kit", "services", "monitoring", "facility"]
preview_image = "data/preview.png"
readme  = "docs/README.md"
repository = ""
title = "Services metrics collecting"
version = "0.3.0"

[dependencies]
"omni.kit.pip_archive" = {}
"omni.services.pip_archive" = {}
"omni.services.core" = {}

[[python.module]]
name = "omni.services.facilities.monitoring.metrics"

[settings]
exts."services.monitoring.metrics".push_metrics = false
exts."services.monitoring.metrics".push_gateway = "http://localhost:9091"
exts."services.monitoring.metrics".push_interval = 10
exts."services.monitoring.metrics".job_name = "services_monitoring_metrics"
exts."services.monitoring.metrics".show_metrics_endpoint = true


[test]
dependencies = ["omni.services.client"]
