
[package]
    archivePath = "https://d4i3qtqj3r0z5.cloudfront.net/omni.kit.core.collection-0.2.3.zip"

    [package.publish]
        kitVersion = "107.0.3+feature.180676.45352709.gl"
        date = 1753064091
        buildNumber = "107.0.2+master.1631.cdf87a60.gl"
        repoName = "kit-usd"
        signed = 1
