
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.numpy.common-719c4fb8e330e8d8.zip"

    [package.publish]
        kitVersion = "107.3.2+production.216791.31d93c69.gl"
        date = 1757755257
        buildNumber = "107.3.2+1073.216791.31d93c69.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
