{%+ for line in copyright -%}
# {{ line -}}
{%+ if loop.last +%}

{%+ endif -%}
{%+ endfor -%}
# This file is automatically generated by idl.py package and should not be edited manually.

from typing import List, Optional, Dict, AsyncIterator
from idl.types import Enum, Record, Literal

{% include "types.pyi" %}