from __future__ import annotations
import usdrt.UsdVol._UsdVol
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd
import usdrt.UsdGeom._UsdGeom

__all__ = [
    "Field3DAsset",
    "FieldAsset",
    "FieldBase",
    "OpenVDBAsset",
    "Tokens",
    "Volume"
]


class Field3DAsset(FieldAsset, FieldBase, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateFieldDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFieldPurposeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Field3DAsset: ...
    def GetFieldDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFieldPurposeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class OpenVDBAsset(FieldAsset, FieldBase, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateFieldClassAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFieldDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> OpenVDBAsset: ...
    def GetFieldClassAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFieldDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class FieldAsset(FieldBase, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateFieldDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFieldIndexAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFieldNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFilePathAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateVectorDataRoleHintAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFieldDataTypeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFieldIndexAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFieldNameAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFilePathAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetVectorDataRoleHintAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class FieldBase(usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    bool_ = 'bool'
    color = 'Color'
    double2 = 'double2'
    double3 = 'double3'
    double_ = 'double'
    field = 'field'
    fieldClass = 'fieldClass'
    fieldDataType = 'fieldDataType'
    fieldIndex = 'fieldIndex'
    fieldName = 'fieldName'
    fieldPurpose = 'fieldPurpose'
    filePath = 'filePath'
    float2 = 'float2'
    float3 = 'float3'
    float_ = 'float'
    fogVolume = 'fogVolume'
    half = 'half'
    half2 = 'half2'
    half3 = 'half3'
    int2 = 'int2'
    int3 = 'int3'
    int64 = 'int64'
    int_ = 'int'
    levelSet = 'levelSet'
    mask = 'mask'
    matrix3d = 'matrix3d'
    matrix4d = 'matrix4d'
    none = 'None'
    normal = 'Normal'
    point = 'Point'
    quatd = 'quatd'
    staggered = 'staggered'
    string = 'string'
    uint = 'uint'
    unknown = 'unknown'
    vector = 'Vector'
    vectorDataRoleHint = 'vectorDataRoleHint'
    pass
class Volume(usdrt.UsdGeom._UsdGeom.Gprim, usdrt.UsdGeom._UsdGeom.Boundable, usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> Volume: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
