[package]
# Semantic Versionning is used: https://semver.org/
version = "106.4.1"

# Which category this extension belongs to
category="Animation"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Animation Curve Editor"
description="Attribute's Animation Curve Editor"

feature = true

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ["animation", "key", "curve", "editor"]

# Preview image. Folder named "data" automatically goes in git lfs (see .gitattributes file).
icon = "data/icon.png"
preview_image = "data/preview.png"

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"
readme = "docs/README.md"

[[python.module]]
name = "omni.anim.curve_editor"

[dependencies]
"omni.usd" = {}
"omni.ui" = {}
"omni.timeline" = {}
"omni.kit.context_menu" = {}
"omni.kit.menu.utils" = {}
"omni.anim.curve.core" = {}
"omni.kit.widget.timeline" = {}
"omni.kit.widget.stage_icons" = {}
"omni.kit.widget.stage" = {}
"omni.kit.notification_manager" = {}
"omni.graph" = {}
"omni.kit.editor" = {tag="full", optional=true}
"omni.kit.actions.core" = {}
"omni.timeline.live_session" = {}
# "omni.kit.hotkeys.core" = {optional=true}
"omni.usd.schema.anim" = {}

[[test]]
dependencies = [
    # "omni.kit.window.viewport",
    "omni.kit.viewport.window",  # to only test against the new viewport
    "omni.kit.window.property",
    "omni.kit.property.usd",
    "omni.kit.property.transform",
    "omni.kit.ui_test",
    "omni.kit.test_suite.helpers",
    "omni.kit.window.content_browser",
]
args = [
    "--/app/asyncRendering=false",
    "--/app/file/ignoreUnsavedOnExit=true",
    "--/persistent/exts/omni.anim.curve_editor/timelineBeginRange=0.0",
    "--/persistent/exts/omni.anim.curve_editor/timelineEndRange=100.0",
    "--no-window",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/exts/omni.kit.viewport.window/startup/windowName=Viewport",  # to only test against the new viewport
]

timeout = 2400

stdoutFailPatterns.exclude = [
    "*Failed to acquire interface [omni::kit::renderer::IGpuFoundation v0.2]*", # Leak
    "*__init__(self, ...) called with invalid `self` argument*", # Unknown Issue with property editor.
]

[package.writeTarget]
kit = true

[package]
writeTarget.usd = true
