
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.widget.text_editor-2f2ff3590e6e5074.zip"

    [package.publish]
        kitVersion = "107.3.3+production.228094.d3a598e6.gl"
        date = 1757755258
        buildNumber = "107.3.3+1073.228094.d3a598e6.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
