from __future__ import annotations
import usdrt.UsdMedia._UsdMedia
import typing
import usdrt.Sdf._Sdf
import usdrt.Usd._Usd
import usdrt.UsdGeom._UsdGeom

__all__ = [
    "SpatialAudio",
    "Tokens"
]


class SpatialAudio(usdrt.UsdGeom._UsdGeom.Xformable, usdrt.UsdGeom._UsdGeom.Imageable, usdrt.Usd._Usd.Typed, usdrt.Usd._Usd.SchemaBase):
    def CreateAuralModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateEndTimeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateFilePathAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateGainAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateMediaOffsetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreatePlaybackModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def CreateStartTimeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def Define(stage: usdrt.Usd._Usd.Stage, path: usdrt.Sdf._Sdf.Path) -> SpatialAudio: ...
    def GetAuralModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetEndTimeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetFilePathAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetGainAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetMediaOffsetAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def GetPlaybackModeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    @staticmethod
    def GetSchemaTypeName() -> TfToken: ...
    def GetStartTimeAttr(self) -> usdrt.Usd._Usd.Attribute: ...
    def __bool__(self) -> bool: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.Prim) -> None: ...
    @typing.overload
    def __init__(self, arg0: usdrt.Usd._Usd.SchemaBase) -> None: ...
    def __repr__(self) -> str: ...
    pass
class Tokens():
    auralMode = 'auralMode'
    endTime = 'endTime'
    filePath = 'filePath'
    gain = 'gain'
    loopFromStage = 'loopFromStage'
    loopFromStart = 'loopFromStart'
    loopFromStartToEnd = 'loopFromStartToEnd'
    mediaOffset = 'mediaOffset'
    nonSpatial = 'nonSpatial'
    onceFromStart = 'onceFromStart'
    onceFromStartToEnd = 'onceFromStartToEnd'
    playbackMode = 'playbackMode'
    spatial = 'spatial'
    startTime = 'startTime'
    pass
