[package]
# Semantic Versioning is used: https://semver.org/
version = "107.0.6"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Cameras in Viewport Menu Bar"
description="Adds a variety of camera settings"

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ["kit", "ui", "menu", "viewport", "camera"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.md"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

category = "Internal"
support_level = "Core"

[dependencies]
"omni.kit.viewport.menubar.core" = {}
"omni.ui.scene" = {}
"omni.kit.commands" = {}
"omni.kit.window.cursor" = {optional=true}
"omni.kit.hotkeys.core" = {optional=true}

# Main python module this extension provides, it will be publicly available as "import omni.kit.viewport.menubar.camera".
[[python.module]]
name = "omni.kit.viewport.menubar.camera"

[settings]
exts."omni.kit.viewport.menubar.camera".visible = true
exts."omni.kit.viewport.menubar.camera".order = -10
exts."omni.kit.viewport.menubar.camera".expand = true
exts."omni.kit.viewport.menubar.camera".showAutoExposure = true
# Whether to use UsdRt for prim-type queries when it is available
exts."omni.kit.viewport.menubar.camera".primQuery.useUsdRt = true

# OM-62401: Cameras whose path starts with filters will not display in menubar
# Default do not show waypoint and markup cameras
exts."omni.kit.viewport.menubar.camera".filters = [
    "/Viewport_Waypoints",
    "/Viewport_Markups",
]


[[test]]
dependencies = [
    "omni.hydra.pxr",
    "omni.kit.viewport.window",
    "omni.kit.viewport.utility",
    "omni.kit.widget.spinner",
    "omni.kit.ui_test",
]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/multiGpu/autoEnable=false", # Disable mGPU with PXR due to OM-51026, OM-53611
    "--/renderer/multiGpu/maxGpuCount=1",
    "--/app/window/width=850",
    "--/app/window/height=300",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/viewport/defaults/hud/visible=false",
    "--/app/viewport/defaults/guide/axis/visible=false",
    "--/app/viewport/defaults/guide/grid/visible=false",
]

# Run tests with optional UsdRt
[[test]]
name = "usdrt.scenegraph"
dependencies = [
    "omni.hydra.pxr",
    "omni.kit.viewport.window",
    "omni.kit.viewport.utility",
    "omni.kit.widget.spinner",
    "omni.kit.ui_test",
    "usdrt.scenegraph",
]
args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/multiGpu/autoEnable=false", # Disable mGPU with PXR due to OM-51026, OM-53611
    "--/renderer/multiGpu/maxGpuCount=1",
    "--/app/window/width=850",
    "--/app/window/height=300",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/viewport/defaults/hud/visible=false",
    "--/app/viewport/defaults/guide/axis/visible=false",
    "--/app/viewport/defaults/guide/grid/visible=false",
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
    "docs/SETTINGS.md",
    "docs/USAGE_PYTHON.md",
]
