
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.stage_column.variant-1.0.17%2B107.3.0.zip"

    [package.target]

        [package.target.kit]
            0 = "107.3.0"

    [package.publish]
        kitVersion = "107.3.0+master.185040.fcf988ef.gl"
        date = 1745252051
        buildNumber = "106.0.1+master.767.642a6560.gl"
        repoName = "kit-widgets"
        signed = 1
