
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.xr.scene_view.core-107.3.109%2B107.3.3.lx64.r.cp311.u353.zip"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.usd]
            0 = "u353f+stock+24.05+cxx11"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kit]
            0 = "107.3.3"

    [package.publish]
        kitVersion = "107.3.3+production.228331.05b9b9d8.gl"
        date = 1757389009
        buildNumber = "107.3.109+107-3-109.31958.fa0f3ce1.gl"
        repoName = "kit-xr-sdk"
        signed = 1
