[package]
title = "Default Graph Delegate"
description = "Simple and Elegant Graph Delegate"
version = "1.2.3"
authors = ["NVIDIA"]
repository = ""
keywords = ["graph", "shader", "editor"]
changelog = "docs/CHANGELOG.md"
preview_image = "data/preview.png"
readme = "docs/README.md"
category = "Rendering"
icon = "icons/icon.svg"

[dependencies]
"omni.kit.widget.graph" = {}
"omni.ui" = {}

[[python.module]]
name = "omni.kit.graph.delegate.default"

[[test]]
dependencies = [
    "omni.kit.mainwindow",
    "omni.kit.graph.editor.example",
    "omni.kit.graph.editor.core",
    "omni.kit.ui_test"
]

args = [
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window"
]
