
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.window.title-d8058b6252b5e148.zip"

    [package.publish]
        kitVersion = "107.3.0+feature.195367.2c7fcd57.gl"
        date = 1757755128
        buildNumber = "107.3.0+1073.195367.2c7fcd57.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
