[package]
title = "Animation Curve"
description = "An bundle of Animation Curve Data runtime and UI elements"
category="Animation"
version = "1.2.3"
feature = true

icon = "data/icon.svg"
preview_image = "data/preview.png"
changelog="docs/CHANGELOG.md"
readme  = "docs/index.rst"


repository = ""

keywords = ["animation", "curve"]

[dependencies]
"omni.anim.curve.core" = {}
"omni.anim.curve.ui" = {}

[[test]]
waiver = "Bundle extension without any code"

[package.writeTarget]
kit = true
usd = true
