
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/isaacsim.util.debug_draw-3.1.0%2B107.3.2.lx64.r.cp311.zip"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kit]
            0 = "107.3.2"

    [package.publish]
        kitVersion = "107.3.2+production.221624.95ab655d.gl"
        date = 1755748447
        buildNumber = "5.0.0-alpha.54+develop.111.f73e32cc.gl"
        repoName = "omni-isaac-sim-internal"
        signed = 1
