[package]
title = "Livestream NVCF Service Endpoint"
description = "Livestream NVCF Service Endpoint."
version = "7.2.0"
category = "services"
authors = ["NVIDIA"]
repository = ""
preview_image = "data/preview.png"
icon = "data/icon.png"
keywords = ["kit", "streaming", "webrtc", "nvcf"]
changelog = "docs/CHANGELOG.md"
readme = "docs/README.md"

# Only available to the Kit version it was built with (and higher)
[package.writeTarget]
kit = true

[dependencies]
"omni.kit.livestream.webrtc" = {}
"omni.services.core" = {}
"omni.services.transport.server.http" = {}

[settings]
app.livestream.fixedHostPort = 0
app.livestream.minHostPort = 47998
app.livestream.maxHostPort = 48020
exts."omni.services.transport.server.http".port = 8011

[[python.module]]
name = "omni.services.livestream.nvcf"

[settings]
app.livestream.nvcf.quitOnSessionEnded = true
app.livestream.nvcf.sessionResumeTimeoutSeconds = 0
app.livestream.nvcf.waitForCustomReadyEvent = false

[[test]]
dependencies = [
    "omni.services.client",
    "omni.services.transport.client.http_async",
]
