[package]
authors = ["NVIDIA"]
category = "services"
changelog = "docs/CHANGELOG.md"
description="A Zeroconf server."
icon = "data/icon.png"
keywords = ["kit", "service", "client", "zeroconf"]
preview_image = "data/preview.png"
readme  = "docs/README.md"
repository = ""
title = "Zeroconf microservice"
version = "1.0.9"

[dependencies]
"omni.services.core" = {}
"omni.services.transport.server.base" = {}
"omni.services.pip_archive" = {}

[[python.module]]
name = "omni.services.transport.server.zeroconf"

[settings]
exts."omni.services.transport.server.zeroconf".zeroconf.enabled = true


[[test]]
# Disable binding to ports when running in tests.
args = [
    "--/exts/omni.services.transport.server.zeroconf/zeroconf/enabled=false"
]
