
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.volume-b6555e15f0aa0e71.zip"

    [package.publish]
        kitVersion = "107.3.3+production.224552.a7123159.gl"
        date = 1757755259
        buildNumber = "107.3.3+1073.224552.a7123159.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
