
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.window.file-c7872f10464cd8c5.zip"

    [package.publish]
        kitVersion = "107.3.0+feature.197424.f6a3cce1.gl"
        date = 1757755127
        buildNumber = "107.3.0+1073.197424.f6a3cce1.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
