
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.graph.nodes-1.170.10%2B107.3.0.lx64.r.cp311.u353.zip"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.usd]
            0 = "u353f+stock+24.05+cxx11"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kit]
            0 = "107.3.0"

    [package.publish]
        kitVersion = "107.3.0+feature.199521.41618880.gl"
        date = 1748978928
        buildNumber = "23-06+master.7693.324dedc3.gl"
        repoName = "kit-omnigraph"
        signed = 1
