
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.livestream.core-7.5.0%2B107.0.3.lx64.r.cp311.u353.zip"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp311"

        [package.target.usd]
            0 = "u353f+stock+24.05+cxx11"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kit]
            0 = "107.0.3"

    [package.publish]
        kitVersion = "107.0.3+mr36087.171495.aeeb3d54.gl"
        date = 1738806182
        buildNumber = "107.0+master.967.149b00f8.gl"
        repoName = "kit-livestream"
        signed = 1
