[package]
# Semantic Versioning is used: https://semver.org/
version = "107.0.0"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
description = "Transform Manipulator Extension"
title = "Transform Manipulator"

# Path (relative to the root) or content of readme markdown file for UI.
readme = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Scene"
support_level = "Core"

# Keywords for the extension
keywords = ["kit", "manipulator"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog = "docs/CHANGELOG.md"

# Preview image and icon. Folder named "data" automatically goes in git lfs (see .gitattributes file).
# Preview image is shown in "Overview" of Extensions window. Screenshot of an extension might be a good preview image.
preview_image = "data/preview.png"

# Icon is shown in Extensions window, it is recommended to be square, of size 256x256.
icon = "data/icon.png"

[dependencies]
"omni.kit.pip_archive" = {}
"omni.kit.window.preferences" = {optional = true}
"omni.ui" = {}
"omni.ui.scene" = {}
"omni.kit.context_menu" = {}

# Main python module this extension provides, it will be publicly available as "import omni.example.hello".
[[python.module]]
name = "omni.kit.manipulator.transform"

[documentation]
pages = [
    "docs/Overview.md",
    "docs/USAGE_PYTHON.md",
    "docs/SETTINGS.md",
    "docs/CHANGELOG.md",
]

[[test]]
dependencies = [
  "omni.kit.ui_test",
]

args = [
  "--/app/window/dpiScaleOverride=1.0",
  "--/app/window/scaleToMonitor=false",
]

[settings]
persistent.exts."omni.kit.manipulator.transform".manipulator.freeRotationType = "Clamped"
persistent.exts."omni.kit.manipulator.transform".manipulator.freeRotationEnabled = true
persistent.exts."omni.kit.manipulator.transform".manipulator.scaleMultiplier = 1.4
persistent.exts."omni.kit.manipulator.transform".manipulator.intersectionThickness = 10
persistent.exts."omni.kit.manipulator.transform".tools.defaultCollapsed = true
persistent.exts."omni.kit.manipulator.transform".manipulator.omniScaleDirection = "XY"  # ["X", "Y", "XY"]
