from __future__ import annotations
import usdrt.Vt._Vt
import typing
import numpy
import usdrt.Gf._Gf
_Shape = typing.Tuple[int, ...]

__all__ = [
    "AssetArray",
    "BoolArray",
    "CharArray",
    "DoubleArray",
    "FloatArray",
    "HalfArray",
    "Int64Array",
    "IntArray",
    "Matrix2dArray",
    "Matrix2fArray",
    "Matrix3dArray",
    "Matrix3fArray",
    "Matrix4dArray",
    "Matrix4fArray",
    "QuatdArray",
    "QuatfArray",
    "QuathArray",
    "ShortArray",
    "StringArray",
    "TimeCodeArray",
    "TokenArray",
    "UCharArray",
    "UInt64Array",
    "UIntArray",
    "UShortArray",
    "Vec2dArray",
    "Vec2fArray",
    "Vec2hArray",
    "Vec2iArray",
    "Vec3dArray",
    "Vec3fArray",
    "Vec3hArray",
    "Vec3iArray",
    "Vec4dArray",
    "Vec4fArray",
    "Vec4hArray",
    "Vec4iArray"
]


class AssetArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: AssetArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt::SdfAssetPath], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    @staticmethod
    def __getitem__(*args, **kwargs) -> typing.Any: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.uint64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt::SdfAssetPath]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def __setitem__(*args, **kwargs) -> typing.Any: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class BoolArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: BoolArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[bool], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> bool: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[bool]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[bool]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: bool) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class CharArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: CharArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[str], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> str: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int8]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[str]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: str) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class DoubleArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: DoubleArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[float], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> float: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[float]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: float) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class FloatArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: FloatArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[float], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> float: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[float]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: float) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class HalfArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: HalfArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[GfHalf], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> GfHalf: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[GfHalf]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: GfHalf) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Int64Array():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Int64Array) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class IntArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: IntArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Matrix2dArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Matrix2dArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Matrix2d], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Matrix2d: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Matrix2d]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Matrix2d) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Matrix2fArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Matrix2fArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Matrix2f], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Matrix2f: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Matrix2f]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Matrix2f) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Matrix3dArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Matrix3dArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Matrix3d], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Matrix3d: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Matrix3d]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Matrix3d) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Matrix3fArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Matrix3fArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Matrix3f], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Matrix3f: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Matrix3f]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Matrix3f) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Matrix4dArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Matrix4dArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Matrix4d], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Matrix4d: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Matrix4d]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Matrix4d) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Matrix4fArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Matrix4fArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Matrix4f], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Matrix4f: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Matrix4f]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Matrix4f) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class QuatdArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: QuatdArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Quatd], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Quatd: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Quatd]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Quatd) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class QuatfArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: QuatfArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Quatf], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Quatf: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Quatf]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Quatf) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class QuathArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: QuathArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Quath], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Quath: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Quath]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Quath) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class ShortArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: ShortArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class StringArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: StringArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[str], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> str: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int8]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[str]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: str) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class TimeCodeArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: TimeCodeArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt::UsdTimeCode], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    @staticmethod
    def __getitem__(*args, **kwargs) -> typing.Any: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[usdrt::UsdTimeCode]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt::UsdTimeCode]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    @staticmethod
    def __setitem__(*args, **kwargs) -> typing.Any: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class TokenArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: TokenArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[TfToken], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> TfToken: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.uint64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[TfToken]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: TfToken) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class UCharArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: UCharArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.uint8]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class UInt64Array():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: UInt64Array) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.uint64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class UIntArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: UIntArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.uint32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class UShortArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: UShortArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[int], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.uint16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[int]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec2dArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec2dArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec2d], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec2d: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec2d]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec2d) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec2fArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec2fArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec2f], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec2f: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec2f]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec2f) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec2hArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec2hArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec2h], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec2h: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec2h]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec2h) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec2iArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec2iArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec2i], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec2i: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec2i]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec2i) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec3dArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec3dArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec3d], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec3d: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec3d]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec3d) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec3fArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec3fArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec3f], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec3f: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec3f]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec3f) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec3hArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec3hArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec3h], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec3h: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec3h]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec3h) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec3iArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec3iArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec3i], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec3i: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec3i]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec3i) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec4dArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec4dArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec4d], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec4d: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float64]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec4d]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec4d) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec4fArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec4fArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec4f], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec4f: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec4f]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec4f) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec4hArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec4hArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec4h], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec4h: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.float16]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec4h]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec4h) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
class Vec4iArray():
    def DetachFromSource(self) -> None: ...
    def HasFabricGpuData(self) -> bool: ...
    def IsFabricData(self) -> bool: ...
    def IsOwnData(self) -> bool: ...
    def IsPythonData(self) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: Vec4iArray) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: typing.Annotated[typing.List[usdrt.Gf._Gf.Vec4i], pybind11_stubgen.typing_ext.FixedSize(0)]) -> bool: ...
    @typing.overload
    def __eq__(self, arg0: object) -> bool: ...
    def __getitem__(self, arg0: int) -> usdrt.Gf._Gf.Vec4i: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, arg0: int) -> None: ...
    @typing.overload
    def __init__(self, arg0: object) -> None: ...
    @typing.overload
    def __init__(self, arg0: numpy.ndarray[numpy.int32]) -> None: ...
    @typing.overload
    def __init__(self, arg0: typing.List[usdrt.Gf._Gf.Vec4i]) -> None: ...
    def __iter__(self) -> typing.Iterator: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(self, arg0: int, arg1: usdrt.Gf._Gf.Vec4i) -> None: ...
    def __str__(self) -> str: ...
    @property
    def __array_interface__(self) -> dict:
        """
        :type: dict
        """
    @property
    def __cuda_array_interface__(self) -> dict:
        """
        :type: dict
        """
    __hash__ = None
    pass
