import carb

TIMELINE_BORDER_WIDTH = 4
TIMELINE_SCRUB_WIDTH = 28
TRACKLIST_MIN_WIDTH = 150
TRACKLIST_DEFAULT_OFFSET = 100
TRACKLIST_WIDTH = TRACKLIST_MIN_WIDTH + TRACKLIST_DEFAULT_OFFSET
DEFAULT_TRACK_HEIGHT = 44
DEFAULT_CLIP_SPACER_HEIGHT = 2
DEFAULT_CLIP_HEIGHT = DEFAULT_TRACK_HEIGHT - (DEFAULT_CLIP_SPACER_HEIGHT * 2)
