[package]
# Semantic Versioning is used: https://semver.org/
version = "1.1.2"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Viewport Utility"
description="Utility functions to access [active] Viewport information"

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ["kit", "viewport", "utility"]

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.rst"

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

category = "Viewport"
support_level = "Core"

[dependencies]
"omni.usd.libs" = {}
"omni.kit.viewport.window" = { optional = true }

# Main python module this extension provides, it will be publicly available as "import omni.kit.viewport.registry".
[[python.module]]
name = "omni.kit.viewport.utility"

[[test]]
samplingFactor = 0.2  # run 20% of tests, after ~5 runs (1/0.2) all tests will have completed

args = [
    "--/renderer/enabled=pxr",
    "--/renderer/active=pxr",
    "--/pxr/rendermode=HdStormRendererPlugin",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/multiGpu/autoEnable=false", # Disable mGPU with PXR due to OM-51026, OM-53611
    "--/renderer/multiGpu/maxGpuCount=1",
    "--/app/asyncRendering=false",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/window/hideUi=true",
    "--/app/renderer/resolution/width=500",
    "--/app/renderer/resolution/height=500",
    "--/app/window/width=500",
    "--/app/window/height=500",
    "--/app/viewport/forceHideFps=true",
]
dependencies = [
    "omni.ui",
    "omni.kit.mainwindow",
    "omni.kit.test_helpers_gfx",
    "omni.kit.ui_test",
    "omni.kit.manipulator.selection",
    "omni.hydra.pxr",
    "omni.kit.viewport.window",
    "omni.kit.context_menu",
    "omni.kit.viewport.actions"
]
stdoutFailPatterns.exclude = [
	"*HydraRenderer failed to render this frame*",  # Can drop a frame or two rendering with OpenGL interop
]

[documentation]
pages = [
    "docs/Overview.md",
    "docs/CHANGELOG.md",
    "docs/USAGE_PYTHON.md",
    "docs/SETTINGS.md"
]
