from __future__ import annotations
import OmniGraphSchema._omniGraphSchema
import typing
import Boost.Python
import OmniGraphSchema
import pxr.Usd

__all__ = [
    "CompoundNodeAPI",
    "CompoundNodeType_1",
    "InputDefAPI",
    "OmniGraph",
    "OmniGraphAPI",
    "OmniGraphCompoundNodeType",
    "OmniGraphNode",
    "OmniGraphNodeType",
    "OutputDefAPI",
    "Tokens"
]


class CompoundNodeAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCompoundGraphRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateCompoundTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCompoundGraphRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetCompoundTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class CompoundNodeType_1(OmniGraphNodeType, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateOmniGraphAssetRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphAssetRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class InputDefAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateAllowedTokensAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConnectionRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDescriptionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHiddenAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLiteralOnlyAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUiNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUiTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAll(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAllowedTokensAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectionRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDescriptionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHiddenAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLiteralOnlyAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUiNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUiTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsOmniGraphInputDefAPIPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class OmniGraph(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAllowAutoInstancingAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEvaluationModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEvaluatorTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFabricCacheBackingAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFileFormatVersionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePipelineStageAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAllowAutoInstancingAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEvaluationModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEvaluatorTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFabricCacheBackingAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFileFormatVersionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPipelineStageAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class OmniGraphAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOmniGraphsRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphsRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class OmniGraphCompoundNodeType(OmniGraphNodeType, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateOmniGraphAssetRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphAssetRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class OmniGraphNode(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateNodeTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateNodeTypeVersionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNodeTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetNodeTypeVersionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class OmniGraphNodeType(pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateOmniGraphCategoriesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOmniGraphDescriptionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOmniGraphNamespaceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOmniGraphTagsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOmniGraphUiNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphCategoriesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphDescriptionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphNamespaceAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphTagsAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOmniGraphUiNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class OutputDefAPI(pxr.Usd.APISchemaBase, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Apply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CanApply(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConnectionRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateDescriptionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateHiddenAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUiNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateUiTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAll(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConnectionRel(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetDescriptionAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetHiddenAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUiNameAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetUiTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def IsOmniGraphOutputDefAPIPath(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 56
    pass
class Tokens(Boost.Python.instance):
    OmniGraph = 'OmniGraph'
    OmniGraphAPI = 'OmniGraphAPI'
    OmniGraphCompoundNodeAPI = 'OmniGraphCompoundNodeAPI'
    OmniGraphCompoundNodeType = 'OmniGraphCompoundNodeType'
    OmniGraphCompoundNodeType_1 = 'OmniGraphCompoundNodeType_1'
    OmniGraphInputDefAPI = 'OmniGraphInputDefAPI'
    OmniGraphNode = 'OmniGraphNode'
    OmniGraphNodeType = 'OmniGraphNodeType'
    OmniGraphOutputDefAPI = 'OmniGraphOutputDefAPI'
    allowAutoInstancing = 'allowAutoInstancing'
    automatic = 'Automatic'
    dirty_push = 'dirty_push'
    evaluationMode = 'evaluationMode'
    evaluatorType = 'evaluator:type'
    execution = 'execution'
    fabricCacheBacking = 'fabricCacheBacking'
    fileFormatVersion = 'fileFormatVersion'
    function = 'function'
    instanced = 'Instanced'
    localNodes = 'local.nodes'
    nodeType = 'node:type'
    nodeTypeVersion = 'node:typeVersion'
    nodetype = 'nodetype'
    omniGraphAsset = 'omni:graph:asset'
    omniGraphCategories = 'omni:graph:categories'
    omniGraphCompoundGraph = 'omni:graph:compoundGraph'
    omniGraphCompoundType = 'omni:graph:compoundType'
    omniGraphDescription = 'omni:graph:description'
    omniGraphInputDef = 'omniGraphInputDef'
    omniGraphInputDef_MultipleApplyTemplate_AllowedTokens = 'omniGraphInputDef:__INSTANCE_NAME__:allowedTokens'
    omniGraphInputDef_MultipleApplyTemplate_Connection = 'omniGraphInputDef:__INSTANCE_NAME__:connection'
    omniGraphInputDef_MultipleApplyTemplate_Description = 'omniGraphInputDef:__INSTANCE_NAME__:description'
    omniGraphInputDef_MultipleApplyTemplate_Hidden = 'omniGraphInputDef:__INSTANCE_NAME__:hidden'
    omniGraphInputDef_MultipleApplyTemplate_LiteralOnly = 'omniGraphInputDef:__INSTANCE_NAME__:literalOnly'
    omniGraphInputDef_MultipleApplyTemplate_Type = 'omniGraphInputDef:__INSTANCE_NAME__:type'
    omniGraphInputDef_MultipleApplyTemplate_UiName = 'omniGraphInputDef:__INSTANCE_NAME__:uiName'
    omniGraphInputDef_MultipleApplyTemplate_UiType = 'omniGraphInputDef:__INSTANCE_NAME__:uiType'
    omniGraphNamespace = 'omni:graph:namespace'
    omniGraphOutputDef = 'omniGraphOutputDef'
    omniGraphOutputDef_MultipleApplyTemplate_Connection = 'omniGraphOutputDef:__INSTANCE_NAME__:connection'
    omniGraphOutputDef_MultipleApplyTemplate_Description = 'omniGraphOutputDef:__INSTANCE_NAME__:description'
    omniGraphOutputDef_MultipleApplyTemplate_Hidden = 'omniGraphOutputDef:__INSTANCE_NAME__:hidden'
    omniGraphOutputDef_MultipleApplyTemplate_Type = 'omniGraphOutputDef:__INSTANCE_NAME__:type'
    omniGraphOutputDef_MultipleApplyTemplate_UiName = 'omniGraphOutputDef:__INSTANCE_NAME__:uiName'
    omniGraphOutputDef_MultipleApplyTemplate_UiType = 'omniGraphOutputDef:__INSTANCE_NAME__:uiType'
    omniGraphTags = 'omni:graph:tags'
    omniGraphUiName = 'omni:graph:uiName'
    omniGraphs = 'omniGraphs'
    pipelineStage = 'pipelineStage'
    pipelineStageOnDemand = 'pipelineStageOnDemand'
    pipelineStagePostRender = 'pipelineStagePostRender'
    pipelineStagePreRender = 'pipelineStagePreRender'
    pipelineStageSimulation = 'pipelineStageSimulation'
    push = 'push'
    shared = 'Shared'
    stageWithHistory = 'StageWithHistory'
    stageWithoutHistory = 'StageWithoutHistory'
    standalone = 'Standalone'
    subgraph = 'subgraph'
    pass
class _CanApplyResult(Boost.Python.instance):
    @property
    def whyNot(self) -> None:
        """
        :type: None
        """
    __instance_size__ = 64
    pass
__MFB_FULL_PACKAGE_NAME = 'omniGraphSchema'
