from typing import AsyncIterator, Dict, List, Optional

from idl.connection.transport import Client
from idl.types import Literal, Record

from .data import *


class NGSearchService:
    def __init__(self, transport: Client):
        self.transport = transport

    async def __aenter__(self) -> "NGSearchService":
        await self.transport.prepare()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.transport.close()

    async def demo_test(self, input: Optional[str] = None) -> DataContent:
        """
        Ping-like method to test the availability of the service.

        @param {string} input optional input that is passed to the service,
        which is then logged to stdout on the service side and returned back to
        the client.
        @returns unchanged input from the client.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: DataContent = await client.demo_test("test request")
        >>> response.data == "test request"
        ```
        """
        _request = {}
        if input is not None:
            _request["input"] = input
        _response = await self.transport.call(
            "NGSearchService", "demo_test", _request, request_type=NgsearchServiceDemoTestArgs, return_type=DataContent
        )
        return _response

    async def datasource_info(
        self,
    ) -> Datasource:
        """
        Get information about the index, where the data is stored.

        @returns index statistics

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: Datasource = await client.datasource_info()
        ```
        """
        _request = {}
        _response = await self.transport.call(
            "NGSearchService",
            "datasource_info",
            _request,
            request_type=NgsearchServiceDatasourceInfoArgs,
            return_type=Datasource,
        )
        return _response

    async def find(
        self, query: SearchQuery, token: str, telemetry_context: Optional[TelemetryContext] = None
    ) -> AsyncIterator[Path]:
        """
        Asynchronous generator function that returns Paths to assets in Nucleus
        (with metadata) that matching the search query.

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery} query search terms, tag list (not used), and
        parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @returns assets in Nucleus that best match the input query (in the
        generator fashion).

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> res: Path
        >>> async for res in client.find(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>
        >>> ):
        >>>     ...
        ```
        """
        _request = {}
        _request["version"] = NGSearchServiceFindClientVersion
        _request["query"] = query
        _request["token"] = token
        if telemetry_context is not None:
            _request["telemetry_context"] = telemetry_context
        agen = self.transport.call_many(
            "NGSearchService", "find", _request, request_type=NgsearchServiceFindArgs, return_type=Path
        )
        try:
            async for _response in agen:
                yield _response
        finally:
            await agen.aclose()

    async def find2(
        self, query: SearchQuery, token: str, telemetry_context: Optional[TelemetryContext] = None
    ) -> SearchResult:
        """
        Asynchronous function that works the same as find method, but returns
        all the results together as a list. Together with the list of paths to
        assets the function returns the status of the operation (of type
        StatusType).

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery} query search terms, tag list (not used), and
        parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @returns assets in Nucleus that best match the input query (as a list
        of results).

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: SearchResult = await client.find2(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>
        >>> )
        >>> paths = response.paths
        ```
        At version 3
        - In request parameters: optional "format" argument was added.
        """
        _request = {}
        _request["version"] = NGSearchServiceFind2ClientVersion
        _request["query"] = query
        _request["token"] = token
        if telemetry_context is not None:
            _request["telemetry_context"] = telemetry_context
        _response = await self.transport.call(
            "NGSearchService", "find2", _request, request_type=NgsearchServiceFind2Args, return_type=SearchResult
        )
        return _response

    async def find_paged_cursor(
        self,
        query: SearchQuery2,
        token: Optional[str] = None,
        size: Optional[float] = None,
        cursor_id: Optional[str] = None,
    ) -> SearchResultCursor:
        """
        Asynchronous function that implements paginated search with a cursor
        and returns results in batches.

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery2} query search terms and parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @param {number} size number of elements that need to be returned in a
        single batch
        @param {string} cursor_id If not provided or None - initiate a new
        search, otherwise continue retrieving results from the already executed
        search (must be the same cursor_id from SearchResultCursor)
        @returns assets in Nucleus that best match the input query.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> first_batch = await client.find_paged_cursor(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>, size=5
        >>> )
        >>> second_batch = await client.find_paged_cursor(
        >>>     query={"parent": "/", "query": '"magical spoon"'},
        >>>     token=<user access token>,
        >>>     cursor_id=first_batch.cursor_id,
        >>> )
        ```

        At version 2
        - In request parameters: optional "format" argument was added.
        """
        _request = {}
        _request["version"] = NGSearchServiceFindPagedCursorClientVersion
        _request["query"] = query
        if token is not None:
            _request["token"] = token
        if size is not None:
            _request["size"] = size
        if cursor_id is not None:
            _request["cursor_id"] = cursor_id
        _response = await self.transport.call(
            "NGSearchService",
            "find_paged_cursor",
            _request,
            request_type=NgsearchServiceFindPagedCursorArgs,
            return_type=SearchResultCursor,
        )
        return _response

    async def find_paged_skip(
        self,
        query: SearchQuery2,
        token: Optional[str] = None,
        size: Optional[float] = None,
        skip_first: Optional[float] = None,
    ) -> SearchResult:
        """
        Asynchronous function that implements paginated search by skipping
        first N results and returns results in batches (this is inefficient, as
        new search is initiated on every request, and find_paged_cursor method
        should be used instead, but it exists to match Nucleus Search service
        APIs).

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery2} query search terms and parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @param {number} size number of elements that need to be returned in a
        single batch
        @param {string} skip_first number of elements that need to be skipped
        from the beginning of the search.
        @returns assets in Nucleus that best match the input query.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> first_batch = await client.find_paged_skip(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>, size=5
        >>> )
        >>> second_batch = await client.find_paged_skip(
        >>>     query={"parent": "/", "query": '"magical spoon"'},
        >>>     size=5,
        >>>     token=<user access token>,
        >>>     skip_first=5,
        >>> )
        ```
        At version 2
        - In request parameters: optional "format" argument was added.
        """
        _request = {}
        _request["version"] = NGSearchServiceFindPagedSkipClientVersion
        _request["query"] = query
        if token is not None:
            _request["token"] = token
        if size is not None:
            _request["size"] = size
        if skip_first is not None:
            _request["skip_first"] = skip_first
        _response = await self.transport.call(
            "NGSearchService",
            "find_paged_skip",
            _request,
            request_type=NgsearchServiceFindPagedSkipArgs,
            return_type=SearchResult,
        )
        return _response

    async def get_prefixes(
        self,
    ) -> PrefixResult:
        """
        Asynchronous function that returns a list of supported prefixes.

        @param {ClientVersion} version - version of the client that connects to
        the service (populated automatically)
        @returns list of prefixes that service supports.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: PrefixResult = await client.get_prefixes()
        >>> prefixes = response.prefixes
        ```
        """
        _request = {}
        _request["version"] = NGSearchServiceGetPrefixesClientVersion
        _response = await self.transport.call(
            "NGSearchService",
            "get_prefixes",
            _request,
            request_type=NgsearchServiceGetPrefixesArgs,
            return_type=PrefixResult,
        )
        return _response

    async def search(
        self,
        query: Optional[str] = None,
        n: Optional[float] = None,
        filter_repeating: Optional[bool] = None,
        filter_by_path: Optional[str] = None,
        filter_by_ext: Optional[List[str]] = None,
        kw_must: Optional[List[str]] = None,
        kw_must_not: Optional[List[str]] = None,
        return_predictions: Optional[bool] = None,
        return_images: Optional[bool] = None,
        return_embeddings: Optional[bool] = None,
        similarity_threshold: Optional[float] = None,
        search_config: Optional[SearchConfig] = None,
        scroll: Optional[bool] = None,
        token: Optional[str] = None,
        only_key: Optional[bool] = None,
    ) -> Results:
        """
        Asynchronous function to search for assets in Nucleus given an input
        query. Together with asset paths it is able to return additional
        information (e.g. previews of assets, from which embeddings were
        generated, predictions for the embeddings and embeddings themselves).

        This function returns all the assets that it find in a single message,
        which can be limited, depending on the transport that the service is
        using (e.g. websockets, http).

        @param {string} query Input text query that can be text or base64
        encoded image
        @param {number} n Number of paths that need to be returned (if set to
        -1 will return all the paths)
        @param {string} filter_by_path path by which the response should be
        filtered (default: None)
        @param {string[]} filter_by_ext filter by path extension (default: None)
        @param {string[]} kw_must must include keyword (default: None)
        @param {string[]} kw_must_not must not include keyword (default: None)
        @param {boolean} return_predictions if true - additional return
        prediction (default: false)
        @param {boolean} return_images if true - additional return images
        (default: false)
        @param {boolean} return_embeddings if true - return embeddings
        (default: false)
        @param {number} similarity_threshold filter out similar results
        (default: 0.0)
        @param {string} token user authentication token
        @param {boolean} only_key if true - optimize the processing to request
        minimal information from ES. In this case return_images and
        return_embedding options are unavailable (default: false)
        @returns assets from Nucleus that best describe the input query (all
        the results are returned in a single message).

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> first_batch = await client.search(
        >>>     "sample query",
        >>>     filter_by_path="/",
        >>>     search_config=SearchConfig(method=SearchMethod.exact)
        >>> )
        ```
        """
        _request = {}
        if query is not None:
            _request["query"] = query
        if n is not None:
            _request["n"] = n
        if filter_repeating is not None:
            _request["filter_repeating"] = filter_repeating
        if filter_by_path is not None:
            _request["filter_by_path"] = filter_by_path
        if filter_by_ext is not None:
            _request["filter_by_ext"] = filter_by_ext
        if kw_must is not None:
            _request["kw_must"] = kw_must
        if kw_must_not is not None:
            _request["kw_must_not"] = kw_must_not
        if return_predictions is not None:
            _request["return_predictions"] = return_predictions
        if return_images is not None:
            _request["return_images"] = return_images
        if return_embeddings is not None:
            _request["return_embeddings"] = return_embeddings
        if similarity_threshold is not None:
            _request["similarity_threshold"] = similarity_threshold
        if search_config is not None:
            _request["search_config"] = search_config
        if scroll is not None:
            _request["scroll"] = scroll
        if token is not None:
            _request["token"] = token
        if only_key is not None:
            _request["only_key"] = only_key
        _response = await self.transport.call(
            "NGSearchService", "search", _request, request_type=NgsearchServiceSearchArgs, return_type=Results
        )
        return _response

    async def scroll(self, scroll_id: str, n: Optional[float] = None) -> Results:
        """
        Asynchronous function that allows doing pagination of results and
        continue retrieving items for the same input query when the search was
        already executed.

        @param {string} scroll_id ID of the search that was already executed
        @param {number} n Number of paths that need to be returned (if set to
        -1 will return all the paths)
        @returns more results for a given search request instance (all the
        results a returned in a single message)

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> first_batch = await client.search("sample query", scroll=True)
        >>> second_batch = await client.scroll(first_batch.scroll_id)
        ```
        """
        _request = {}
        _request["scroll_id"] = scroll_id
        if n is not None:
            _request["n"] = n
        _response = await self.transport.call(
            "NGSearchService", "scroll", _request, request_type=NgsearchServiceScrollArgs, return_type=Results
        )
        return _response

    async def search_gen(
        self,
        query: Optional[str] = None,
        n: Optional[float] = None,
        filter_repeating: Optional[bool] = None,
        filter_by_path: Optional[str] = None,
        filter_by_ext: Optional[List[str]] = None,
        kw_must: Optional[List[str]] = None,
        kw_must_not: Optional[List[str]] = None,
        return_predictions: Optional[bool] = None,
        return_images: Optional[bool] = None,
        return_embeddings: Optional[bool] = None,
        similarity_threshold: Optional[float] = None,
        search_config: Optional[SearchConfig] = None,
        token: Optional[str] = None,
        batch_size: Optional[float] = None,
        only_key: Optional[bool] = None,
    ) -> AsyncIterator[Item]:
        """
        Asynchronous function that implements the same functionality as search
        method, but instead of returning all the results in a single message -
        returns a generator that emits results in batches.

        @param {string} query Input text query that can be text or base64
        encoded image
        @param {number} n Number of paths that need to be returned (if set to
        -1 will return all the paths)
        @param {string} filter_by_path path by which the response should be
        filtered (default: None)
        @param {string[]} filter_by_ext filter by path extension (default: None)
        @param {string[]} kw_must must include keyword (default: None)
        @param {string[]} kw_must_not must not include keyword (default: None)
        @param {boolean} return_predictions if true - additional return
        prediction (default: false)
        @param {boolean} return_images if true - additional return images
        (default: false)
        @param {boolean} return_embeddings if true - return embeddings
        (default: false)
        @param {number} similarity_threshold filter out similar results
        (default: 0.0)
        @param {string} token user authentication token
        @param {number} batch_size number of results requested from ES at once
        (default: 5)
        @param {boolean} only_key if true - optimize the processing to request
        minimal information from ES. In this case return_images and
        return_embedding options are unavailable (default: false)
        @returns generator of results in batches

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> r: Item
        >>> async for r in client.search_gen(
        >>>     "car",
        >>>     filter_by_path="/",
        >>>     return_embeddings=True,
        >>>     return_images=True,
        >>>     token=<user access token>,
        >>>     n=-1,
        >>>     batch_size=5,
        >>> ):
        >>>     ...
        ```
        """
        _request = {}
        if query is not None:
            _request["query"] = query
        if n is not None:
            _request["n"] = n
        if filter_repeating is not None:
            _request["filter_repeating"] = filter_repeating
        if filter_by_path is not None:
            _request["filter_by_path"] = filter_by_path
        if filter_by_ext is not None:
            _request["filter_by_ext"] = filter_by_ext
        if kw_must is not None:
            _request["kw_must"] = kw_must
        if kw_must_not is not None:
            _request["kw_must_not"] = kw_must_not
        if return_predictions is not None:
            _request["return_predictions"] = return_predictions
        if return_images is not None:
            _request["return_images"] = return_images
        if return_embeddings is not None:
            _request["return_embeddings"] = return_embeddings
        if similarity_threshold is not None:
            _request["similarity_threshold"] = similarity_threshold
        if search_config is not None:
            _request["search_config"] = search_config
        if token is not None:
            _request["token"] = token
        if batch_size is not None:
            _request["batch_size"] = batch_size
        if only_key is not None:
            _request["only_key"] = only_key
        agen = self.transport.call_many(
            "NGSearchService", "search_gen", _request, request_type=NgsearchServiceSearchGenArgs, return_type=Item
        )
        try:
            async for _response in agen:
                yield _response
        finally:
            await agen.aclose()

    async def list_searchable_keywords(
        self,
        filter_by_path: Optional[str] = None,
        filter_by_ext: Optional[List[str]] = None,
        kw_must: Optional[List[str]] = None,
        kw_must_not: Optional[List[str]] = None,
    ) -> KeywordList:
        """
        Asynchronous function that returns a list of keywords that are
        available for searching. These keywords can be defined per embedding
        and typically contain the information about the model that was used to
        compute embeddings from asset previews.

        @param {string} filter_by_path path by which the response should be
        filtered (default: None)
        @param {string[]} filter_by_ext filter by path extension (default: None)
        @param {string[]} kw_must must include keyword (default: None)
        @param {string[]} kw_must_not must not include keyword (default: None)
        @returns list of keywords that can be used for filtering search results
        """
        _request = {}
        if filter_by_path is not None:
            _request["filter_by_path"] = filter_by_path
        if filter_by_ext is not None:
            _request["filter_by_ext"] = filter_by_ext
        if kw_must is not None:
            _request["kw_must"] = kw_must
        if kw_must_not is not None:
            _request["kw_must_not"] = kw_must_not
        _response = await self.transport.call(
            "NGSearchService",
            "list_searchable_keywords",
            _request,
            request_type=NgsearchServiceListSearchableKeywordsArgs,
            return_type=KeywordList,
        )
        return _response

    async def get_predictions(self, query: str) -> PredictionList:
        """
        Asynchronous function that computes predictions for an input query.
        Predictions are computed as top 5 matches between the embedding of the
        input query and a database of object hierarchy (taken from WordNet
        dataset).

        @remarks
        Requires DeepSearch service to be available on the Nucleus instance.

        @param {string} query: input query that needs to be converted to
        embedding and for which predictions need to be computed
        @returns list of predictions for the input query

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: PredictionList = await client.get_predictions("pizza box")
        >>> predictions = response.predictions
        ```
        """
        _request = {}
        _request["query"] = query
        _response = await self.transport.call(
            "NGSearchService",
            "get_predictions",
            _request,
            request_type=NgsearchServiceGetPredictionsArgs,
            return_type=PredictionList,
        )
        return _response

    async def get_embeddings(self, query_list: List[str]) -> DataItems:
        """
        Asynchronous function that returns the list of embeddings for a list of
        input queries.

        @remarks
        Requires DeepSearch service to be available on the Nucleus instance

        @param {string[]} query_list: list of input querries that need to be
        converted to embeddings
        @returns list of embeddings for the input list of queries

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: DataItems = await client.get_embeddings(["pizza box",
        "pizza", "box"])
        >>> embeddings = [emb.data for emb in response.data]
        ```

        This code will provide with serialized embeddings. You can them use
        any_from_string function provided as part of the python client for
        desialization of results.

        ```
        >>> embeddings = [any_from_string(e) for e in embeddings]
        ```
        """
        _request = {}
        _request["query_list"] = query_list
        _response = await self.transport.call(
            "NGSearchService",
            "get_embeddings",
            _request,
            request_type=NgsearchServiceGetEmbeddingsArgs,
            return_type=DataItems,
        )
        return _response

    async def search_gen_2(
        self,
        query: SearchQuery2,
        token: str,
        return_predictions: Optional[bool] = None,
        return_images: Optional[bool] = None,
        return_embeddings: Optional[bool] = None,
        return_projections: Optional[bool] = None,
        similarity_threshold: Optional[float] = None,
        search_config: Optional[SearchConfig] = None,
        projection_config: Optional[ProjectionConfig] = None,
        batch_size: Optional[float] = None,
        telemetry_context: Optional[TelemetryContext] = None,
        max_pages: Optional[int] = None,
    ) -> AsyncIterator[BatchedSearchItem]:
        """
        Asynchronous generator function that returns search results in batches.
        The main different with search_gen method is that this method relies on
        the input query that is the same as for find2 method, which is commonly
        used in Nucleus Search service.

        @param {ClientVersion} version version of the client that is connecting
        to the service (populated automatically)
        @param {SearchQuery2} query input query, which is then transformed to a
        query for Elastic Search service backend.
        @param {string} token user access token to Nucleus. This token is used
        for verification of user acccess to assets in Nucleus.
        @param {boolean} return_predictions return predictions together with
        search results
        @param {boolean} return_images return asset previews together with
        search results from which CLIP embeddings were generated
        @param {boolean} return_embeddings return CLIP embeddings together with
        search results
        @param {boolean} return_projections return projections of CLIP
        embeddings into a lower dimentional space
        @param {number} similarity_threshold filter out those assets that have
        CLIP embedding similarity higher than a given value
        @param {SearchConfig} search_config search request configuration
        parameters
        @param {number} batch_size number of elements that are returned as a
        single batch
        @param {TelemetryContext} telemetry_context Additional request context
        for telemetry purposes
        @param {number} max_pages Maximum number of pages to fetch

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> res: BatchedSearchItem
        >>> async for res in client.search_gen_2(
        >>>     query=SearchQuery2(parent="/", query="some input query"),
        >>>     search_config=SearchConfig(method="exact"),
        >>>     token=<user access token>,
        >>> ):
        >>>     ...
        ```
        """
        _request = {}
        _request["version"] = NGSearchServiceSearchGen2ClientVersion
        _request["query"] = query
        _request["token"] = token
        if return_predictions is not None:
            _request["return_predictions"] = return_predictions
        if return_images is not None:
            _request["return_images"] = return_images
        if return_embeddings is not None:
            _request["return_embeddings"] = return_embeddings
        if return_projections is not None:
            _request["return_projections"] = return_projections
        if similarity_threshold is not None:
            _request["similarity_threshold"] = similarity_threshold
        if search_config is not None:
            _request["search_config"] = search_config
        if projection_config is not None:
            _request["projection_config"] = projection_config
        if batch_size is not None:
            _request["batch_size"] = batch_size
        if telemetry_context is not None:
            _request["telemetry_context"] = telemetry_context
        if max_pages is not None:
            _request["max_pages"] = max_pages
        agen = self.transport.call_many(
            "NGSearchService",
            "search_gen_2",
            _request,
            request_type=NgsearchServiceSearchGen2Args,
            return_type=BatchedSearchItem,
        )
        try:
            async for _response in agen:
                yield _response
        finally:
            await agen.aclose()

    async def get_embedding_hierarchy(
        self,
        query: SearchQuery2,
        token: str,
        return_predictions: Optional[bool] = None,
        return_images: Optional[bool] = None,
        return_embeddings: Optional[bool] = None,
        return_projections: Optional[bool] = None,
        similarity_threshold: Optional[float] = None,
        search_config: Optional[SearchConfig] = None,
        clustering_config: Optional[ClusteringConfig] = None,
        telemetry_context: Optional[TelemetryContext] = None,
    ) -> EmbeddingHierarchy:
        """
        For a given batch of samples - get embeddings organized in a
        hierarchial structure that can be visualized by the UI.

        @param {ClientVersion} version version of the client that is connecting
        to the service (populated automatically)
        @param {SearchQuery2} query input query, which is then transformed to a
        query for Elastic Search service backend.
        @param {string} token user access token to Nucleus. This token is used
        for verification of user acccess to assets in Nucleus.
        @param {boolean} return_images return asset previews together with
        search results from which CLIP embeddings were generated
        @param {number} similarity_threshold filter out those assets that have
        CLIP embedding similarity higher than a given value
        @param {SearchConfig} search_config search request configuration
        parameters
        @param {ClusteringConfig} clustering_config clustering configuration
        parameters
        @param {TelemetryContext} telemetry_context Additional request context
        for telemetry purposes

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> res: BatchedSearchItem
        >>> res = await client.get_embedding_hierarchy(
        >>>     query=SearchQuery2(parent="/", query="some input query"),
        >>>     search_config=SearchConfig(method="exact"),
        >>>     token=<user access token>,
        >>> ):
        >>>     ...
        ```
        """
        _request = {}
        _request["version"] = NGSearchServiceGetEmbeddingHierarchyClientVersion
        _request["query"] = query
        _request["token"] = token
        if return_predictions is not None:
            _request["return_predictions"] = return_predictions
        if return_images is not None:
            _request["return_images"] = return_images
        if return_embeddings is not None:
            _request["return_embeddings"] = return_embeddings
        if return_projections is not None:
            _request["return_projections"] = return_projections
        if similarity_threshold is not None:
            _request["similarity_threshold"] = similarity_threshold
        if search_config is not None:
            _request["search_config"] = search_config
        if clustering_config is not None:
            _request["clustering_config"] = clustering_config
        if telemetry_context is not None:
            _request["telemetry_context"] = telemetry_context
        _response = await self.transport.call(
            "NGSearchService",
            "get_embedding_hierarchy",
            _request,
            request_type=NgsearchServiceGetEmbeddingHierarchyArgs,
            return_type=EmbeddingHierarchy,
        )
        return _response

    async def compute_hierarchical_clustering(
        self,
        serialized_embeddings_with_scores: str,
        clustering_config: Optional[ClusteringConfig] = None,
        telemetry_context: Optional[TelemetryContext] = None,
        token: Optional[str] = None,
    ) -> HierarchicalClustering:
        """
        Compute hierarchical clustering for a given list of embeddings with
        respective scores

        @param {ClientVersion} version version of the client that is connecting
        to the service (populated automatically)
        @param {ClusteringConfig} clustering_config clustering configuration
        parameters
        @param {TelemetryContext} telemetry_context Additional request context
        for telemetry purposes
        @param {string} token user access token to Nucleus. This token is used
        for verification of user acccess to assets in Nucleus.
        """
        _request = {}
        _request["version"] = NGSearchServiceComputeHierarchicalClusteringClientVersion
        _request["serialized_embeddings_with_scores"] = serialized_embeddings_with_scores
        if clustering_config is not None:
            _request["clustering_config"] = clustering_config
        if telemetry_context is not None:
            _request["telemetry_context"] = telemetry_context
        if token is not None:
            _request["token"] = token
        _response = await self.transport.call(
            "NGSearchService",
            "compute_hierarchical_clustering",
            _request,
            request_type=NgsearchServiceComputeHierarchicalClusteringArgs,
            return_type=HierarchicalClustering,
        )
        return _response

    async def telemetry_event_click(
        self,
        query: str,
        token: str,
        n: int,
        n_results_total: int,
        asset_id: str,
        asset_rank: int,
        click_order: int,
        time_to_present: float,
        time_to_click: float,
        query_time: float,
        search_request_id: str,
        telemetry_context: TelemetryContext,
    ) -> StatusOnlyResponse:
        """
        Telemetry event sent when user clicks on a search result item.

        @param {string} query search query
        @param {string} token user authentication token
        @param {number} n Number of paths requested
        @param {number} n_results_total Total number of results returned up to
        click event
        @param {string} asset_id The ID of the asset on which user has clicked
        @param {number} asset_rank The rank of the asset in search results
        @param {number} click_order Order number of the click in a given search
        request; must start with 1
        @param {number} time_to_present Time in seconds between user initiating
        the search and the results being shown
        @param {number} time_to_click Time in seconds between showing results
        and clicking
        @param {number} query_time NGSearch response time in seconds
        @param {string} search_request_id search_request_id of the associated
        search request
        @param {TelemetryContext} telemetry_context Telemetry context
        """
        _request = {}
        _request["query"] = query
        _request["token"] = token
        _request["n"] = n
        _request["n_results_total"] = n_results_total
        _request["asset_id"] = asset_id
        _request["asset_rank"] = asset_rank
        _request["click_order"] = click_order
        _request["time_to_present"] = time_to_present
        _request["time_to_click"] = time_to_click
        _request["query_time"] = query_time
        _request["search_request_id"] = search_request_id
        _request["telemetry_context"] = telemetry_context
        _response = await self.transport.call(
            "NGSearchService",
            "telemetry_event_click",
            _request,
            request_type=NgsearchServiceTelemetryEventClickArgs,
            return_type=StatusOnlyResponse,
        )
        return _response

    async def telemetry_event_results_presented(
        self,
        query: str,
        token: str,
        n: int,
        n_results_total: int,
        time_to_present: float,
        query_time: float,
        thumbnail_load_time: List[float],
        search_request_id: str,
        telemetry_context: TelemetryContext,
    ) -> StatusOnlyResponse:
        """
        Telemetry event sent when search results are shown to the user.

        @param {string} query search query
        @param {string} token user authentication token
        @param {number} n Number of paths requested
        @param {number} n_results_total Total number of results returned
        @param {number} time_to_present Time in seconds between user initiating
        the search and the results being shown
        @param {number} query_time NGSearch response time in seconds
        @param {number[]} thumbnail_load_time Array of load times for
        individual thumbnails in seconds
        @param {string} search_request_id search_request_id of the associated
        search request
        @param {TelemetryContext} telemetry_context Telemetry context
        """
        _request = {}
        _request["query"] = query
        _request["token"] = token
        _request["n"] = n
        _request["n_results_total"] = n_results_total
        _request["time_to_present"] = time_to_present
        _request["query_time"] = query_time
        _request["thumbnail_load_time"] = thumbnail_load_time
        _request["search_request_id"] = search_request_id
        _request["telemetry_context"] = telemetry_context
        _response = await self.transport.call(
            "NGSearchService",
            "telemetry_event_results_presented",
            _request,
            request_type=NgsearchServiceTelemetryEventResultsPresentedArgs,
            return_type=StatusOnlyResponse,
        )
        return _response

    async def livez(
        self,
    ) -> LivezResponse:
        """ """
        _request = {}
        _response = await self.transport.call(
            "NGSearchService", "livez", _request, request_type=NgsearchServiceLivezArgs, return_type=LivezResponse
        )
        return _response

    async def readyz(
        self,
    ) -> ReadyzResponse:
        """ """
        _request = {}
        _response = await self.transport.call(
            "NGSearchService", "readyz", _request, request_type=NgsearchServiceReadyzArgs, return_type=ReadyzResponse
        )
        return _response

    __interface_name__ = "NGSearchService"
    __interface_origin__ = "Search.idl.ts"
    __interface_capabilities__ = NGSearchServiceClientLocalCapabilities


class Search:
    def __init__(self, transport: Client):
        self.transport = transport

    async def __aenter__(self) -> "Search":
        await self.transport.prepare()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        await self.transport.close()

    async def find(self, query: SearchQuery, token: str) -> AsyncIterator[Path]:
        """
        Asynchronous generator function that returns Paths to assets in Nucleus
        (with metadata) that matching the search query.

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery} query search terms, tag list (not used), and
        parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @returns assets in Nucleus that best match the input query (in the
        generator fashion).

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> res: Path
        >>> async for res in client.find(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>
        >>> ):
        >>>     ...
        ```
        """
        _request = {}
        _request["version"] = SearchFindClientVersion
        _request["query"] = query
        _request["token"] = token
        agen = self.transport.call_many("Search", "find", _request, request_type=SearchFindArgs, return_type=Path)
        try:
            async for _response in agen:
                yield _response
        finally:
            await agen.aclose()

    async def find2(self, query: SearchQuery, token: str) -> SearchResult:
        """
        Asynchronous function that works the same as find method, but returns
        all the results together as a list. Together with the list of paths to
        assets the function returns the status of the operation (of type
        StatusType).

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery} query search terms, tag list (not used), and
        parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @returns assets in Nucleus that best match the input query (as a list
        of results).

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: SearchResult = await client.find2(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>
        >>> )
        >>> paths = response.paths
        ```
        At version 3
        - In request parameters: optional "format" argument was added.
        """
        _request = {}
        _request["version"] = SearchFind2ClientVersion
        _request["query"] = query
        _request["token"] = token
        _response = await self.transport.call(
            "Search", "find2", _request, request_type=SearchFind2Args, return_type=SearchResult
        )
        return _response

    async def find_paged_cursor(
        self,
        query: SearchQuery2,
        token: Optional[str] = None,
        size: Optional[float] = None,
        cursor_id: Optional[str] = None,
    ) -> SearchResultCursor:
        """
        Asynchronous function that implements paginated search with a cursor
        and returns results in batches.

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery2} query search terms and parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @param {number} size number of elements that need to be returned in a
        single batch
        @param {string} cursor_id If not provided or None - initiate a new
        search, otherwise continue retrieving results from the already executed
        search (must be the same cursor_id from SearchResultCursor)
        @returns assets in Nucleus that best match the input query.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> first_batch = await client.find_paged_cursor(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>, size=5
        >>> )
        >>> second_batch = await client.find_paged_cursor(
        >>>     query={"parent": "/", "query": '"magical spoon"'},
        >>>     token=<user access token>,
        >>>     cursor_id=first_batch.cursor_id,
        >>>
        ```
        At version 2
        - In request parameters: optional "format" argument was added.
        """
        _request = {}
        _request["version"] = SearchFindPagedCursorClientVersion
        _request["query"] = query
        if token is not None:
            _request["token"] = token
        if size is not None:
            _request["size"] = size
        if cursor_id is not None:
            _request["cursor_id"] = cursor_id
        _response = await self.transport.call(
            "Search",
            "find_paged_cursor",
            _request,
            request_type=SearchFindPagedCursorArgs,
            return_type=SearchResultCursor,
        )
        return _response

    async def find_paged_skip(
        self,
        query: SearchQuery2,
        token: Optional[str] = None,
        size: Optional[float] = None,
        skip_first: Optional[float] = None,
    ) -> SearchResult:
        """
        Asynchronous function that implements paginated search by skipping
        first N results and returns results in batches (this is inefficient, as
        new search is initiated on every request, and find_paged_cursor method
        should be used instead, but it exists to match Nucleus Search service
        APIs).

        @param {ClientVersion} version version of the client that is being
        connected to the service (populated automatically)
        @param {SearchQuery2} query search terms and parent folder of search.
        @param {string} token user authentication token that is used for
        verification of user access for each returned asset path
        @param {number} size number of elements that need to be returned in a
        single batch
        @param {string} skip_first number of elements that need to be skipped
        from the beginning of the search.
        @returns assets in Nucleus that best match the input query.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> first_batch = await client.find_paged_skip(
        >>>     query={"parent": "/", "query": '"magical spoon"'}, token=<user
        access token>, size=5
        >>> )
        >>> second_batch = await client.find_paged_skip(
        >>>     query={"parent": "/", "query": '"magical spoon"'},
        >>>     size=5,
        >>>     token=<user access token>,
        >>>     skip_first=5,
        >>> )
        ```
        At version 2
        - In request parameters: optional "format" argument was added.
        """
        _request = {}
        _request["version"] = SearchFindPagedSkipClientVersion
        _request["query"] = query
        if token is not None:
            _request["token"] = token
        if size is not None:
            _request["size"] = size
        if skip_first is not None:
            _request["skip_first"] = skip_first
        _response = await self.transport.call(
            "Search", "find_paged_skip", _request, request_type=SearchFindPagedSkipArgs, return_type=SearchResult
        )
        return _response

    async def get_prefixes(
        self,
    ) -> PrefixResult:
        """
        Asynchronous function that returns a list of supported prefixes.

        @param {ClientVersion} version - version of the client that connects to
        the service (populated automatically)
        @returns list of prefixes that service supports.

        @example
        Sample function usage from the python autogenerated client.
        ```
        >>> response: PrefixResult = await client.get_prefixes()
        >>> prefixes = response.prefixes
        ```
        """
        _request = {}
        _request["version"] = SearchGetPrefixesClientVersion
        _response = await self.transport.call(
            "Search", "get_prefixes", _request, request_type=SearchGetPrefixesArgs, return_type=PrefixResult
        )
        return _response

    __interface_name__ = "Search"
    __interface_origin__ = "Search.idl.ts"
    __interface_capabilities__ = SearchClientLocalCapabilities


class NgsearchServiceDemoTestArgs(Record):
    input: Optional[str]


class NgsearchServiceDatasourceInfoArgs(Record):
    pass


class NgsearchServiceFindArgs(Record):
    version: Literal(NGSearchServiceFindClientVersion) = NGSearchServiceFindClientVersion
    query: SearchQuery
    token: str
    telemetry_context: Optional[TelemetryContext]


class NgsearchServiceFind2Args(Record):
    version: Literal(NGSearchServiceFind2ClientVersion) = NGSearchServiceFind2ClientVersion
    query: SearchQuery
    token: str
    telemetry_context: Optional[TelemetryContext]


class NgsearchServiceFindPagedCursorArgs(Record):
    version: Literal(NGSearchServiceFindPagedCursorClientVersion) = NGSearchServiceFindPagedCursorClientVersion
    query: SearchQuery2
    token: Optional[str]
    size: Optional[float]
    cursor_id: Optional[str]


class NgsearchServiceFindPagedSkipArgs(Record):
    version: Literal(NGSearchServiceFindPagedSkipClientVersion) = NGSearchServiceFindPagedSkipClientVersion
    query: SearchQuery2
    token: Optional[str]
    size: Optional[float]
    skip_first: Optional[float]


class NgsearchServiceGetPrefixesArgs(Record):
    version: Literal(NGSearchServiceGetPrefixesClientVersion) = NGSearchServiceGetPrefixesClientVersion


class NgsearchServiceSearchArgs(Record):
    query: Optional[str]
    n: Optional[float]
    filter_repeating: Optional[bool]
    filter_by_path: Optional[str]
    filter_by_ext: Optional[List[str]]
    kw_must: Optional[List[str]]
    kw_must_not: Optional[List[str]]
    return_predictions: Optional[bool]
    return_images: Optional[bool]
    return_embeddings: Optional[bool]
    similarity_threshold: Optional[float]
    search_config: Optional[SearchConfig]
    scroll: Optional[bool]
    token: Optional[str]
    only_key: Optional[bool]


class NgsearchServiceScrollArgs(Record):
    scroll_id: str
    n: Optional[float]


class NgsearchServiceSearchGenArgs(Record):
    query: Optional[str]
    n: Optional[float]
    filter_repeating: Optional[bool]
    filter_by_path: Optional[str]
    filter_by_ext: Optional[List[str]]
    kw_must: Optional[List[str]]
    kw_must_not: Optional[List[str]]
    return_predictions: Optional[bool]
    return_images: Optional[bool]
    return_embeddings: Optional[bool]
    similarity_threshold: Optional[float]
    search_config: Optional[SearchConfig]
    token: Optional[str]
    batch_size: Optional[float]
    only_key: Optional[bool]


class NgsearchServiceListSearchableKeywordsArgs(Record):
    filter_by_path: Optional[str]
    filter_by_ext: Optional[List[str]]
    kw_must: Optional[List[str]]
    kw_must_not: Optional[List[str]]


class NgsearchServiceGetPredictionsArgs(Record):
    query: str


class NgsearchServiceGetEmbeddingsArgs(Record):
    query_list: List[str]


class NgsearchServiceSearchGen2Args(Record):
    version: Literal(NGSearchServiceSearchGen2ClientVersion) = NGSearchServiceSearchGen2ClientVersion
    query: SearchQuery2
    token: str
    return_predictions: Optional[bool]
    return_images: Optional[bool]
    return_embeddings: Optional[bool]
    return_projections: Optional[bool]
    similarity_threshold: Optional[float]
    search_config: Optional[SearchConfig]
    projection_config: Optional[ProjectionConfig]
    batch_size: Optional[float]
    telemetry_context: Optional[TelemetryContext]
    max_pages: Optional[int]


class NgsearchServiceGetEmbeddingHierarchyArgs(Record):
    version: Literal(
        NGSearchServiceGetEmbeddingHierarchyClientVersion
    ) = NGSearchServiceGetEmbeddingHierarchyClientVersion
    query: SearchQuery2
    token: str
    return_predictions: Optional[bool]
    return_images: Optional[bool]
    return_embeddings: Optional[bool]
    return_projections: Optional[bool]
    similarity_threshold: Optional[float]
    search_config: Optional[SearchConfig]
    clustering_config: Optional[ClusteringConfig]
    telemetry_context: Optional[TelemetryContext]


class NgsearchServiceComputeHierarchicalClusteringArgs(Record):
    version: Literal(
        NGSearchServiceComputeHierarchicalClusteringClientVersion
    ) = NGSearchServiceComputeHierarchicalClusteringClientVersion
    serialized_embeddings_with_scores: str
    clustering_config: Optional[ClusteringConfig]
    telemetry_context: Optional[TelemetryContext]
    token: Optional[str]


class NgsearchServiceTelemetryEventClickArgs(Record):
    query: str
    token: str
    n: int
    n_results_total: int
    asset_id: str
    asset_rank: int
    click_order: int
    time_to_present: float
    time_to_click: float
    query_time: float
    search_request_id: str
    telemetry_context: TelemetryContext


class NgsearchServiceTelemetryEventResultsPresentedArgs(Record):
    query: str
    token: str
    n: int
    n_results_total: int
    time_to_present: float
    query_time: float
    thumbnail_load_time: List[float]
    search_request_id: str
    telemetry_context: TelemetryContext


class NgsearchServiceLivezArgs(Record):
    pass


class NgsearchServiceReadyzArgs(Record):
    pass


class SearchFindArgs(Record):
    version: Literal(SearchFindClientVersion) = SearchFindClientVersion
    query: SearchQuery
    token: str


class SearchFind2Args(Record):
    version: Literal(SearchFind2ClientVersion) = SearchFind2ClientVersion
    query: SearchQuery
    token: str


class SearchFindPagedCursorArgs(Record):
    version: Literal(SearchFindPagedCursorClientVersion) = SearchFindPagedCursorClientVersion
    query: SearchQuery2
    token: Optional[str]
    size: Optional[float]
    cursor_id: Optional[str]


class SearchFindPagedSkipArgs(Record):
    version: Literal(SearchFindPagedSkipClientVersion) = SearchFindPagedSkipClientVersion
    query: SearchQuery2
    token: Optional[str]
    size: Optional[float]
    skip_first: Optional[float]


class SearchGetPrefixesArgs(Record):
    version: Literal(SearchGetPrefixesClientVersion) = SearchGetPrefixesClientVersion
