[package]
# Semantic Versionning is used: https://semver.org/
version = "1.4.9"

# Lists people or organizations that are considered the "authors" of the package.
authors = ["NVIDIA"]

# The title and description fields are primarly for displaying extension info in UI
title = "Sample Browser"
description="A browser to the amazing sample for Omniverse Kit"

# URL of the extension source repository.
repository = ""

# Keywords for the extension
keywords = ['browser', 'samples']

# Location of change log file in target (final) folder of extension, relative to the root.
# More info on writing changelog: https://keepachangelog.com/en/1.0.0/
changelog="docs/CHANGELOG.rst"

category = "Rendering"
readme  = "docs/README.md"
preview_image = "data/preview.png"
icon = "data/icon.svg"

[dependencies]
"omni.kit.browser.core" = {}
"omni.kit.browser.folder.core" = {}
"omni.kit.menu.utils" = {}
"omni.kit.window.file" = {}

# Main python module this extension provides, it will be publicly available as "import omni.kit.browser.sky".
[[python.module]]
name = "omni.kit.browser.sample"

[settings.exts."omni.kit.browser.sample"]
folders = [
    "https://omniverse-content-production.s3.us-west-2.amazonaws.com/Samples/Examples/2024_1"
]
folders_hide_in_category = ["2024_1"]
custom_folders = []
data.timeout = 10

[[trigger]]
menu.name = "Window/Browsers/Examples"
menu.window = "Examples"

[[test]]
args = [
    "--no-window",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--/app/menu/legacy_mode=false",
    "--/exts/omni.kit.browser.sample/folders/0=${omni.kit.browser.sample}/data/tests/root"
]

stdoutFailPatterns.exclude = [
    "*unload wait time exceeded limit of*", # ETM test failure with kit 105.0.1 integ-master
]
