
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.graph.image.core-e505635a386f6306.zip"

    [package.publish]
        kitVersion = "107.3.2+production.219701.4663cf0b.gl"
        date = 1757755257
        buildNumber = "107.3.2+1073.219701.4663cf0b.gl"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.platform]
            0 = "linux-x86_64"

        [package.target.kitHash]
            0 = "69cbf6ad"
