[package]
version = "2.1.3"
authors = ["NVIDIA"]
title = "OmniGraph Visualization Nodes"
description="OmniGraph nodes for viewport display"
readme  = "docs/README.md"
repository = ""
category = "Graph"
keywords = ["graph", "visualization", "nodes"]
changelog="docs/CHANGELOG.md"
preview_image="data/preview.png"
icon = "data/icon.png"

[[python.module]]
name = "omni.graph.visualization.nodes"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py"]

[dependencies]
"omni.graph" = {}
"omni.ui" = {}
"omni.ui.scene" = {}
"omni.kit.manipulator.viewport" = {}
"omni.kit.viewport.registry" = {}
"omni.kit.viewport.utility" = {}

[[test]]
args = [
    "--/renderer/enabled=rtx",
    "--/renderer/active=rtx",
    "--/app/viewport/forceHideFps=true",
    "--/app/window/hideUi=true",
    "--/app/window/width=800",
    "--/app/window/height=600",
    "--/app/renderer/resolution/width=800",
    "--/app/renderer/resolution/height=600",
    "--/app/viewport/grid/enabled=false",
    "--/app/viewport/defaults/guide/grid/visible=false",
    "--/app/viewport/show/lights=false",
    "--/renderer/multiGpu/enabled=false",
    "--/renderer/multiGpu/autoEnable=false", # Disable mGPU with PXR due to OM-51026, OM-53611
    "--/renderer/multiGpu/maxGpuCount=1",
    "--/app/asyncRendering=false",
    "--/app/window/dpiScaleOverride=1.0",
    "--/app/window/scaleToMonitor=false",
    "--no-window",
]
dependencies = [
    "omni.hydra.rtx",
    "omni.kit.test_helpers_gfx",
    "omni.kit.viewport.window",  # Viewport Next
    "omni.kit.ui_test",
    "omni.graph.bundle.action",
]