from .test_action_mapping import *
from .test_appear_after import *
from .test_custom_style import *
from .test_debug_menu import *
from .test_helper import *
from .test_helper_full import *
from .test_hooks import *
from .test_hotkey import *
from .test_menu_icons import *
from .test_menu_layouts import *
from .test_menu_layouts2 import *
from .test_menus import *
from .test_radio_buttons import *
from .test_refresh import *
from .test_replace import *
from .test_right_menus import *
from .test_tearoff_menus import *
