# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
import os
import unittest

import carb
import numpy as np
import omni.graph.core as og
import omni.kit
import omni.replicator.core as rep
import omni.usd
import warp as wp
from omni.replicator.core.utils import rng
from PIL import Image
from pxr import Sdf, UsdGeom, UsdShade

from .utils import gitlab_output_image_comparison, tc_output_image_comparison

# Currently we check if we can create the augmentation from function nodes, send and image through them, ensure
# the output image from the node a 3D array, and then destroy the node.
# We do NOT check for the quality of information encoded in the image for each augmentation node.
# TODO: add more rigorous tests for that check the quality of images generated by augmentations


TEST_DATA_DIR = os.path.join(os.path.dirname(os.path.realpath(__file__)), "data")


class TestOgnAugFunction(omni.kit.test.AsyncTestCase):
    async def setUp(self):
        if os.getenv("ETM_ACTIVE"):
            self.skipTest("skip in ETM to keep tests lean")

        self.cached_opt_in = carb.settings.get_settings().get_as_bool("/app/omni.graph.scriptnode/opt_in")
        carb.settings.get_settings().set("/app/omni.graph.scriptnode/opt_in", True)
        carb.settings.get_settings().set("/rtx-transient/post/aa/limitedOps", False)
        await omni.usd.get_context().new_stage_async()
        await omni.kit.app.get_app().next_update_async()
        rep.set_global_seed(1234)

        self._aug_node_dict = dict()

        carb.settings.get_settings().set("/omni/replicator/RTSubframes", 10)

        self._fill_im_folderpath = os.path.join(TEST_DATA_DIR, "aug/fill_im")
        soccerball_texture = os.path.join(TEST_DATA_DIR, "aug/shape_mtl/ball_DefaultMaterial_BaseColor.png")
        blueyellow_texture = os.path.join(TEST_DATA_DIR, "aug/shape_mtl/GradientBlueYellow.png")
        kite_texture = os.path.join(TEST_DATA_DIR, "aug/fill_im/kite.exr")

        # rep.create.light(light_type="dome", texture=kite_texture, rotation=(9, -56, -94))

        mat_1 = rep.create.material_omnipbr(diffuse=(0.8, 0.1, 0.1))
        mat_2 = rep.create.material_omnipbr(diffuse_texture=blueyellow_texture)
        mat_3 = rep.create.material_omnipbr(diffuse_texture=soccerball_texture)

        rep.create.cube(position=(100, 200, 100), scale=3, material=mat_1, semantics=[("class", "cube")])
        rep.create.torus(position=(-150, 200, 100), scale=2, material=mat_2, semantics=[("class", "torus")])
        rep.create.sphere(position=(0, -200, 100), scale=3, material=mat_3, semantics=[("class", "sphere")])

        camera = rep.create.camera(position=(0, 0, 2000))
        self.rp = rep.create.render_product(camera, (640, 480))
        self.ldr_color = rep.AnnotatorRegistry.get_annotator("LdrColor", device="cuda")

        self.out_dir = carb.tokens.get_tokens_interface().resolve("${temp}/test_augmentations")
        os.makedirs(self.out_dir, exist_ok=True)
        self.golden_dir = os.path.join(TEST_DATA_DIR, "golden")

    async def tearDown(self):
        carb.settings.get_settings().set("/omni/replicator/RTSubframes", 1)
        await omni.usd.get_context().new_stage_async()

    async def test_augmentation_adjust_sigmoid(self):
        """Test raises error from failed adjust sigmoid augmentation"""
        self.ldr_color = self.ldr_color.augment(
            augmentation="AdjustSigmoid",
            cutoff=0.5,
            gain=10.0,
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_adjust_sigmoid.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_adjust_sigmoid.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_adjust_sigmoid", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_adjust_sigmoid", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_brightness(self):
        """Test raises error from failed brightness augmentation"""
        self.ldr_color = self.ldr_color.augment(
            augmentation="Brightness",
            brightness_factor=rep.distribution.uniform(-100, 100, seed=1234),
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_brightness.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_brightness.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_brightness", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_brightness", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_brightness_cpu(self):
        """Test raises error from failed brightness augmentation"""
        anno = rep.annotators.get("LdrColor").augment(
            augmentation="Brightness",
            brightness_factor=rep.distribution.uniform(-100, 100, seed=1234),
            device="cpu",
        )
        anno.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = anno.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image, os.path.join(self.golden_dir, "aug_brightness.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_brightness.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_brightness", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_brightness_cpu", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_speckle_noise(self):
        """Test raises error from failed speckle noise augmentation"""
        self.ldr_color = self.ldr_color.augment("SpeckleNoise", seed=1234, sigma=0.5)
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_speckle_noise.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_speckle_noise.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_speckle_noise", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_speckle_noise", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_shot_noise(self):
        """Test raises error from failed shot noise augmentation"""
        self.ldr_color = self.ldr_color.augment("ShotNoise", seed=1234, sigma=25)
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_shot_noise.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_shot_noise.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_shot_noise", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_shot_noise", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_rgb_to_hsv(self):
        """Test raises error from failed rgb to hsv augmentation"""
        self.ldr_color = self.ldr_color.augment("RgbToHsv")
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_rgb_to_hsv.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_rgb_to_hsv.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_rgb_to_hsv", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_rgb_to_hsv", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_hsv_to_rgb(self):
        """Test raises error from failed hsv to rgb augmentation"""
        self.ldr_color = self.ldr_color.augment("HsvToRgb")
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_hsv_to_rgb.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_hsv_to_rgb.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_hsv_to_rgb", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_hsv_to_rgb", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_glass_blur(self):
        """Test raises error from failed glass blur augmentation"""
        self.ldr_color = self.ldr_color.augment(
            augmentation="GlassBlur",
            kernel_seed=1234,
            data_out_shape=(-1, 4),
            delta=12,
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async(rt_subframes=2)
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_glass_blur.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_glass_blur.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_glass_blur", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_glass_blur", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_bgrand(self):
        """Test raises error from failed background rand augmentation"""
        self.ldr_color = self.ldr_color.augment("BackgroundRand", folderpath=self._fill_im_folderpath)
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        golden_file_path = os.path.join(self.golden_dir, "aug_bgrand.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_bgrand", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_bgrand", golden_file_path, image_data=image.numpy())
        self.assertLess(std_dev, 2)

    async def test_augmentation_colorize_depth(self):
        """Test raises error from failed colorize depth augmentation"""
        anno = rep.annotators.get("distance_to_camera", device="cuda").augment("ColorizeDepth", near=10.0, far=50.0)
        anno.attach(self.rp)

        await rep.orchestrator.step_async()
        data = anno.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        golden_file_path = os.path.join(self.golden_dir, "aug_colorize_depth.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_colorize_depth", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_colorize_depth", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_colorize_normals(self):
        """Test raises error from failed colorize normals augmentation"""
        anno = rep.annotators.get("normals", device="cuda").augment("ColorizeNormals")
        anno.attach(self.rp)

        await rep.orchestrator.step_async()
        data = anno.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        golden_file_path = os.path.join(self.golden_dir, "aug_colorize_normals.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_colorize_normals", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_colorize_normals", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_sobel_edges(self):
        """Test raises error from failed sobel edges augmentation"""
        anno_normals = rep.annotators.get("normals", device="cuda").augment("ColorizeNormals").augment("Sobel")
        anno_normals.attach(self.rp)
        anno_segmentation = rep.annotators.get("semantic_segmentation", device="cuda", init_params={"colorize": True})
        # anno_segmentation = anno_segmentation.augment("sobel_edges")  # TODO: fix issue setting init params to augmented annotator
        anno_segmentation.attach(self.rp)

        await rep.orchestrator.step_async()
        data_normals = anno_normals.get_data()
        data_segmentation_in = anno_segmentation.get_data()["data"]
        data_segmentation = wp.empty_like(data_segmentation_in)
        wp.launch(
            rep.augmentations_default.sobel_edges,
            dim=data_normals.shape[:2],
            inputs=[data_segmentation_in, data_segmentation],
            device=data_segmentation_in.device,
        )
        self.assertEqual(len(data_normals.shape), 3)
        self.assertEqual(len(data_segmentation.shape), 3)

        golden_file_path_normals = os.path.join(self.golden_dir, "aug_sobel_edges_normals.png")
        golden_file_path_segmentation = os.path.join(self.golden_dir, "aug_sobel_edges_segmentation.png")
        golden_image_normals = np.asarray(Image.open(golden_file_path_normals))
        golden_image_segmentation = np.asarray(Image.open(golden_file_path_segmentation))

        std_dev_normals = np.sqrt(np.square(data_normals.numpy() - golden_image_normals).astype(float).mean())
        if std_dev_normals > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison(
                    "aug_sobel_edges_normals", golden_file_path_normals, self.out_dir, data_normals.numpy()
                )
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_sobel_edges_normals", golden_file_path_normals, image_data=data_normals.numpy()
                )
        self.assertLess(std_dev_normals, 2)

        std_dev_segmentation = np.sqrt(
            np.square(data_segmentation.numpy() - golden_image_segmentation).astype(float).mean()
        )
        if std_dev_segmentation > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison(
                    "aug_sobel_edges_segmentation",
                    golden_file_path_segmentation,
                    self.out_dir,
                    data_segmentation.numpy(),
                )
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_sobel_edges_segmentation",
                    golden_file_path_segmentation,
                    image_data=data_segmentation.numpy(),
                )
        self.assertLess(std_dev_segmentation, 2)

    async def test_augmentation_canny(self):
        """Test raises error from failed canny augmentation"""
        anno = self.ldr_color.augment("Canny", thresholdLow=100, thresholdHigh=200)
        anno.attach(self.rp)

        await rep.orchestrator.step_async()
        data = anno.get_data()

        golden_file_path = os.path.join(self.golden_dir, "aug_canny.png")
        Image.fromarray(data.numpy()).save(golden_file_path)
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(data.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_canny", golden_file_path, self.out_dir, data.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_canny", golden_file_path, image_data=data.numpy())
        self.assertLess(std_dev, 2)

    async def test_augmentation_contrast(self):
        """Test raises error from failed contrast augmentation"""
        self.ldr_color = self.ldr_color.augment(
            "Contrast", contrastFactor=rep.distribution.uniform(0.2, 1.8, seed=1234)
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_contrast.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_contrast.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_contrast", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_contrast", golden_file_path, image_data=image.numpy())
        self.assertLess(std_dev, 2)

    async def test_augmentation_conv_2d(self):
        """Test raises error from failed conv 2d augmentation"""
        self.ldr_color = self.ldr_color.augment(
            "Conv2d", alpha=0.7, kernel=rep.distribution.normal(0.0, math.sqrt(1 / 3), num_samples=9, seed=1234)
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_conv2d.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_conv2d.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_conv2d", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_conv_2d", golden_file_path, image_data=image.numpy())
        self.assertLess(std_dev, 2)

    async def test_augmentation_bgrand_crop_resize_rotate(self):
        """Test raises error from failed combination of multiple augmentations, which test not only for proper
        sequencing of the image but also for transform computation among multiple node transform changes.
        """

        self.ldr_color = self.ldr_color.augment(
            "BackgroundRand",
            folderpath=self._fill_im_folderpath,
        )
        self.ldr_color = self.ldr_color.augment(
            "CropResize",
            cropFactor=0.7,  # should be a tuple
            offsetFactor=(-1, 1),
        )
        self.ldr_color = self.ldr_color.augment(
            "Rotate",
            rotation=30,
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        xform = data["info"]["xform"].reshape(3, 3)

        centre = np.array([200.0, 400.0, 1.0])
        centre_adj = np.matmul(centre, xform)[:2]
        image_np = image.numpy()
        for i in range(-15, 15):
            for j in range(-15, 15):
                y = int(round(centre_adj[0])) + i
                x = int(round(centre_adj[1])) + j
                image_np[y, x] = [0, 255, 0, 255]

        golden_file_path = os.path.join(self.golden_dir, "aug_bgrand_crop_resize_rotate.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        image_np_cube_zoom = image_np[
            int(round(centre_adj[0])) - 30 : int(round(centre_adj[0])) + 30,
            int(round(centre_adj[1])) - 30 : int(round(centre_adj[1])) + 30,
        ]
        golden_image_cube_zoom = golden_image[
            int(round(centre_adj[0])) - 30 : int(round(centre_adj[0])) + 30,
            int(round(centre_adj[1])) - 30 : int(round(centre_adj[1])) + 30,
        ]

        std_dev = np.sqrt(np.square(image_np_cube_zoom - golden_image_cube_zoom).astype(float).mean())
        self.assertLess(std_dev, 2)

        centre = np.array([240.0, 320.0, 1.0])
        centre_adj = np.matmul(centre, xform)[:2]
        image_np = image.numpy()
        for i in range(-15, 15):
            for j in range(-15, 15):
                y = int(round(centre_adj[0])) + i
                x = int(round(centre_adj[1])) + j
                image_np[y, x] = [0, 255, 0, 255]

        golden_file_path = os.path.join(self.golden_dir, "aug_bgrand_crop_resize_rotate.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        image_np_cube_zoom = image_np[
            int(round(centre_adj[0])) - 30 : int(round(centre_adj[0])) + 30,
            int(round(centre_adj[1])) - 30 : int(round(centre_adj[1])) + 30,
        ]
        golden_image_cube_zoom = golden_image[
            int(round(centre_adj[0])) - 30 : int(round(centre_adj[0])) + 30,
            int(round(centre_adj[1])) - 30 : int(round(centre_adj[1])) + 30,
        ]

        std_dev = np.sqrt(np.square(image_np_cube_zoom - golden_image_cube_zoom).astype(float).mean())
        if std_dev < 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison(
                    "aug_bgrand_crop_resize_rotate", golden_file_path, self.out_dir, image.numpy()
                )
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_bgrand_crop_resize_rotate", golden_file_path, image_data=image.numpy()
                )
        self.assertGreater(std_dev, 2)

    async def test_augmentation_crop_resize(self):
        """Test raises error from failed crop resize augmentation"""
        self.ldr_color = self.ldr_color.augment(
            "CropResize",
            cropFactor=0.75,
            offsetFactor=(-0.9, -0.9),
            # cropFactor=rep.distribution.uniform(0.3, 0.8, seed=1234),
            # offsetFactor=rep.distribution.uniform(lower=(-0.5, 0.5), upper=(0.5, 0.5), seed=1234),
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_crop_resize.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_crop_resize.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_crop_resize", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_crop_resize", golden_file_path, image_data=image)
        self.assertLess(std_dev, 2)

    async def test_augmentation_cutmix(self):
        """Test raises error from failed cutmix augmentation"""
        self.ldr_color = self.ldr_color.augment("CutMix", folderpath=self._fill_im_folderpath, kernel_seed=1234)
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_cutmix.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_cutmix.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_cutmix", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_cutmix", golden_file_path, image_data=image.numpy())
        self.assertLess(std_dev, 2)

    async def test_augmentation_img_blend(self):
        """Test raises error from failed image blend augmentation"""
        self.ldr_color = self.ldr_color.augment(
            "ImageBlend",
            folderpath=self._fill_im_folderpath,
            blendFactor=rep.distribution.uniform(0.1, 0.9, seed=1234),
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_img_blend.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_img_blend.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_img_blend", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_img_blend", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_motion_blur(self):
        """Test raises error from failed motion blur augmentation"""
        self.ldr_color = self.ldr_color.augment(
            "MotionBlur",
            alpha=1.0,
            kernelSize=11,
            strength=0.7,
            motionAngle=rep.distribution.uniform(0.0, 359.0, seed=1234),
        )
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_motion_blur.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_motion_blur.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_motion_blur", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_motion_blur", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_pixellate(self):
        """Test raises error from failed pixellate augmentation"""
        self.ldr_color = self.ldr_color.augment("Pixellate", kernelSize=40)
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_pixellate.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_pixellate.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_pixellate", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison(
                    "test_augmentation_pixellate", golden_file_path, image_data=image.numpy()
                )
        self.assertLess(std_dev, 2)

    async def test_augmentation_rotate(self):
        """Test raises error from failed rotate augmentation"""
        self.ldr_color = self.ldr_color.augment("Rotate", rotation=rep.distribution.uniform(0.0, 359.0, seed=1234))
        self.ldr_color.attach(self.rp)

        await rep.orchestrator.step_async()
        data = self.ldr_color.get_data()
        if isinstance(data, dict):
            image = data["data"]
        else:
            image = data
        self.assertEqual(len(image.shape), 3)

        # save_image(image.numpy(), os.path.join(self.golden_dir, "aug_rotate.png"))

        golden_file_path = os.path.join(self.golden_dir, "aug_rotate.png")
        golden_image = np.asarray(Image.open(golden_file_path))

        std_dev = np.sqrt(np.square(image.numpy() - golden_image).astype(float).mean())
        if std_dev > 2:
            if omni.kit.test.utils.is_running_in_teamcity():
                tc_output_image_comparison("aug_rotate", golden_file_path, self.out_dir, image.numpy())
            if omni.kit.test.utils.is_running_in_gitlab():
                gitlab_output_image_comparison("test_augmentation_rotate", golden_file_path, image_data=image.numpy())
        self.assertLess(std_dev, 2)

    async def test_augmentation_depth(self):
        @wp.kernel
        def gaussian_noise_depth_wp(
            data_in: wp.array2d(dtype=wp.float32), data_out: wp.array2d(dtype=wp.float32), sigma: float, seed: int
        ):
            i, j = wp.tid()
            state = wp.rand_init(seed, wp.tid())
            data_out[i, j] = data_in[i, j] + sigma * wp.randn(state)

        rep.annotators.register_augmentation(
            "depth_noise", rep.annotators.Augmentation.from_function(gaussian_noise_depth_wp, sigma=0.01, seed=None)
        )

        anno = rep.annotators.get("distance_to_camera")
        anno.augment("depth_noise")
        anno.attach(self.rp)

        await rep.orchestrator.step_async()

        data = anno.get_data()

        self.assertEqual(type(data), wp.array)
        self.assertEqual(data.shape, (480, 640))
        self.assertTrue(
            all([v > 0.0 for v in data.numpy().reshape([-1])]),
            f"One or more output values were not updated: {data.numpy()}",
        )

    async def test_augmentation_gpu_dtype_change(self):
        # GPU depth colorize kernel
        @wp.kernel
        def colorize_depth(
            data_in: wp.array2d(dtype=wp.float32), data_out: wp.array2d(dtype=wp.uint8), z_far: float = 100.0
        ):
            i, j = wp.tid()
            data_out[i, j] = wp.uint8((1.0 - (min(z_far, data_in[i, j]) / z_far)) * 255.0)

        anno = rep.annotators.get("distance_to_camera").augment(colorize_depth)
        anno.attach(self.rp)
        await rep.orchestrator.step_async()
        data = anno.get_data()

        self.assertEqual(data.shape, (480, 640))
        self.assertEqual(data.dtype, wp.uint8)

    async def test_augmentation_cpu_dtype_change(self):
        # CPU noise kernel
        def image_gaussian_noise_np(data_in: np.ndarray, seed, sigma: float = 25.0):
            np.random.seed(seed)
            return data_in + sigma * np.random.randn(*data_in.shape)

        def to_uint32(data_in: np.ndarray):
            data_in = np.nan_to_num(data_in, posinf=10000)
            return data_in.astype(np.int32)

        anno = rep.annotators.get("distance_to_camera").augment(image_gaussian_noise_np, seed=1234)
        anno.attach(self.rp)
        await rep.orchestrator.step_async()
        data = anno.get_data()

        self.assertEqual(data.shape, (480, 640))
        self.assertEqual(data.dtype, np.float64)

        anno = anno.augment(to_uint32)
        await rep.orchestrator.step_async()
        data = anno.get_data()

        self.assertEqual(data.shape, (480, 640))
        self.assertEqual(data.dtype, np.int32)

    async def test_augmentation_gpu_name_change(self):
        # GPU depth colorize kernel
        @wp.kernel
        def colorize_depth(
            data_in: wp.array2d(dtype=wp.float32), data_out: wp.array2d(dtype=wp.float32), z_far: float = 100.0
        ):
            i, j = wp.tid()
            data_out[i, j] = 1.0 - (min(z_far, data_in[i, j]) / z_far)

        anno = rep.annotators.get("distance_to_camera").augment(colorize_depth, name="FooDepth")
        anno.attach(self.rp)
        await rep.orchestrator.step_async()
        data = anno.get_data()

        self.assertEqual(data.shape, (480, 640))
        self.assertEqual(data.dtype, wp.float32)
        self.assertEqual(anno.get_name(), "FooDepth")

    async def test_augmentation_cpu_name_change(self):
        # CPU noise kernel
        def image_gaussian_noise_np(data_in: np.ndarray, seed, sigma: float = 25.0):
            np.random.seed(seed)
            return data_in + sigma * np.random.randn(*data_in.shape)

        anno = rep.annotators.get("normals").augment(image_gaussian_noise_np, seed=1234, name="FooNoise")
        anno.attach(self.rp)
        await rep.orchestrator.step_async()
        data = anno.get_data()

        self.assertEqual(data.shape, (480, 640, 4))
        self.assertEqual(data.dtype, np.float64)
        self.assertEqual(anno.get_name(), "FooNoise")
