
[package]
    archivePath = "http://d4i3qtqj3r0z5.cloudfront.net/omni.kit.widget.options_menu-588fa889ca209184.zip"

    [package.publish]
        kitVersion = "107.3.0+feature.195367.2c7fcd57.gl"
        date = 1757755126
        buildNumber = "107.3.0+1073.195367.2c7fcd57.gl"

    [package.target]

        [package.target.kitHash]
            0 = "69cbf6ad"
