
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.profiler.window-2.3.5.zip"

    [package.publish]
        kitVersion = "108.0.0+master.208884.46cf6a8c.gl"
        date = 1751872171
        buildNumber = "103.0.0+master.567.e868e27e.gl"
        repoName = "kit-devtools"
        signed = 1
