from __future__ import annotations
import OmniAudioSchema._omniAudioSchema
import typing
import Boost.Python
import OmniAudioSchema
import pxr.Usd
import pxr.UsdGeom

__all__ = [
    "Listener",
    "OmniListener",
    "OmniSound",
    "Sound",
    "Tokens"
]


class Listener(OmniListener, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class OmniListener(pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateConeAnglesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConeLowPassFilterAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConeVolumesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateOrientationFromViewAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConeAnglesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConeLowPassFilterAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConeVolumesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetOrientationFromViewAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Sound(OmniSound, pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class OmniSound(pxr.UsdGeom.Xformable, pxr.UsdGeom.Imageable, pxr.Usd.Typed, pxr.Usd.SchemaBase, Boost.Python.instance):
    @staticmethod
    def CreateAttenuationRangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateAttenuationTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateAuralModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConeAnglesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConeLowPassFilterAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateConeVolumesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEnableDistanceDelayAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEnableDopplerAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEnableInterauralDelayAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateEndTimeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateFilePathAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateGainAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateLoopCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateMediaOffsetEndAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateMediaOffsetStartAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreatePriorityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateStartTimeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def CreateTimeScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Define(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def Get(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttenuationRangeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAttenuationTypeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetAuralModeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConeAnglesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConeLowPassFilterAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetConeVolumesAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEnableDistanceDelayAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEnableDopplerAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEnableInterauralDelayAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetEndTimeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetFilePathAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetGainAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetLoopCountAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMediaOffsetEndAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetMediaOffsetStartAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetPriorityAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetSchemaAttributeNames(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetStartTimeAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def GetTimeScaleAttr(*args, **kwargs) -> typing.Any: ...
    @staticmethod
    def _GetStaticTfType(*args, **kwargs) -> typing.Any: ...
    __instance_size__ = 48
    pass
class Tokens(Boost.Python.instance):
    Listener = 'Listener'
    OmniListener = 'OmniListener'
    OmniSound = 'OmniSound'
    Sound = 'Sound'
    attenuationRange = 'attenuationRange'
    attenuationType = 'attenuationType'
    auralMode = 'auralMode'
    coneAngles = 'coneAngles'
    coneLowPassFilter = 'coneLowPassFilter'
    coneVolumes = 'coneVolumes'
    default_ = 'default'
    enableDistanceDelay = 'enableDistanceDelay'
    enableDoppler = 'enableDoppler'
    enableInterauralDelay = 'enableInterauralDelay'
    endTime = 'endTime'
    filePath = 'filePath'
    gain = 'gain'
    inverse = 'inverse'
    linear = 'linear'
    linearSquare = 'linearSquare'
    loopCount = 'loopCount'
    mediaOffsetEnd = 'mediaOffsetEnd'
    mediaOffsetStart = 'mediaOffsetStart'
    nonSpatial = 'nonSpatial'
    off = 'off'
    on = 'on'
    orientationFromView = 'orientationFromView'
    priority = 'priority'
    spatial = 'spatial'
    startTime = 'startTime'
    timeScale = 'timeScale'
    pass
__MFB_FULL_PACKAGE_NAME = 'omniAudioSchema'
