
[package]
    archivePath = "https://d2cerybs4newgl.cloudfront.net/omni.kit.widget.schema_api-1.0.3.zip"

    [package.publish]
        kitVersion = "108.0.0+mr37350.191069.c82efd5a.gl"
        date = 1748979613
        buildNumber = "106.0.1+master.822.369c8598.gl"
        repoName = "kit-widgets"
        signed = 1
