[package]
authors = ["NVIDIA"]
category = "Services"
changelog="docs/CHANGELOG.md"
description="Facility to monitor progress of tasks and long-running operations"
icon = "data/icon.png"
keywords = ["kit", "services", "farm", "monitoring", "facility"]
preview_image = "data/preview.png"
readme  = "docs/README.md"
repository = ""
title = "Progress facility"
toggleable = false
version = "0.2.4"

[dependencies]
"omni.kit.pip_archive" = {}
"omni.services.pip_archive" = {}
"omni.services.core" = {}
"omni.services.client" = {}
"omni.services.facilities.base" = {}

[[python.module]]
name = "omni.services.facilities.monitoring.progress"
